Add velocity forwarding secret file support
PaperMC/Paper pull request #10127
Opened 2024-01-04 09:19 UTC by oliverjanka

Currently the secret can only be specified as string in the config. This makes it almost impossible to run the server within a containerized environment like Kubernetes. Also I don't want secret data to be specified along with 'general' data. 

This PR aims to add the functionality to load the secret from an external file (like it is already the default in velocity)

2024-01-04 09:22 UTC, oliverjanka commented
FYI: I only changed the files GlobalConfiguration, VelocityProxy and PaperConfigurations I don't know why `rebuildPatches` also changed the other patches.

2024-01-04 09:24 UTC, electronicboy commented
Being frank, this has kinda been on the todo list for a while, but if we wanna do this, we would want to maintain consistency with velocities current expected behavior, i.e. the secret if already set should probably be migrated to the file, and we should follow the file naming of velocity so that people can just copy the file over and save confusion

2024-01-04 13:12 UTC, oliverjanka commented
@electronicboy I added functionality to migrate in-config secrets to file automatically. I hope this fits what you meant.

2024-01-12 15:03 UTC, jorishaenseler15 commented
I really need this feature to run a minecraft server securely on k8s. So i'm looking forward to see the merged pullrequest. @electronicboy

2024-01-17 13:41 UTC, Nevah5 commented
Bump

2024-02-09 20:26 UTC, Machine-Maker requested changes
If the goal is to replace the `secret` setting with a `secretFile`, then there should be a proper migration/transformation for this and then we remove the `secret` setting. If the goal is to offer both an in-config secret, and a secret file, I think there should be a setting that sets where the secret is coming from.

Basically a lot of that logic added in `postProcess` should either be moved to a proper migration, or use a third setting to determine where to read the secret from.

2024-08-25 15:33 UTC, oliverjanka commented
@Machine-Maker what's the status of this issue?

2024-08-25 23:20 UTC, Machine-Maker requested changes

2024-08-25 23:20 UTC, Machine-Maker commented on patches/server/0005-Paper-config-files.patch
> ++            final String secretFile = getSecretFile(value);
I think we can assume that since this versioned migration is running, the secret file path isn't set in the config right?

2024-08-25 23:20 UTC, Machine-Maker commented on patches/server/0005-Paper-config-files.patch
> ++            Files.writeString(Path.of(secretFile), secret, StandardOpenOption.CREATE_NEW);
The path should be relative to the `config` folder, *I think*.

2024-09-21 21:16 UTC, lynxplay commented
I moved this PR over to an environment variable, which should be a lot easier to use than a volume mount from a secret.
The PR will still respect a potentially configured value to enable people on restrictive hosts etc to continue to define their secrets via a config, but once the configured env var is set, it'll take precedent.

The PR is gonna be up for more in-depth review tomorrow, if you have time till then to give feedback on my changes, that would be great so we can merge (would not wanna merge without an okay from you @oliverjanka, given the drastic changes).

If we wanna revert to your previous state, 4d85ab46001bded20077c2b7bcb8763783211588 was the previous HEAD.

2024-09-22 15:11 UTC, oliverjanka commented
Actually I'm not in favour of providing secret data through environment variables due to security concerns. This is one of the reasons I opted for this approach (along with the fact that Velocity works similarly).
However, I'm currently very busy and do not have time to work on my previous or an alternative approach and I'd like to see this feature implemented soon.

Therefore, I won’t stand in the way of you proceeding with this method 🙂.

2024-09-22 15:17 UTC, lynxplay commented
Thanks for your quick feedback.
While yea, an environment variable is accessible by anything in the pod, so is the velocity secret file given the user running the server process does need read permissions, and the server internal field storing said secret.

I'll proceed with the environment variable just to get *some* way of doing it in, and if we care enough, the above ref can always be used to potentially revisit a file based approach as well as the env variable.

2024-09-22 18:11 UTC, Machine-Maker approved these changes

2024-09-22 18:24 UTC, lynxplay approved these changes

2024-09-22 18:25 UTC, merged