Create API for CanPlaceOn and CanDestroy NBT tags
PaperMC/Paper pull request #1015
Opened 2018-02-21 18:42 UTC by mikroskeem

This feature is present since Minecraft 1.8, but was not implemented into API yet. So here is my try to add the API for these two tags :smile:

2018-02-21 23:26 UTC, Mystiflow commented
Why not PR for Spigot?

2018-02-22 01:50 UTC, aikar commented
Id much rather this wait until 1.13 so we don't have to worry about converting ID's.

@Mystiflow many developers have given up on Spigot. Easier to just PR here and help keep making Paper better.

Let me note that we do not discourage PR'ing to Spigot, just explaining that it pretty much is Paper first, and then Spigot maybe if the contributor is up for the battle.

2018-02-22 04:02 UTC, Mystiflow commented
@aikar I understand that the spigot team is selective about what they push into it, but this looks like one of the PRs that would more likely be accepted with a few amendments as it's something that was forgotten to be added to the API.

2018-08-07 23:40 UTC, kashike commented
[![attention](https://i.ytimg.com/vi/nfs8NYg7yQM/hqdefault.jpg)](https://www.youtube.com/watch?v=nfs8NYg7yQM)

2018-08-08 01:28 UTC, aikar commented
@mikroskeem can you rebase this to 1.13 please

2018-08-08 01:28 UTC, aikar requested changes
can you rebase to 1.13 please

2018-08-08 09:49 UTC, mikroskeem commented
Yea sure.

---- On Wed, 08 Aug 2018 01:28:07 +0000 notifications@github.com wrote ----

@mikroskeem can you rebase this to 1.13 please

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

2018-09-12 15:55 UTC, mikroskeem commented
Rebased, ready for a review

2018-09-12 16:01 UTC, aikar requested changes

2018-09-12 16:01 UTC, aikar commented on Spigot-Server-Patches/0369-Implement-an-API-for-CanPlaceOn-and-CanDestroy-NBT-v.patch
> ++        return java.util.Collections.unmodifiableSet(canDestroy);
Lets return a normal hashset here. Still be a copy, just mutable

otherwise using the api will require making yet another copy.

2018-09-12 16:01 UTC, aikar commented on Spigot-Server-Patches/0369-Implement-an-API-for-CanPlaceOn-and-CanDestroy-NBT-v.patch
> ++        return java.util.Collections.unmodifiableSet(canPlaceOn);
same as above, normal hashset

2018-09-12 16:01 UTC, aikar commented on Spigot-Server-Patches/0369-Implement-an-API-for-CanPlaceOn-and-CanDestroy-NBT-v.patch
> ++        if(canDestroy.stream().anyMatch(Material::isLegacy))
braces, space before (

2018-09-12 16:01 UTC, aikar commented on Spigot-Server-Patches/0369-Implement-an-API-for-CanPlaceOn-and-CanDestroy-NBT-v.patch
> ++        if(canPlaceOn.stream().anyMatch(Material::isLegacy))
braces, space before (

2018-09-12 16:20 UTC, Black-Hole commented
EnumSet fits better than HashSet.

2018-09-12 16:31 UTC, aikar commented
@Black-Hole yes performance wise, but EnumSet's on Material class has huge memory overhead.

For the use case here, it's unnecessary.

2018-09-22 15:03 UTC, zachbr approved these changes

2018-09-23 03:21 UTC, aikar approved these changes

2018-09-23 03:30 UTC, merged