fill command event
PaperMC/Paper pull request #10163
Opened 2024-01-13 21:11 UTC by yannicklamprecht

**TODO:**

- [ ] cleanup diff -> formatting is messed
- [ ] tbd.

2024-01-13 21:33 UTC, Owen1212055 commented
I think we need to decide the usefulness of this event. I generally think that this doesn’t have much use, as most server owners will not give players access to fill / setblock due to not only how primitive it is.. but also like it’s not as performant as what world edit and such may offer.

2024-01-13 21:48 UTC, Machine-Maker commented
My reason for thinking this is a good thing to have, is it allows client-side mods to take advantage of the vanilla commands for pasting schematics and such.

2024-01-13 21:49 UTC, Machine-Maker requested changes

2024-01-13 21:49 UTC, Machine-Maker commented on patches/api/0458-fill-command-event.patch
> ++        return boundingBox;
Need to clone as its mutable

2024-01-13 21:52 UTC, Owen1212055 commented
> My reason for thinking this is a good thing to have, is it allows client-side mods to take advantage of the vanilla commands for pasting schematics and such.

Schematic paster mods typically already have this logic for by placing blocks, which is now gonna be easier with the block interaction attribute.

Just donno, I seriously do not know servers that would even use setblock/fill over FAWE, which has been the standard in general for stuff like this.

2024-01-13 21:54 UTC, Machine-Maker commented
> Schematic paster mods typically already have this logic for by placing blocks, which is now gonna be easier with the block interaction attribute.

They didn't yesterday in chat when someone was asking about this for Litematica support. I don't think the printer functionality is built-in anymore. Plus, printing is still different from pasting all at once.

2024-01-13 21:55 UTC, Machine-Maker commented
> I seriously do not know servers that would even use setblock/fill over FAWE

This doesn't replace worldedit by any means, and having one enable doesn't disable the other.

2024-01-16 23:25 UTC, yannicklamprecht commented on patches/api/0456-fill-command-event.patch
> ++     * Is the state tha will be set by the fill command
Missing t

2024-01-16 23:25 UTC, yannicklamprecht commented on patches/api/0456-fill-command-event.patch
> ++ * The placement mode of the fill command see
Needs a complete sentence.

2024-01-20 19:03 UTC, yannicklamprecht commented
Any updates here?

2024-06-19 20:07 UTC, closed without merging