Call EntityChangeBlockEvent for extinguishing (cake) candles
PaperMC/Paper pull request #10176
Opened 2024-01-18 03:44 UTC by rowan-vr

Calls the EntityChangeBlockEvent for when candles, normal ones and the ones on cakes, are extinguished as described in #10112

2024-01-18 21:16 UTC, kennytv commented
Thank you for the PR! There's already a patch for adding tons of missing calls, please merge it into that: `Fire EntityChangeBlockEvent in more places` (patch number 0824 currently)

2024-01-20 17:38 UTC, kennytv submitted a review, later dismissed
(otherwise approved)

2024-01-23 20:50 UTC, Owen1212055 requested changes
This does not handle cases where the player is null. Such as extinguishing with potions.

2024-01-27 18:28 UTC, Machine-Maker requested changes
Looking at how extinguishing happens, I no longer think this event is appropriate for it. Extinguishing candles can happen due to non-entity related interactions, like water flowing. We need a solution that covers all these cases, not just some of them.

2024-01-28 00:45 UTC, rowan-vr commented
Maybe a blockextinguishevent and a playerblockextinguish event? Both events could extend some event to be able to listen to it
  
  
  
  
  
  
  

  
  
>   
> On Jan 27, 2024 at 7:28 PM,  <Jake Potrebic ***@***.***)>  wrote:
>   
>   
>   
>
>
>
>   
>
> @Machine-Maker  requested changes on this pull request.
>
>   
>
> Looking at how extinguishing happens, I no longer think this event is appropriate for it. Extinguishing candles can happen due to non-entity related interactions, like water flowing. We need a solution that covers all these cases, not just some of them.
>
>   
>
> —
>  Reply to this email directly,   view it on GitHub (https://github.com/PaperMC/Paper/pull/10176#pullrequestreview-1847151825), or   unsubscribe (https://github.com/notifications/unsubscribe-auth/AF3TQRKI43GCLBXTU34HPKLYQVBN3AVCNFSM6AAAAABB7SUUXWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQNBXGE2TCOBSGU).
>  You are receiving this because you authored the thread.Message ID:  ***@***.***>
>
>   
>

2025-03-23 19:15 UTC, closed without merging