Allow enabling sand duping
PaperMC/Paper pull request #10191
Opened 2024-01-27 02:28 UTC by Owen1212055

Because this exploit has been widely known for years and has not been fixed by Mojang, we decided that it was worth allowing people to toggle it on/off due to how easy it is to make it configurable.

It should be noted that this decision does not promise all future exploits will be configurable. 

*paper-global.yml:*
```yml
unsupported-settings:
    allow-unsafe-end-portal-teleportation: true
```

With hard forking on the future, we are hoping to open Paper up to more groups of people who may have utilized exploits like this.

Tested with world provided from https://www.youtube.com/watch?v=lCYR2FN20lk
Please feel free to test your sand dupe setups using the jar provided below.

2024-01-27 05:26 UTC, EterNityCH commented
I believe this would be beneficial to the project, given the considerable amount of time I've spent assisting people in the Paper-help channel. It is indeed a frequently requested feature, and since @Owen1212055 has volunteered to maintain it, there should be no issue!

It would just be part of the `unsupported settings`, receiving similar treatment to bedrock breaking and TNT duping. 👍

2024-01-27 12:56 UTC, olijeffers0n commented
Needs docs before merge, maybe even an announcement that we now support it

2024-01-27 13:26 UTC, electronicboy approved these changes

2024-01-27 14:10 UTC, olijeffers0n commented
https://github.com/PaperMC/docs/pull/292

2024-02-16 04:05 UTC, Riley19280 commented
Any update on releasing this?

2024-03-03 21:37 UTC, kennytv approved these changes

2024-03-03 21:47 UTC, kashike approved these changes

2024-03-03 21:47 UTC, kashike requested changes, later dismissed
Please fix the merge conflicts.

2024-03-03 22:05 UTC, merged