Check for server JARs in plugin directory
PaperMC/Paper pull request #10228
Opened 2024-02-07 14:25 UTC by jstN0body

Simple detection logic to address the issue #10223

2024-02-07 14:26 UTC, electronicboy commented on patches/server/1045-Check-for-server-JARs-in-plugin-directory.patch
> +             throw new IllegalArgumentException(source + " does not contain a " + String.join(" or ", PluginFileType.getConfigTypes()) + "! Could not determine plugin type, cannot load a plugin from
The logic this PR adds should probably be inside of here

2024-02-07 14:31 UTC, micah-rao commented on patches/server/1045-Check-for-server-JARs-in-plugin-directory.patch
> +             throw new IllegalArgumentException(source + " does not contain a " + String.join(" or ", PluginFileType.getConfigTypes()) + "! Could not determine plugin type, cannot load a plugin from
Sorry if I'm just missing the obvious, but when you say "here", where exactly are you referencing?

2024-02-07 14:31 UTC, jstN0body commented
![image](https://github.com/PaperMC/Paper/assets/49841276/df86d051-afb4-4f6d-9527-5d768bb6f00e)
Output when first starting the server.
![image](https://github.com/PaperMC/Paper/assets/49841276/f0fb0b1b-afe6-41d9-9190-f7c76b78ba56)
Output when reloading the server. (notice that worldedit reloads with no issue)

2024-02-07 14:32 UTC, electronicboy commented on patches/server/1045-Check-for-server-JARs-in-plugin-directory.patch
> +             throw new IllegalArgumentException(source + " does not contain a " + String.join(" or ", PluginFileType.getConfigTypes()) + "! Could not determine plugin type, cannot load a plugin from
inside of the `type == null` body, that way we only blow up just because a plugin bundles a version.json file inside of its meta folder

2024-02-08 23:35 UTC, kashike requested changes

2024-02-08 23:35 UTC, kashike commented on patches/server/1046-fixup-Check-for-server-JARs-in-plugin-directory.patch
> ++                throw new IllegalArgumentException(context + " is a server JAR");
This should be non-fatal, and ignore the server JAR.

2024-02-09 19:33 UTC, electronicboy approved these changes
approving, but this should be merged into the paper plugins patch
maybe some better tongtangulation for the message too

2024-02-09 20:51 UTC, electronicboy approved these changes

2024-02-09 21:05 UTC, merged