Add RayTraceBuilder
PaperMC/Paper pull request #10237
Opened 2024-02-10 11:49 UTC by notTamion

closes #9942 
Adds a RayTraceBuilder which can be constructed using a starting Location, direction and max distance.
I am currently still unsure of how to integrate the raytrace methods on LivingEntity and Block. i am unsure if those need to be integrated at all since calling Entity#rayTraceEntites(distance) seems a lot easier and straight forward then creating a RayTraceBuilder for that simple purpose. I would definitely love to hear some feedback on that.

2024-02-10 17:37 UTC, Machine-Maker requested changes
I think this should be setup in a way similar to adventure's JoinConfiguration. interfaces+builder that are then used in a method on World rather than calling some method on the builder itself to get the ray trace result.

2024-02-10 17:53 UTC, notTamion commented
Could you give me an example explanation specifically for RayTrace in mind? (i don't exactly understand what you mean) do you mean like a RayTrace class that can be constructed which holds all the info about the direction etc. and then gets passed into the raytrace method on World, LivingEntity etc.?

2024-02-11 07:54 UTC, notTamion commented
what should be done regarding LivingEntity or Block? those interfaces only have methods for raytracing with the target of there own type

2024-02-17 18:48 UTC, notTamion commented
Alright i am really not sure about this. I feel like the kind of RayTraceBuilder or RayTraceExecutor we had in the beginnning just feels better. Using a configuration where stuff like starting point, distance, direction all need to be adjusted for each use specificly doesn't seem very convenient. I guess in the example of the JoinConfiguration that just works better cause not that many variables need to be adjusted for each use.

2025-01-04 13:44 UTC, closed without merging