Add entity heal API
PaperMC/Paper pull request #10267
Opened 2024-02-19 18:30 UTC by TotalledZebra

I haven't contributed to Paper yet so I'm not sure if this is all correct. I feel like this is useful since healing an entity is a pretty common use case and there already is a heal method in NMS.

2024-02-20 14:59 UTC, TotalledZebra commented
I've added the missing annotations required by the tests. However after some discussion on Discord I believe the healing either needs to happen without calling an event or there needs to be some sort of flag to control whether or not the EntityRegainHealthEvent is called.

2024-02-24 10:55 UTC, notTamion requested changes
I think its fine to call the event here considering that Damageable#damage also calls the event iirc

2024-02-24 10:55 UTC, notTamion commented on patches/api/0465-Add-entity-heal-API.patch
> ++
Missing paper start and end comments here.

2024-05-30 15:04 UTC, kennytv approved these changes

2024-05-30 20:16 UTC, lynxplay approved these changes

2024-05-30 20:31 UTC, merged