Change the direction, rather than the power of fireballs
PaperMC/Paper pull request #10302
Opened 2024-03-06 00:08 UTC by TonytheMacaroni

Fixes #10186.

Patch previously modified the power of the projectile, which actually controls how fast it accelerates. It now uses `AbstractHurtingProjectile#setDirection`, which also sets the power but with the default magnitude of `0.1`.

2024-03-06 01:07 UTC, TonytheMacaroni commented
On second thought, is setting the direction when you set the velocity even a sensible thing to do? Perhaps just a javadoc note on `Fireball#setVelocity` is necessary?

2024-03-17 16:16 UTC, maxcom1 requested changes

2024-03-17 16:16 UTC, maxcom1 commented on patches/api/0466-Expose-power-for-fireball-projectiles.patch
> ++
Missing `// Paper start` and `// Paper end` comments - https://github.com/PaperMC/Paper/blob/master/CONTRIBUTING.md

2024-03-17 16:16 UTC, maxcom1 commented on patches/server/0948-Expose-power-on-fireball-projectiles.patch
>  +
Missing new `// Paper start` and `// Paper end` comments - https://github.com/PaperMC/Paper/blob/master/CONTRIBUTING.md

2024-03-20 21:25 UTC, Machine-Maker approved these changes

2024-03-20 21:33 UTC, merged