Add next steps message if it is initial start
PaperMC/Paper pull request #10312
Opened 2024-03-10 19:28 UTC by Leguan16

This is a PR as a response to #10309.

What i have done here is by no means final and just an attempt to find a way to check if it is the "initial" start of a server. 
I decided to go for the `server.properties` file because this is the first file that came to my mind that you wouldnt really delete.

Basically, I am checking if the file exists and set a boolean if it doens't. After the server has been started, I check that boolean and print a message if it's the initial start. 

Obviously, you could just delete the file and get that message again so it wouldn't be the "initial" start anymore. So, if you have any other idea how to handle this, please leave feedback. 

The message is also not final. 

This would also allow for a `InitialServerStartEvent` later on once this is merged.

2024-03-10 19:38 UTC, masmc05 commented
I think most of the time people that are starting the server for the first time see the eula message, I think it may be good enough to just add the additional info with the link to documentation after/before the eula message

2024-03-10 19:39 UTC, Leguan16 commented
> I think most of the time people that are starting the server for the first time see the eula message, I think it may be good enough to just add the additional info with the link to documentation after/before the eula message

I think that would be too early.

2024-03-11 15:45 UTC, MiniDigger commented
I like the idea of improving the onboarding process

2024-03-11 17:02 UTC, Malfrador commented
I'm not 100% sure about storing Paper things in the server.properties file. This would be the first time for Bukkit, Spigot and Paper to add a new value there.
While it's not really gonna cause issues, this doesn't seem like the proper thing to do. IMO just using the paper global configuration would be fine - yes you get the message again if you delete your config, but it's just a log message, not a big deal, and idk if the event really is needed. There's a good chance users have no plugins installed during the first startup anyways. 

I do agree that the EULA is too early though. Some panels also realise EULA acceptance with a checkbox or similar, so not everyone will see it.

2024-03-11 19:07 UTC, Leguan16 commented
> I'm not 100% sure about storing Paper things in the server.properties file.

I'm not sure if I'm actually storing something in the server.properties. Besides that,  thinking further this might still be too early. Ideally the message would be shown after the first successful server start. So if a plugin crashes the server the message won't be shown at all since at the next startup the server.properties file already exists.

2024-03-11 21:56 UTC, Leguan16 commented
You are absolutely right. This is generally for people who set up a server for their first time. They won't have plugins if they do it for their first time. I will change it to the global config tomorrow. 

Another thing: We could send the same message to the first person joining the server. Or would that be too much?

2024-03-14 09:17 UTC, CodeByCam requested changes

2024-03-14 09:17 UTC, CodeByCam commented on patches/server/1054-Add-onboarding-message-on-initial-start.patch
> ++            // Paper start - Add info if it is the initial start
"Onboarding message for initial server start"?

2024-03-14 09:17 UTC, codebycam commented on patches/server/1054-Add-onboarding-message-on-initial-start.patch
> ++                LOGGER.info("##############################################################");
This could probably be condensed a little?
```
This is the first time you're starting this server. 
It's recommended you read our 'Getting Started' documentation for guidance.
View this and more helpful information here: <link>
```

2024-03-14 09:23 UTC, CodeByCam commented
> Another thing: We could send the same message to the first person joining the server. Or would that be too much?
Yeah I definitely wouldn't be sending the message to the first person joining. Just having it in console is fine in my opinion.

2024-03-14 10:31 UTC, Leguan16 commented on patches/server/1054-Add-onboarding-message-on-initial-start.patch
> ++                LOGGER.info("##############################################################");
Sounds great!

2024-03-14 15:12 UTC, Leguan16 commented
> If we're going to add an onboarding message, we really should have an onboarding docs page. Just linking to a category is not really accessible, IMHO, and just leaves more "where do I go" questions than it answers;

That was the plan anyway I think. 

> We might also want to consider adding a header message to the GUI app too, in order to provide a clickable link for people not using a terminal

Good idea.

2024-03-14 21:54 UTC, Leguan16 commented
I addressed the comments and added a message in the GUI. It is centered by default, idk if we leave it that way. Also, should we display it always? IMO yeah. 
![image](https://github.com/PaperMC/Paper/assets/59799222/44b430a2-d947-4a5f-8197-5878e5e80143)

2024-03-14 22:14 UTC, olijeffers0n commented
Looks good GUI wise - is the link clickable? It can stay for the entire of the first launch I think. 

Once I have made my page you can use that as a link - PR blocked by docs for now.

2024-03-14 22:32 UTC, Leguan16 commented
> It can stay for the entire of the first launch I think.

I am more talking of a permanent component of this GUI. Like it doesn't really take up that much space and I think the GUI is used by relatively new people anyways. 

> is the link clickable?

yes.

> Once I have made my page you can use that as a link - PR blocked by docs for now.

Obviously, I just used it as a placeholder.

2024-03-15 00:47 UTC, granny commented
1. add a colon after "you can visit"   `...you can visit: <link>`
1. make it obvious that the link is clickable, e.g. underlined and set to the color blue

> I am more talking of a permanent component of this GUI. Like it doesn't really take up that much space and I think the GUI is used by relatively new people anyways.

Wouldn't hurt to permanently have it available in the GUI. It could also be abstracted into some kind of banner with rotating text.

2024-03-15 21:23 UTC, olijeffers0n commented
Docs have been merged :) - https://docs.papermc.io/paper/next-steps

2024-03-15 23:24 UTC, Leguan16 commented
Thanks Ollie. 
I changed the link, made it clear that its clickable (decided against a blue link since i don't think it would fit in the GUI if everything else is just black) and added more catches.  
![image](https://github.com/PaperMC/Paper/assets/59799222/000fdcd2-d914-4e67-9fe7-b713ac84f858)

2024-03-15 23:26 UTC, olijeffers0n commented
Yeah I like that, nice work

2024-03-16 18:09 UTC, lynxplay approved these changes

2024-03-16 18:10 UTC, Machine-Maker approved these changes

2024-03-16 18:10 UTC, merged