Add ItemStack array serialization methods
PaperMC/Paper pull request #10387
Opened 2024-04-04 15:01 UTC by kennytv

Serializing multiple items to bytes isn't trivial, so often beginners fall into the trap of using output IO streams and Bukkit serialization instead, so these provide helpful extra methods to deal with item arrays.

Also kept the serialization methods exposed in API as a sort of textbook example/nudge in the right direction of what should be used instead of object streams

2024-04-04 15:30 UTC, electronicboy commented on patches/api/0189-Add-Raw-Byte-ItemStack-Serialization.patch
> ++                if (item == null) {
this should handle empty stacks too

2024-04-04 16:01 UTC, electronicboy approved these changes

2024-04-12 21:17 UTC, Owen1212055 requested changes, later dismissed

2024-04-12 21:17 UTC, Owen1212055 commented on patches/api/0189-Add-Raw-Byte-ItemStack-Serialization.patch
> ++import org.bukkit.inventory.ItemStack;
stop kenny

2024-04-12 21:19 UTC, kennytv commented on patches/api/0189-Add-Raw-Byte-ItemStack-Serialization.patch
> ++import org.bukkit.inventory.ItemStack;
L+ratio https://discord.com/channels/289587909051416579/925530366192779286/1225463811859812382

2024-05-26 22:43 UTC, lynxplay requested changes
Brought up in a merge party in VC, but iirc the general notion was to move away from null item stacks in the API as they require a double check of `item != null && !item.isEmpty()`.

Would it make more sense for this method to yield back ItemStack#empty() instead of null if 0 is read?

2024-05-28 10:22 UTC, kennytv commented
While the api output still provides null items, I would not enforce air, otherwise you either produce inconsistent results or break easy use from api input

2024-05-30 23:41 UTC, bridgelol commented
Something nice for this might be to allow developers to directly invoke input streams upon deserialization and have a method that outputs a ByteArrayOutputStream as well, making it easier to apply compression

2024-06-07 17:17 UTC, Kinqdos commented
So whats the consensus now?

2024-07-19 20:30 UTC, gepron1x commented on patches/api/0187-Add-Raw-Byte-ItemStack-Serialization.patch
> ++                input.read(itemBytes);
consider using readNBytes or readFully? I used the similiar method for deserializing item arrays and, for long byte sequences, read() failed. I fixed the issue by doing
```java
final byte[] itemBytes = input.readNBytes(length);
```

2024-09-22 18:36 UTC, lynxplay approved these changes

2024-09-22 18:37 UTC, lynxplay commented on patches/api/0187-Add-Raw-Byte-ItemStack-Serialization.patch
> ++                input.read(itemBytes);
Resolved under the premise  that we are using a ByteArrayInputStream which does have full access to all data that will ever be read and hence will not require blocking/waiting for the nth byte to be available.

2024-09-22 18:39 UTC, kennytv commented on patches/api/0182-Add-Raw-Byte-ItemStack-Serialization.patch
> ++    public static @Nullable ItemStack @NotNull [] deserializeItemsFromBytes(final byte @NotNull [] bytes) {
Not nullable

2024-09-22 18:39 UTC, lynxplay commented on patches/api/0182-Add-Raw-Byte-ItemStack-Serialization.patch
> ++    public static @Nullable ItemStack @NotNull [] deserializeItemsFromBytes(final byte @NotNull [] bytes) {
True

2024-09-22 19:02 UTC, merged