Update patches to handle vineflower decompiler
PaperMC/Paper pull request #10406
Opened 2024-04-10 21:37 UTC by Machine-Maker

2024-04-10 21:54 UTC, jpenilla commented on patches/server/0202-Add-EntityKnockbackByEntityEvent-and-EntityPushedByE.patch
>  +                target.push(vec33.x() * e, vec33.y() * d, vec33.z() * e, entity); // Paper - Add EntityKnockbackByEntityEvent and EntityPushedByEntityAttackEvent
this looks like it needs indent

2024-04-10 21:56 UTC, jpenilla commented on patches/server/0245-Improve-death-events.patch
>  +            //this.setCarryingChest(false); // Paper - moved to post death logic
maybe update this comment while we are here

2024-04-10 21:58 UTC, kennytv commented on patches/server/0407-Fix-AdvancementDataPlayer-leak-due-from-quitting-ear.patch
> ++        manager.criterionData.computeIfAbsent(this, managerx -> Sets.newHashSet()).add(conditions);
Missing comment

2024-04-10 21:59 UTC, jpenilla commented on patches/server/0441-Reduce-blockpos-allocation-from-pathfinding.patch
>  +                    FluidState fluidState = blockState.getFluidState(); // Paper - Perf: Reduce blockpos allocation from pathfinding
indent looks wrong here

2024-04-10 22:14 UTC, jpenilla commented on patches/server/1013-Use-Velocity-compression-and-cipher-natives.patch
> ++        }
looks like start/end comments might need to be moved here?

2024-04-10 22:16 UTC, jpenilla commented on patches/server/1034-Improve-tag-parser-handling.patch
> +-                list.add((T)((NumericTag)tag).getAsByte());
should these be moved to mcdev fixes?

2024-04-10 22:23 UTC, Maintenancer commented on patches/server/1008-Optimise-general-POI-access.patch
> ++        });
move .map down a line and put the Paper end commend above that (and revert indent change on these 3 lines)

2024-04-12 14:25 UTC, kennytv requested changes

2024-04-12 14:25 UTC, kennytv commented on patches/server/1015-Collision-optimisations.patch
> ++                            if (!io.papermc.paper.util.CollisionUtil.voxelShapeIntersect(this.box, (double)i, (double)j, (double)k, (double)i + 1.0D, (double)j + 1.0D, (double)k + 1.0D)) { // Paper
Bad negation

2024-04-12 17:57 UTC, kennytv approved these changes
Should start a server and see if things around collision work as expected, but otherwise should be good

2024-04-12 18:49 UTC, lynxplay approved these changes

2024-04-12 19:14 UTC, merged

2024-04-12 19:14 UTC, jpenilla approved these changes