Add Configuration for finding Structures outside World Border
PaperMC/Paper pull request #10437
Opened 2024-04-19 20:54 UTC by notTamion

resolves #10391 
decided to go with the config option here since adding exclusions for only ender eyes seems unreasonable

2024-04-19 21:14 UTC, kennytv approved these changes

2024-04-20 14:40 UTC, olijeffers0n commented
Needs Docs PR please

2024-04-20 15:23 UTC, notTamion commented
will do

2024-04-20 18:18 UTC, lynxplay requested changes

2024-04-20 18:18 UTC, lynxplay commented on patches/server/0005-Paper-config-files.patch
> ++        public boolean findStructuresOutsideWorldBorder = false;
```suggestion
+        public boolean locateStructuresOutsideWorldBorder = false;
```

2024-04-20 19:29 UTC, lynxplay approved these changes

2024-04-20 19:29 UTC, merged