Add missing SpigotConfig logCommands check
PaperMC/Paper pull request #10659
Opened 2024-05-04 16:36 UTC by NonSwag

fixed the option commands.log in spigot.yml again
unsigned commands are logged even if command execution logging is disabled
fixes https://github.com/PaperMC/Paper/issues/10658

2024-05-04 19:48 UTC, notTamion commented on patches/server/1046-Add-missing-SpigotConfig-logCommands-check.patch
> ++        }
can just remove the brackets since this is only a 1 line if statement

2024-05-05 05:52 UTC, Machine-Maker requested changes
This can be merged into the general logging changes patch that we have. Either author can do that or whoever merges this.

2024-05-05 06:23 UTC, NonSwag commented
how do i do that ?

2024-05-05 06:35 UTC, notTamion commented
there are multiple ways. you can just go inside Paper-Server and soft reset the commit you created, then stash your changes, rebase edit the commit like explained in the contributing.md, stash pop, and then just continue like the contributing.md says

2024-05-05 07:10 UTC, NonSwag commented
Thanks, but I was more confused about the `general logging changes patch`
because i couldn't find anything like that

2024-05-05 08:12 UTC, notTamion commented
i assume Machine is talking about https://github.com/PaperMC/Paper/blob/master/patches/server/0805-Improve-logging-and-errors.patch

2024-05-05 16:37 UTC, Machine-Maker approved these changes

2024-05-05 16:40 UTC, lynxplay approved these changes

2024-05-05 16:41 UTC, merged