Added option to ignore entities when lightning strikes
PaperMC/Paper pull request #10689
Opened 2024-05-10 19:21 UTC by Jakush

Hey, in short, this patch adds option to ignore specific entity (or type of entity) from being damaged by lightning when lightning strikes.

2024-05-10 19:27 UTC, lynxplay commented
Hi, thank you for your PR :tada: 

Could you please elaborate on the usage of this API over simply listening to the respective events (Combust, HangingBreak, DamageEvent) which all expose the lightning strike entity?

This kind of API seems pretty counter active to the event driven design of the bukkit API.

2024-05-10 19:27 UTC, Machine-Maker commented
I would be more in favor of an event fired right before the lighting searches for an entity to hit to configure the parameters for that search or even to specify a specific entity before the search even happens. That seems more useful to me.

2024-05-10 20:01 UTC, lynxplay commented
Yea, then go with Machines way :+1: 
Adding this kind of state to the entity feels very off, an event prior to the lightnings actual strike sounds like the API friendlier approach.

2024-05-11 15:52 UTC, lynxplay commented
> Hello, I am trying to rebase my commit as in method 1, though I am not able to select anything, could you help me please?

Would probably be best if you ask for help on our [discord](https://discord.gg/papermc), github isn't a good place for that.

2024-05-11 17:16 UTC, notTamion commented on patches/server/1050-Added-option-to-ignore-entities-when-lightning-is-st.patch
> ++import org.bukkit.entity.LightningStrike;
Please use fully qualified imports as you are modifying a non-paper file

2024-05-11 17:22 UTC, notTamion requested changes
Adding methods for ignoring entities seems wrong. Why not call the event right after the server looks for entities to hit? then you can pass in the entities to the event and let the user add/remove entities

2024-05-11 17:32 UTC, Jakush commented on patches/server/1050-Added-option-to-ignore-entities-when-lightning-is-st.patch
> ++import org.bukkit.entity.LightningStrike;
Should be resolved

2024-05-11 17:44 UTC, notTamion commented
> For me it is better to use more "direct" way to somehow ignore other entities than to check with EntityDamageByEntityEvent, of course it could be done just with this event.

why exactly do you not want to use EntityDamageByEntityEvent? this really seems like a very simple and intended way of doing this. we also don't have an event that gets called for when a zombie is checking for players they can attack, so why add one for this?

2024-05-12 17:18 UTC, notTamion commented
> You could use this event as a more direct way for filtering entities
I feel like that event is already as direct as you need it to be
> I could also imagine more features in this event in the future as configuring selection radius which you wouldn't want in EntityDamageByEntityEvent
Sure though i believe such a thing could be added to the LightningStrikeEvent or LightningStrike Entity. though you could also manually get the Entities in a specific area and damage them which gives you even more control over it.
> Event for zombie checking for players which he could attack does not exist though there is more general event for this EntityTargetEvent
EntityTargetEvent is called when a Mob starts targeting a player not when he checks if they are in reach to attack

2024-05-12 17:56 UTC, closed without merging

2024-05-12 18:16 UTC, notTamion commented
oh i would have waited for other peoples opinion on this. Perhaps someone else has a different opinion on it

2024-05-12 19:15 UTC, notTamion commented
Thanks for your work on this anyways!