Expose anvil cost in the API
PaperMC/Paper pull request #10682
Opened 2024-05-09 17:11 UTC by pontaoski

2024-05-11 21:54 UTC, Machine-Maker requested changes
Looks good! I think this should be merged into our existing "More Enchantment API" patch however.

2024-05-11 23:05 UTC, pontaoski commented
done

2024-05-11 23:19 UTC, Machine-Maker approved these changes

2024-05-23 17:29 UTC, kennytv approved these changes

2024-05-23 22:49 UTC, lynxplay approved these changes

2024-05-23 23:02 UTC, pontaoski commented
rebartled

2024-05-25 23:47 UTC, merged