Fix Color Particle API
PaperMC/Paper pull request #10895
Opened 2024-06-17 03:55 UTC by TreemanKing

Checks particle datatype instead of particle type.

Closes #10872

2024-06-17 07:51 UTC, kennytv approved these changes

2024-06-18 00:45 UTC, Machine-Maker requested changes
To me, it doesn't make sense to allow calling color(Color,float) for non DustOptions types. The float size doesn't apply to stuff like ENTITY_EFFECT.

2024-06-18 01:57 UTC, TreemanKing commented
> To me, it doesn't make sense to allow calling color(Color,float) for non DustOptions types. The float size doesn't apply to stuff like ENTITY_EFFECT.

Currently, all colour methods lead to this as shown below, hence I didn't want to make changes to make big changes to the existing API as seen below. 

```java
public ParticleBuilder color(@Nullable Color color) {
    return color(color, 1);
}

@NotNull
public ParticleBuilder color(int r, int g, int b) {
    return color(Color.fromRGB(r, g, b));
}

@NotNull
public ParticleBuilder color(final int rgb) {
    return color(Color.fromRGB(rgb));
}
```

I'll go ahead and add that size doesn't apply to `ENTITY_EFFECT` unless you prefer for me to change up the first colour method to make that execute it for the datatype of `COLOR`.

2024-07-27 13:24 UTC, Lulu13022002 commented
This actually wouldn't work too since entity_effect take an argb integer and not a rgb so you would need to support both format in color(int) and handle conflict when the alpha channel is not set (for rgb it should be opaque, for argb it should be transparent).
I still believe there's no issue here except maybe the method name which is too generic but people should use #data directly for entity_effect.

2024-07-28 13:03 UTC, TreemanKing commented
> This actually wouldn't work too since entity_effect take an argb integer and not a rgb so you would need to support both format in color(int) and handle conflict when the alpha channel is not set (for rgb it should be opaque, for argb it should be transparent). I still believe there's no issue here except maybe the method name which is too generic but people should use #data directly for entity_effect.

I've gone ahead and added the ARGB and tested it with DUST and normal Color and it works with both. 

I'm unsure whether I should be changing anything within the `color(color, size)` function or whether it is fine as I am a bit confused so a bit of clarification would help.

2024-09-05 19:48 UTC, xmorose commented
![558213cfcd8a3e9bbed7fbc0a08f93a8](https://github.com/user-attachments/assets/b04b381e-613f-41b3-a38a-4a95618c2886)

2024-09-22 20:30 UTC, lynxplay approved these changes

2024-09-22 20:32 UTC, Machine-Maker approved these changes

2024-09-22 21:06 UTC, merged