Add option to throttle spawn attempts after several failures
PaperMC/Paper pull request #11099
Opened 2024-07-17 13:18 UTC by froobynooby

This patch adds an option to use a longer ticks-per-spawn for given mob types in chunks where previous spawn attempts have consecutively failed (e.g. spawnproofed chunks). The ticks-per-spawn and the number of failed attempts before they kick in are both configurable (the setting is disabled by default). The number of failed spawn attempts is stored with the chunk so it persists across unloads. As soon as a mob is able to spawn in a chunk, the failed spawn attempt counter resets and the chunk starts using the default ticks-per-spawn again.

This behaviour is useful on servers where players use mob farms. Mob farms typically require spawnproofing the surrounding chunks to improve rates, which causes the server to waste CPU cycles trying to find suitable spawn locations. By identifying suspected spawnproof chunks and throttling attempts at spawning mobs in them, it is possible to improve performance without noticeably affecting overall mob spawning behaviour.

I've been using a [similar patch](https://github.com/FroobWorld/Nabulus/commit/edd916abed9fbf921a023fccbbedd77bc7475858) on my reasonably busy survival server for nearly a year without any complaints from players.

For illustrative purposes I ran a simple test spending 5 minutes AFK at standard spawning-tower mob farm which had been properly spawnproofed.

Without patch (default ticks-per-spawn):
![image](https://github.com/user-attachments/assets/f037acaa-8d35-4466-be24-ac44e343c412)
With patch (multiplying default ticks-per-spawn by 10 after 1200 failed attempts):
![Screenshot from 2024-07-17 22-08-00](https://github.com/user-attachments/assets/284d3602-cb92-4cd1-9482-4ad4883e32f4)

2024-07-17 13:37 UTC, molor commented
It looks a bit like https://github.com/PaperMC/Paper/pull/9400

2024-07-17 21:38 UTC, froobynooby commented
Similar concept, but different implementations targeted at different problems. The other PR relates to spawn attempts that are failing due to plugins cancelling or aborting the PreCreatureSpawnEvent, while this one primarily relates to chunks where mobs have repeatedly failed to spawn for other reasons (e.g. no suitable spawning locations)

2024-07-18 09:39 UTC, lynxplay requested changes
I like the general concept of the patch 👍 
Keeping this on the chunk presumably also makes sense, I think there is some discussion to be had regarding EnumMap and object Long usage, but beyond that, just some minor nitpicks.

2024-07-18 09:39 UTC, lynxplay commented on patches/server/1042-Throttle-failed-spawn-attempts.patch
> ++                public int failedAttemptsThreshold = 1200;
Am I missing something here or is this value arbitary?

In which case, imo, it should be an IntOr.Disabled.

2024-07-18 09:39 UTC, lynxplay commented on patches/server/1042-Throttle-failed-spawn-attempts.patch
> ++    public final Map<net.minecraft.world.entity.MobCategory, Long> failedSpawnAttempts = new java.util.EnumMap<>(net.minecraft.world.entity.MobCategory.class); // Paper - throttle failed spawn attem
Is there a point in e.g. Int2Long/LongArrayList here?
May also just be premature tho. Sad fastutil hasn't added Enum2LongMaps yet.

2024-07-18 09:39 UTC, lynxplay commented on patches/server/1042-Throttle-failed-spawn-attempts.patch
> ++++ b/src/main/java/io/papermc/paper/configuration/WorldConfiguration.java
Configuration diff goes into the Paper Configurations patch.

2024-07-18 10:58 UTC, froobynooby commented on patches/server/1042-Throttle-failed-spawn-attempts.patch
> ++    public final Map<net.minecraft.world.entity.MobCategory, Long> failedSpawnAttempts = new java.util.EnumMap<>(net.minecraft.world.entity.MobCategory.class); // Paper - throttle failed spawn attem
Not too sure on what the best map is too be honest. There seems to be some use of Object2LongOpenHashMap for enum keys in other parts of the code - maybe that?

2024-07-18 13:08 UTC, froobynooby commented on patches/server/1042-Throttle-failed-spawn-attempts.patch
> ++    public final Map<net.minecraft.world.entity.MobCategory, Long> failedSpawnAttempts = new java.util.EnumMap<>(net.minecraft.world.entity.MobCategory.class); // Paper - throttle failed spawn attem
I've just changed it to use an array which I think is probably the simplest approach, let me know if you think there's a better way

2024-07-18 13:12 UTC, lynxplay commented on patches/server/1042-Throttle-failed-spawn-attempts.patch
> ++    public final Map<net.minecraft.world.entity.MobCategory, Long> failedSpawnAttempts = new java.util.EnumMap<>(net.minecraft.world.entity.MobCategory.class); // Paper - throttle failed spawn attem
Idk, didn't have to change it just yet, I was hoping for some feedback from other team members 😅 
But yea, this certainly works and avoids unboxing nicely. Thank you :)

2024-08-10 12:10 UTC, froobynooby commented
> This patch makes creeper farms not work. Can you fix this? https://www.youtube.com/watch?v=qyUZ0iXkdBA

Do you have a world download/schematic and configuration you could share?

The patch slows down spawn attempts in chunks that have repeatedly failed to spawn mobs - it shouldn't be stopping spawn attempts altogether. Make sure you're not configuring `failed-attempts-threshold` too low (I recommend setting it to 1200) or the `throttled-ticks-per-spawn` settings too high (I recommend setting them to 10x the normal `ticks-per-spawn` settings)

2024-08-11 22:14 UTC, electronicboy commented
I would imagine that anything relying on spawn proofing is generally going to suck hard with this sort of feature, the concepts are pretty much incompatible, IMHO.

2025-03-23 19:16 UTC, closed without merging