spark
PaperMC/Paper pull request #11093
Opened 2024-07-16 23:05 UTC by kashike

https://github.com/PaperMC/Paper/discussions/10565

2024-07-17 07:30 UTC, MiniDigger commented
see https://github.com/PaperMC/docs/issues/446 for docs changes

2024-07-17 07:36 UTC, SirYwell commented on patches/server/1043-spark.patch
> ++            this.server.spark.enableBackgroundProfiler(); // Paper - spark
Does this mean the OpenJ9 warning is printed twice?

2024-07-17 09:12 UTC, Outfit8TSB requested changes
remove timings patch as it's going to replaced with spark.
i heard that it's now deprecated and marked for removal in paper.

2024-07-17 09:19 UTC, zlataovce commented
> remove timings patch as it's going to replaced with spark. i heard that it's now deprecated and marked for removal in paper.

it is deprecated and turned off by default now, but it shouldn't be removed entirely yet, since there are people which may still want to use it/need to use it

2024-07-17 09:19 UTC, Outfit8TSB commented
> remove timings patch as it's going to replaced with spark. i heard that it's now deprecated and marked for removal in paper.

disregard this comment, this is not gonna happen as this will turned off as default

2024-07-17 15:29 UTC, Leguan16 commented
Should also add a config option to disable spark.

2024-07-19 09:47 UTC, kennytv requested changes
The `We recommend installing the spark profiler as a replacement:` warning in the timings patch needs updating

It also currently throws exceptions on stop (if you have any other plugin installed) due to a bukkit service being registered with a null plugin, presumably within spark

2024-07-19 09:47 UTC, kennytv commented on patches/server/1041-spark.patch
> ++                MCUtil.ensureMain(runnable);
Should try catch the runnable with logging instead of breaking on main, just in case

2024-07-19 09:47 UTC, kennytv commented on patches/server/1041-spark.patch
> ++    implementation("me.lucko:spark-paper:1.10.79-SNAPSHOT")
Don't forget to update spark before merging 👀

2024-07-20 16:12 UTC, kennytv approved these changes

2024-07-20 16:35 UTC, merged

2024-07-29 05:34 UTC, Outfit8TSB commented
I swear that this will lead to confusion as lucko/spark#424 didn't merge. If Spark keeps disabling after the update, it will get confused, This Pull was necessary to merge. As Spark will get disabled without warning.