Disable default world loading
PaperMC/Paper pull request #1125
Opened 2018-05-18 13:42 UTC by theminecoder

This enables minigame-like servers that most of the time are loading pre-made worlds
to not have the extra main world(s) loaded on top of their custom ones.

When in this mode and no world are loaded by the time the server is loaded a new
will print out to the console to make sure that people know what they are doing.

2018-05-18 14:02 UTC, aikar requested changes
This patch idea scares me for maintainability. This will require lots of diffs to fix the expectation to always have a world loaded.

A server without any worlds is useless..

I feel like this isn't the right way to solve this desire.

I've always wanted simple multi world management to be built into paper, and I feel that would better so your custom world would then fall into slot 0.

I also think you can pretty much enable this behavior today by setting keep spawn loaded radius to 0. That would avoid any chunks loading for the world.

maybe instead a world-setting for disabled: true that implies 0 spawn radius, and skip ticking the world all together?

That would be better to maintain and understand than this approach.

2018-05-18 14:02 UTC, aikar commented on Spigot-Server-Patches/0299-Add-ability-to-not-load-default-worlds.patch
> ++        savePlayerData = loadDefaultWorlds && getBoolean("settings.save-player-data", savePlayerData);
This doesn't feel intuitive to me that player data saving would be disabled for this.

I understand that data is saved in a worlds folder, but that is more an implementation detail to me.

I would rather see player save data location and enablement to be a separate patch / config.

2018-05-18 14:22 UTC, electronicboy requested changes
Aikar beat me to it on a lot of points, but there are a lot of concerns about this patch, the maintainability of it, and the complications this could cause.

There is no sane reason for a server to ever be running without a world, it would make more sense to just minimize the impact of having these worlds loaded, or to provide some way to allow people to set where to load the default world from programmatically, e.g. with a system property

2018-05-18 14:22 UTC, electronicboy commented on Spigot-Server-Patches/0299-Add-ability-to-not-load-default-worlds.patch
> ++        if(server.worlds.size() <= 0) {
// Paper

2018-05-18 14:22 UTC, electronicboy commented on Spigot-Server-Patches/0299-Add-ability-to-not-load-default-worlds.patch
> ++    public CustomFunctionData getCustomFunctionData() {
OBF helpers should be placed directly above the method as a one liner so that it conflicts on a method change.

2018-05-18 14:22 UTC, electronicboy commented on Spigot-Server-Patches/0299-Add-ability-to-not-load-default-worlds.patch
> ++import com.destroystokyo.paper.PaperConfig;
as above; Please don't modify lines added by existing patches unless needed.

2018-05-18 14:22 UTC, electronicboy commented on Spigot-Server-Patches/0299-Add-ability-to-not-load-default-worlds.patch
> ++import com.destroystokyo.paper.PaperConfig;
Don't use an import here, qualify the class properly

2018-05-18 14:22 UTC, electronicboy commented on Spigot-Server-Patches/0299-Add-ability-to-not-load-default-worlds.patch
> +-        int worldCount = 3;
Undo *all* indentation changes in here. This will needlessly conflict and cause headaches on a merge.

2018-05-18 16:40 UTC, aikar reviewed
This is getting even more unruly with changes. I am not comfortable adding this patch at all. It would be one that would be immediately dropped on 1.13 and I rather us not add more patches like that.

2018-06-10 14:11 UTC, electronicboy commented
While the premise is nice, I think the there is some level of agreement that this patch is a bit too unruly and poses many concerns over maintenance with the scope of changes, it would be nice to have patches akin to this which make the server optionally fit the needs of people who don't need stuff like this, however, for every patch, the advantages have to outweigh the maintenance cost, and shamefully, especially considering the number of people who'd likely take advantage of this, I cannot personally justify the costs for this patch

Due to this and the lack of overall commentary, I'm going to be closing this in the meantime.

There are ways in which the intent of this patch could likely be achieved with less invasive means or in a manner which would make it more useful to the world as opposed to a smaller audience

2018-06-10 14:11 UTC, closed without merging