Properly destroy placed blocks on the end platform
PaperMC/Paper pull request #11292
Opened 2024-08-18 11:22 UTC by DerEchtePilz

Fixes #11142 
Please let me know if there's something I should change or if this is even the right approach to fixing this bug but in my local testing, this patch definitely seemed to do the trick and blocks were properly destroyed.

2024-08-18 21:09 UTC, Machine-Maker requested changes
Might also be worth actually commenting out the destroyBlock call above this with a comment saying it was moved down.

2024-08-18 21:09 UTC, Machine-Maker commented on patches/server/1051-Properly-destroy-placed-blocks-on-the-end-platform.patch
> ++            }
Make the loop variable type `CraftBlockState` and then you can use `CraftBlockState#getPosition` to directly get the BlockPos.

Also, this loop should be behind a check on that boolean flag that also guards the destroyBlock call from above.

2024-08-20 20:31 UTC, Machine-Maker approved these changes

2024-08-25 19:02 UTC, lynxplay approved these changes

2024-08-25 19:19 UTC, merged