Fix setDamage being ran on compasses
PaperMC/Paper pull request #11317
Opened 2024-08-22 22:01 UTC by NewwindServer

In VanillaChestLoot, compasses accidentally have a setdamage loot function on them, but compasses don't take durability, resulting in a warning 
"Couldn't set damage of loot item 1 minecraft:compass"
This patch simply removes attempting to add damage to compass

2024-08-22 22:43 UTC, Owen1212055 commented
Is there a vanilla bug report on this?

2024-08-23 00:38 UTC, Machine-Maker requested changes
Changing it here doesn't do anything. You are just changing it for the data generator. You have to actually change the vanilla loot table.

Vanilla issue: https://bugs.mojang.com/browse/MC-266489

2024-08-25 17:51 UTC, lynxplay approved these changes

2024-08-25 17:51 UTC, Machine-Maker approved these changes

2024-08-25 17:52 UTC, merged

2024-08-26 11:33 UTC, MiniDigger commented
do we add the vanilla issue to the patch description and the paper comment?