Skip Entity and Tile Entity ticking in chunks scheduled for unload
PaperMC/Paper pull request #1132
Opened 2018-05-27 19:24 UTC by mikroskeem

Fixes #1131

Obviously, code should be reviewed and I think that one if statement could be omitted and `&&`/`||` trickery could be used instead.

2018-05-28 04:10 UTC, zachbr commented
This should be merged back into the patch that introduced the chunk unload delay prior to merging.

2018-05-28 04:18 UTC, zachbr commented
Miscellaneous style aside, I'm not entirely sure @aikar wanted a config option for this.

I can't think of any cases, gameplay or performance, in which you'd want to tick these chunks.

2018-05-28 05:00 UTC, zachbr commented on Spigot-Server-Patches/0140-Delay-Chunk-Unloads-based-on-Player-Movement.patch
> ++    public static boolean skipEntityTickingInChunksScheduledForUnload = true;
Move to PaperWorldConfig

Can wait until we figure out why we want it.

2018-05-29 15:39 UTC, aikar requested changes

2018-05-29 15:39 UTC, aikar commented on Spigot-Server-Patches/0140-Delay-Chunk-Unloads-based-on-Player-Movement.patch
> ++        // Paper start - Skip ticking in chunks scheduled for unload
Please move this check to checkIfActive instead on ActivationRange, where we already have a chunk reference.

2018-05-30 15:26 UTC, aikar approved these changes

2018-05-30 20:31 UTC, merged