Fix/scoreboard delegate
PaperMC/Paper pull request #11453
Opened 2024-09-30 15:29 UTC by Intybyte

Fixes #11296

2024-09-30 16:32 UTC, Leguan16 reviewed
Usually, if nms/bukkit files are modified FQN should be used instead of imports to reduce the diff. Also, every line that is added needs to be marked with a comment. For more information refer to the CONTRIBUTING.md :)

2024-10-01 02:18 UTC, Machine-Maker submitted a review, later dismissed

2024-10-01 02:18 UTC, Machine-Maker commented on patches/server/1065-Create-Limited-set-for-Entity.patch
> ++++ b/src/main/java/io/papermc/paper/entity/PaperLimitedSet.java
Lets put this in some `util` package or smth. Instead of `entity`. Also, just call it like `SizeLimitedSet`, Paper doesn't really apply to it.

2024-10-01 02:18 UTC, Machine-Maker commented on patches/server/1065-Create-Limited-set-for-Entity.patch
> ++public class PaperLimitedSet extends HashSet<String> {
Use `@NullMarked`

2024-10-01 02:18 UTC, Machine-Maker commented on patches/server/1065-Create-Limited-set-for-Entity.patch
> ++import org.jetbrains.annotations.NotNull;
Use `@NullMarked` on the type and remove any `NotNull/NonNull` annotations.

2024-10-01 09:42 UTC, imDaniX requested changes

2024-10-01 09:42 UTC, imDaniX commented on patches/server/1065-Create-Limited-set-for-Entity.patch
> ++        return this.add(tag);
Did you mean `super.add(tag)`? Otherwise, seems like a recursive loop to me

2024-10-01 09:42 UTC, imDaniX commented on patches/server/1065-Create-Limited-set-for-Entity.patch
> ++        int currentSize = this.size();
The `currentSize` field seems redundant? We already have the `size()` method, which is automatically increased anyway

2024-10-01 09:42 UTC, imDaniX commented on patches/server/1065-Create-Limited-set-for-Entity.patch
> ++            edited = added || edited;
Without `currentSize`, this can be simplified to `edited |= this.add(tag)`.

2024-10-04 16:49 UTC, Lulu13022002 commented on patches/server/1065-Create-Limited-set-for-Entity.patch
> ++        this.tags = new io.papermc.paper.util.SizeLimitedSet(1024); // Paper - Create Limited set for Entity
you can use the constant MAX_ENTITY_TAG_COUNT

2024-10-04 16:49 UTC, Lulu13022002 commented on patches/server/1065-Create-Limited-set-for-Entity.patch
> ++        if (this.size() >= maxTags) {
Add this. before field access

2024-10-04 16:49 UTC, Lulu13022002 commented on patches/server/1065-Create-Limited-set-for-Entity.patch
> ++public class SizeLimitedSet extends HashSet<String> {
I feel the name is too generic for what this does unless you add a generic to it and remove tag reference.

2024-10-20 08:03 UTC, Amejonah1200 commented on patches/server/1065-Create-Limited-set-for-Entity.patch
> ++    private final int maxTags;
It has nothing to do with tags, consider renaming to `maxSize` instead.

2024-10-20 23:11 UTC, electronicboy approved these changes
I do ponder if we should move the set over to mc-util, but, otherwise, this lgtm

2024-10-20 23:42 UTC, lynxplay approved these changes

2024-10-21 16:47 UTC, Intybyte commented
what are the advantages of using a delegate in this case?

2024-10-21 16:48 UTC, electronicboy commented
it's a reusable generic container wrapper class

2024-10-21 16:48 UTC, lynxplay commented
The fact that we can reuse this type for different set implementations. The previous implementation would lock the type into the speed/contracts of hashset.

2024-12-08 22:37 UTC, merged