Add test for org.bukkit.craftbukkit.entity.CraftMinecart#minecartEntityTypeToMaterial
PaperMC/Paper pull request #11536
Opened 2024-10-30 22:35 UTC by Abelkrijgtalles

Hi, I hope you're having a wonderful day.
I've added a test for org.bukkit.craftbukkit.entity.CraftMinecart#minecartEntityTypeToMaterial, as requested in https://github.com/PaperMC/Paper/issues/11511.
In the current approach I've hardcoded the Minecart types, as is done in the function.

2024-10-30 22:40 UTC, lynxplay commented
The whole point of the test is to ensure that the hardcoded values in the function are still correct.
Testing this with *another* set of hardcoded function is useless.
Iterate the item registry, find MinecartItems, reflectively access their entity type, ensure the static method correctly matches that.

2024-10-30 22:46 UTC, Abelkrijgtalles commented
Alright, I will try to fix it to use the Item registry

2024-10-30 22:53 UTC, lynxplay requested changes
Also merge this into the respective patch that introduces the method under test.
No need for a new patch here.

2024-10-31 12:13 UTC, Abelkrijgtalles commented
I've fixed it to not be hard-coded, except for `EntityType.SPAWNER_MINECART`, as that doesn't have a corresponding item, and the function just returns a normal minecart. I've used a string based system, as I couldn't find any other way to do it. The current approach gets the short string of the entitytype (like `chest_minecart`), and gets the item with the corresponding  `ResourceLocation`

2024-10-31 12:16 UTC, lynxplay commented
Thanks!
You'll need to annotate the class with `@AllFeatures` in order for the test suite to pick it up and run correctly.

2024-10-31 12:16 UTC, Abelkrijgtalles commented
I'll probably also make a PR for changing it to a switch statement, as that's a better choice then 7 if/else statements.

2024-10-31 12:17 UTC, Abelkrijgtalles commented
> Thanks! You'll need to annotate the class with `@AllFeatures` in order for the test suite to pick it up and run correctly.

Will do

2024-10-31 12:37 UTC, Abelkrijgtalles commented
I've added it, so it should be good to go.

2024-10-31 12:56 UTC, Leguan16 commented on patches/server/0448-API-to-get-Material-from-Boats-and-Minecarts.patch
> ++
I know it's a massive nit but couldn't the diff be reduced by a bit by removing the empty lines? 
(Edit: I meant inside the method body not all lines, I thought I wouldn't have to specify)

2024-10-31 12:59 UTC, masmc05 commented on patches/server/0448-API-to-get-Material-from-Boats-and-Minecarts.patch
> ++
Is the diff size important in new files? I thought it was important purely to prevent conflicts in future merges, which is unrelated in context of new files

Edit: yeah, removing the whitespaces indeed worsened the readability of the code, and I'm sure making it a nightmare to work with in future. Not worth at all the decreased patch size

2024-10-31 13:28 UTC, Abelkrijgtalles commented on patches/server/0448-API-to-get-Material-from-Boats-and-Minecarts.patch
> ++
I'll remove it just in case

2024-10-31 13:32 UTC, Abelkrijgtalles commented
I've removed the empty lines. If it's to aggressive, just let me know.

2024-10-31 13:47 UTC, Abelkrijgtalles commented
Alright.

2024-10-31 15:51 UTC, Abelkrijgtalles commented
Hi, I was just wondering, are there any specific things holding the merge back?

2024-10-31 15:53 UTC, lynxplay commented
The fact that no developer had time to review this yet.
Give it time, someone will get it merged soon enough.

2024-10-31 16:25 UTC, Abelkrijgtalles commented
Alright, thanks for the update

2024-10-31 17:09 UTC, closed without merging

2024-10-31 17:09 UTC, lynxplay commented
Can you reopen the PR to master please :)
I'll try to review it tonight and get that merged.

2024-10-31 21:09 UTC, Abelkrijgtalles commented
Alright, will do