[ci skip] Fix UseCooldownComponent javadocs
PaperMC/Paper pull request #11565
Opened 2024-11-02 13:34 UTC by Leguan16

I also changed the method name in the Craft equivalent class. I don't know if it makes sense. Can also just be dropped if not needed. 

If it can be kept and there is already a patch for such things lmk. I didn't find one in my quick search.

2024-11-02 16:26 UTC, Machine-Maker requested changes

2024-11-02 16:26 UTC, Machine-Maker commented on patches/api/0053-Fix-upstream-javadocs.patch
> ++     * Gets the time in seconds it will take for this item to be used again.
`for this item to be available for use again`

2024-11-02 16:26 UTC, Machine-Maker commented on patches/api/0053-Fix-upstream-javadocs.patch
> ++     * Sets the time in seconds it will take for this item to be used again.
`for this item to be available for use again`

2024-11-02 19:50 UTC, Machine-Maker approved these changes

2024-11-03 09:26 UTC, MiniDigger commented on patches/api/0053-Fix-upstream-javadocs.patch
> ++ * Represents a component which determines the cooldown applied to use this item.
```suggestion
+ * Represents a component which determines the cooldown applied when using this item before it is available for use again.
```

2024-11-03 12:55 UTC, Leguan16 commented on patches/api/0053-Fix-upstream-javadocs.patch
> ++ * Represents a component which determines the cooldown applied to use this item.
changed it.

2024-11-03 18:44 UTC, MiniDigger approved these changes

2024-11-09 22:18 UTC, lynxplay approved these changes

2024-11-09 22:24 UTC, merged