configure mockito agent
PaperMC/Paper pull request #11560
Opened 2024-11-01 23:47 UTC by yannicklamprecht

Addresses issues with newer Java versions and Mockito.

- https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html#0.3
- https://openjdk.org/jeps/451

2024-11-05 14:27 UTC, electronicboy approved these changes
maybe somebody more in-tune with gradle will flag this, but, this LGTM

2024-11-05 19:19 UTC, jpenilla requested changes
This should use a CommandLineArgumentProvider to avoid resolving dependencies during configuration time - I think there are some other spots that may need to change in this direction too, for example stuff used by Javadoc, but it would be better to not increase the tech debt here.

2024-11-05 20:12 UTC, yannicklamprecht commented
> This should use a CommandLineArgumentProvider to avoid resolving dependencies during configuration time - I think there are some other spots that may need to change in this direction too, for example stuff used by Javadoc, but it would be better to not increase the tech debt here.

Hopefully addressed that to your liking.

2024-11-05 22:53 UTC, jpenilla requested changes

2024-11-05 22:53 UTC, jpenilla commented on patches/api/0003-Test-changes.patch
> ++import org.gradle.kotlin.dsl.newInstance // Paper - configure mockito agent that is needed in newer java versions
I don't think this should be needed from a kts build script

2024-11-05 22:56 UTC, jpenilla commented on patches/api/0003-Test-changes.patch
> ++import org.gradle.kotlin.dsl.newInstance // Paper - configure mockito agent that is needed in newer java versions
Also, you don't need to annotate with `InputFiles` on properties annotated with `CompileClasspath` - our build script won't run with Gradle versions old enough to require both.

2024-11-05 23:18 UTC, jpenilla approved these changes
Looks fine, but one thing to consider is if Spigot configures the equivalent in Maven then this should move to the setup gradle build patch.

2024-11-09 21:47 UTC, Machine-Maker approved these changes

2024-11-09 21:49 UTC, merged