Manually reset attribute map on restoring player instance
PaperMC/Paper pull request #11580
Opened 2024-11-04 22:03 UTC by electronicboy

Spigots reuse of the entity instances causes the server to try to copy a players existing attributes back onto itself, which causes an error.

We'll manually clear the applicable attribute modifiers, but, in the long run, we should just revert out of the broken behavior of trying to reuse ServerPlayer instances.

2024-11-06 10:21 UTC, kennytv approved these changes

2024-11-06 10:21 UTC, kennytv commented on patches/server/1060-Manually-reset-attribute-map-on-restoring-player-ins.patch
> ++    public void removeAllTransientModifiers() {
This method scared me for a second, should add a note that we expect the getters to return copies

2024-11-09 23:12 UTC, lynxplay commented
Removing transient modifiers means armor needs to reapply.
That does not happen because we are not actually a new entity.

2024-11-09 23:12 UTC, lynxplay requested changes
Removing transient modifiers means armor needs to reapply.
That does not happen because we are not actually a new entity.

2024-11-24 22:29 UTC, lynxplay commented
Closing this as the immediate issue has been solved by upstream.
It was solved however by breaking vanilla logic and no longer removing attribute modifiers on death.

The API needs to be fleshed out to support plugins to set attribute modifiers that do/do not persist through death.

2024-11-24 22:29 UTC, closed without merging