Added PlayerUseBowWithoutProjectileEvent #11668
PaperMC/Paper pull request #11669
Opened 2024-11-26 16:38 UTC by Chaosdave34

Added PlayerUseBowWithoutProjectileEvent when a player tries to load a crossbow or draw a bow without having a suitable projectile in their inventory. Makes it possible to set a projectile and enable the player to use the weapon nevertheless.

2024-11-26 18:08 UTC, lynxplay requested changes
Welcome to paper and thank you for your first PR :partying_face: 

Left some basic comments regarding annotations.
The PR is also missing javadocs on the API types.

Beyond that, the event name feels a bit off, the player isn't using the bow there, it is searching for a projectile. We already have some other events there so *maybe* we can look into merging those concepts? Not sure tho.

2024-11-26 18:08 UTC, lynxplay commented on patches/api/0501-Added-PlayerUseBowWithoutProjectileEvent.patch
> ++public class PlayerUseBowWithoutProjectileEvent extends PlayerEvent {
`@NullMarked`

2024-11-26 18:08 UTC, lynxplay commented on patches/api/0501-Added-PlayerUseBowWithoutProjectileEvent.patch
> ++    public PlayerUseBowWithoutProjectileEvent(@NotNull final Player player) {
Remove `@NotNull` as per contributing.md, we use jspecify annotations in new paper types.

2024-11-26 18:08 UTC, lynxplay commented on patches/api/0501-Added-PlayerUseBowWithoutProjectileEvent.patch
> ++        return projectile;
Requires defensive copy.

2024-11-26 18:08 UTC, lynxplay commented on patches/api/0501-Added-PlayerUseBowWithoutProjectileEvent.patch
> ++        this.projectile = projectile;
Requires defensive copy.

2024-11-27 10:46 UTC, Chaosdave34 commented
Maybe PlayerTryUseBowWithoutProjectileEvent would be better?

I already thought about using the PlayerReadyArrowEvent for this.
The simplest way to implement the functionality to let a player fire a bow without having an arrow in their inventory seems to be this for me, because when creating a new ItemStack (even with CraftItemStack#asNmsCopy(), to set the arrow from the CraftItemStack used in the event), it would be diffcult to consume the arrow (removing the arrow from the player inventory) when the arrow ist not manipulated by the event.
(get the arrow ->  create a craftbukkit copy -> call the event with the arrow -> the arrow is not manipulated -> get the arrow from the event -> create a nms copy -> created a new ItemStack although the original one was not changed -> Player#useAmmo() breaks; or am I missing something?)

2024-12-01 19:26 UTC, lynxplay commented
No you are not missing anything I don't think.
I don't see a nice way to have this interact with player ready arrow event either no.

Naming wise, well, realistically this should probably not be limited to bows only.
It is a general "PlayerFailedProjectileSearch" or something (shitty name but you get the gist :sweat_smile:) as this is going to be called for crossbows as well.

I'll try to get this PR into a pr party next weekend so I can poke some other maintainers on a better name for this, but I think the functionality this is adding is worth having :+1:

2024-12-22 23:28 UTC, closed without merging