Add removal reason to EntityRemoveFromWorldEvent
PaperMC/Paper pull request #11779
Opened 2024-12-23 05:10 UTC by TonytheMacaroni

Supercedes #10149.

2024-12-23 09:19 UTC, kennytv commented
Building fails - you can also now remove the // Paper comments inside of source files, and for those lines that had a CB comment only from adding the event cause, you can replace their comment with ours

2024-12-24 05:43 UTC, TonytheMacaroni commented
Re-added the missing test file diff; seems I missed it when updating the PR. Modified the comments.

2024-12-24 22:21 UTC, Machine-Maker requested changes
For the `Cause` enum, I think the 2 booleans should be removed and just be made booleans on the event itself. I don't like tying those to the removal reason. What if a removal reason can be used in 2 places where those values should be different. I don't see much benefit tying them together instead of just putting them on the event itself.

2025-01-12 20:49 UTC, lynxplay commented
After *even more* discussion on this, apparently the intention of our RemoveFromWorldEvent is not the same as EntityRemoveEvent, specifically around the time they are called.

The bukkit remove event has a cause but may be called at times (especially around chunk unloads) where edits to the entity are not longer respected.

I'll open a follow up PR undeprecating the bukkit event with your as co-author given all the work you did here (and it was a lot of work) so all credits to you and sorry for the confusion on this change.

2025-01-12 20:49 UTC, closed without merging