Fix BlockRedstoneEvent for tripwire hooks
PaperMC/Paper pull request #11791
Opened 2024-12-23 18:24 UTC by Lulu13022002

Original: https://github.com/PaperMC/Paper/pull/9724

2024-12-24 14:56 UTC, lynxplay requested changes
Tested and works, just nitpicks (especially around the obfhelpers, the other is whatever)

2024-12-24 14:56 UTC, lynxplay commented on paper-server/patches/sources/net/minecraft/world/level/block/TripWireHookBlock.java.patch
> ++            boolean wasPowered = flag1, willBePowered = flag3; // Paper - OBFHELPER
These should diff the actual final assignment of the values, otherwise this kind of diff does not *really* help during an update (e.g. if flag3 becomes flag4, the diff *might* still apply and the developer might not notice.

2024-12-24 14:56 UTC, lynxplay commented on paper-server/patches/sources/net/minecraft/world/level/block/TripWireHookBlock.java.patch
> ++                    level.getCraftServer().getPluginManager().callEvent(redstoneEvent);
callEvent();

2024-12-24 14:56 UTC, lynxplay commented on paper-server/patches/sources/net/minecraft/world/level/block/TripWireHookBlock.java.patch
> ++                        cancelledReceiverHook = true;
`cancelledReceiverHook = redstoneEvent.getNewCurrent() != newCurrent;`
saves us a random if and imo is a fine change for such a readable expression.

2024-12-24 14:56 UTC, lynxplay commented on paper-server/patches/sources/net/minecraft/world/level/block/TripWireHookBlock.java.patch
> ++                level.getCraftServer().getPluginManager().callEvent(eventRedstone);
Same two comments as above. callEvent() and `if(bool) a = true` being a weird thing.

2024-12-26 18:40 UTC, lynxplay approved these changes

2024-12-26 18:41 UTC, Machine-Maker approved these changes

2024-12-26 18:42 UTC, merged