Banner pattern registry modification
PaperMC/Paper pull request #11803
Opened 2024-12-24 02:26 UTC by kokiriglade

https://github.com/PaperMC/Paper/pull/11658

2024-12-24 22:30 UTC, Machine-Maker requested changes

2024-12-24 22:30 UTC, Machine-Maker commented on paper-api/src/main/java/io/papermc/paper/registry/data/BannerPatternRegistryEntry.java
> +@NullMarked
Don't need this since the package-info.java in that directory has it.

2024-12-24 23:59 UTC, Machine-Maker approved these changes

2024-12-26 23:57 UTC, Owen1212055 approved these changes
Tested locally, looks good to me!

2024-12-26 23:57 UTC, merged