Add new Lidded API, deprecating existing bukkit Lidded API. Adds PlayerLiddedOpenEvent
PaperMC/Paper pull request #11814
Opened 2024-12-25 02:00 UTC by 456dev

replaces #11379, pre hard-fork pr

minimal changes from previous pr, mostly some variable renames + //paper comments, to be in-line with the new guidelines.

Additionally, I need to double check the implementation of PlayerLiddedOpenEvent for shulker boxes, particularly if players can leak.

previous description below:

Featuring
- 5 LidModes, 3 of which were not possible before
- The ability to get if the lid actually should be open, if a player is in the container
- The ability to get if the lid is open, from api or the player itself

This also deprecates Bukkits api because of the confusing and outright incorrect javadocs (so those now accurately represent the behaviour)

Testable with the included testplugin commands.

I'm not 100% sure if the PaperLidded interface is the best way of doing this, but it is working
Also, let me know if the naming needs to change.
- [ ] see if anything important is skipped in the check method scheduled every 5 ticks on chests

2024-12-25 02:13 UTC, 456dev commented
Fixed #11364 with new api

2024-12-25 03:50 UTC, 456dev commented on paper-api/src/main/java/org/bukkit/block/Lidded.java
> +@Deprecated // Paper - Deprecate Bukkit's Lidded API
TODO: remove this lone `// paper` comment
```suggestion
@Deprecated
```

2024-12-25 03:53 UTC, 456dev commented on paper-api/src/main/java/io/papermc/paper/event/player/PlayerLiddedOpenEvent.java
> + * This event is called twice for double chests, once for each half.
todo: fix global implementation for double chests.

iirc as well as this double-fire behaviour, modifying the state of the non-dominant half doesnt play a sound, but still keeps the animation open seperately.

2024-12-25 03:54 UTC, 456dev commented on paper-api/src/main/java/io/papermc/paper/block/Lidded.java
> +     * Gets how the lid would be without any lidded mode, based on players interacting with the block.
TODO: replace with smth like

```suggestion
     * Gets how the lid would be with {@link LidMode.DEFAULT}
     * I.E. based on players interacting with the block.
```

2024-12-25 03:55 UTC, 456dev commented on paper-api/src/main/java/io/papermc/paper/block/LidState.java
> +@NullMarked
Is this actually needed, since its a very simple enum?

2025-03-17 09:02 UTC, Warriorrrr requested changes

2025-03-17 09:02 UTC, Warriorrrr commented on paper-api/src/main/java/io/papermc/paper/block/LidState.java
> +@NullMarked
This enum and LidMode don't have anything that would be affected by it, so I would say it's not needed.

2025-03-17 09:02 UTC, Warriorrrr commented on paper-api/src/main/java/org/bukkit/block/Lidded.java
>      boolean isOpen();
If these names are misleading, I think it would be better to fix the implementation rather than changing the javadoc and deprecating the methods.

I think it would also be better to add onto this class rather than creating a whole new interface.

2025-03-17 09:02 UTC, Warriorrrr commented on paper-server/src/main/java/org/bukkit/craftbukkit/block/CraftBarrel.java
> +    }
The methods being moved around like this creates a lot of unnecessary diff.

2025-03-18 13:43 UTC, 456dev commented on paper-api/src/main/java/org/bukkit/block/Lidded.java
>      boolean isOpen();
Just to confirm, it would be preferred to completely replace this API in 1 step?

I didn't want to create any breaking changes, and making it separate would allow for it to be cleanly removed separately at a later point.

2025-03-18 19:56 UTC, Warriorrrr commented on paper-api/src/main/java/org/bukkit/block/Lidded.java
>      boolean isOpen();
What I'd prefer would be to add the methods to the existing API and leave the old methods the same, and changing the impl of the old methods to use the new api impl.

I'll wait for others to respond with their thoughts in case I'm not making sense.

2025-10-05 22:29 UTC, lynxplay commented
This is the third of fourth time I am reading through this PR and I think the surface area of this is just too large for me to be confortable with merging this.
The fact that we are duplicating seemingly large parts of the process between the shulker and containers screams for externalized handling.

The same can be said for the commented out craftbukkit diff. Just delete it, it makes the code feel even *more* duplicate.

`private final java.util.Set<Player> cancelledPlayer` feels dangerous.

But yea, I think the only sane way we will ever get a PR like this in is completely ripping out CB lidded diff in commit A and reintroducing a very much externalised lidded system into the affected types.
With that I mean `io.papermc.something.ContainerLiddedState` classes that do *all* the things that are currently copied around like maintaining the lidded state, openCounter etc.

As said, the giant diff in the CB types also does not help making this more reviewable but moving thins from patches into normal types to handle state would be a good start to this.

2025-11-01 17:34 UTC, lynxplay commented
Going to close this PR for now, feel free to reopen if / when you find time to heavily reduce / externalize the diff.
Might also be worth to first flesh out the entire API in an API only PR or whatnot given it'd be a shame if you put in a lot of internal work just to then have a lot of changes requested to the API surface.

2025-11-01 17:34 UTC, closed without merging