PlayerShootProjectileEvent
PaperMC/Paper pull request #1193
Opened 2018-07-05 16:46 UTC by BillyGalbreath

I'm pretty sure I got all player launched projectiles (except arrows). Let me know if I missed any.

This a use-case specific issue that was discovered [here](https://www.spigotmc.org/threads/projectilehitevent-doesnt-work-in-survival-mode.327097/page-2#post-3059433). I have a use-case example a few posts down, [here](https://www.spigotmc.org/threads/projectilehitevent-doesnt-work-in-survival-mode.327097/page-2#post-3060204).

Not sure what to do about arrows since we have an EntityShootBowEvent already.

2018-07-13 21:00 UTC, aikar requested changes

2018-07-13 21:00 UTC, aikar commented on Spigot-API-Patches/0126-PlayerShootProjectileEvent.patch
> ++public class PlayerShootProjectileEvent extends EntityEvent implements Cancellable {
PlayerEvent

2018-07-13 21:00 UTC, aikar commented on Spigot-API-Patches/0126-PlayerShootProjectileEvent.patch
> ++    public Player getEntity() {
This isn't needed when extending PlayerEvent

2018-07-13 21:00 UTC, aikar commented on Spigot-API-Patches/0126-PlayerShootProjectileEvent.patch
> ++    public Player getShooter() {
again becomes less useful with getPlayer(), PlayerShootItemEvent is clear enough getPlayer is the shooter, we don't need this method.

2018-07-13 21:00 UTC, aikar commented on Spigot-API-Patches/0126-PlayerShootProjectileEvent.patch
> ++    public Entity getProjectile() {
return Projectile, not Entity

2018-07-13 21:00 UTC, aikar commented on Spigot-API-Patches/0126-PlayerShootProjectileEvent.patch
> ++    public boolean getConsumeStack() {
I don't like this term. Why would it ever consume the entire stack?

Needs to be more clearly named of shouldConsume/setShouldConsume

2018-07-13 21:00 UTC, aikar commented on Spigot-Server-Patches/0329-PlayerShootProjectileEvent.patch
> +         entityhuman.b(StatisticList.b((Item) this));
I'm not sure we should fire statistics for cancelled events? same for the rest of the changed items.

2018-07-13 21:01 UTC, aikar commented
Also I think we should go with PlayerLaunchProjectileEvent

as you said, we have ShootBowEvent, you're not shooting these projectiles from anything.

Also, the API for launching them is clearly called .launchProjectile(), so lets go with that name.

2018-07-14 02:53 UTC, BillyGalbreath commented
All fixed up

2018-07-21 08:13 UTC, closed without merging