Send from world
PaperMC/Paper pull request #1196
Opened 2018-07-05 22:59 UTC by Mystiflow

2018-07-05 23:02 UTC, Mystiflow commented
Whoops. Forgot to add Paper comments. Working on it.

2018-07-06 03:09 UTC, aikar requested changes
the player can be null

2018-07-18 12:53 UTC, Mystiflow commented
This PR is ready for further review. 

I've addressed your issue above.

Also I've expanded this PR to send nearby packets using the world field instead of dimension field as the predicator of which world to send the packets to. Previously they were sent by the same dimension;- so if there were 2 worlds with same dim in server - one player could send a packet to another in a parallel world, which is incorrect.

I do however still need to add some missing comments to annotate the changes from ```this.world``` to ```this.world.dimension```.

2018-08-08 23:10 UTC, mikroskeem approved these changes

2018-08-17 22:04 UTC, aikar approved these changes

2018-08-17 22:05 UTC, merged