Skip item merges if stack size is above/equal to the max stack size
PaperMC/Paper pull request #1217
Opened 2018-07-16 10:53 UTC by hugmanrique

Closes #1211

2018-07-16 11:23 UTC, mikroskeem commented on Spigot-Server-Patches/0330-Avoid-item-merge-if-stack-size-above-max-stack-size.patch
> ++
You can make the diff smaller by removing empty newlines

2018-07-16 11:23 UTC, mikroskeem commented on Spigot-Server-Patches/0330-Avoid-item-merge-if-stack-size-above-max-stack-size.patch
> ++        }
... and by removing the brackets, as you are doing `return` anyway.

2018-07-16 12:45 UTC, mikroskeem reviewed
Don't forget to squash that commit to previous one to make git history pretty :smile:

2018-07-16 13:23 UTC, aikar approved these changes

2018-07-16 13:25 UTC, mikroskeem approved these changes

2018-07-16 15:46 UTC, stephan-gh requested changes

2018-07-16 15:46 UTC, Minecrell commented on Spigot-Server-Patches/0330-Avoid-item-merge-if-stack-size-above-max-stack-size.patch
> +From: Hugo Manrique <hugmanrique@gmail.com>
Note: This is not the same email you added to the MIT license file. You probably want to add this mail to to `LICENSE.md` or reconfigure Git to use the other mail address.

2018-07-16 16:25 UTC, hugmanrique commented
It should be fine now! Thanks for the help, this was the first time I worked on a patch-based setup 😅

2018-07-16 20:38 UTC, kashike approved these changes

2018-07-19 15:51 UTC, zachbr approved these changes

2018-07-19 15:51 UTC, merged

2018-07-19 15:52 UTC, zachbr commented
Thanks! 👍