Re-add Vanished players don't have rights patch
PaperMC/Paper pull request #1256
Opened 2018-07-23 12:38 UTC by hugmanrique

Readds patch 0177. Moves away from `AxisAlignedBB`s to `VoxelShape`s.

The `checkNoVisiblePlayerCollisions` method is similar to the method below.

The `defaultReturn` boolean was adapted to use the `VoxelShape` provided by `IBlockData#h(World, BlockPosition)`, which is also used in the `EntityArrow` class (which I used as inspiration). Here's the changes on that class:

1.12:
```
if (iblockdata.getMaterial() != Material.AIR) {
        AxisAlignedBB axisalignedbb = iblockdata.d(this.world, blockposition);

        if (axisalignedbb != Block.k && axisalignedbb.a(blockposition).b(new Vec3D(this.locX, this.locY, this.locZ))) {
            this.inGround = true;
        }
}
```

1.13:
```
if (!iblockdata.isAir() && !flag) {
        VoxelShape voxelshape = iblockdata.h(this.world, blockposition);

        if (!voxelshape.b()) {
            Iterator iterator = voxelshape.d().iterator();

            while (iterator.hasNext()) {
                AxisAlignedBB axisalignedbb = (AxisAlignedBB) iterator.next();

                if (axisalignedbb.a(blockposition).b(new Vec3D(this.locX, this.locY, this.locZ))) {
                    this.inGround = true;
                    break;
               }
           }
        }
}
```

2018-07-23 13:22 UTC, kashike requested changes

2018-07-23 13:22 UTC, kashike commented on Spigot-Server-Patches/0307-Vanished-players-don-t-have-rights.patch
> ++        if (voxelshape.b()) {
Please create an obfuscation helper for `b()`.

2018-07-23 13:22 UTC, kashike commented on Spigot-Server-Patches/0307-Vanished-players-don-t-have-rights.patch
> ++            List list = this.getEntities((Entity) null, voxelshape.a());
Please create an obfuscation helper for `a()`.

2018-07-23 13:24 UTC, aikar requested changes

2018-07-23 13:24 UTC, aikar commented on Spigot-Server-Patches/0307-Vanished-players-don-t-have-rights.patch
> ++        boolean defaultReturn = iblockdata.canPlace(world, blockactioncontext.getClickPosition()) && world.a(iblockdata, blockactioncontext.getClickPosition()) && world.checkNoVisiblePlayerCollision
Please also add an obf helper for iblockdata.h() here too, as that method was not originally in the line replaced.

2018-07-23 20:32 UTC, kashike requested changes

2018-07-23 20:32 UTC, kashike commented on Spigot-Server-Patches/0307-Vanished-players-don-t-have-rights.patch
> ++    default VoxelShape getBlockShape(IBlockAccess iblockaccess, BlockPosition blockposition) { return h(iblockaccess, blockposition); } // Paper - OBFHELPER
Please put this on the line *directly* (no blank line between) above the method the obfuscation helper is for.
Example:
```java
default VoxelShape getBlockShape(IBlockAccess iblockaccess, BlockPosition blockposition) { return h(iblockaccess, blockposition); } // Paper - OBFHELPER
// <h(IBlockAccess, BlockPosition) method on this line>
```

2018-07-24 14:42 UTC, aikar requested changes

2018-07-24 14:42 UTC, aikar commented on Spigot-Server-Patches/0307-Vanished-players-don-t-have-rights.patch
> ++    public AxisAlignedBB getBounds() { return a(); } // Paper - OBFHELPER
This Obf helper is also in the wrong location, see kashikes comment.

2018-07-24 14:42 UTC, aikar commented on Spigot-Server-Patches/0307-Vanished-players-don-t-have-rights.patch
> ++    public boolean isEmpty() { return b(); } // Paper - OBFHELPER
This Obf helper is also in the wrong location, see kashikes comment.

2018-07-24 14:42 UTC, aikar commented on Spigot-Server-Patches/0307-Vanished-players-don-t-have-rights.patch
> ++                event.setCancelled(true);
Go ahead and return here. We shouldn't fire the event. There should not be opportunity for a plugin to break this.

2018-07-24 14:42 UTC, aikar commented on Spigot-Server-Patches/0307-Vanished-players-don-t-have-rights.patch
> ++                event.setCancelled(true);
I know original patch didn't do that, time to improve ;)

2018-07-25 22:03 UTC, aikar approved these changes

2018-07-25 22:05 UTC, aikar commented
are you able to resolve the conflicts or do you need us to?

2018-07-25 23:42 UTC, merged