Expand ArmorStand API
PaperMC/Paper pull request #1277
Opened 2018-07-26 06:40 UTC by willies952002

Add the following:
- Add proper methods for getting and setting items in both hands. Deprecates old methods
- Enable/Disable slot interactions

2018-07-26 06:49 UTC, kashike requested changes

2018-07-26 06:49 UTC, kashike commented on Spigot-API-Patches/0127-Expand-ArmorStand-API.patch
> +     ItemStack getItemInHand();
Please add the `@Deprecated` annotation.

2018-07-26 06:49 UTC, kashike commented on Spigot-API-Patches/0127-Expand-ArmorStand-API.patch
> +     void setItemInHand(ItemStack item);
Please add the `@Deprecated` annotation.

2018-07-26 06:49 UTC, kashike commented on Spigot-API-Patches/0127-Expand-ArmorStand-API.patch
> ++    ItemStack getItemInMainHand();
I'd like to see a method like https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0091-Access-items-by-EquipmentSlot.patch#L18-L24:
```java
ItemStack getItemInHand(final org.bukkit.inventory.EquipmentSlot slot);
```

2018-07-26 06:49 UTC, kashike commented on Spigot-API-Patches/0127-Expand-ArmorStand-API.patch
> ++    void setItemInMainHand(ItemStack item);
I'd like to see a method like https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0091-Access-items-by-EquipmentSlot.patch#L39-L47:
```java
ItemStack setItemInHand(final org.bukkit.inventory.EquipmentSlot slot, final ItemStack item);
```

2018-07-26 06:49 UTC, kashike commented on Spigot-API-Patches/0127-Expand-ArmorStand-API.patch
> ++    void setDisabledSlots(EquipmentSlot... slots);
```java
void addDisabledSlot(final EquipmentSlot... slots);

void removedDisabledSlot(final EquipmentSlot... slots);
```

2018-07-26 07:40 UTC, kashike requested changes

2018-07-26 07:40 UTC, kashike commented on Spigot-API-Patches/0127-Expand-ArmorStand-API.patch
> ++    List<EquipmentSlot> getDisabledSlots();
Should be a `Set`.

2018-07-26 07:49 UTC, willies952002 commented on Spigot-API-Patches/0127-Expand-ArmorStand-API.patch
> ++    List<EquipmentSlot> getDisabledSlots();
in what way..?

2018-07-27 06:16 UTC, kashike requested changes

2018-07-27 06:16 UTC, kashike commented on Spigot-API-Patches/0127-Expand-ArmorStand-API.patch
> ++import org.bukkit.inventory.EquipmentSlot; // Paper
Avoid the import statement - fully qualify below.

2018-07-27 06:16 UTC, kashike commented on Spigot-API-Patches/0127-Expand-ArmorStand-API.patch
> ++import java.util.Set; // Paper
Avoid the import statement - fully qualify below.

2018-07-27 06:16 UTC, kashike commented on Spigot-Server-Patches/0315-Implement-Expanded-ArmorStand-API.patch
> ++        disabled.removeAll(java.util.Arrays.asList(slots));
Just do a normal for loop here:
```java
for (final org.bukkit.inventory.EquipmentSlot slot : slots) disabled.remove(slot);
```

2018-07-27 06:31 UTC, kashike submitted a review, later dismissed

2018-07-27 06:31 UTC, kashike commented on Spigot-Server-Patches/0315-Implement-Expanded-ArmorStand-API.patch
> ++        disabled.addAll(java.util.Arrays.asList(slots));
`java.util.Collections.addAll(disabled, slots);`

2018-07-28 05:47 UTC, aikar requested changes

2018-07-28 05:47 UTC, aikar commented on Spigot-Server-Patches/0315-Implement-Expanded-ArmorStand-API.patch
> ++    public ItemStack getItemInHand(org.bukkit.inventory.EquipmentSlot slot) {
Actually, we should very well make this setItem/getItem(slot) and make all the slots work.

2018-07-29 03:09 UTC, willies952002 commented
is there any other changes that need to be made?

2018-07-29 16:23 UTC, aikar requested changes

2018-07-29 16:23 UTC, aikar commented on Spigot-API-Patches/0127-Expand-ArmorStand-API.patch
> ++    /**
I think all of the disabled slots API's should describe just what this API does so people don't have to go dig into technical wiki articles on what disabled slots do.

I don't even know!

2018-07-29 16:23 UTC, aikar commented on Spigot-API-Patches/0127-Expand-ArmorStand-API.patch
> ++    ItemStack getItemInMainHand();
I don't think we need these API's anymore with .getItem and setItem, it introduces confusion on "are these different", so let's just remove the hand specific ones.

Update the deprecated tags above too.

After that, I think we're good to merge.

2018-07-30 01:07 UTC, willies952002 commented on Spigot-API-Patches/0127-Expand-ArmorStand-API.patch
> ++    /**
`This makes it so a player is unable to place, remove, or replace an item in the given slot(s)`

does this seem like it's not enough of a description?
For some reason I feel this needs a slightly longer explanation

2018-07-30 01:29 UTC, aikar commented on Spigot-API-Patches/0127-Expand-ArmorStand-API.patch
> ++    /**
maybe something like "This makes it so a player is unable to interact with the Armor Stand to place, remove, or replace an item in the given slot(s)."

I assume the items fall if the armor stand is broken still, so may be worth noting that expectation, that once a slot is disabled, item retrieval can only be done on break?

2018-07-30 03:39 UTC, aikar approved these changes

2018-07-30 03:54 UTC, merged