Allow Blocks to be accessed via a long key
PaperMC/Paper pull request #1335
Opened 2018-08-15 04:49 UTC by Spottedleaf

The key can be retrieved via methods Location#toBlockKey() and
Block#getBlockKey()

World provides lookup for blocks by long key via method World#getBlockAtKey(long)

The formatting for the key is as follows:

4 bits unused|8 bit y|26 bit z|26 bit x

The y value is considered unsigned while z and x are considered two's complement

Y range: [0, 255]
X, Z range: [-33 554 432, 33 554 431]

Checked encoding and decoding via https://gist.github.com/Spottedleaf/eaf274e7959daf11b6302424e1df75f6

2018-08-15 04:50 UTC, DemonWav commented on Spigot-API-Patches/0128-Allow-Blocks-to-be-accessed-via-a-long-key.patch
> ++        return ((long)getBlockX() & 0x3FFFFFFL) | (((long)getBlockY() & 0xFFL) << 52) | (((long)getBlockZ() & 0x3FFFFFFL) << 26);
I hate that you ordered it this way. I think having the two big ones first makes more sense.

2018-08-15 04:53 UTC, aikar requested changes
Id rather go ahead and give X/Z the extra 2 bits incase mojang ever increases max size... be future proof.
28/28/8

And can you please update your git client and rebuild the patches.

2018-08-15 05:53 UTC, aikar commented
though I question, I guess it's more likely mojang would increase the height cap than x/z, so maybe give y 9 bits and x/z 27 bits

2018-08-15 06:09 UTC, Shevchik commented
Maybe use network position format instead?

2018-08-15 12:18 UTC, VADemon commented
Imho if Mojang is going to make changes to the bit distribution, it's most likely that the code will need to be changed. They could use the 4 bits for something else and if you expand the coordinates now, the result will be unpredictable.
They will make changes with regards to current code and it's best not to deviate from that (unless you want to experimentally allow bigger >30m worlds now).

2018-08-15 12:33 UTC, aikar commented
Mojang has no control over these bytes. We're talking about the concept of storing 3 integers and which one is likely to grow. I still stand by my request for 27 27 9.

2018-08-15 13:17 UTC, Spottedleaf commented
oops changes weren't properly commited don't merge

2018-08-15 13:44 UTC, Spottedleaf commented
I've gone ahead and used 10 bits for y and 27 for both x and z.

Tested via

https://gist.github.com/Spottedleaf/74f4e241012ca2fa67d8f1c7e8e34722

2018-08-17 21:54 UTC, aikar approved these changes

2018-08-17 21:55 UTC, merged