Fix view distance API
PaperMC/Paper pull request #1419
Opened 2018-09-07 20:21 UTC by Rickyboy320

Aims to fix #1349 by properly using the view distance API in the EntityTracker.
Also removed the Math.max line which caused the (original) issue of not being able to set the distance lower than spigot's view distance, and replaced more occurrences of the spigot viewdistance with the API. (I believe I've got them all, directly or indirectly)

2018-09-08 23:45 UTC, zachbr requested changes
Just needs an obfuscation helper. If you have any trouble with that let us know and we can handle it later.

2018-09-08 23:45 UTC, zachbr commented on Spigot-Server-Patches/0032-Add-player-view-distance-API.patch
> ++            this.getWorld().getTracker().a(player);
This needs an obfuscation helper.

2018-09-09 13:04 UTC, Rickyboy320 commented
Great! Added the obfuscation helper.

2018-09-09 18:38 UTC, zachbr approved these changes

2018-09-09 18:38 UTC, merged

2018-09-09 18:38 UTC, zachbr commented
Thanks