Add option to allow non-op players to place blocks with NBT
PaperMC/Paper pull request #1425
Opened 2018-09-08 23:47 UTC by BillyGalbreath

This adds a new option to paper.yml to bring back the vanilla behavior of allowing non-op and non-creative users to place blocks with BlockEntityTag NBT data on them.

This was snuffed out in CraftBukkit for being considered "exploitable" but I don't see any harm in letting server owners decide for themselves if they want this or not.

The default option is `false` to leave it snuffed out the way CraftBukkit has it.

2018-09-08 23:56 UTC, zachbr approved these changes

2018-09-09 09:01 UTC, kashike commented
Could you provide a use-case for something like this? I'm curious why you want it.

2018-09-09 15:54 UTC, BillyGalbreath commented
@kashike a use-case would be to give players a chest as a reward. The user should be able to place their chest down and receive their rewards. Server admins have the ability to make their own loot tables with the use of datapacks now, but here is an example command you can try yourself without any datapacks to see for yourself:

`/give @p minecraft:chest{BlockEntityTag:{LootTable:"minecraft:chests/simple_dungeon"}}`

This chest works in vanilla for any player that places it, but in CraftBukkit/Spigot/Paper it only works for Op players that are ALSO in creative mode.

2018-09-09 16:14 UTC, aikar requested changes
oh that makes a lot of sense now. 

But I'm going to say no on this approach - this is super dangerous.

Instead, lets just undo md5's stupid change of bringing chests into this filter breaking vanilla.

This filteredNBT was only used for op related stuff like command blocks before. I see no reason for it to be applied on chests, as it's the Creative Mode filters responsibility to filter out users creating hacked chests.

If a user obtains a chest in survival mode, I see no reason for it to be filtered.

We don't need a config, just delete the lines added to TileEntityChest

2018-09-09 16:50 UTC, aikar approved these changes

2018-09-09 16:53 UTC, merged