Use EntityTypes
PaperMC/Paper pull request #1533
Opened 2018-10-04 21:07 UTC by BillyGalbreath

2018-10-05 15:54 UTC, aikar approved these changes
Overall maintenance burden is a concern but I think it might be ok. Mainly worried if files come in that are more 'broken'...

Hopefully mojang will do this themselves though. I'll ping them and see.

2018-10-05 19:13 UTC, BillyGalbreath commented
@aikar There's a lot more, I only care for the EntityLiving ones, though ;)

2018-10-05 19:19 UTC, zachbr requested changes
Not sure how I feel about doing this for only a small portion of entities. It should probably be all or none.

2018-10-05 19:22 UTC, BillyGalbreath commented
@zachbr I didn't do the others for the same maintainability concern @aikar brought up. This patch is actually for my Ridables plugin to work with less hacks.

2018-10-05 19:24 UTC, zachbr commented
That's great and all, but not particularly relevant to Paper as a larger project.

2018-10-05 19:28 UTC, BillyGalbreath commented
@zachbr Well, I mean it can be edited to include more when/if they are needed. I just didn't see a need/point in all the others at this time. Not like this would be the [first patch](https://github.com/PaperMC/Paper/blob/master/Spigot-API-Patches/0077-PreCreatureSpawnEvent.patch#L39-L40) with "more can be added later" submitted...

2018-10-05 19:30 UTC, zachbr commented
Thats because you're still thinking of your own Ridables plugin. It's great that you want to clean up your own code and NMS should arguably be doing this anyway but that doesn't mean much to Paper. We shouldn't really be taking NMS changes just to make plugin based NMS hacks any easier but if we must I'd rather we do it consistently across the codebase rather than just doing it in the places only you care about.

2018-10-05 19:35 UTC, BillyGalbreath commented
Then nevermind this. I don't have the time or need to include the others. You always say that we should hack NMS less and should send in PRs to prevent that. I tried. ¯\_(ツ)_/¯

2018-10-05 19:36 UTC, zachbr commented
This is still hacking NMS, its just maintenance burden on us.
This response is pretty indicative of what I expected and all the more reason to reject this.

2018-10-05 20:01 UTC, zachbr commented
Lots of internal discussion about this on Discord. Specifically there are concerns about edge cases in the non-living types as well as general maintainability. Outside of the edge cases I don't expect a ton of maintainability problems, but obviously we need to explore that to be sure.

I want to see how bad the edge cases around non-living entities are and we can go from there.

2018-10-09 21:13 UTC, zachbr commented
After looking through the internals around this its quite clear that it would be a disaster to implement this for every single entity and then maintain it. There are simply too many edge cases.

2018-10-09 21:14 UTC, zachbr approved these changes

2018-10-09 21:50 UTC, kashike requested changes

2018-10-09 21:50 UTC, kashike commented on Spigot-Server-Patches/0386-Use-EntityTypes.patch
> +Subject: [PATCH] Use EntityTypes
".. where possible"

2018-10-24 20:26 UTC, merged