Change the reserved channel check to be sensible
PaperMC/Paper pull request #1610
Opened 2018-10-23 16:39 UTC by DoNotSpamPls

2018-10-23 16:47 UTC, aikar requested changes

2018-10-23 16:47 UTC, aikar commented on Spigot-API-Patches/0167-Change-the-reserved-channel-check-to-be-sensible.patch
> ++        return channel.equals("minecraft:register") || channel.equals("minecraft:unregister");
Need to paper tag this

2018-10-24 13:55 UTC, DoNotSpamPls commented
I've just noticed that the tests fail, fixing right now!

2018-11-20 05:10 UTC, zachbr approved these changes

2018-12-01 00:08 UTC, merged

2018-12-01 00:09 UTC, zachbr commented
Thanks, merged pretty late now that upstream allows `minecraft:brand` but still useful for other stuff.