Add PlayerPostRespawnEvent
PaperMC/Paper pull request #1622
Opened 2018-10-27 04:54 UTC by MisterVector

It would be nice to capture the state the player is in after having respawned. Currently we can only capture them in the act of respawning. An event like this would, for example, mitigate the requirement of a 1ms timer for some things that cannot be done while the player is currently in the act of respawning. It would also mark the player as having freshly respawned.

2018-10-27 04:58 UTC, electronicboy commented on Spigot-API-Patches/0167-Add-PlayerPostRespawnEvent.patch
> ++        return respawnedLocation;
This should be cloned, location is a mutable object

2018-10-27 05:45 UTC, kashike requested changes

2018-10-27 05:45 UTC, kashike commented on Spigot-API-Patches/0168-Clone-the-location-object.patch
> +From 7ac07ac07ac07ac07ac07ac07ac07ac07ac07ac0 Mon Sep 17 00:00:00 2001
Squash this into the first patch.

2018-11-22 03:22 UTC, kashike approved these changes

2019-03-04 20:21 UTC, electronicboy approved these changes

2019-03-24 17:50 UTC, merged