Elide unnecessary synchronization of chunkmap
PaperMC/Paper pull request #1847
Opened 2019-02-10 06:31 UTC by Spottedleaf

Synchronizing on the chunkmap has no affect since all synchronization
for chunkmap has been moved inside ChunkMap itself. Thus the only purpose
the synchronization could offer was synchronization between some other
thread, but there is no corresponding thread and thus the synchronization
was unnecessary.

2019-02-11 16:28 UTC, aikar commented
While the one in the chunk map does appear unnecessary, i don't agree on the CPS one as that method is not guaranteed to be on main when async chunks is disabled (and maybe even not guaranteed with AC for regenerateChunk which I still need to look into)

this current usage is a putIfAbsentOrReturnExisting pattern, which needs synchronization to be 'safe'

If you want to update it to revert the CPS one I guess go ahead, but im ok with just closing PR and leaving as is as nothing really changes behavior here.

I'm almost thinking we should leave the Async method as is too, as that protects the chunk from being used by worldgen threads until it is fully finalized from the .put()...

2019-02-11 16:29 UTC, aikar requested changes

2019-02-11 16:29 UTC, aikar commented on Spigot-Server-Patches/0366-Async-Chunk-Loading-and-Generation.patch
> ++        //synchronized (this.chunks) { // Paper - Elide unnecessary synchronization
revert

2019-02-11 18:37 UTC, Spottedleaf commented
I disagree with your reasoning for CPS. For now I'm going to split the code into two branches, one where it calls put() and one where it does not (this is correct given the code and your explanation). It splits on whether the chunk exists in the map. First, the one where it calls put (chunk in map == null) must be on main, given the internal restriction of ChunkMap (see the async catcher on put()). The put() method synchronizes and thus ensures the chunk is published correctly. So there's no effective logical difference caused by my change, other than the call is non-atomic but as stated it does not need to be atomic since all writes are on main.

The second branch (chunk in map != null) is easy, all it calls is get() which is synchronized if asynchronous. So in the second branch synchronization is unnecessary, whether or not the calling thread is the main thread.

If you inspect the ACPS change closely, you'll notice that the only changes that are not published with the call to put() are the neighbouring chunk data in Chunk (see calls to Chunk#H and Chunk#setNeighborLoaded). I don't think worldgen threads should be reading those values at all since they're racey, but I assumed they are not since it would be racey (with respect to other chunk loads). Everything else (including any actions performed by the completable futures) is guaranteed to be made visible to reading threads (aka calls on get()) due to the nature of synchronized in the put() call. So if you think that neighbour count data is important to at least have initial values possibly correct, then I can move the synchronized block around the put call instead and this will ensure those writes are visible.

2019-02-11 19:17 UTC, aikar commented
@Spottedleaf yes thats why I said the ACPS could be safely changed since that only behaves on main, however CURRENTLY the entire .put() call is synchronized.

If we remove it there, only the ACTUAL map.put will be synchronized, but all of the code that runs in the overridden .put() method in the chunk map could run concurrently to a worldgen thread calling .get(), meaning a chunks state may not be fully 'processed' at the time of the .get() on the worldgen thread.

2019-02-11 19:49 UTC, Spottedleaf commented
And I correctly pointed out the only state that is not guaranteed to be fully processed the neighbour chunk count and the neighbour chunk bitset, which again is not safe to read off-main.

2019-04-26 00:00 UTC, Spottedleaf commented
Since 1.14 is coming out I doubt this diff will stand, and there doesn't seem to be interest in pulling it. If the diff is still valid I'll discuss it on discord while async chunks gets brought over to 1.14.

2019-04-26 00:00 UTC, closed without merging