Emancipate more features to PlayerHandshakeEvent
PaperMC/Paper pull request #1912
Opened 2019-03-21 06:41 UTC by cakoyo

* The hostname and socket address was not null when the event fired, but the event does not provide the value, the change allows plugins to use the old value.
* Since `proxyLogicEnabled` will be checked after the event fired, to check the config value will allow plugins to modify it during the event handling.

2019-04-13 21:38 UTC, electronicboy requested changes

2019-04-13 21:38 UTC, electronicboy commented on Spigot-Server-Patches/0103-Add-handshake-event-to-allow-plugins-to-handle-clien.patch
> ++                if (!handledByEvent && org.spigotmc.SpigotConfig.bungee) {
This is not a safe change, if you want to expose something to the event, it should be handled via the event

2020-11-03 20:39 UTC, Proximyst approved these changes, later dismissed

2020-12-14 16:56 UTC, electronicboy approved these changes, later dismissed

2020-12-16 20:44 UTC, MiniDigger commented on Spigot-API-Patches/0016-Player-Tab-List-and-Title-APIs.patch
> +
left others from last merge, nothing to see here

2020-12-16 20:44 UTC, MiniDigger commented
@limbo-app ready

2020-12-16 20:44 UTC, limbo-app approved these changes
Pull request automatically approved for merging - a core team member has previously approved this pull request.

2020-12-16 20:52 UTC, merged

2020-12-16 20:56 UTC, MiniDigger commented
better late than never I guess