Fix SpawnChangeEvent not firing for all use-cases
PaperMC/Paper pull request #1964
Opened 2019-04-13 20:52 UTC by BillyGalbreath

This moves the event firing from CraftWorld to World.

Fixes #1913

2019-04-14 23:45 UTC, electronicboy approved these changes

2019-04-16 23:03 UTC, zachbr approved these changes

2020-02-07 03:02 UTC, electronicboy requested changes

2020-02-07 03:02 UTC, electronicboy commented on Spigot-Server-Patches/0438-Fix-SpawnChangeEvent-not-firing-for-all-use-cases.patch
> +     public void v(BlockPosition blockposition) {
Reeeeeeebase required *runs*

2020-03-21 17:14 UTC, closed without merging