AreaEffectCloud should always check radius
PaperMC/Paper pull request #2089
Opened 2019-05-27 22:42 UTC by BillyGalbreath

This is a vanilla bug, but I could not find any tickets on mojira about it.

All cases of the AreaEffectCloud spawning set a radius per tick to a non 0 value (they shrink over time), except for the case when a dragon is in SITTING_FLAMING phase. The AreaEffectCloud itself checks for when the radius gets too small it will despawn itself, but _only_ in if the radius per tick is a non 0 value.

This change moves the radius size check outside the radius per tick check and to the top of the tick so it is despawned when it gets too small regardless of the radius per tick value.

Fixes #2088

2019-05-27 22:43 UTC, BillyGalbreath commented
God damn it... PR'd to wrong branch

2019-05-27 22:47 UTC, BillyGalbreath commented
@Spottedleaf so smart <3

2019-05-28 03:38 UTC, zachbr approved these changes

2019-05-28 17:47 UTC, kashike requested changes

2019-05-28 17:47 UTC, kashike commented on Spigot-Server-Patches/0398-AreaEffectCloud-should-always-check-radius.patch
> ++        // Paper start
Please open (or find an existing) a vanilla tricket if this is a vanilla bug, and then add it in a comment - `// Paper start - fix MC-??????`.

2019-05-29 00:44 UTC, kashike approved these changes

2019-05-29 00:44 UTC, merged