Add BlockSoundGroup to Block & Implement
PaperMC/Paper pull request #2097
Opened 2019-05-28 12:00 UTC by jacobsandersen

This PR aims to close #2045 by creating a new `BlockSoundGroup` interface in `org.bukkit.block` which exposes five methods *getBreakSound*, *getStepSound*, *getPlaceSound*, *getHitSound*, and *getFallSound*.

The interface is implemented in `CraftBlockSoundGroup` in `org.bukkit.craftbukkit.block` which accepts the `SoundEffectType` type. The implementation uses `CraftSound#getSoundByEffect` method to retrieve the Bukkit `Sound` object corresponding to each `SoundEffect` denoted by the provided `SoundEffectType`.

Some paper OBFHELPERs were added to `SoundEffectType` to clarify which methods correspond to which sound effect. Two methods, *getBreakSound* and *getHitSound*, were added, because the fields were private and no getters already existed. My IDE noted that they were unused at the current time.

`CraftBlock#getBlockSoundGroup` is implemented by creating a new `CraftBlockSoundGroup` and passing the NMS block's blockdata's `SoundEffectType` to the constructor. I believe this is the correct method to call, as `CraftBlock#getStepSound` accepts a blockdata parameter. This should have no effect to API users.

Still new to PRing, so would appreciate any comments/suggestions/fixups.

2019-05-28 12:07 UTC, MiniDigger commented
I would consider using the "complex" obf helper syntax described here, so that they don't silently break when mojang shuffles methods or smth https://github.com/PaperMC/Paper/blob/master/CONTRIBUTING.md#obfuscation-helpers

2019-05-28 12:09 UTC, Spottedleaf commented on Spigot-Server-Patches/0398-Implement-CraftBlockSoundGroup.patch
> ++import org.bukkit.block.BlockSoundGroup;
import

2019-05-28 17:39 UTC, kashike requested changes

2019-05-28 17:39 UTC, kashike commented on Spigot-API-Patches/0184-Add-BlockSoundGroup-interface-and-method-to-Block.patch
> ++    BlockSoundGroup getBlockSoundGroup();
Just `getSoundGroup`.

2019-05-29 02:06 UTC, Spottedleaf commented on Spigot-Server-Patches/0398-Implement-CraftBlockSoundGroup.patch
> ++    public final SoundEffect getBreakSound() {
move to field obfhelper

2019-05-29 02:07 UTC, Spottedleaf commented on Spigot-Server-Patches/0398-Implement-CraftBlockSoundGroup.patch
> ++        return this.B;
move to field obfhelper

2019-05-29 02:07 UTC, Spottedleaf commented on Spigot-Server-Patches/0398-Implement-CraftBlockSoundGroup.patch
> ++
enclose in // paper

2019-05-29 02:08 UTC, Spottedleaf commented on Spigot-Server-Patches/0398-Implement-CraftBlockSoundGroup.patch
> ++package org.bukkit.craftbukkit.block;
should be in our package

2019-05-29 02:08 UTC, Spottedleaf commented on Spigot-API-Patches/0184-Add-BlockSoundGroup-interface-and-method-to-Block.patch
> ++package org.bukkit.block;
probably should be in our package too

2019-05-29 03:20 UTC, jacobsandersen commented on Spigot-API-Patches/0184-Add-BlockSoundGroup-interface-and-method-to-Block.patch
> ++    BlockSoundGroup getBlockSoundGroup();
Should be fixed now.

2019-06-01 08:57 UTC, kashike approved these changes

2019-06-02 04:13 UTC, Spottedleaf approved these changes

2019-06-02 04:13 UTC, merged