scripts/rebuildPatches.sh: Reduce diff when regenerating patches
PaperMC/Paper pull request #2324
Opened 2019-07-17 08:09 UTC by Minecrell

I was looking the the `git format-patch` man page a while ago and thought these extra command line parameters might help to reduce the ugly random diff when regenerating patches.

See commit description for details.
Regenerated patches with these changes: https://github.com/Minecrell/Paper/commit/410eaf85a776aaf3476aff12725897fab7ea768e

Eventually, some parts of [`cleanupPatches`](https://github.com/PaperMC/Paper/blob/58bc259a18b6f8f4fa0e30f6aa62db22bf0db2f8/scripts/rebuildPatches.sh#L15-L32) could be removed after this change.

2019-07-17 14:07 UTC, aikar requested changes
No on the zero commit. causes huge problems when doing upstream updates (git uses that data to help apply patches when the line numbers no longer line up), but the other things are nice.

2019-07-17 14:42 UTC, Minecrell commented
> No on the zero commit. causes huge problems when doing upstream updates (git uses that data to help apply patches when the line numbers no longer line up), but the other things are nice.

As far as I know, only the `index aaa..bbb` lines are used for the `--3way` merge.

The commit hash in `From 0000000000000000000000000000000000000000 Mon Sep 17 00:00:00 2001` is the original commit the patch was generated from.

It is not very helpful when applying the patch. The reason is that only the person that generated the patch will eventually still have that commit hash in their local repository. Every time the patch is applied a new commit hash is generated.

I'm quite sure that commit hash is simply ignored when applying the patch...

2019-07-17 14:50 UTC, aikar commented
I thought the same too, and git surprised me. git uses the hashes to build a cross reference lookup "This patch 0003 references a non existent commit ID, but I have record of a previous patch 0001 using this ID that ended up being applied as this other ID, so use this ID as the base instead"

though i don't know how much thats tied to commit vs file hashes, but i don't see it as worth the risk, as you don't know how much it bites you until the next upstream update and stuff fails to apply that would have otherwise.

2019-07-19 12:25 UTC, Minecrell commented
I can imagine that it does a lot of magic with the `index` lines, but I still doubt that also applies to the commit hash in the `From` line. I had a glance at the Git source code before opening this pull request and I was not able to find any use for the commit hash. The only exception was some internal use together with `git rebase`, but that's not used when invoking `git am` directly.

The `--zero-commit` option was really the original reason for me to open this PR, since that is the part that changes literally every time a patch is regenerated. In my opinion there is not much risk but I could be wrong. So at the end it's up to you: If you think it's too risky then I'll remove it. Or maybe you could just give it a try?

2019-07-20 16:57 UTC, zachbr commented
I'm not convinced that first `From ... Mon Sep 17 00:00:00 2001` line hash is used anywhere. When we did our version of this we zero'd significantly more than just that. I'm not sure we should draw any comparisons from that experience.

2019-07-24 03:11 UTC, zachbr commented
I'll try to run through some scenarios later this week (oh god I'm giving out time frames again) to confirm that this shouldn't cause any glaring issues.

2019-11-04 03:16 UTC, Spottedleaf commented
I've had local issues specifically with `--no-signature` and patch rebuilding failing to generate new changes. Removing the flag fixes the issue (re-adding the flag again gives the same issue).

I will be looking into taking this issue to git over the next week or so, but decided to comment here to let anyone know who is using these flags to perhaps be aware of issues and a solution.

2019-11-04 11:52 UTC, Minecrell commented
@Spottedleaf That doesn't really make sense. I'm not sure if I understand the issue you have, but if your issue is that new changes don't show up in the regenerated patches you might want to check if the [`cleanupPatches`](https://github.com/PaperMC/Paper/blob/58bc259a18b6f8f4fa0e30f6aa62db22bf0db2f8/scripts/rebuildPatches.sh#L15-L32) function is now reverting changes because it expects the Git version to be here.

2019-11-04 14:50 UTC, aikar commented
While From may not be needed, as we've demonstrated, the rest are absolutely required, so we're talking about simply 1 set of hashes per file.

Not worth the complexity over a single extra diff section especially if the solution provided, Leaf has mentioned has problems.

2019-11-04 14:57 UTC, zachbr commented
What complexity? No arm chair quarterbacking in this. Either _you_ have issues or you don’t.

Leafs issue remains an open question. No changes required at this time.

2019-11-04 14:58 UTC, Minecrell commented
@aikar 
There is still `--full-index`, which reduces diffs where one of the index hashes changes in length depending on the number of objects you have in your (local) repository.

Like here: https://github.com/PaperMC/Paper/commit/df984898acc79ead4a645c7fd26e3876f62058cc#diff-1ec14d830e42ae37bf8a5d4b7d83d5cfL8

2019-11-04 15:13 UTC, zachbr commented
@Spottedleaf is this just some generic issue with rebuilds on these patches or is there some specific case you’ve narrowed it too?

Would like to see if we can get some reproduction on it and go from there.

2019-11-04 15:25 UTC, aikar commented
Oh yes that flag is good, I had been meaning to look into why that problem was happening ages ago.

2019-11-04 15:28 UTC, aikar commented
@zachbr the issue stems that if someone builds on an older repo that has more stale/temp objects in it, and that git actually encounters a short hash conflict, it adds 1 more character to the shorthash to overcome the conflict.

So people on fresh repos would nearly always result in a standard shorthash, but occasionally older checkouts might have an object conflict resulting in other patch files getting changed in a way that cleanupPatches can't filter out.

2019-11-04 19:49 UTC, Spottedleaf commented
Cleanup patches is reverting the patches

2019-11-04 20:05 UTC, Spottedleaf commented
The specific issue can be found here:
https://github.com/Spottedleaf/Concrete/commit/60bd62e669ddcc29b1a064f581ebb10deabbba02#diff-1dc4086bc209a34819532fe08eb11b4cR1567

2019-11-04 20:29 UTC, Minecrell commented
With this PR, pretty much none of `cleanupPatches` is really needed, so it just needs to be modified to handle only the remaining cases where useless diff is still generated, if there are any. I didn't do it because that method is a bit tooo magic for me.

2019-11-05 01:26 UTC, aikar commented
No cleanup would still be needed as soon as you drop --zero-commit
Zero commit specifically is what breaks everything in future patch application.

See here:

Patch 2 does this:

```
 index a5abc0717422b05cfa4e851e3c531f6fae64a4c0..75a3a8a88838d64c233ac7a191a19e8782054c3b 100644
 --- a/src/main/java/org/bukkit/craftbukkit/CraftWorld.java
 +++ b/src/main/java/org/bukkit/craftbukkit/CraftWorld.java
```
which source CraftWorld might of been hash (using simple numbers here) "42" instead
The result of applying this patch, results in a 3 way merge with a new hash for Craftworld as "52"

Git records `75a3a8a88838d64c233ac7a191a19e8782054c3b` = `52`


Patch 10 then does
```
 index 75a3a8a88838d64c233ac7a191a19e8782054c3b..8798ecae34a8fa1a6a9fe5092089dea9e7f89d68 100644
 --- a/src/main/java/org/bukkit/craftbukkit/CraftWorld.java
 +++ b/src/main/java/org/bukkit/craftbukkit/CraftWorld.java
```
well `75a3a8a88838d64c233ac7a191a19e8782054c3b` doesn't exist, but hey I have a mapping that says `75a3a8a88838d64c233ac7a191a19e8782054c3b` = `52`, let me apply this diff onto `52` instead!

Well, new result = 62, add new mapping `8798ecae34a8fa1a6a9fe5092089dea9e7f89d68` = 62

Then another...
```
index 8798ecae34a8fa1a6a9fe5092089dea9e7f89d68..16de4efef9a56bcd758bfea18974855b245a0e33 100644
 --- a/src/main/java/org/bukkit/craftbukkit/CraftWorld.java
 +++ b/src/main/java/org/bukkit/craftbukkit/CraftWorld.java
```
`8798ecae34a8fa1a6a9fe5092089dea9e7f89d68` maps to `62` and `16de4efef9a56bcd758bfea18974855b245a0e33` now maps to 72
 While those hashes are non existent in the final result, git is able to use those in memory ties to realize a previous patch files target hash now aliases to the result of the 3 way merge instead, so that future patches can build upon the results of previous.

So when you go zero'ing out the source of a file, all of that is thrown out the window, and patches have a harder time applying.

this is EXACTLY the same thing I did with the taco patches, just zero's instead of tacos.

The --no-signature and --full-commit are valid improvements, but zero WILL cause problems. We've proven that already.

2019-11-05 01:34 UTC, aikar commented
I think cleanup will still be needed, as otherwise a change of a lower file will result in the index lines of every subsequent line changing, generating more noise instead of reducing it.

2020-01-23 03:57 UTC, Spottedleaf commented
I ran into some issues a while ago with patches again not rebuilding correctly - decided to cut regen patches entirely and I've not run into further issues.

2020-05-06 09:29 UTC, aikar approved these changes

2020-05-06 09:31 UTC, merged