Add PlayerFlowerPotManipulateEvent
PaperMC/Paper pull request #2448
Opened 2019-08-11 15:29 UTC by MisterVector

Added an event for when a player places an item in or takes an item out of a flower pot.

This is a revisit to an old PR I had submitted nearly 3 years ago but wasn't able to finish because of an issue with server-side code that handles event cancellation.

2019-08-12 21:31 UTC, jacobsandersen requested changes

2019-08-12 21:31 UTC, simpleauthority commented on Spigot-Server-Patches/0445-Implement-PlayerFlowerPotManipulateEvent.patch
> ++            if (event.isCancelled()) {
Just test the result of callEvent, as it handles event cancellation already.

2019-08-12 21:33 UTC, jacobsandersen requested changes

2019-08-12 21:33 UTC, simpleauthority commented on Spigot-Server-Patches/0445-Implement-PlayerFlowerPotManipulateEvent.patch
> ++            org.bukkit.block.Block bukkitblock = org.bukkit.craftbukkit.block.CraftBlock.at(world, blockposition);
Starting here, this is extremely verbose with fully-qualified classes. Try using imports when you are using the same class more than once.

2019-08-12 21:33 UTC, kickash32 commented
I suggest you use imports in BlockFlowerPot.java as currently the implementation of the event is very hard to read.

2019-08-12 21:35 UTC, kickash32 commented
Additionally master is not accepting new PRs, only the 1.14 branch is. You need to change the target of this PR (if you can, else create a new one).

2019-08-13 01:21 UTC, MisterVector commented
> 
> 
> Additionally master is not accepting new feature PRs, only the 1.14 branch is. You need to port this patch to the 1.14 branch and then submit a new PR.

According to https://papermc.io/forums/t/july-project-status-update/1391 they aren't formally feature-freezing the master branch (Minecraft 1.13.2). So on that note what should I do?

2019-08-13 04:59 UTC, kickash32 commented
Although its not documented here, it has been talked about on the discord and PRs will only be accepted for 1.13 if they are bug fixes or also PR'd for 1.14.

2019-08-13 08:13 UTC, MisterVector commented
Alright then that is what I will do.

2019-08-13 08:13 UTC, closed without merging