Performance patches
PaperMC/Paper pull request #2802
Opened 2019-12-28 04:57 UTC by Spottedleaf

Original patches:
https://github.com/Spottedleaf/Concrete/blob/bleeding/patches/server/0004-Util-patch.patch
https://github.com/Spottedleaf/Concrete/blob/bleeding/patches/server/0010-Add-soft-async-catcher.patch
https://github.com/Spottedleaf/Concrete/blob/bleeding/patches/server/0011-Guard-against-serializing-mismatching-chunk-coordina.patch
https://github.com/Spottedleaf/Concrete/blob/bleeding/patches/server/0012-Remove-logic-creating-lots-of-garbage-on-the-heap.patch
https://github.com/Spottedleaf/Concrete/blob/bleeding/patches/server/0022-Improve-autosave-performance.patch
https://github.com/Spottedleaf/Concrete/blob/bleeding/patches/server/0023-Avoid-immediately-autosaving-newly-generated-loaded-.patch
https://github.com/Spottedleaf/Concrete/blob/bleeding/patches/server/0013-Per-player-view-distance-implementation.patch
https://github.com/Spottedleaf/Concrete/blob/bleeding/patches/server/0015-Optimize-isOutsideRange-to-use-a-square-radius-check.patch
https://github.com/Spottedleaf/Concrete/blob/bleeding/patches/server/0019-Delay-chunk-unloads.patch
https://github.com/Spottedleaf/Concrete/blob/bleeding/patches/server/0020-Optimize-entity-list-iteration-requiring-entities-be.patch
https://github.com/Spottedleaf/Concrete/blob/bleeding/patches/server/0021-Optimize-ChunkProiverServer-s-chunk-level-checking-h.patch
https://github.com/Spottedleaf/Concrete/blob/bleeding/patches/server/0024-Optimise-TickListServer-by-rewriting-it.patch
https://github.com/Spottedleaf/Concrete/blob/bleeding/patches/server/0025-Improve-random-tick-performance.patch
https://github.com/Spottedleaf/Concrete/blob/bleeding/patches/server/0026-Optimise-ActivationRange-activateEntities-World.patch
https://github.com/Spottedleaf/Concrete/blob/bleeding/patches/server/0027-Optimise-ArraySetSorted-removeIf.patch
https://github.com/Spottedleaf/Concrete/blob/bleeding/patches/server/0029-Optimise-getPlayersInRange-type-functions.patch

See patch notes for details

They've all been dumped in this PR since they tend to have dependencies on each other (most notably the mc-util patch)

Up to now I've only compile tested

Things to do:
- nuke old distance map
- full chunk and plugin loaded chunk inconsistency
- run it

2019-12-28 05:18 UTC, electronicboy commented
pre-looking at the patches comment: gfdi leaf

2019-12-28 17:35 UTC, Spottedleaf commented
now it's just the patches that cause big diffs

2019-12-29 16:43 UTC, AJMFactsheets commented
I built this branch for local testing and the only problem I found is that when a player dies, there is a high chance they will get stuck in a limbo mode where chunks won't load, entities jitter, and they player can't move.

2019-12-29 17:31 UTC, Spottedleaf commented
can't produce locally, paste output of /version

2019-12-29 18:06 UTC, HexedHero commented
#LeafForProjectDev

2019-12-29 19:10 UTC, Callahhh commented
FWIW, here's a spark report with ~35 players online:
 https://sparkprofiler.github.io/#Oes5zdvftS. 
This is one without the patches:
https://sparkprofiler.github.io/#msNHaXfBlD

Here's also a timings report with the patches (30ish minutes):
https://timings.aikar.co/?id=a872c4b888c54ed2bb067fc7c2b43c11

I had to revert back since TPS was worse than usual. After looking/comparing both of those reports for like an hour, I couldn't find anything noticeably different or where it went wrong. 

I apologize if this is all pretty worthless info, just thought I'd share. 

Appreciate the hard work ❤️

2019-12-29 19:14 UTC, electronicboy commented
mostly looks like your server is overworked from mob spawning/player movement

2019-12-29 19:15 UTC, Spottedleaf commented
yeah I don't see much of a difference between the two, and without a testing environment I can't do anything about it

2019-12-29 19:23 UTC, AJMFactsheets commented
Output of /version: This server is running Paper version git-Paper-"59df758f" (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)

After further testing, I have found that the death bug only happens after a player has slept in a bed.

2019-12-29 21:18 UTC, Spottedleaf commented
unable to produce after sleeping in a bed

2019-12-30 03:43 UTC, AJMFactsheets commented
I built a new jar based off of the new commit and the death glitch still persists. I realized beds have nothing to do with the glitch, but it has something to do with spawn chunks.

Start a new world with default settings, and /kill yourself at the world spawn. Upon respawning, you should be unable to move, unless you relog or teleport far away.

The glitch reminds me of [MC-138539](https://bugs.mojang.com/browse/MC-138539)
I also tested with 1.15.1 Paper-31 and didn't have any problems.

2019-12-30 04:13 UTC, Spottedleaf commented
Yeah I see what's going on here now - a typo. The reason it only happens at spawn is because once chunks get loaded they are sent to the player - at spawn they only load once. 

Fixed in latest commit.

Thanks for your patience and detailed report.

2020-01-02 23:25 UTC, electronicboy reviewed
- [x] Spottedleaf/Concrete:patches/server/0004-Util-patch.patch@bleeding 

- [ ] Spottedleaf/Concrete:patches/server/0022-Improve-autosave-performance.patch@bleeding 
- [x] Spottedleaf/Concrete:patches/server/0023-Avoid-immediately-autosaving-newly-generated-loaded-.patch@bleeding 
- [ ] Spottedleaf/Concrete:patches/server/0013-Per-player-view-distance-implementation.patch@bleeding 
- [ ] Spottedleaf/Concrete:patches/server/0015-Optimize-isOutsideRange-to-use-a-square-radius-check.patch@bleeding 
- [x] Spigot-Server-Patches/0420-Optimise-getChunkAt-calls-for-loaded-chunks.patch

2020-01-25 21:09 UTC, electronicboy commented on scripts/importmcdev.sh
> +importLibrary com.mojang datafixerupper com/mojang/datafixers/util Either.java
Either?!

2020-01-25 21:09 UTC, electronicboy approved these changes

2020-01-26 01:47 UTC, Spottedleaf commented
updated to 1.15.2, fixed build

2020-01-26 01:49 UTC, electronicboy requested changes
https://www.youtube.com/watch?v=woySeSNBL3o

2020-01-26 01:56 UTC, electronicboy approved these changes

2020-01-27 05:36 UTC, zachbr approved these changes

2020-01-28 00:16 UTC, merged

2020-01-28 18:52 UTC, Misio12320 commented
How much % the game has been upgraded with performance and when release of view distance for 1.15.2?

2020-01-28 18:55 UTC, Callahhh commented
> How much % the game has been upgraded with performance and when release of view distance for 1.15.2?

yes

2020-01-28 22:50 UTC, Spottedleaf commented
it's a prereq patch so like maybe 2% at most

2020-01-28 22:52 UTC, OceanFoxy commented
Are you going to bring the per-player view distance patch back in the future?

2020-01-28 22:52 UTC, Spottedleaf commented
yes, some other stuff needs to go in first though

2020-01-28 23:25 UTC, nicuch commented
> it's a prereq patch so like maybe 2% at most

that's a lot :O gonna test it now on my 20gb server, i'll report back the performance.