WIP Implement daemon mode to interop with paperd
PaperMC/Paper pull request #2836
Opened 2020-01-11 03:07 UTC by DemonWav

Re-opened from #2319 to target `master`.

This commit adds the necessary logic so Paper can communicate with [paperd](https://github.com/PaperMC/paperd).

[paperd's 1.0.0 release](https://github.com/PaperMC/paperd/tree/1.0.0) marks the first release and compatible version with this PR.

[Documentation on usage can be found here.](https://github.com/PaperMC/paperd/blob/master/usage.md)

[Documentation on the internals of the communication system can be found here.](https://github.com/PaperMC/paperd/blob/master/protocol.md)

---
### Build Changes

[This change also requires updates to `paperclip-maven-plugin` which were done here.](https://github.com/PaperMC/PaperclipMavenPlugin/commit/2c36e4b16c6ab074a103c4d708aaa15791ae1bb2)

[And the change to Paperclip to incorporate that Maven plugin update is here.](https://github.com/PaperMC/Paperclip/commit/707e3703cda460b069eaf04bd0294da7904890c2)

Both `paperclip-maven-plugin` and Paperclip itself were moved to the `io.papermc` package as well as a normal `SNAPSHOT` version bump.

---

### Necessary steps before merging:
 - [x] Implement a protocol versioning system
 - [x] Implement base command set
   - [x] Start
   - [x] Stop
   - [x] Restart
   - [x] Status
   - [x] Send Command
   - [x] Timings
   - [x] Console
 - [x] Command option features (PaperMC/paperd#1 & PaperMC/paperd#2)
 - [ ] Third party testing -- _in progress_

2020-01-31 11:15 UTC, kaplan-michael commented
Hello, do you have any update on third party testing? could i help somehow?

Thanks Michael

2020-04-12 21:44 UTC, DemonWav commented
@aikar @zachbr @electronicboy if y'all could take a gander I'd appreciate it - it's somewhat of a large change but 99% of it is all new code.

2020-08-23 08:48 UTC, Proximyst requested changes
This looks pretty damn good. Thank you for this new feature!

2020-08-23 08:48 UTC, Proximyst commented on Spigot-Server-Patches/0554-Implement-daemon-mode-to-interop-with-paperd.patch
> ++            <version>2.12.0</version>
We already have `log4j-core` for `2.8.1` defined; do we need 2.12 here?

2020-08-23 08:48 UTC, Proximyst commented on Spigot-Server-Patches/0554-Implement-daemon-mode-to-interop-with-paperd.patch
> ++    private static final String SOCK_FILE = "paper.sock";
Customisable perhaps? Most software which operates using sockets allows at least for some env-var to set the socket path.

2020-08-23 08:48 UTC, Proximyst commented on Spigot-Server-Patches/0554-Implement-daemon-mode-to-interop-with-paperd.patch
> ++     * IF we are in {@link #IS_DAEMON daemon mode} this will be set to the {@link Path} created from {@link #SOCK_FILE}
```suggestion
+     * If we are in {@link #IS_DAEMON daemon mode} this will be set to the {@link Path} created from {@link #SOCK_FILE}
```

2020-08-23 08:48 UTC, Proximyst commented on Spigot-Server-Patches/0554-Implement-daemon-mode-to-interop-with-paperd.patch
> ++                this.usedMemory = (usedMemory / 1_000_000) + " MB";
These strings should probably be left to paperd.

2020-08-23 08:48 UTC, Proximyst commented on Spigot-Server-Patches/0554-Implement-daemon-mode-to-interop-with-paperd.patch
> ++            /* Paper daemon - this is misleading, calling MinecraftServer.close above will already call System.exit
In that case, this seems like it's unnecessary diff.

This should probably also be reported to Spigot's JIRA.

2020-08-23 08:48 UTC, Proximyst commented on Spigot-Server-Patches/0554-Implement-daemon-mode-to-interop-with-paperd.patch
> ++++ b/src/main/java/com/destroystokyo/paper/daemon/CloseableQueue.java
Although not really a big deal for internal classes, perhaps we should use `io.papermc.paper` here? The JNI part makes this change harder for us to do, as not everyone might update their paperd while updating Paper, which would break it as a package changes in the future while paperd doesn't accomodate it. paperd isn't even released yet, so it shouldn't really pose any issue to be future proof.

2020-08-23 09:40 UTC, DenWav commented on Spigot-Server-Patches/0554-Implement-daemon-mode-to-interop-with-paperd.patch
> ++            <version>2.12.0</version>
I have no clue why that's there honestly. I'll need to look again.

2020-08-23 09:40 UTC, DenWav commented on Spigot-Server-Patches/0554-Implement-daemon-mode-to-interop-with-paperd.patch
> ++    private static final String SOCK_FILE = "paper.sock";
That's a good thought, easy to add in too.

2020-08-23 09:40 UTC, DenWav commented on Spigot-Server-Patches/0554-Implement-daemon-mode-to-interop-with-paperd.patch
> ++                this.usedMemory = (usedMemory / 1_000_000) + " MB";
Good point.

2020-12-02 21:06 UTC, Proximyst commented
Stale who? Stale you! Wonder if we can make the bot ignore some issues...

2020-12-02 21:23 UTC, JRoy commented
FeelsWeirdMan stale bot

2022-10-22 21:12 UTC, closed without merging