Allow nerfed blazes, endermen to take water damage (fixes #2841)
PaperMC/Paper pull request #2847
Opened 2020-01-12 08:50 UTC by Trigary

In case you believe that the mentioned issue should be addressed here, in Paper, this is my take at doing that.

2020-01-12 17:56 UTC, kickash32 commented
You only changed the nerfed mobs patch, correct?

2020-01-12 20:21 UTC, Trigary commented
That's right. Well, 17 other files also got unintentionally changed thanks to the rebase.

2020-01-12 20:26 UTC, kickash32 commented
Next time I would recommend you don't commit the unnecessary changes.

2020-01-12 20:30 UTC, Trigary commented
Will do. I thought that these hashes changed for a reason and that stuff would break if they weren't updated, but it would seem that I was wrong.

2020-01-12 20:35 UTC, electronicboy commented
This would probably be much more suited towards #2763 (or, an extension thereof)

2020-01-13 00:52 UTC, kickash32 requested changes
I think it being in this patch is good because the activation range patch, PR already deals with mobs in water however, if they are nerfed, it wouldn't really change the behaviour if they were activated or otherwise.

I would recommend forcing a diff on the damage entity line, just in case in the future, there are changes to the behaviour of certain mobs touching water. Also I won't what would be the affects of doing mobTick() for nerfed mobs.

2020-01-13 00:59 UTC, electronicboy commented
Ignore my comment, my brain is trashed, for some reason I thought this was an EAR thing, not a nerf'd mob thing

2020-01-13 06:42 UTC, Trigary commented
> I would recommend forcing a diff on the damage entity line, just in case in the future, there are changes to the behaviour of certain mobs touching water. Also I won't what would be the affects of doing mobTick() for nerfed mobs.

While calling `mobTick()` on nerfed blazes seems to be fine, endermen, on the other hand, attempt random teleports in that method. What do you mean by "forcing a diff on the damage entity line"? Are you suggesting the use of empty, protected methods that subclasses can overwrite instead of `instanceof` checks?

2020-01-13 23:04 UTC, kickash32 commented
No I mean the lines you copied from the blaze and enderman classes, should be included in the patch so that when/if they are changed they cause a conflict, instead of silently changing and causing a bug in the future.

2020-01-14 06:12 UTC, Trigary commented
Oh, makes sense. Let me fix this PR.

2020-01-14 14:24 UTC, Trigary commented
Okay, so I have undone the unnecessary file changes and created a diff for the enderman class. I didn't create a diff for the blaze class because, to quote electroniccat:
> pulling in a class to add an collision thing is a bit bleh...

2020-01-15 04:44 UTC, kickash32 approved these changes

2020-01-15 07:38 UTC, electronicboy commented on Spigot-Server-Patches/0013-Allow-nerfed-mobs-to-jump-and-take-water-damage.patch
> +2.16.1.windows.4
2018 wants der git bak

2020-01-15 07:40 UTC, electronicboy approved these changes

2020-02-02 20:02 UTC, zachbr approved these changes

2020-02-09 04:19 UTC, merged