Lag compensate eating
PaperMC/Paper pull request #2861
Opened 2020-01-14 23:34 UTC by Spottedleaf

When the server is lagging, players will wait longer when eating.
Change to also use a time check instead if it passes.

2020-01-15 12:05 UTC, jiongjionger commented
Maybe you can add the realtime function of sponge to optimize the game experience. Eating food, digging blocks, etc

2020-02-07 02:51 UTC, electronicboy requested changes
.

2020-02-07 02:58 UTC, electronicboy approved these changes

2020-02-07 03:06 UTC, zachbr approved these changes

2020-02-07 03:06 UTC, merged

2020-02-07 11:05 UTC, LoneDev6 commented
> 
> 
> Maybe you can add the realtime function of sponge to optimize the game experience. Eating food, digging blocks, etc

What's this exactly? :O seems interesting

2020-02-08 06:19 UTC, WMGameLive commented
I'm curious that is it possible for Paper to do the same thing for breaking block?
When the server lagging, breaking block always need to wait.