#2772 - Send command map with config option
PaperMC/Paper pull request #2938
Opened 2020-02-07 21:38 UTC by Callahhh

Continuation of #2772, wanted to speed that along...
Fixes #2588

2020-02-08 01:14 UTC, Callahhh commented
Fixed the bug that left you in an unpleasant state.

2020-02-08 01:15 UTC, BillyGalbreath approved these changes

2020-02-08 01:50 UTC, Puremin0rez approved these changes
I can confirm that any issues I experienced initially are now resolved by the latest changes.

2020-02-09 01:02 UTC, Spottedleaf commented on Spigot-Server-Patches/0437-Dont-recalculate-permissions-on-world-change.patch
> ++    	recalculatePermsOnWorldChange = getBoolean("recalculate-perms-on-world-change", recalculatePermsOnWorldChange);
this indentation

2020-02-09 01:55 UTC, Spottedleaf commented on Spigot-Server-Patches/0437-Dont-recalculate-permissions-on-world-change.patch
> ++	public boolean recalculatePermsOnWorldChange = false;
no tabs

2020-02-09 02:16 UTC, electronicboy commented on Spigot-Server-Patches/0437-Dont-recalculate-permissions-on-world-change.patch
> ++    public boolean recalculatePermsOnWorldChange = false;
I'm iffy on this, this is one of those things which I believe should be opt-in, people use permissions across world, let's not break their setups

2020-02-09 06:29 UTC, BillyGalbreath requested changes

2020-02-09 06:29 UTC, BillyGalbreath commented on Spigot-Server-Patches/0437-Dont-recalculate-permissions-on-world-change.patch
> ++        recalculatePermsOnWorldChange = getBoolean("recalculate-perms-on-world-change", recalculatePermsOnWorldChange);
This should probably be in the `settings` section of the config

2020-02-12 04:58 UTC, Spottedleaf commented on Spigot-Server-Patches/0437-Dont-recalculate-permissions-on-world-change.patch
> ++    private void recalculatePermsOnWorldChange() {
needs to be static

2020-02-24 00:05 UTC, SrBedrock commented
Could this break permissions that depend on the world as a context?

Example: Player has a permission that is only given in the world world_nether.
Using luckperms would be something like:
/lp user `<player>` permission set `my.permission` true `world=world_nether`

If the player with that permission goes to the world called world_nether, would the permission have no effect?
This permission is verified when the player dies.

2020-02-24 00:17 UTC, Artuto commented
This is only for the command list

2020-02-24 00:28 UTC, SrBedrock commented
Thanks @Artuto

2020-03-25 07:50 UTC, Plutoren commented
I am getting a 700ms lag spike on every player's world change and I'm told this could fix it so... bump

2020-03-25 12:32 UTC, clrxbl commented
There is no need to "bump" PR's on Github. If you think this can fix it, build a Paper jar w/ the patch and see if it does.

2020-03-25 12:58 UTC, Plutoren commented
Ahh, my bad, I only did so at the suggestion of someone on the discord, and it appears someone has already tested it and confirmed it fixes the issue. I can test it myself if that would help the pr get merged it just seems like a pretty critical issue (I have 10+ world changes per minute on my server which means my server is stalling about 15% of the time) But I am not trying to break the workflow around here I just talked about it on discord and someone said this branch was the cure and to bump it so I hope it gets merged one day :)

2020-03-27 06:25 UTC, electronicboy commented
Sorry for the immense delay on this,
I'm confused about the total intent of this, the PR states that it's preventing the command structure from being recalculated, but, it doesn't stop that, and instead just restricts the actual permission recalculation? am I missing something?

2020-03-30 22:26 UTC, Callahhh commented
> Sorry for the immense delay on this,
> I'm confused about the total intent of this, the PR states that it's preventing the command structure from being recalculated, but, it doesn't stop that, and instead just restricts the actual permission recalculation? am I missing something?

Yep, you're correct. The if statement needed to be moved down. I have since adjusted it and have tested it with @Plutoren (who was suffering from this issue) to make sure:
1) No more lag spikes on world changes
2) The bug that left you in an unpleasant state didn't show up again with these changes.

I believe from our testing both of these criteria have been met.

However, if anyone would like to test themselves, here's the jar: 
https://drive.google.com/file/d/1gf0yAUtvVC5FPmJh_NVXQUdBWsXW4Nu7/view?usp=sharing

2020-03-31 00:47 UTC, Plutoren commented
Just confirming this. My very consistent 1 second lag spikes on world change have been completely removed after trying the most recent jar. I’m testing this on a production server and have had no complaints about other bugs being introduced. Switching worlds is incredibly fast now. There is still the same lag on any server join to send the command map but I suppose that’s unavoidable, however this is a huge help so thank you.

2020-03-31 08:07 UTC, aikar reviewed
the PaperConfig is still named about permissions and not about command map.

Though would be cool if we could store results of permission checks when building the command map.

Id suggest Map<String, Boolean> on EntityPlayer where key is command name, and value is if they had permission or not.

and then when this code is invoked, after permissions are recalculated, test every command in the cached results map, and if the result is different than previous, resend command map.

This would be nicer and wouldn't require a config, and could maybe even not do a full rebuild, but instead just the different nodes?

Thoughts?

2020-03-31 17:21 UTC, Callahhh commented
Fixed the settings name, I like the idea and it sounds good but I don't think I'd be able to implement such a system at this time.

2020-04-09 06:51 UTC, closed without merging