add itemWorldMapUpdateRenderRadiusWorld(No/Has)Ceiling a configuable value
PaperMC/Paper pull request #2954
Opened 2020-02-13 14:21 UTC by jeffry1829

make itemWorldMapUpdateRenderRadiusWorldNoCeiling/HasCeiling a configuable value

2020-02-13 14:31 UTC, MiniDigger commented
Whats the usecase?

2020-02-13 14:41 UTC, EbonJaeger commented
That's a _really_ long name, and I have absolutely no idea what it's supposed to do just by looking at it.

2020-02-13 14:42 UTC, jeffry1829 commented
> Whats the usecase?

Add a option to reduce lag caused by net.minecraft.server.v1_15_R1.ItemWorldMap.a()
![image](https://user-images.githubusercontent.com/6897769/74445844-fe3fe680-4eb1-11ea-9ea1-a3bccd890e10.png)

2020-02-13 14:49 UTC, jeffry1829 commented
> That's a _really_ long name, and I have absolutely no idea what it's supposed to do just by looking at it.

Maybe change to ItemMapUpdateRadius(No/Has)Ceiling?

2020-02-13 15:17 UTC, jeffry1829 commented
Ah, I'll explain what this PR does.
Item Map currently have update radius 128 for Overworld, and 64 for worlds has ceiling
We would need to call getChunkAtWorldCoords for (128*2)^2, i.e. 65535 times per updating.
Adding a option to limit the radius may be useful

2020-02-13 20:11 UTC, Black-Hole commented
To me it seems that there is chunk loading involved. So not loading chunks there should fix it much better.

2020-02-14 16:39 UTC, jeffry1829 commented
> To me it seems that there is chunk loading involved. So not loading chunks there should fix it much better.

You mean loading the chunk but don't ticking it?

2020-11-28 05:12 UTC, electronicboy requested changes

2020-11-28 05:12 UTC, electronicboy commented on Spigot-Server-Patches/0440-make-itemWorldMapUpdateRenderRadiusWorldNoCeiling-Ha.patch
> +             WorldMap.WorldMapHumanTracker worldmap_worldmaphumantracker = worldmap.a((EntityHuman) entity);
everything below here seems unneeded?

2020-11-28 05:12 UTC, electronicboy commented on Spigot-Server-Patches/0440-make-itemWorldMapUpdateRenderRadiusWorldNoCeiling-Ha.patch
> ++            if (world.worldProvider.g()) { // Paper - world.worldProvider.hasCeiling() - OBFHELPER
OBFHELPERS should be added to the class being called as per the contrib docs, not as comments in the method, but, this seems unneeded, nothing is changing here?

Looks like this has actually been mapped now, however

2020-11-28 05:12 UTC, electronicboy commented on Spigot-Server-Patches/0440-make-itemWorldMapUpdateRenderRadiusWorldNoCeiling-Ha.patch
> ++            	j1 = world.paperConfig.itemWorldMapUpdateRenderRadiusWorldNoCeiling / i;
`if (hasCieling) { //noCieling value` ? This seems reversed

2021-01-23 11:33 UTC, MiniDigger commented
@jeffry1829 do you plan on addressing the reviews?

2022-10-22 19:09 UTC, Owen1212055 commented
Closing PR, as it seems that this has gone inactive.

If you're still interested in continuing this PR, feel free to rebase and leave a comment and we can reopen it for you. 😄

2022-10-22 19:09 UTC, closed without merging