Fix MC-167561 - All players can make a dog stand up or sit
PaperMC/Paper pull request #2960
Opened 2020-02-14 16:24 UTC by Callahhh

2020-02-14 16:33 UTC, mikroskeem requested changes

2020-02-14 16:33 UTC, mikroskeem commented on Spigot-Server-Patches/0440-Fix-MC-167561-All-players-can-make-a-dog-stand-up-or.patch
> ++                    if ((!flag || this.isBaby()) && this.i(entityhuman)) {
`// Paper - Fix MC-167561`

2020-02-15 08:05 UTC, BillyGalbreath commented
To be completely honest, the best move here is to revert the entire method back to what it was on 1.14.4, I did that on purpur and _all_ wolf interaction bugs went away

2020-02-15 08:07 UTC, BillyGalbreath requested changes

2020-02-15 08:07 UTC, BillyGalbreath commented on Spigot-Server-Patches/0440-Fix-MC-167561-All-players-can-make-a-dog-stand-up-or.patch
> ++                    if ((!flag || this.isBaby()) && this.i(entityhuman)) { // Paper - Fix MC-167561
But, if reverting the entire method isn't in the core team's interest, at least make an obfhelper for the `isOwner` call here

2020-02-15 09:03 UTC, electronicboy commented
Need to reference what mojang have opted to do in 1.16 to make a decision on this, I'm not 100% convinced that this is the proper fix, the behavior here needs comparing to what it "should" be

2020-02-15 10:19 UTC, KennyTV commented
They moved a check and execution up to that part, also including the isOwned check, it should look like this
```
                if (!(item instanceof ItemDye)) {
                    boolean flag = super.a(entityhuman, enumhand);

                    if ((!flag || this.isBaby()) && this.i(entityhuman) && !this.i(itemstack)) {
                        this.goalSit.setSitting(!this.isSitting());
                        this.jumping = false;
                        this.navigation.o();
                        this.setGoalTarget((EntityLiving) null, TargetReason.FORGOT_TARGET, true); // CraftBukkit - reason
                    }

                    return flag;
                }
```
as well as removing that part from below

2020-02-21 18:48 UTC, closed without merging