Async command map building
PaperMC/Paper pull request #3116
Opened 2020-04-09 07:12 UTC by Callahhh

Builds the command map async, focuses on fixing the root problem described in #2938 instead of just ignoring it. Leaf said he had a better idea but since I had this finished already.. thought might as well PR it. 

Needs testing from someone who suffers from lag spikes when players connect/change worlds.
Shows up as CommandDispatcher.a() in sampler reports.

2020-04-09 07:17 UTC, aikar commented
Impl looks perfectly fine to me. is it running fine for you behaviorally? Tested with a plugin using the event?

2020-04-09 07:17 UTC, aikar approved these changes

2020-04-09 07:18 UTC, aikar requested changes

2020-04-09 07:18 UTC, aikar commented on Spigot-Server-Patches/0463-Async-command-map-building.patch
> ++    // Paper end - Async command map building
this should be up at the private void runSync

2020-04-09 07:18 UTC, aikar commented on Spigot-Server-Patches/0463-Async-command-map-building.patch
> ++
paper start here

2020-04-09 07:18 UTC, aikar commented on Spigot-Server-Patches/0463-Async-command-map-building.patch
> ++    private void sendAsync(EntityPlayer entityplayer) {
paper end here

2020-04-09 07:31 UTC, aikar approved these changes

2020-04-10 18:37 UTC, Callahhh commented
Had someone test it, looks like it broke tab complete completely. no errors in console either. https://i.gyazo.com/1c9616a53411e3acd73159de77a159ef.png 

Guess it's not possible?

2020-04-10 18:45 UTC, electronicboy commented
I did actually wanna look into this a while back, but there was a thing or two which I'd figured I'd have to look into, but it's doable

2020-04-10 19:05 UTC, BillyGalbreath commented on Spigot-Server-Patches/0463-Async-command-map-building.patch
> ++        java.util.concurrent.ForkJoinPool.commonPool().submit(() -> {
Shouldn't this be `invoke` so its executed? You're just `submit`ting it to queue but never executing.

2020-04-10 21:36 UTC, Callahhh commented
As Billy pointed out, I was using `submit` instead of `execute` for the async task. Issue still persisted, but I also noticed that I was using `postToMainThread` for the sync task. That method does not do as the name suggests, so that has also been changed to `execute`. After testing, it looks like these were the correct changes as it retains the same functionality as before, just now off the server thread.

2020-04-12 21:12 UTC, merged