Entity Tick Limiter
PaperMC/Paper pull request #3134
Opened 2020-04-12 09:50 UTC by MiniDigger

This is rather experimental, haven't properly tested it yet.

It basically allows you to skip some ticks of some entities, either via config, or on demand via a command.

The impact is quite noticeable, both on the performance side:
![https://i.imgur.com/QPzEh7N.png](https://i.imgur.com/QPzEh7N.png)
(ticklimit for villager 1/2/3/4)

but also on the gameplay side, you can see the entities lagging:
https://streamable.com/lc9hzh

But, at 2 it isn't that noticeable and it's still better than your whole server lagging, so server owners might take that tradeoff. 

At dyescape we had great experience with setting high values for ender pearls, we use those at nametags and it eliminated the lag coming from them.
That's just one example how different setups may take use of this.

2020-04-12 13:30 UTC, clrxbl commented
decreased entity ticking by 11%, good shit

2020-04-12 14:41 UTC, A248 commented
What's the difference between this and Spigot's max-tick-time?

2020-04-12 16:59 UTC, aikar requested changes
Going to leave a general review.

Overall not happy with current implementation as it exhibits the same issues we forcefully removed Spigot's tick limiter.

This needs to hook into EAR instead, as ultimately what you are seeking to control here is not ticking an entity 1 in 20 ticks, and instead tick it in 1 in X ticks instead.

The "tick every" value should be stored on the entity in the constructor like so:

this.tickInactiveEvery = PaperConfig.tickLimiters.getOrDefault(this.getMinecraftKeyString(), 20); // default 20 for existing behavior. Use minecraft key instead of anything to do with EntityTypes

the check for ticksLived % every needs to be modified at ActivationRange 309 area... but DO NOT modify that % 20 there.

Instead put it below and control the isActive:

```
--- a/src/main/java/org/spigotmc/ActivationRange.java
+++ b/src/main/java/org/spigotmc/ActivationRange.java
@@ -312,12 +312,13 @@ public class ActivationRange
                 // Paper start
                 int immunity = checkEntityImmunities(entity);
                 if (immunity >= 0) {
+                    isActive = true;
                     entity.activatedTick = MinecraftServer.currentTick + immunity;
-                } else {
+                } else if ( ( MinecraftServer.currentTick - entity.activatedTick - 1 ) % entity.tickInactiveEvery == 0 ){
+                    isActive = true;
                     entity.isTemporarilyActive = true;
                 }
                 // Paper end
-                isActive = true;
```

That should be all that is needed. This will keep all the safety features of EAR and further reduce entity cost of inactive entities per mob by your control. 

This will require the value be a multiple of 20, but thats fine IMO.

Might be easier to then put it under spigot.yml entity-activation-range section for ease of keeping EAR's settings together. We did that for previous additions.
```
entity-activation-range:
  tick-inactive-every-by-mob:
     "minecraft:item": 60
```

2020-05-29 14:04 UTC, pczmr8v5n454iycf commented
This would be more useful if Paper has something like Sponge's `Realtime`

2020-05-29 14:24 UTC, aikar commented
Forgot this was open, but we are not interested in any form of tick limiting. Strongly discourage ever doing this.

2020-05-29 14:24 UTC, closed without merging

2020-05-29 14:27 UTC, aikar commented
Also this is similar to the % 4 we have currently for EAR, but that's done in a safer way. so can make that configurable too.

2020-05-29 18:39 UTC, MiniDigger commented
If I ever want to take a shot at implementing your suggestions I'll find this PR. Maybe when dyescape actually runs in Prod and we need to take such measures to address performance issues.
Nothing I plan on picking up any time soon tho, so it's fine to be closed.