Allow using signs inside of spawn protection
PaperMC/Paper pull request #3143
Opened 2020-04-15 00:50 UTC by ntoonio

Signs have the ability to have a `run_command` tag that allows the player to execute a command by right clicking the sign. However the game sees this as "using a sign" in the same way as "using a chest" so it doesn't allow it.

I propose we do allow signs to be right clicked inside of the spawn protection. I think this will be beneficial for most servers, for example choosing team in spawn. In case some server would like only op to use the signs that can be done in other ways using scoreboards.

2020-04-15 09:46 UTC, aikar requested changes
This isn't the correct place for this, would need to go in DedicatedServer line 551~ and then check if type = sign and fail if not. 

And this would need to be a PaperWorldConfig to enable this, default off.

2020-04-15 16:01 UTC, ntoonio commented
As I understand it, the function you're referring to (DedicatedServer:539) checks if a block is protected or not. And if every block that is a signs return that it's not protected that would mean that signs can be destroyed, and possibly placed. Therefore I decided to put it where I did.

Definitely agree that it should be configurable tho.

2020-04-28 14:35 UTC, Proximyst approved these changes
Looks good to me :)

2020-04-29 04:01 UTC, aikar requested changes

2020-04-29 04:01 UTC, aikar commented on Spigot-Server-Patches/0477-Allow-using-signs-inside-spawn-protection.patch
> ++        } else if (this.teleportPos == null && this.player.g((double) blockposition.getX() + 0.5D, (double) blockposition.getY() + 0.5D, (double) blockposition.getZ() + 0.5D) < 64.0D && (worldserver
lets wrap the condition here with ( ) to be clearer to read.

2020-04-29 04:01 UTC, aikar commented on Spigot-Server-Patches/0477-Allow-using-signs-inside-spawn-protection.patch
> ++    public boolean allowUsignSignsInsideSpawnProtection = false;
typo in Using

2020-05-11 17:09 UTC, ntoonio commented
How does it work now that other patches has been merged. Patch number 477 (the number my patch was given) already exists in the repo. Do i have to rename the patch and make a new commit?

2020-05-11 17:13 UTC, aikar commented
you can leave as is, we will rename it for you or itll rename on next rebuild we do either one.
I'll see about reviewing and merging this tonight

2020-12-02 20:01 UTC, electronicboy approved these changes

2021-03-09 19:02 UTC, merged

2021-03-09 19:03 UTC, MiniDigger commented
thank you for your first contribution! I apologize for taking so long to get this in :/