Add StructureGenerateEvent
PaperMC/Paper pull request #3240
Opened 2020-04-27 17:48 UTC by NahuLD

It's an event that is called when a structure is generated in a world.
For anyone wondering why it doesn't extend a ChunkEvent or a WorldEvent it's because they are both sync (as well as this event being fired before the chunk generation).

2020-04-27 17:52 UTC, Proximyst requested changes

2020-04-27 17:52 UTC, Proximyst commented on Spigot-API-Patches/0200-Add-StructureGenerateEvent.patch
> ++ * Async event called when a structure is generated on the world.
A structure is generated *in* a world.

2020-04-27 17:52 UTC, Proximyst commented on Spigot-API-Patches/0200-Add-StructureGenerateEvent.patch
> ++    private final int chunkX, chunkZ;
Split these into their own, separate declarations.

2020-04-27 17:52 UTC, Proximyst commented on Spigot-API-Patches/0200-Add-StructureGenerateEvent.patch
> ++     * @return chunk Z.
Use a new line to be consistent with the formatting already used.

2020-04-27 17:52 UTC, Proximyst commented on Spigot-API-Patches/0200-Add-StructureGenerateEvent.patch
> ++    /**
Just use `{@inheritDoc}`

2020-04-27 17:52 UTC, Proximyst commented on Spigot-API-Patches/0200-Add-StructureGenerateEvent.patch
> ++     * Check whether the event is being cancelled.
Just use `{@inheritDoc}`

2020-04-27 17:52 UTC, Proximyst commented on Spigot-Server-Patches/0494-Add-StructureGenerateEvent.patch
> ++                    // Paper end
Just use a single `// Paper` comment on the ending brace.

2020-04-27 18:32 UTC, NahuLD commented on Spigot-API-Patches/0200-Add-StructureGenerateEvent.patch
> ++ * Async event called when a structure is generated on the world.
Solved.

2020-04-27 18:32 UTC, NahuLD commented on Spigot-API-Patches/0200-Add-StructureGenerateEvent.patch
> ++    private final int chunkX, chunkZ;
Solved.

2020-04-27 18:32 UTC, NahuLD commented on Spigot-API-Patches/0200-Add-StructureGenerateEvent.patch
> ++     * Check whether the event is being cancelled.
Solved.

2020-04-27 18:49 UTC, chickeneer commented
Looking at the nms event implementation in the code. This is not going to fire for any strongholds currently. (look up above) at the CraftBukkit section.

2020-04-27 18:55 UTC, NahuLD commented
I'm not too sure why that was split and messing with it would be messing with CraftBukkit changes.

2020-04-27 19:02 UTC, chickeneer commented
Context. https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/c03b2befb25ee6813f5f426ce7e4c2e6d13a837f#nms-patches/ChunkGenerator.patch

2020-04-27 19:21 UTC, NahuLD commented
The only workaround for this I can think of is firing the event again although that would look pretty ugly.
Anyone got any ideas?

2020-04-27 19:26 UTC, KennyTV commented
it's an if-else for the CB check, so just throw the eventcode into a method to not have duplicated code and call it in both the STRONGHOLD case and the normal one after the else

2020-06-23 15:39 UTC, NahuLD commented
This PR doesn't contain the singlethreaded patch I've made after realizing it'd crash in some cases. Will remake it once 1.16 is out.

2020-06-23 15:39 UTC, closed without merging