Add files via upload
PaperMC/Paper pull request #3359
Opened 2020-05-12 21:12 UTC by Nesaak

Getting the PersistentDataContainer of an ItemStack can be much slower than using NMS to get the NBT due to the use of cloning in getItemMeta(). This API patch would add a way to edit the PDC of an ItemStack directly by using its current ItemMeta.

2020-05-12 21:13 UTC, kickash32 commented
You should change your title.

2020-05-12 23:51 UTC, mikroskeem requested changes

2020-05-12 23:51 UTC, mikroskeem commented on Spigot-API-Patches/0207-Add-PersistentDataContainer-getter-in-ItemStack.patch
> ++import org.bukkit.persistence.PersistentDataContainer; // Paper
Remove this import, unneeded diff.

2020-05-12 23:51 UTC, mikroskeem commented on Spigot-API-Patches/0207-Add-PersistentDataContainer-getter-in-ItemStack.patch
> ++    public PersistentDataContainer getPersistentDataContainer() {
... and use fully qualified type name here instead

2020-05-13 00:15 UTC, Nesaak commented on Spigot-API-Patches/0207-Add-PersistentDataContainer-getter-in-ItemStack.patch
> ++import org.bukkit.persistence.PersistentDataContainer; // Paper
wait why is it unneeded?

2020-05-13 00:17 UTC, mikroskeem commented on Spigot-API-Patches/0207-Add-PersistentDataContainer-getter-in-ItemStack.patch
> ++import org.bukkit.persistence.PersistentDataContainer; // Paper
See my next comment on this patch file

2020-05-13 01:28 UTC, aikar requested changes

2020-05-13 01:28 UTC, aikar commented on Spigot-API-Patches/0207-Add-PersistentDataContainer-getter-in-ItemStack.patch
> ++     * Gets the {@link PersistentDataContainer} of this items current {@link ItemMeta}. Can be faster than cloning ItemMeta using {@link #getItemMeta()}.
Needs to make a comment that this is a live map, and that any updates to it will be immediate without using setItemMeta

2020-05-14 01:37 UTC, Nesaak commented
I've just realized that this method doesn't work if the item is a CraftItemStack because of how it handles Material type. I'm not sure if this is still possible in this form. There definitely are performance improvements that *could* be made.

2020-05-14 01:45 UTC, aikar commented
I think it's becasue it needs setItemMeta(getItemMeta()), but I think we may actually want to instead implement PersistentDataContainer interface ON ItemStack

so you can then do 
item.get(key, type)
item.set(key, type, value);

if meta is null, get returns null.
if meta is null, set initializes meta (using above full syntax which does more than what you did initially) and calls the appropriate setter.

2020-05-14 17:18 UTC, Nesaak commented
This is still consistently slower than NMS, especially when comparing Bukkit and CraftBukkit item stacks, using NMS can be faster by 10x. This also still causes issues when the ItemStack is an instance of CraftItemStack, not sure if I messed up implementation though.

2020-05-14 17:33 UTC, aikar requested changes

2020-05-14 17:33 UTC, aikar commented on Spigot-API-Patches/0207-Implement-PersistentDataContainer-in-ItemStack.patch
> ++    public boolean isEmpty() {
grr, can't do this :/ going to need to do like .getLivePersistentDataContainer() instead that moves all this logic into an accessor class.

2020-05-14 17:35 UTC, aikar commented
show your benchmarks showing that .get() or  an itemstack with NO meta or with meta is that slow

It's either creating or reusing what's there, how can that be 10x slower?

Do not measure first time set performance. Yes it'll be slower, but you'll just have to deal with that, you're not going to be creating new meta thousands of times a second.

2020-05-14 17:38 UTC, A248 commented
Directly accessing internals is always going to be ever so slightly faster because it doesn't have to go through another method call. However, this is negligible for most purposes, and pales in comparison to the benefits of API.

2020-05-14 18:33 UTC, Nesaak commented
> Directly accessing internals is always going to be ever so slightly faster because it doesn't have to go through another method call. However, this is negligible for most purposes, and pales in comparison to the benefits of API.

Yes in my testing I completed 10 million reads in ~1000ms using the PersistentDataContainer API and <100ms using internals. Here is the code I used to benchmark:
```
        start = System.nanoTime();
        for (int i = 0; i < 10_000_000; i++) {
            pdc.get(key, PersistentDataType.INTEGER);
        }
        sender.sendMessage("PDC finished 10,000,000 reads in " + ((System.nanoTime() - start) / 1000000) + "ms");

        start = System.nanoTime();
        for (int i = 0; i < 10_000_000; i++) {
            ((CraftItemStack) nms).getHandle().getOrCreateTag().get("id");
        }
        sender.sendMessage("NMS finished 10,000,000 reads in " + ((System.nanoTime() - start) / 1000000) + "ms");
```
where the ItemStack were defined here:
```
        pdc = new ItemStack(Material.SLIME_BALL);
        pdc.set(key, PersistentDataType.INTEGER, 5);

        nms = CraftItemStack.asNewCraftStack(Items.SLIME_BALL);
        NBTTagCompound tag = ((CraftItemStack) nms).getHandle().getOrCreateTag();
        tag.setInt("test", 5);
        ((CraftItemStack) nms).getHandle().setTag(tag);
```
These ItemStacks were only defined once. I would assume the ItemMeta of pdc should be created and be ready for access and should not have that big of a performance impact.

2020-05-14 20:38 UTC, Nesaak commented
I think the problems stem from CraftItemStack not using any stored Meta and just getting the current meta of it's NMS handle. This behavior is expected for this class but is pretty expensive. It involves reading the entire NBT tag of the NMS Itemstack and creating a new instance of CraftMetaItem (or child) which is where the bottleneck is.

2020-05-15 14:15 UTC, aikar commented
This is solvable.

make a .getLivePersistentDataContainer() on ItemStack that returns an instance of all the methods this current PR state adds (can just create a single cached instance and reuse it) in ItemStack.java

Then in CraftItemStack, override this method and return an NMS version that directly references the NMS version of PDC.

```java
        if (!persistentDataContainer.isEmpty()) {
            NBTTagCompound bukkitCustomCompound = new NBTTagCompound();
            Map<String, NBTBase> rawPublicMap = persistentDataContainer.getRaw();

            for (Map.Entry<String, NBTBase> nbtBaseEntry : rawPublicMap.entrySet()) {
                bukkitCustomCompound.set(nbtBaseEntry.getKey(), nbtBaseEntry.getValue());
            }
            itemTag.set(BUKKIT_CUSTOM_TAG.NBT, bukkitCustomCompound);
```

2020-05-15 16:34 UTC, Nesaak commented
When you say an instance of all the methods in current PR state, do you mean an anonymous instance of PersistentDataContainer? Then I would have a new field in ItemStack which stores that container? I was thinking about overriding CraftItemStack's implementation of it but wanted to keep this to just an API patch. Also, I don't understand how that piece of code would work, wouldn't you have to set the NBT each time a change in pdc occurs?

2020-05-15 17:48 UTC, aikar commented
Yes, that's the entire idea of a live edit.

But yes your custom implementing PDC in craft stacks.

2020-05-15 18:21 UTC, Nesaak commented
How would I get an NMS version of PDC though, the only way I could get a PDC from CraftItemStack is through getItemMeta which is a clone and doesn't translate to NMS. I'm just confused about how I'm supposed to implement getLivePersistentDataContainer() without just manually writing out the logic for the PDC into the handle NMS NBT.

2021-01-02 10:43 UTC, electronicboy approved these changes
Looks good to me, no idea if anybody requesting changes previously would like to double check

2022-10-22 19:11 UTC, Owen1212055 commented
Closing PR, as it seems that this has gone inactive.

And in general, there are plans to modify this whole area by making item meta a wrapper, so we will be able to have a way to return a live version like this in the future.

If you're still interested in continuing this PR, feel free to rebase and leave a comment and we can reopen it for you. 😄

2022-10-22 19:11 UTC, closed without merging