Expose getItemStack() in Arrows
PaperMC/Paper pull request #3433
Opened 2020-05-22 18:03 UTC by Nesaak

This PR exposes getItemStack() in AbstractArrow which I have implemented CraftArrow to return the NMS method of getItemStack(). This is currently not possible in the API without some trickery and would involve little maintenance in future versions. The only NMS change I had to make was changing the visibility of getItemStack() in EntityArrow and subclasses from protected to public.

2020-05-22 18:13 UTC, HexedHero commented
Is there even any use cases for this?

2020-05-22 18:18 UTC, Nesaak commented
> Is there even any use cases for this?

I've found use cases such as when a trident is hit, returning it to the player in ItemStack form. For normal arrows, you can just create a new ItemStack of an arrow but I feel like there should be an API method to cover all types of arrows such as tridents. Overall I feel like it'd a useful method in Arrow where it's currently lacking.

2020-05-23 06:50 UTC, MiniDigger commented
You should mark your changes with // Paper comments

2020-05-23 06:53 UTC, electronicboy commented on Spigot-Server-Patches/0530-Expose-Arrow-getItemStack.patch
> +-    protected abstract ItemStack getItemStack();
this patch could be simplified by adding a public obfhelper, would be more future-proof too

2020-05-29 08:21 UTC, Proximyst requested changes
Squash commits

2020-06-20 20:34 UTC, merged