Fix black lore not serializing
PaperMC/Paper pull request #3443
Opened 2020-05-24 20:45 UTC by Nesaak

Allows black lore to properly serialize, would solve #3440

2020-05-24 21:02 UTC, JRoy requested changes
Needs paper comment

2020-05-24 21:02 UTC, JRoy commented on Spigot-Server-Patches/0532-Fix-black-lore-not-serializing.patch
> ++            builder.put(LORE.BUKKIT, ImmutableList.copyOf(Lists.transform(lore, lore -> { return CraftChatMessage.fromComponent(lore, EnumChatFormat.RESET); })));
```suggestion
+            builder.put(LORE.BUKKIT, ImmutableList.copyOf(Lists.transform(lore, lore -> { return CraftChatMessage.fromComponent(lore, EnumChatFormat.RESET); }))); // Paper - Fix SPIGOT-5749
```

2020-05-25 07:53 UTC, aurorasmiles commented
Isn't that kind of a duplicate to https://github.com/PaperMC/Paper/pull/2672

2020-05-25 11:39 UTC, Nesaak commented
> Isn't that kind of a duplicate to #2672

Never saw that one as it's quite old. While that attempts to solve the same problem it does it completely wrong, changing vanilla functionality which would cause issues in other places.

2020-05-25 12:09 UTC, aurorasmiles commented
But this only fixes it for black Lores if I understand correctly, while #2672 would also fix it for names.

2020-05-25 12:24 UTC, electronicboy commented
The problem is is that all these fixes end up changing how stuff is exposed in the API, this is something that really needs to be fixed upstream, doing it here is really iffy due to the behavioral change, which, I know is desired for you, but often has side-effects of breaking plugins, especially those which have for a long time been working around these issues, it really ends up throwing these "simple" types of PRs on the fence, especially as I know that there is a good fair chance that we'll have to revert this due to some plugin

2020-05-25 12:59 UTC, Nesaak commented
> The problem is is that all these fixes end up changing how stuff is exposed in the API, this is something that really needs to be fixed upstream, doing it here is really iffy due to the behavioral change, which, I know is desired for you, but often has side-effects of breaking plugins, especially those which have for a long time been working around these issues, it really ends up throwing these "simple" types of PRs on the fence, especially as I know that there is a good fair chance that we'll have to revert this due to some plugin

I've tested fairly extensively and the only change that I was able to observe was the addition of first black format symbol when using ItemStack serialization. This change should be much more stable than the previous PR mentioned, I get your point though.

2020-05-28 11:14 UTC, bloggy commented
It seems this is fixed in spigot or am I wrong?
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/cfeef75cd979c5d2b408645909325a055376c520
Really hope for paper to fix it, too. This issue destroys all our items with black lore that worked fine on 1.13.2 but no more in 1.15.2 because of this bug.

2020-05-28 11:16 UTC, aurorasmiles commented
seems so, nice :)

2020-05-28 11:23 UTC, closed without merging