Add missing extends in mob interfaces
PaperMC/Paper pull request #3801
Opened 2020-07-05 04:18 UTC by Code-You-Fools

I think I caught most of the interface extensions that were missing. Improved my earlier PR #3794, resubmitted due to scope change.

2020-07-05 04:47 UTC, aikar requested changes
I'm a bit torn here. Ideally, Flying would not be bound to monster, but mojang does currently have 2 degrees of flying.

I feel like there should be a FlyingMonster extends Flying, Monster, and FlyingAnimal extends Flying, Animal

but currently bukkit is matching Flying -> FlyingMonster.

I question can we safely change Flying usages to FlyingMonster. 

However, the scary part is it really needs to align to mojangs definitions.

Currently, the flying interface is only used by animals, so thats just flying animals.

The Entityflying doesn't bind to anything monster oriented, but animals don't currently use it.

This one im iffy on doing too much ourselves, this may be best to PR to spigot with a breakout of FlyingMonster/FlyingAnimal type stuff.

Please join us on discord to talk about this more.

2020-07-05 04:47 UTC, aikar commented on Spigot-API-Patches/0217-Add-missing-extends.patch
> ++public interface Vex extends Monster, Flying { // Paper - Vexes fly
Mojang does not consider them flying.

2020-07-05 04:47 UTC, aikar commented on Spigot-API-Patches/0217-Add-missing-extends.patch
> ++public interface Wither extends Monster, Boss, RangedEntity, Flying { // Paper - Withers fly
Not flying to Mojang.

2020-07-05 09:05 UTC, Code-You-Fools commented
@aikar Your hesitance on doing this downstream from Spigot is understandable - I probably should've started with them, was just a bit confused on how to get access to do so. Found out after submitting this PR.

Once I'm more awake, I'll see if the Spigot devs would consider pushing a patch like this - if not, I'll come back and update this one w/ requested changes.

2020-11-14 19:54 UTC, Proximyst commented
Source repository is deleted; unmergeable PR.

2020-11-14 19:54 UTC, closed without merging