added PlayerNameEntityEvent
PaperMC/Paper pull request #3805
Opened 2020-07-05 07:36 UTC by Machine-Maker

2020-11-01 20:03 UTC, Proximyst submitted a review, later dismissed

2020-11-01 20:03 UTC, Proximyst commented on Spigot-API-Patches/0215-added-PlayerNameEntityEvent.patch
> ++package com.destroystokyo.paper.event.player;
```suggestion
+package io.papermc.paper.event.player;
```

2020-11-01 20:29 UTC, MiniDigger commented
what would be the usecase for overriding the entity?

2020-11-02 16:25 UTC, Machine-Maker commented
I'm sure there's something. I mean that's mainly in there because it was easy to add. Probably some plugin author can come up with a way to use it. Force a player to rename one specific entity, or something like that.

2020-11-02 20:34 UTC, Machine-Maker commented
Ok, this was rebased.

2020-12-14 16:57 UTC, electronicboy requested changes
a d v e n t u r e

2020-12-14 17:05 UTC, Machine-Maker commented
Yeah, I have several PRs that are just waiting on adventure :)

2021-03-04 18:46 UTC, MiniDigger commented
@Machine-Maker mind updating?

2021-03-04 19:44 UTC, Machine-Maker commented
@MiniDigger done

2021-03-04 22:55 UTC, merged