added Wither API
PaperMC/Paper pull request #3814
Opened 2020-07-05 22:42 UTC by Machine-Maker

Various methods to affect Wither entities

2020-08-23 10:32 UTC, Proximyst requested changes

2020-08-23 10:32 UTC, Proximyst commented on Spigot-API-Patches/0218-added-Wither-API.patch
> ++    boolean isPowered();
```suggestion
+    boolean isCharged();
```

2020-08-23 10:32 UTC, Proximyst commented on Spigot-API-Patches/0218-added-Wither-API.patch
> ++     * @return powered state
```suggestion
+     * @return whether the wither is charged
```

The Minecraft gamepedia wiki uses `shielded`. Choose charged or shielded and be consistent with it, I suppose.

2020-08-23 10:32 UTC, Proximyst commented on Spigot-API-Patches/0218-added-Wither-API.patch
> ++     * @return invulnerable ticks
```suggestion
+     * @return ticks the wither is invulnerable for
```

2020-08-23 10:32 UTC, Proximyst commented on Spigot-API-Patches/0218-added-Wither-API.patch
> ++     * Sets for how long in the future, the wither should be invulnerable
```suggestion
+     * Sets for how long in the future, the wither should be invulnerable.
```

2020-08-23 10:32 UTC, Proximyst commented on Spigot-API-Patches/0218-added-Wither-API.patch
> ++     * @param ticks tick amount
```suggestion
+     * @param ticks ticks the wither is invulnerable for
```

2020-08-23 10:32 UTC, Proximyst commented on Spigot-API-Patches/0218-added-Wither-API.patch
> ++     * @return true if allowed, false if not
```suggestion
+     * @return whether the wither can travel through portals
```

2020-08-23 10:32 UTC, Proximyst commented on Spigot-API-Patches/0218-added-Wither-API.patch
> ++     * Sets whether this wither can travel through portals
```suggestion
+     * Sets whether the wither can travel through portals.
```

2020-08-23 10:32 UTC, Proximyst commented on Spigot-API-Patches/0218-added-Wither-API.patch
> ++     * @param value true to allow travel, false to deny
```suggestion
+     * @param value whether the wither can travel through portals
```

2020-08-23 10:32 UTC, Proximyst commented on Spigot-Server-Patches/0538-added-Wither-API.patch
> ++    public boolean isPowered() { return this.T_(); } // Paper - OBFHELPER
```suggestion
+    public final boolean isPowered() { return this.T_(); } // Paper - OBFHELPER
```

2020-08-23 10:32 UTC, Proximyst commented on Spigot-Server-Patches/0538-added-Wither-API.patch
> ++    public void setCanPortal(boolean canPortal) { this.canPortal = canPortal; } // Paper
Move up to field declaration.

2020-08-23 10:32 UTC, Proximyst commented on Spigot-Server-Patches/0538-added-Wither-API.patch
> ++    // Paper start
```suggestion
     }
+
+    // Paper start
```

2020-11-02 21:20 UTC, Machine-Maker commented
Ok, this was rebased.

2020-12-19 15:18 UTC, Proximyst approved these changes
LGTM! Sorry for the review taking a while 😝

2021-01-17 20:01 UTC, merged