Add Block#isValidTool
PaperMC/Paper pull request #3834
Opened 2020-07-06 19:47 UTC by Machine-Maker

As talked about in the discord

2020-07-06 20:16 UTC, FranKusmiruk commented
Just an idea, but I would rename  the method to be `isBreakable(ItemStack)` and also an additional method `isBreakable` without arguments to match the style of `breakNaturally`

2020-07-06 20:28 UTC, kickash32 commented
isBreakable returning false implies you cannot break it at all like bedrock. I like the idea with following the style of breakNaturally though.

2020-08-23 10:20 UTC, Proximyst requested changes

2020-08-23 10:20 UTC, Proximyst commented on Spigot-API-Patches/0218-Add-Block-isValidTool.patch
> ++    boolean isValidTool(ItemStack itemStack);
Perhaps we should use a tristate here instead? I.e. either you can break it as it's supposed to, can break but not ideal tool, or cannot break at all. (cc @kickash32)

2020-08-23 15:36 UTC, kickash32 commented
I believe there is also issue with the implementation, this only checks if the drops are non zero, however for certain actions like breaking ice with a non silk touch pickaxe, you could argue that it is a valid tool. Maybe add this information to the docs that this does not behave like some people may expect it to. Maybe theres something in adventure mode we could use?

2020-08-23 15:36 UTC, kickash32 commented on Spigot-API-Patches/0218-Add-Block-isValidTool.patch
> ++    boolean isValidTool(ItemStack itemStack);
Not exactly opposed to it but maybe that should be a *different* method that returns a 3 valued enum. The original purpose of this API addition was to have a create a simple API call which would help reduce code complexity for API consumers, so lets not lose sight of that.

2020-11-02 21:32 UTC, Machine-Maker commented
k, rebased.

2020-12-14 16:58 UTC, electronicboy approved these changes, later dismissed

2021-03-09 18:38 UTC, merged