Add smithing item helpers
PaperMC/Paper pull request #3937
Opened 2020-07-18 11:05 UTC by KennyTV

because I can only count to 1

2020-07-19 17:45 UTC, CanadianBaconBoi commented
All this does is add bulk code, if I were you, I'd learn to count to 1

2020-07-19 17:46 UTC, Proximyst commented
There is already a patch for this exact thing. This only adds more of the same as every other part of that same patch to the API.

2020-08-23 14:14 UTC, Proximyst submitted a review, later dismissed

2020-08-23 14:15 UTC, kashike requested changes

2020-08-23 14:15 UTC, kashike commented on Spigot-API-Patches/0201-Add-item-slot-convenience-methods.patch
> ++    default ItemStack getInputGear() {
`getInputEquipment`?

2020-08-23 14:15 UTC, kashike commented on Spigot-API-Patches/0201-Add-item-slot-convenience-methods.patch
> ++    default void setInputGear(@Nullable ItemStack itemStack) {
`setInputEquipment`?

2020-08-23 14:22 UTC, Proximyst approved these changes

2020-08-23 14:26 UTC, kashike approved these changes

2020-08-23 14:39 UTC, merged