Configurable dungeon seed
PaperMC/Paper pull request #3940
Opened 2020-07-18 14:14 UTC by BillyGalbreath

Fixes #3909

2020-07-18 14:48 UTC, KaptainWutax commented
A quick disclaimer that this will cause every single dungeon in the world will be exactly the same (same size, same floor, same loot, same mob type) and around 10% of world seeds will contain no dungeons whatsoever as a side effect (with all 8 attempts being too high in the sky, it's a simple binomial dist with n=8, p=0.25).

2020-07-18 14:55 UTC, Proximyst commented
I haven't been following the discussion entirely myself, but I'm fairly sure I've yet to see you provide any kind of input to fix the issues you're describing. Do you have anything to offer there?

2020-07-18 15:05 UTC, KaptainWutax commented
I suggest adding a salt like with structures, it should counter a lot of the simpler attacks-- though it will still be possible to use a multi-chunk approach to eliminate salt dependency and continue to abuse dungeons. 

For seed cracking in general, I don't have a proper solution laid out that I am 100% confident will work but I'm working on it. I'm just giving y'all a heads-up since calling this is a fix is a stretch... I find it a little frustrating that one can be this oblivious to their own patch. This will cause major issues for normal casual gameplay if it gets merged. 

The best I can do now is help with the analysis instead of waiting for someone to tweak the seed cracking tools to match those restrictions and have this entire mess start over again. If I can't be trusted to be helpful it that regard though I will gladly step down and figure it out on my own.

2020-07-18 15:08 UTC, Proximyst commented
I'm sure your frustrations can be solved by providing a simpler to follow explanation (graph the math, show us where the logic went wrong, etc.) for us, both Billy and anyone reading & participating in the discussion. Apparently, Billy also did not find the 10% having no dungeons to be true in his testing, but I cannot really say more as I haven't done any investigating myself.

2020-07-18 15:16 UTC, KaptainWutax commented
Pretty obvious-- same seed = same generation. If you set the decorator to the same seed for every chunk, you will get the same coordinates to get spit out. If you set the feature to the same seed for every chunk, you get the same floor, loot, mob type to get spit out. That 10% comes from the fact that decorator does nextInt(256) to determine dungeon height of 8 trials. I just calculated the probability of 8 trials spawning a dungeon above y64-- which will be consistent across the entire world.

2020-07-18 16:31 UTC, aikar requested changes
By not recreating instance this will solve the concern so that matter is closed

Just need to improve impl to store on world

2020-07-18 16:31 UTC, aikar commented on Spigot-Server-Patches/0546-Configurable-dungeon-seed.patch
> ++            int seed = com.destroystokyo.paper.PaperConfig.dungeonSeed;
This should be stored on world for the instance and then just create local as world version or existing local without any field additions as this instance is concurrently accessed and different worlds can have different seeds

2020-07-18 16:38 UTC, KaptainWutax commented
Making dungeons non-deterministic is a fix I suppose. Small suggestion would be to replace the dungeon-seed entry in the config to some boolean "random-dungeons" since the seed doesn't have any effect anymore-- it's pretty much just a new Random(). Maybe you could make use of the world rng? Anyway, looks good. 👍

2020-07-18 17:35 UTC, aikar commented
Hmm that's a good point, this should simply behave just like every other seed and be base seed + salt seed for dungeons, then it takes in xz right?

2020-07-18 17:43 UTC, KaptainWutax commented
Yea, I think a salt is the best solution if you wanna keep it deterministic.

2020-07-23 11:48 UTC, BillyGalbreath commented
Closing this in favor of leaf's patch

2020-07-23 11:48 UTC, closed without merging