Use title packet for actionbar methods
PaperMC/Paper pull request #3959
Opened 2020-07-19 21:16 UTC by KennyTV

This is quite the micro change, but this makes Paper's actionbar methods use the title packet instead of the chat packet to *ever so slightly* reduce encoded data (without the uuid, since that's always the system uuid anyways).
Also puts the title packet use for components to a method inside of the Player interface, as opposed to Spigot's sub class, so that using the stupid sub class isn't encouraged any more than it already is

Thought this might *just* be enough to be at least slightly better in cases of extremely frequent actionbar spam / using the 'more appropriate' packet, since what you send isn't  "Game Info", but a custom actionbar title, which also spares the client from 1-2 extra checks

2020-07-19 21:49 UTC, BillyGalbreath approved these changes
This also fixes https://bugs.mojang.com/browse/MC-119145

2020-07-19 22:32 UTC, aikar commented
I'm confused, does mojang have 2 different ways to show text in the action bar, or is this just going to show titles instead?

def not a fan of an action bar api faking as a title

2020-07-19 22:36 UTC, Proximyst approved these changes

2020-07-19 23:06 UTC, KennyTV commented
You can both use the chat and title packet to display actionbar messages, yes.
Differences are checking against the sender uuid, some extra failure checking, and getting the handler for the chat packet vs. a switch and direct setting with the title packet, but both end up at the same exact place

2020-07-19 23:10 UTC, yannicklamprecht commented
You're able to time action bar messages through title packets. Same like title. Idk what was added first.

2020-07-21 15:17 UTC, MrIvanPlays commented
perhaps add sendActionbar with fadeIn, stay and fadeOut too?

2020-07-21 15:21 UTC, KennyTV commented
Not possible.

2020-07-22 07:01 UTC, aikar requested changes

2020-07-22 07:01 UTC, aikar commented on Spigot-Server-Patches/0131-String-based-Action-Bar-API.patch
> ++        getHandle().playerConnection.sendPacket(new PacketPlayOutTitle(PacketPlayOutTitle.EnumTitleAction.ACTIONBAR, new net.minecraft.server.ChatComponentText(message)));
This is an API break. it should be CraftChatMessage.fromString() instead.

2020-07-22 08:01 UTC, merged