Apply advancements async
PaperMC/Paper pull request #4057
Opened 2020-08-04 12:18 UTC by Proximyst

Asynchronous advancements, take 3.

Advancements are loaded in the same way as before, except asynchronously.
This uses the approach from take 1 (#3454), except with the notes from Aikar
taken into account.

A player with *all* advancements took an estimated 15-30ms or so every login
on my own machine. The first login of which always took well over 200ms,
hanging around at about 300ms. I'll take the stance that this change will
provide favourable performance alleviations for servers.

I've again taken the approach of a "get if loaded" method in certain cases,
mostly just those which save data. This should lead to corrupt data or simply
not yet loaded data not being saved which results in no data loss and no
waiting for the loading to finish.

2020-08-04 17:45 UTC, tofipix commented
Why isn't async advancements setting turned on by default? , because in my opinion it should

2020-08-05 05:16 UTC, MrIvanPlays commented
> Why isn't async advancements setting turned on by default?

Because by default every setting should replicate vanilla behavior (or shouldn't, but that's how it is in upstream projects so paper follows) and as this is not vanilla's default behavior in order to get it we disable it by default.

2020-08-05 10:19 UTC, Proximyst commented
> Because by default every setting should replicate vanilla behavior

No. Default settings in Paper are what people would most likely prefer.

> Why isn't async advancements setting turned on by default?

Because I just typed out the setting while not really thinking over defaults.
I'm all for moving it to default on, but I'd like to hear if anyone else agrees
to that first. (Feel free to :+1: this to show you agree with default on)
Ultimately, the merger can also just make it default on if they feel that
would be the best option.

2020-08-05 13:10 UTC, Unprotesting commented
> > Because by default every setting should replicate vanilla behavior
> 
> No. Default settings in Paper are what people would most likely prefer.
> 
> > Why isn't async advancements setting turned on by default?
> 
> Because I just typed out the setting while not really thinking over defaults.
> I'm all for moving it to default on, but I'd like to hear if anyone else agrees
> to that first. (Feel free to 👍 this to show you agree with default on)
> Ultimately, the merger can also just make it default on if they feel that
> would be the best option.

It needs to be default on because its something that not a large amount of server owners will understand. I know a lot of server owners who wouldn't even know what asynchronous means. By making it default it means those server owners get the performance advantage of computing more tasks asynchronously without having to learn the difference between a task being used by the main thread or not. Paper should set its default options to "what people would most likely prefer," and I think that this option being set to default is just that.

2020-08-05 14:57 UTC, MrIvanPlays commented
> Default settings in Paper are what people would most likely prefer.

Not exactly true but sure

2020-08-05 15:03 UTC, Proximyst commented
> > Default settings in Paper are what people would most likely prefer.
> 
> Not exactly true but sure

That is literally quoting a project lead.

2020-08-10 14:56 UTC, krolik-exe reviewed
default to true

2020-08-10 14:56 UTC, krolik-exe commented on Spigot-Server-Patches/0551-Apply-advancements-async.patch
> ++    public static boolean asyncAdvancements;
```suggestion
+    public static boolean asyncAdvancements = true;
```

2020-08-10 14:56 UTC, krolik-exe commented on Spigot-Server-Patches/0551-Apply-advancements-async.patch
> ++    public static boolean asyncAdvancements;
default to true

2020-08-11 13:47 UTC, aikar requested changes
You got it :) this is exactly what I was envisioning. Outside of the few adjustments, I see nothing here that will change game behavior.

So, there's no reason for us to even have a config then, as we only add configs for optimizations if it comes with a con, and i'm not seeing one here.

2020-08-11 13:47 UTC, aikar commented on Spigot-Server-Patches/0551-Apply-advancements-async.patch
> ++import java.util.concurrent.CompletableFuture;
lets inline this import

2020-08-11 13:47 UTC, aikar commented on Spigot-Server-Patches/0551-Apply-advancements-async.patch
> ++        if (!com.destroystokyo.paper.PaperConfig.asyncAdvancements) {
let's just drop this config section

2020-08-11 13:47 UTC, aikar commented on Spigot-Server-Patches/0551-Apply-advancements-async.patch
> ++        if (this.advancementDataPlayer == null) {
should add a double checked lock here to ensure we don't accidently load twice if this is called concurrently (lets not forget how dumb plugins can be)

2020-08-11 13:47 UTC, aikar commented on Spigot-Server-Patches/0551-Apply-advancements-async.patch
> ++    public static boolean asyncAdvancements;
Let's drop the config entirely. See full review comment.

2020-08-11 13:49 UTC, aikar commented
> > Default settings in Paper are what people would most likely prefer.
> 
> Not exactly true but sure

@MrIvanPlays What Proxi said is correct. That was a quote from me.

2020-08-11 14:02 UTC, Proximyst commented
I've amended the PR with the changes requested, and also removed some unnecessary null checks (thanks for the `final` reminder, IntelliJ!) on the future, as it is set in the constructor.

2020-08-16 18:19 UTC, krolik-exe commented
what is the status on this?

2020-08-17 00:44 UTC, aikar commented
Waiting for 1.16.2, we can't merge prs until it's in master

2020-08-17 04:37 UTC, Proximyst commented
I can rebase it onto 1.16.2 and open a PR if you'd like?

2020-08-19 19:23 UTC, krolik-exe commented
You can, if you want to rebase it on 1.16.2, it would be useful for those who merge it, at least so i think. You can correct me in the comments

2020-08-19 19:39 UTC, electronicboy commented
rebasing is bad for the git history, and only means that there is double the merging effort

2020-08-19 19:41 UTC, Proximyst commented
I'm somewhat disappointed I have to clarify I mean making a new PR for 1.16.2.
(Assuming it isn't merged into 1.16.2 branch first,) once it becomes master, this will be fixed for merging into master anyways.

August 19, 2020 9:40 PM, "Shane Freeder" <notifications@github.com (mailto:notifications@github.com?to=%22Shane%20Freeder%22%20<notifications@github.com>)> wrote:
	rebasing is bad for the git history, and only means that there is double the merging effort

	—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub (https://github.com/PaperMC/Paper/pull/4057#issuecomment-676622050), or unsubscribe (https://github.com/notifications/unsubscribe-auth/AEXQ6M4I6VDEFOFL23TI23LSBQTBPANCNFSM4PUK3WCA).

2020-08-19 19:43 UTC, electronicboy commented
I misread the last comment, I don't think there'd be an issue rebasing onto .2, too early I thought they meant master

2020-10-27 21:37 UTC, closed without merging