Add BukkitScheduler#createAsyncExecutor API
PaperMC/Paper pull request #4064
Opened 2020-08-05 20:10 UTC by A248

Currently, the CraftScheduler will commence asynchronous tasks every tick, per `CraftAsyncScheduler#mainThreadHeartbeat`. However, if the main thread is blocked, async tasks will not begin.

A common use case involves awaiting the result of an asynchronous computation on the main thread. Using the current API in the BukkitScheduler, this might cause a deadlock, since initiation of async tasks requires the main thread to keep beating.

To solve this, I added the `BukkitScheduler#createAsyncExecutor` API. This method returns an `Executor` not coupled to the server tick loop. If the main thread is blocked, it will still be able to submit tasks, using the server's cached thread pool.

**Why not tell people experiencing this issue to create their own ExecutorService?**
That's completely possible, and I do not want to say it is a bad idea. For many cases, an own thread pool would be preferable. However, doing so negates the advantage of the scheduler's common thread pool, which reuses Craft Scheduler Threads as they become available. Also, creating an ExecutorService for a small task is overkill when there is one available.

**Error Reporting**
I followed the same approach the scheduler normally uses for CraftAsyncTasks - catch-all and print the exception. However, the log message is slightly different to indicate the task was created through such an Executor.

2020-08-21 19:52 UTC, Proximyst requested changes
Some paper comments missing, otherwise LGTM.

2020-08-21 19:52 UTC, Proximyst commented on Spigot-Server-Patches/0551-Implement-CraftScheduler-createAsyncExecutor-API.patch
> ++    final ThreadPoolExecutor executor = new ThreadPoolExecutor(
```suggestion
+    final ThreadPoolExecutor executor = new ThreadPoolExecutor( // Paper
```

2020-08-21 19:52 UTC, Proximyst commented on Spigot-Server-Patches/0551-Implement-CraftScheduler-createAsyncExecutor-API.patch
> ++            this.asyncScheduler = (CraftAsyncScheduler) this;
```suggestion
+            this.asyncScheduler = (CraftAsyncScheduler) this; // Paper
```

Unless this is inside a paper block already (as one was started above).

2020-08-21 19:52 UTC, Proximyst commented on Spigot-Server-Patches/0551-Implement-CraftScheduler-createAsyncExecutor-API.patch
> ++    int nextId() { // Paper
```suggestion
+    int nextId() { // Paper - private -> package private
```

2020-08-21 22:13 UTC, A248 commented on Spigot-Server-Patches/0551-Implement-CraftScheduler-createAsyncExecutor-API.patch
> ++    final ThreadPoolExecutor executor = new ThreadPoolExecutor(
I figured it wouldn't make sense to add a Paper comment there since the whole class is Paper-original. (CraftAsyncScheduler was itself added in [0200-Improved-Async-Task-Scheduler](https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0200-Improved-Async-Task-Scheduler.patch))

2020-08-21 22:13 UTC, A248 commented on Spigot-Server-Patches/0551-Implement-CraftScheduler-createAsyncExecutor-API.patch
> ++            this.asyncScheduler = (CraftAsyncScheduler) this;
Yes, there's a `// Paper start` a little above the first constructor, which continues until after this one.

2020-08-21 22:15 UTC, Proximyst commented on Spigot-Server-Patches/0551-Implement-CraftScheduler-createAsyncExecutor-API.patch
> ++    final ThreadPoolExecutor executor = new ThreadPoolExecutor(
That makes sense, disregard my comment in that case

2020-08-21 22:16 UTC, Proximyst submitted a review, later dismissed

2020-10-06 04:50 UTC, aikar requested changes
the scheduler needs to keep track of these when created, and when a plugin is disabled, shut down the executor so that tasks may flush and try to gracefully shutdown and pause the disable event.

But it should use same timeout that current async tasks do where it gives them time to stop but gives up and will shutdown anyways if not.

.shutdown() should be called before the current async tasks waiting code, and the "wait for executors" should factor in all time spent async tasks (ie if we give 30s and async tasks used 20s of it, don't blindly wait for another 30s, it should be 30s total for both combined)

30s is off memory on what it actually is, and is purely for example purposes.
just this waiting shouldn't add any additional time.

2020-10-06 22:09 UTC, A248 commented
I took a slightly different approach which preserves the existing behaviour (present in normal async tasks) of allowing, but strongly warning against, incomplete tasks on reload and shutdown. This I found was slightly easier to implement than calling shutdown() and having to recreate the ExecutorService over reloads while still preserving existing behaviour.

2021-01-01 22:02 UTC, A248 commented
Not stale, don't close.

This PR is ready for review in terms of code changes. I will rebase it when I get the chance.

2021-02-19 01:14 UTC, Auriium commented
I support this >:)

2022-10-22 19:13 UTC, Owen1212055 commented
Closing PR, as it seems that this has gone inactive.

Seems like you did comment that you'll rebase it whenever so feel free to rebase and leave a comment and we can reopen it for you. 😄

2022-10-22 19:13 UTC, closed without merging