Fix Wither Hostility Bug
PaperMC/Paper pull request #4153
Opened 2020-08-19 14:16 UTC by TheShermanTanker

Fixed a surprisingly under-reported bug where the Wither's main head is neutral to Players it can see, when it is supposed to be hostile to all non item or projectile entities that are not undead: https://www.reddit.com/r/Minecraft/comments/bt0ojy/wither_boss_is_neutral_towards_player_and_not/

2020-08-19 14:38 UTC, JRoy commented
The reddit post you linked is over one year old, I highly doubt this is a bug.

Additionally, you haven't gave a Mojira report, let alone steps to reproduce this.

2020-08-19 16:43 UTC, TheShermanTanker commented
> 
> 
> The reddit post you linked is over one year old, I highly doubt this is a bug.
> 
> Additionally, you haven't gave a Mojira report, let alone steps to reproduce this.

I can't find a report anywhere because this bug is extremely under-reported, likely because Players often hit the Wither and trigger it's hostility the moment it spawns, while on the wiki it clearly states that the Wither is hostile to everything that isn't an undead monster. The steps to reproduce are pretty obvious: Just summon a Wither in survival mode, be it through commands or the normal way, the bug will still occur; The side heads are hostile to Players while the main head is neutral until the Player attacks the Wither

2020-08-19 18:44 UTC, electronicboy commented
The MC wiki is often wrong as it's croud sourced, we'd need proof that this
is a bug and not intended behaviour

On Wed, 19 Aug 2020, 17:43 TheShermanTanker, <notifications@github.com>
wrote:

> The reddit post you linked is over one year old, I highly doubt this is a
> bug.
>
> Additionally, you haven't gave a Mojira report, let alone steps to
> reproduce this.
>
> I can't find a report anywhere because this bug is extremely
> under-reported, likely because Players often hit the Wither and trigger
> it's hostility the moment it spawns, while on the wiki it clearly states
> that the Wither is hostile to everything that isn't an undead monster. The
> steps to reproduce are pretty obvious: Just summon a Wither in survival
> mode, be it through commands or the normal way, the bug will still occur;
> The side heads are hostile to Players while the main head is neutral until
> the Player attacks the Wither
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/PaperMC/Paper/pull/4153#issuecomment-676537429>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAJMAZHP7CO6E73G6Z4QBS3SBP6LLANCNFSM4QE7W6ZQ>
> .
>

2020-08-20 15:23 UTC, zanson commented
I don't think this type of thing should be patched in Paper.  Report it as a bug to Mojang and if they fix it upstream it will be changed here with that upstream release.

2020-08-20 15:34 UTC, BillyGalbreath commented
https://bugs.mojang.com/browse/MC-29274

2020-08-20 15:36 UTC, BillyGalbreath approved these changes

2020-08-20 15:37 UTC, Proximyst requested changes

2020-08-20 15:37 UTC, Proximyst commented on Spigot-Server-Patches/0553-Wither-Bugfix.patch
> ++        this.targetSelector.a(2, new PathfinderGoalNearestAttackableTarget<>(this, EntityLiving.class, 0, false, false, EntityWither.bF));
Paper comment

2020-08-20 15:44 UTC, JRoy requested changes
As far as I can tell mojang hasn't comment if this is intended or not. If paper does want to assume it is not intended, I think a config option should be added under gameplay changes.

2020-08-20 15:45 UTC, BillyGalbreath commented
> As far as I can tell mojang hasn't comment if this is intended or not

With mojang, if it's an open ticket it's a bug. They are quick to "works as intended" or "invalid" tickets

2020-08-20 16:23 UTC, aikar requested changes
Mojang has commented on it too, it is marked as Confirmed.

However I believe that this is likely better fixed by adding ANOTHER target goal for EntityHuman.class above the Insentient one instead of replacing insentient, as otherwise it'll target Armor Stands.

2020-08-21 00:53 UTC, FranKusmiruk commented
> As far as I can tell mojang hasn't comment if this is intended or not. If paper does want to assume it is not intended, I think a config option should be added under gameplay changes.
Besides Mojang confirming it, it just doesn't make sense, why would the final boss be neutral to players?

2020-09-20 14:30 UTC, closed without merging