Add Wandering Trader spawn rate config options
PaperMC/Paper pull request #4158
Opened 2020-08-20 06:53 UTC by jmanpenilla

Adds config options for adjusting Wandering Trader spawn rates to paper.yml.
- villagerTraderSpawnAttemptDelay: how many ticks between spawn attempts. 24000 or 20 minutes in vanilla.
- villagerTraderSpawnChanceMin: the minimum/starting spawn chance
- villagerTraderSpawnChanceMax: the maximum spawn chance
- villagerTraderSpawnChanceFailureIncrement: how much to increment the spawn chance on a failed attempt

These values are all easy to understand after a quick read of this page on the Minecraft wiki: https://minecraft.gamepedia.com/Wandering_Trader#Spawning

2020-08-20 13:39 UTC, JRoy requested changes
Please make sure to create minimal diffs when submitting pull requests.

Additionally, you'll need to add OBFHELPERs for any obfuscated variable you use. (See contributing document)

2020-08-20 13:39 UTC, JRoy commented on Spigot-Server-Patches/0553-Add-Wandering-Trader-spawn-rate-config-options.patch
> ++    //private int d; // Paper
Do no remove fields, this breaks plugins relying on nms

2020-08-20 13:39 UTC, JRoy commented on Spigot-Server-Patches/0553-Add-Wandering-Trader-spawn-rate-config-options.patch
> ++        //this.d = iworlddataserver.v();
Please don't comment code out, just remove it as commenting increases the diff

2020-08-20 20:56 UTC, jmanpenilla commented
updated with suggestions from Aikar and JRoy
- added obfhelpers
- kept the code in the constructor commented out instead of deleting
- kept use of this.d
- kept logic closer to vanilla for an easier to understand/smaller diff
![discord](https://i.imgur.com/BiQqz7U.png)

Please let me know if theres anything else I should chage

2020-08-21 05:13 UTC, JRoy requested changes
You have the right idea but you're still breaking NMS compatibility with MobSpawnerTrader which will cause problems for plugins using it. Please find a way to keep the current variables somehow.

2020-08-21 05:23 UTC, jmanpenilla commented
> You have the right idea but you're still breaking NMS compatibility with MobSpawnerTrader which will cause problems for plugins using it. Please find a way to keep the current variables somehow.

Could you please elaborate on where I am breaking NMS compatibility with MobSpawnerTrader? I am using the original 3 fields, just with obfhelpers.

2020-08-21 13:01 UTC, JRoy commented
> Could you please elaborate on where I am breaking NMS compatibility with MobSpawnerTrader? I am using the original 3 fields, just with obfhelpers.

Nevermind,  I read the diff incorrectly.:P

2020-08-21 18:16 UTC, incredimike commented
I'm excited for this to be merged!

2020-11-14 19:23 UTC, Proximyst approved these changes, later dismissed
LGTM!

2020-11-15 23:00 UTC, zachbr approved these changes, later dismissed

2020-11-19 19:36 UTC, MiniDigger commented
@limbo-app ready

2020-11-19 19:36 UTC, limbo-app approved these changes
Pull request automatically approved for merging - a core team member has previously approved this pull request.

2020-11-19 19:41 UTC, merged

2020-11-19 19:42 UTC, MiniDigger commented
thanks for your contribution