Update issue templates with notices about the version and forks of paper.
PaperMC/Paper pull request #4166
Opened 2020-08-21 13:14 UTC by aurorasmiles

Add comment about the versions and forks

2020-08-21 13:18 UTC, Proximyst requested changes

2020-08-21 13:18 UTC, Proximyst commented on .github/ISSUE_TEMPLATE/behavior-bug---plugin-incompatibility.md
> +<!--- Forks of Paper receive no support here. Please make sure that your issue is reproducable on Paper first.  -->
Only two hyphens for comments. Also, a new comment directive here when theres another right above seems wasteful.

2020-08-21 13:20 UTC, aurorasmiles commented on .github/ISSUE_TEMPLATE/behavior-bug---plugin-incompatibility.md
> +<!--- Forks of Paper receive no support here. Please make sure that your issue is reproducable on Paper first.  -->
I think it looks prettier with a new comment, but I don't think that matters too much

2020-08-21 13:40 UTC, Proximyst commented on .github/ISSUE_TEMPLATE/behavior-bug---plugin-incompatibility.md
> +<!--- Forks of Paper receive no support here. Please make sure that your issue is reproducable on Paper first.  -->
In that case, at least remember comments are *two* hyphens, not three.

2020-08-21 13:43 UTC, aurorasmiles commented on .github/ISSUE_TEMPLATE/behavior-bug---plugin-incompatibility.md
> +<!--- Forks of Paper receive no support here. Please make sure that your issue is reproducable on Paper first.  -->
I already changed that :D

2020-08-21 13:45 UTC, Proximyst submitted a review, later dismissed

2020-08-21 13:45 UTC, Proximyst commented on .github/ISSUE_TEMPLATE/feature_request.md
> +<!-- Before requesting a new feature, please make sure you are using the latest version and that the feature you are requesting is not already in Paper -->
Full stop :>

2020-08-21 13:52 UTC, Proximyst submitted a review, later dismissed

2020-08-21 16:34 UTC, Chew commented
Should be a general thing about "Paper only for supported versions", because spigot and craftbukkit aren't forks but are also not supported.

2020-08-23 09:55 UTC, Proximyst approved these changes
Sorry for making this my testing grounds <3

2020-08-23 10:18 UTC, DenWav approved these changes

2020-08-23 10:20 UTC, merged