Add -install-mvn option
PaperMC/Paper pull request #4175
Opened 2020-08-22 19:02 UTC by Proximyst

This adds an `-install-mvn` option to install the paper jar to the local maven repository.
This should be trivial to backport if wanted.

This has been tested only on Linux with non-paperclipped and paperclipped jars.

2020-08-22 19:04 UTC, BillyGalbreath commented
Wouldn't this be better added to the ./paper build script? (and also made the default)

2020-08-22 19:05 UTC, Proximyst commented
`paper build` should already install it; this adds it to the compiled jar so you can merely download and `-install-mvn` (e.g. on CIs where compiling Paper every time is not ideal).

2020-08-22 19:08 UTC, BillyGalbreath commented
> `paper build` should already install it

[It does not](https://github.com/PaperMC/Paper/blob/master/paper#L66), which has been requested before. I don't believe anyone's opposed the idea, just no ones ever gotten around to doing it.

> this adds it to the compiled jar so you can merely download and `-install-mvn` (e.g. on CIs where compiling Paper every time is not ideal).

I guess. I thought this was to answer the beck and call from the masses about above ^

2020-08-22 19:10 UTC, Proximyst commented
> It does not, which has been requested before. I don't believe anyone's opposed the idea, just no ones ever gotten around to doing it.

~~I suppose that's another PR in the bag for me, then :p~~

There's `paper install` for this.

> I guess. I thought this was to answer the beck and call from the masses about above ^

This is more to answer those who can't figure out how to compile it themselves, and especially for CIs where it's just not ideal. Compiling manually is fine on Jenkins and all, but GH Actions, Travis, etc. would suffer from doing that every compile.

2020-08-23 14:54 UTC, aurorasmiles submitted a review, later dismissed

2020-08-24 07:55 UTC, MiniDigger commented
Its also useful for devs who just want to build against NMS, without having to build paper. 
Ill test this later on windows.

2020-08-24 08:07 UTC, KennyTV commented
Tested on Win, works:tm:

2020-08-26 14:18 UTC, electronicboy requested changes, later dismissed

2020-08-26 14:18 UTC, electronicboy commented on Spigot-Server-Patches/0565-Add-install-mvn-option.patch
> ++            Path mavenRepo = Paths.get(System.getProperty("user.home"), ".m2", "repository", "com", "destroystokyo", "paper", "paper", version).toAbsolutePath();
This shouldn't be hardcoded due to the whole nature of this being configurable in maven itself. The best option, imho, would be to just copy the pom file into the folder and invoke `mvn install:file` or something

2020-08-26 18:44 UTC, aikar commented
Id rather this be at Paperclip itself.

The idea was that someone should be able to download the jar and install it, and not have to run it first.

2020-08-29 20:47 UTC, closed without merging

2020-08-30 03:35 UTC, theminecoder commented
ehhh I'm not so sure about that. For those people that fork off paper for any number of reasons they usually tend to send the compiled server jar rather than paperclip (tunity and purpur being the exceptions so far that I've seen). In theory as well, paperclip passes its args directly to the server so adding it into the server means paperclip can run it just fine as well, solving both cases (there's still the custom pom location to talk about in regard to forks but baby steps)

2020-08-30 07:37 UTC, Proximyst commented
> ehhh I'm not so sure about that. For those people that fork off paper for any number of reasons they usually tend to send the compiled server jar rather than paperclip (tunity and purpur being the exceptions so far that I've seen).

Time for change.

> there's still the custom pom location to talk about in regard to forks but baby steps

If they're forking, they might as well also fork Paperclip; it's not like it'll have to be maintained very actively so shouldn't really cause any issues. We could also store the location in the Paperclip jar.