Add playPickupItemAnimation to LivingEntity
PaperMC/Paper pull request #4185
Opened 2020-08-23 17:47 UTC by Proximyst

Updated #1966.

2020-08-24 07:49 UTC, MiniDigger requested changes
just the imports, also not sure about the name, I would call it playItemPickupAnimation but I also speak minilang soooo

2020-08-24 07:49 UTC, MiniDigger commented on Spigot-Server-Patches/0559-Add-playPickupItemAnimation-to-LivingEntity.patch
> +-import java.util.ArrayList;
E V I L

2020-08-24 07:50 UTC, Proximyst commented on Spigot-Server-Patches/0559-Add-playPickupItemAnimation-to-LivingEntity.patch
> +-import java.util.ArrayList;
IntelliJ goes rogue, part 37169

2020-08-24 07:51 UTC, KennyTV commented on Spigot-Server-Patches/0559-Add-playPickupItemAnimation-to-LivingEntity.patch
> +-import java.util.ArrayList;
_always blame it on the ide_

2020-08-24 14:06 UTC, Proximyst commented
I'm not so sure about the method name; as it stands now it's pretty okay in my non-minilang eyes, but I am not a native English speaker either.

2020-08-24 14:14 UTC, kashike commented
It is worth noting that this will not only play the animation, but the item entity will be removed on the client-side.

2020-08-24 14:18 UTC, MiniDigger approved these changes, later dismissed

2020-08-24 14:35 UTC, aikar submitted a review, later dismissed

2020-08-26 12:45 UTC, Proximyst commented
@limbo-app ready

2020-08-26 12:45 UTC, limbo-app approved these changes
Pull request automatically approved for merging - a core team member has previously approved this pull request.

2020-08-26 12:51 UTC, merged

2020-08-26 13:36 UTC, rrvk commented
Should this not be merged to the master instead of the progres branch?

2020-08-26 13:37 UTC, Proximyst commented
It should and will; didn't notice the base it was on. We're going to have to handle all the PRs based on that branch...