Add hex color code support for console logging
PaperMC/Paper pull request #4221
Opened 2020-08-27 09:24 UTC by Esophose

Spigot very recently added hex code message support to the ColouredConsoleSender. Since Paper uses a different logging system which currently outputs a garbled mess when using hex color codes, this PR aims to add that feature. The solution used is largely based on [this commit](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/74b6982b034962cc85f38368a3e27f8890a6130a) as previously referenced.

Before:
![Before Patch](https://user-images.githubusercontent.com/7158089/91421756-8b75d780-e813-11ea-92d6-18ad95c9850f.png)

After:
![After Patch](https://user-images.githubusercontent.com/7158089/91422056-e90a2400-e813-11ea-9ec4-eb7ac51d14f8.png)

Thanks to @zml2008 for pointing this out to me in #4220.

2020-08-27 13:47 UTC, aikar requested changes
Rather this be merged into the Terminal Console patch that updates our console,
as well as there is already code in that patch dealing with converting colors I believe, so needs to modify that code (unless that code lives in the external artifact)

Also, would like to see a System property setup to disable this and engage your other version instead if colors are disabled.

And likely also need to not engage this if jansi console isn't even enabled. 

Not sure if Terminal Sender is conditionally used or not.

2020-08-27 19:39 UTC, Esophose commented
> Rather this be merged into the Terminal Console patch that updates our console,
> as well as there is already code in that patch dealing with converting colors I believe, so needs to modify that code (unless that code lives in the external artifact)

The code that deals with converting the legacy console colors does indeed live in the [external artifact](https://github.com/Minecrell/TerminalConsoleAppender/blob/master/src/main/java/net/minecrell/terminalconsole/MinecraftFormattingConverter.java). This patch has been merged into `0146-Use-TerminalConsoleAppender-for-console-improvements`.

> Also, would like to see a System property setup to disable this and engage your other version instead if colors are disabled.

Setting `terminal.ansi` to false will strip out the colors. This is supported through the [`TerminalConsoleAppender#isAnsiSupported`](https://github.com/Minecrell/TerminalConsoleAppender/blob/master/src/main/java/net/minecrell/terminalconsole/TerminalConsoleAppender.java#L189) check. Additionally, I added support for the property `terminal.keepMinecraftFormatting` which the terminalconsole library also uses. Setting it to true will just print the color codes to the console as raw text.

> And likely also need to not engage this if jansi console isn't even enabled.
> 
> Not sure if Terminal Sender is conditionally used or not.

From what I can tell, I think the check for if Ansi is supported will also check if the terminal exists, so this _should_ be fine as-is. I could be wrong about that though.

2020-08-28 18:51 UTC, Proximyst reviewed
Not so sure we'll get any better without forking TCA or just PRing to it...
LGTM, I suppose :p

2020-09-05 14:14 UTC, Narimm commented
I did PR this to TCA

2020-09-05 14:30 UTC, Narimm commented
I am just going to add that the way Ansi is supported by various terminals is largely arbitrary.  Detecting colour is nearly impossible some terminals do provide  an environment variable that details the level of color that they provide but its not consistent.  Jansi itself struggles with this issue.  The good news is that ESC codes that a terminal doesn't understand are removed.  And good terminals will take a RGB esc code and downsample it to a 256 color or 16 Color or even 2 color...I did test this heavily when I wrote it ...running tests in Screen(2 Color), Tmux(16color) and a full color terminal.  

The code Euph pr'd is the code I wrote originally for Adventure-text's deserializer -  and prior to that it has been used in our own remoteconsole server system.

2020-09-06 22:41 UTC, Narimm commented
> I did PR this to TCA
https://github.com/Minecrell/TerminalConsoleAppender/pull/17

2020-10-08 19:16 UTC, x1p commented
I was told to report here that I have strange characters in my log file which should be related to this PR.
The issue is explained here: https://github.com/pl3xgaming/Purpur/issues/77
Flags, besides the aikar flags: `-Dterminal.jline=false -Dterminal.ansi=true`
I had this flags adviced about a year ago and worked fine until now.
Running Purpur on a Ptero setup (containers).

2020-10-08 19:17 UTC, electronicboy commented
That would mean that this PR is leaking ansi into the log files

2020-10-08 19:23 UTC, electronicboy commented
https://github.com/Minecrell/TerminalConsoleAppender/pull/17#issuecomment-705773203

Basically, this PR is wrong as it's trying to deal with converting these characters in the complete wrong place for this, going to see what minecrell says, otherwise we'll have to consider stripping this mess, or breaking existing log4j configs to migrate to a rgb aware impl

2020-10-08 20:58 UTC, Esophose commented
Changed the ansi reset character to use [m instead of [0m since it seems to be more commonly used. Kind of doubt that will fix the issue that x1p was having, unless the only ansi code that was leaking happened to be the reset one.

@x1p Were you able to find any other ansi codes besides the `�[0m` one you mentioned? They would show up wherever an rgb color would be used.

2020-10-08 21:18 UTC, x1p commented
Only the one described.
I don't use (1.16) rgb colors yet. I doubt that plugins use it on their default startup logo's.
Just a few examples
![Screenshot_20201008_231633](https://user-images.githubusercontent.com/28690790/95514566-736da800-09bc-11eb-996c-8ccc050422ff.png)
![Screenshot_20201008_231658](https://user-images.githubusercontent.com/28690790/95514569-74063e80-09bc-11eb-966c-509062e1448e.png)

2020-10-08 21:21 UTC, electronicboy commented
The problem is that you're pumping ansi into the logger, the logger expects text, it deals with the color conversions and ensuring that ansi does not get dumped into the log files in TCA;
This needs to be put into TCAs Minecraft formatter in order to be handled properly, basically

2020-10-08 21:26 UTC, Esophose commented
Yeah that's what I was expecting to be the case unfortunately. I'll keep this pull request open for now, though it seems the people over at TCA don't want to add Spigot's janky hex format to their project.

2020-10-09 00:21 UTC, HexedHero commented
Can we at least have a temp patch to remove hex colors from console?
so we don't have a fuck ton of random §x's in there?

2020-10-09 01:05 UTC, Narimm commented
It needs discussion and Paper may need to revise the way console is handled -  ie devise a new console handler and no longer depend on TCA...or fork TCA but to be honest  - keeping it as a seperate dependency no longer really serves any purpose from Paper's point of view IMO

2020-10-09 01:20 UTC, electronicboy commented
Our intent is likely going to be to get TCA to remove their Minecraft formatter impl so we can pull it over here without breaking existing L4J configs, as I said on the TCA issue

2020-12-15 02:40 UTC, closed without merging

2021-01-18 23:34 UTC, JRoy commented
Can core team please reconsider merging this as a temporary patch, it's been months since the TCA PR has gotten touched let alone since hex color codes were introduced. The benefit of not seeing section signs in your console outweighs downsides of pumping ANSI through the logger in my eyes.

2021-01-18 23:36 UTC, electronicboy commented
I was looking into dealing with this better but didn't figure out how to
get log4j to pull in a custom plugin or something, need to figure out how
to get the thing detected properly I'd imagine

On Mon, 18 Jan 2021, 23:34 Josh Roy, <notifications@github.com> wrote:

> Can core team please reconsider merging this as a temporary patch, it's
> been months since the TCA PR has gotten touched let alone since hex color
> codes were introduced. The benefit of not seeing section signs in your
> console outweighs downsides of pumping ANSI through the logger in my eyes.
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/PaperMC/Paper/pull/4221#issuecomment-762513805>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAJMAZCJ2PEV5IX3H42ZDB3S2TAQLANCNFSM4QMYSRYQ>
> .
>

2021-01-19 00:03 UTC, Andre601 commented
I too would appreciate a possible implementation for this.
It's frustrating when a plugin uses hex color for things like chat, but the console only renders the "known" colors, as this can cause issues like #FF0000 resulting in the text being black and therefore not visible on many consoles/terminals.

I would be happy enough if it even was just a setting in f.e. the paper.yml to disable colored console outputs alltogether, which would then replace/filter out color codes with empty Strings or something similar.
But right now is it frustrating as you can't clearly see, when a specific played said something not allowed, or similar and you can't figure out what the name of the player is (Not without selecting and copy-pasting it which may not be easy to do)

2021-01-19 00:06 UTC, electronicboy commented
Basically, I ha the implementation down based on a PR pushed to MCA, however, when testing it was losing all formatting, my biggest lead is that I just wasn't getting it to pick up the plugin to be able to actually provide formatting or something, not a log4j pro, so, maybe will look at somepoint over the next few days or something, depends on how I feel unless somebody wants to PR that

2021-01-27 08:52 UTC, Esophose commented
For those still suffering from this that want immediate relief, I released this patch as a plugin that you can find here: https://www.spigotmc.org/resources/paperconsolehexpatch.88338/

2021-01-27 10:31 UTC, Sikatsu commented
Works wonders, thanks! Wish paper would just implement this.