Add PlayerInsertLecternBookEvent
PaperMC/Paper pull request #4245
Opened 2020-08-29 20:23 UTC by Proximyst

Surprisingly big diff for such a small event...

Closes #2286.

2020-08-29 20:24 UTC, KennyTV commented on Spigot-API-Patches/0222-Add-PlayerInsertLecternBookEvent.patch
> ++        if (book == null)
*borkets*

2020-08-29 20:24 UTC, Proximyst commented on Spigot-API-Patches/0222-Add-PlayerInsertLecternBookEvent.patch
> ++        if (book == null)
sorry mr wandering knenwald, your borkets aren't a valid currency here

2020-08-29 20:25 UTC, KennyTV commented on Spigot-API-Patches/0222-Add-PlayerInsertLecternBookEvent.patch
> ++        if (book == null)
**brokcets**

2020-11-29 07:06 UTC, electronicboy requested changes

2020-11-29 07:06 UTC, electronicboy commented on Spigot-Server-Patches/0594-Add-PlayerInsertLecternBookEvent.patch
> ++                org.bukkit.craftbukkit.inventory.CraftItemStack.asCraftMirror(itemstack)
looks like you never touch the new book if it's been changed in the event

2022-01-10 03:08 UTC, Machine-Maker commented
Superseded by https://github.com/PaperMC/Paper/pull/7305

2022-01-10 03:08 UTC, closed without merging