Add javadocs to readme
PaperMC/Paper pull request #427
Opened 2016-09-19 18:34 UTC by MiniDigger

2016-09-19 18:34 UTC, MylesIsCool commented
👍 useful

2016-09-19 18:34 UTC, AlfieC commented
IMO `paper` should be `Paper` and `api` should be `API`.

2016-09-19 18:38 UTC, MiniDigger commented
(should be squashed while merging)

2016-09-19 18:39 UTC, AlfieC commented
You could squash it yourself - `git pull` the patch branch, squash them and `push --force`.

2016-09-19 18:42 UTC, MiniDigger commented
@AlfieC that would force me to check out the repo onto my pc. I did this using the online visual editor. that comment was just to tell who ever will be merging this to use the "squash and merge" and not the "create a merge commit" merge option.

2016-09-19 23:40 UTC, Zbob750 commented
May as well fix paper's capitalization directly above, then properly capitalize the additions.

As @AlfieC suggests,
> IMO `paper` should be `Paper` and `api` should be `API`.

2016-09-19 23:57 UTC, kashike commented on README.md
> +Access the paper docs here: [paper.readthedocs.io](https://paper.readthedocs.io/)
`paper` -> `Paper`

2016-09-19 23:57 UTC, kashike commented on README.md
> +Access the paper api javadocs here: [paperdocs.emc.gs](https://paperdocs.emc.gs)
`paper` -> `Paper`
`api` -> `API`

2016-09-19 23:57 UTC, kashike requested changes

2016-09-20 00:51 UTC, AlfieC commented
I'd recommend adding the [CI-SKIP] tag too - no need to waste a CI build on a readme change.

2016-09-20 06:08 UTC, MiniDigger commented
Last commit addressed the capitalisation @kashike

2016-09-20 15:01 UTC, kashike approved these changes

2016-09-22 03:50 UTC, merged