Add hit entity to ProjectileHitEvent
PaperMC/Paper pull request #430
Opened 2016-09-22 03:47 UTC by AlphaBlend

We know what projectile hit something in ProjectileHitEvent but we don't know what it hit. This adds a hit entity so we can grab what was hit.

2016-09-22 03:49 UTC, zachbr requested changes
Nullable annotations missing

2016-09-22 08:39 UTC, AlfieC commented
Unrequired. Projectiles are entities - EntityDamageByEntity event applies here.

2016-09-22 09:25 UTC, MiniDigger commented
well, if we have that event anyways, why not add all useful info we can get? I :+1:

2016-09-22 13:34 UTC, kashike commented on Spigot-Server-Patches/0173-Add-hit-entity-to-ProjectileHitEvent.patch
> ++        ProjectileHitEvent event = new ProjectileHitEvent((Projectile) entity.getBukkitEntity(), (hitEntity == null ? null : (org.bukkit.entity.Entity) hitEntity.getBukkitEntity()));
Why do you have a cast to `org.bukkit.entity.Entity` here? It shouldn't be required.

2016-09-23 00:45 UTC, AlphaBlend commented on Spigot-Server-Patches/0173-Add-hit-entity-to-ProjectileHitEvent.patch
> ++        ProjectileHitEvent event = new ProjectileHitEvent((Projectile) entity.getBukkitEntity(), (hitEntity == null ? null : (org.bukkit.entity.Entity) hitEntity.getBukkitEntity()));
If you have a look at CraftEventFactory, there are several org.bukkit.entity.Entity references as the current scope is at the NMS entity, not the bukkit one.

2016-10-05 21:10 UTC, Zbob750 commented
Merged via 96b534f1f1ecfbfb6c8958392a84a36f7e6c0d8f

2016-10-05 21:10 UTC, closed without merging