[WIP] New Plugin Life-cycle API
PaperMC/Paper pull request #4319
Opened 2020-09-12 22:28 UTC by JRoy

WIP PR for the new plugin life-cycle API.

See #4317 for a better description

2020-10-05 19:18 UTC, kashike requested changes

2020-10-05 19:18 UTC, kashike commented on Spigot-API-Patches/0229-Add-Server-isStarting-Bukkit-isStarting-API.patch
> ++     * Checks if the server is in the process of being started for the first time.
```suggestion
+     * Checks if the server is in the process of being started.
```

2020-10-05 19:18 UTC, kashike commented on Spigot-API-Patches/0229-Add-Server-isStarting-Bukkit-isStarting-API.patch
> ++     * Checks if the server is in the process of being started for the first time.
```suggestion
+     * Checks if the server is in the process of being started.
```

2020-11-14 19:21 UTC, Proximyst requested changes

2020-11-14 19:21 UTC, Proximyst commented on Spigot-API-Patches/0232-Add-plugin-reload-policy.patch
> ++     * <li>Have the {@link org.bukkit.plugin.PluginReloadPolicy#SAME_HASH SAME_HASH} reload policy and the plugin's file is unmodified from startup.
*cries in `</li>`*

2020-11-14 19:21 UTC, Proximyst commented on Spigot-API-Patches/0232-Add-plugin-reload-policy.patch
> ++            return valueOf(name.toUpperCase(Locale.ENGLISH).replaceAll("[^A-Z-]", "").replace("-", "_"));
```suggestion
+            return valueOf(name.toUpperCase(Locale.ENGLISH).replace("-", "_"));
```

Don't correct the user; them entering e.g. `123` is not grounds for Paper to care as that's their fault. The replacing `-` -> `_` is however alright as that's a very easy thing to fuck up (*cough* Bungee & depend/-s...).

2022-07-29 15:51 UTC, JRoy commented
being continued by @Owen1212055 in #8108

2022-07-29 15:51 UTC, closed without merging