Fixed Withers not being hostile to Players
PaperMC/Paper pull request #4345
Opened 2020-09-20 14:31 UTC by TheShermanTanker

Reimplementation of fix in https://github.com/PaperMC/Paper/pull/4153 as requested by reviewers

2020-09-20 14:36 UTC, Proximyst requested changes

2020-09-20 14:36 UTC, Proximyst commented on Spigot-Server-Patches/0582-Fix-Wither-Not-Hostile-To-Plaers-Bug.patch
> ++    private static Predicate<EntityLiving> getWitherTargetEvaluatorNotUndead() { //Paper - OBFHELPER
Put this on the field.

2020-09-20 14:36 UTC, Proximyst commented on Spigot-Server-Patches/0582-Fix-Wither-Not-Hostile-To-Plaers-Bug.patch
> ++        this.targetSelector.a(2, new PathfinderGoalNearestAttackableTarget<>(this, EntityInsentient.class, 0, false, false, getWitherTargetEvaluatorNotUndead()));
Don't modify the existing line.

2020-09-21 19:04 UTC, aikar requested changes

2020-09-21 19:04 UTC, aikar commented on Spigot-Server-Patches/0582-Fix-Wither-Not-Hostile-To-Plaers-Bug.patch
> +Subject: [PATCH] Fix-Wither-Not-Hostile-To-Plaers-Bug
Rename patch to

MC-29274: Fix Wither hostility towards players

2020-09-21 19:04 UTC, aikar commented on Spigot-Server-Patches/0582-Fix-Wither-Not-Hostile-To-Plaers-Bug.patch
> ++        this.targetSelector.a(2, new PathfinderGoalNearestAttackableTarget<>(this, EntityHuman.class, 0, false, false, getWitherTargetEvaluatorNotUndead())); //Fix Wither not hostile to Players
tag with // Paper, as well as remove the predicate, players can't be undead.

I also question, should this be ABOVE Insentient so it prefers players first?
Also worth considering a config option for those "MAH VANILLA" people.

2020-10-03 11:33 UTC, closed without merging