Add EntityZapEvent, replace PigZapEvent, include villagers
PaperMC/Paper pull request #449
Opened 2016-10-17 06:33 UTC by AlphaBlend

This PR does 2 things. First of all, it adds a missing event for villagers getting zapped by lightning. Secondly, it creates a generalized event, EntityZapEvent, which also replaces the current PigZapEvent which has been deprecated.

2016-10-17 06:36 UTC, kashike requested changes

2016-10-17 06:36 UTC, kashike commented on Spigot-API-Patches/0040-Add-EntityZapEvent-replace-PigZapEvent-include-villa.patch
> ++    public HandlerList getHandlers() {
`@Override`

2016-10-17 06:36 UTC, kashike commented on Spigot-API-Patches/0040-Add-EntityZapEvent-replace-PigZapEvent-include-villa.patch
> ++    public Entity getChangedEntity() {
Perhaps `getReplaceentEntity` or something would be a more fitting name (applies to the field, as well).

2016-10-17 06:36 UTC, kashike commented on Spigot-Server-Patches/0180-Add-EntityZapEvent-replace-PigZapEvent-include-villa.patch
> ++            if (CraftEventFactory.callEntityZapEvent(this, entitylightning, entitypigzombie).isCancelled()) {
Calling before vs calling after `PigZapEvent`?

2016-10-17 06:36 UTC, kashike commented on Spigot-Server-Patches/0180-Add-EntityZapEvent-replace-PigZapEvent-include-villa.patch
> ++import org.bukkit.craftbukkit.event.CraftEventFactory; // Paper
Not necessary.

2016-10-17 06:36 UTC, kashike commented on Spigot-Server-Patches/0180-Add-EntityZapEvent-replace-PigZapEvent-include-villa.patch
> ++    public static EntityZapEvent callEntityZapEvent (Entity entity, Entity lightning, Entity changedEntity) {
Missing `// Paper - start` and `// Paper - end` comments.

2016-10-17 07:05 UTC, kashike requested changes

2016-10-17 07:05 UTC, kashike commented on Spigot-API-Patches/0040-Add-EntityZapEvent-replace-PigZapEvent-include-villa.patch
> ++    public Entity getReplacedEntity() {
I think `getReplacementEntity` would be a better name.

2016-10-17 07:05 UTC, kashike commented on Spigot-Server-Patches/0180-Add-EntityZapEvent-replace-PigZapEvent-include-villa.patch
> +-
![whitespace](http://www.co2partners.com/blog/wp-content/uploads/2013/10/finding-white-space.png)

2016-10-17 07:05 UTC, kashike commented on Spigot-Server-Patches/0180-Add-EntityZapEvent-replace-PigZapEvent-include-villa.patch
> +-
![whitespace](http://www.co2partners.com/blog/wp-content/uploads/2013/10/finding-white-space.png)

2016-10-17 07:05 UTC, kashike commented on Spigot-Server-Patches/0180-Add-EntityZapEvent-replace-PigZapEvent-include-villa.patch
> ++import com.destroystokyo.paper.event.entity.EntityZapEvent; // Paper
You don't need to import this.

2016-10-17 07:05 UTC, kashike commented
> 07:02:42      AlphaBlend | kashike: go nuts with the new potential comments or PR review completion :)

![ok](http://www.brainlesstales.com/images/2011/Nov/go-nuts.jpg)

2016-10-17 07:14 UTC, AlphaBlend commented on Spigot-Server-Patches/0180-Add-EntityZapEvent-replace-PigZapEvent-include-villa.patch
> +-
My IDE actually removed the white space.

2016-10-17 07:14 UTC, MisterVector commented on Spigot-Server-Patches/0180-Add-EntityZapEvent-replace-PigZapEvent-include-villa.patch
> +-
My IDE actually removed the white space.

2016-10-17 11:53 UTC, Mystiflow commented on Spigot-API-Patches/0040-Add-EntityZapEvent-replace-PigZapEvent-include-villa.patch
> +@@ -15,6 +15,10 @@ public class PigZapEvent extends EntityEvent implements Cancellable {
`extends EntityZapEvent`?

2016-10-17 20:19 UTC, AlphaBlend commented
event has been fully qualified, white spaces have been put back, and i think it's all ready to go!

2016-10-22 17:50 UTC, aikar commented on Spigot-API-Patches/0040-Add-EntityZapEvent-replace-PigZapEvent-include-villa.patch
> +@@ -15,6 +15,10 @@ public class PigZapEvent extends EntityEvent implements Cancellable {
Yes, the correct way to handle this is to extend EntityZapEvent, remove the getHandlers and getHandlerList from this class (comment out)

Also, do not deprecate. It's a bukkit API that will never be removed, and can be useful for people who only want to listen to pig zaps.

2016-10-23 22:04 UTC, Zbob750 commented
Nullability annotations need to be added either before the merge or immediately after. We have them, I expect them to be used, at least for all additions.

2016-10-24 20:54 UTC, AlphaBlend commented
I did everything Kashike suggested. As for what Z wanted, I'm not exactly sure where the nullables should go, so if someone wants to take care of that, that'd be awesome! I can always learn from someone else.

2016-10-31 02:35 UTC, Zbob750 commented
Cherry-picked on top of latest with minor changes.
Thanks

2016-10-31 02:35 UTC, closed without merging