Fix distance in checkHighPriorityChunks (#4582)
PaperMC/Paper pull request #4605
Opened 2020-10-03 12:57 UTC by ForceUpdate1

Fixes (#4582)

2020-10-03 13:03 UTC, KennyTV requested changes

2020-10-03 13:03 UTC, KennyTV commented on Spigot-Server-Patches/0488-Implement-Chunk-Priority-Urgency-System-for-Chunks.patch
>  +                updateChunkPriorityMap(priorities, coord.pair(), (int) (25 - Math.sqrt(dist) * twoThirdModifier));
```suggestion
+                double dist = MCUtil.distance(playerChunkX, 0, playerChunkZ, coord.x, 0, coord.z);
+                updateChunkPriorityMap(priorities, coord.pair(), (int) (25 - dist * twoThirdModifier));
```

2020-10-03 13:03 UTC, KennyTV commented on Spigot-Server-Patches/0488-Implement-Chunk-Priority-Urgency-System-for-Chunks.patch
>  +                updateChunkPriorityMap(priorities, coord.pair(), (int) (25 - Math.sqrt(dist) * twoThirdModifier));
```suggestion
+                double dist = MCUtil.distance(playerChunkX, 0, playerChunkZ, coord.x, 0, coord.z);
+                updateChunkPriorityMap(priorities, coord.pair(), (int) (25 - dist * twoThirdModifier));
```

2020-10-03 13:03 UTC, KennyTV commented on Spigot-Server-Patches/0488-Implement-Chunk-Priority-Urgency-System-for-Chunks.patch
>  +            updateChunkPriorityMap(priorities, coord.pair(), (int) (25 - Math.sqrt(dist) * twoThirdModifier));
```suggestion
+            double dist = MCUtil.distance(playerChunkX, 0, playerChunkZ, coord.x, 0, coord.z);
+            updateChunkPriorityMap(priorities, coord.pair(), (int) (25 - dist * twoThirdModifier));
```

2020-10-06 20:31 UTC, electronicboy submitted a review, later dismissed

2020-10-11 22:20 UTC, aikar approved these changes
ignore the comment about I thought it was wrong. Initially I had used squared results to avoid some operations and thought I was double square rooting intentionally in some of those places, but after further review it was good as is.

2020-10-11 22:24 UTC, merged