Add EntityChargeCrossbowEvent
PaperMC/Paper pull request #4626
Opened 2020-10-07 16:08 UTC by JRoy

Tested on the following code:
```java
  @EventHandler
  public void onCharge(EntityChargeCrossbowEvent event) {
    event.setCancelled(true);
    if (event.getEntity() instanceof Player) {
      ((Player) event.getEntity()).updateInventory();
    }
    Bukkit.broadcastMessage("yo");
  }
```

Closes #4619

2020-10-07 20:04 UTC, Proximyst submitted a review, later dismissed

2020-10-08 12:37 UTC, FazziClay commented
test 1111

2020-11-12 09:08 UTC, kadenscott commented on Spigot-API-Patches/0229-Add-EntityChargeCrossbowEvent.patch
> ++    private boolean canceled;
method name is `setCancelled`, variable name is `canceled`

2020-11-12 09:11 UTC, BillyGalbreath commented
I would suggest renaming this event to `EntityLoadCrossbowEvent` since this is triggered when a crossbow is _loaded_ with a projectile.

Unless I'm missing some magical charge or enchantment that this is for, in which case ignore this comment..

2020-11-12 09:11 UTC, kadenscott requested changes
sorry jroy im a stickler for these things 😩

2020-11-12 09:11 UTC, kadenscott commented on Spigot-API-Patches/0229-Add-EntityChargeCrossbowEvent.patch
> ++    private boolean canceled;
method name is setCancelled, variable name is canceled

2020-11-12 09:11 UTC, kadenscott commented on Spigot-API-Patches/0229-Add-EntityChargeCrossbowEvent.patch
> ++     * Set whether or not to cancel the crossbow being charged. If canceled, the
_canceled_

2020-11-12 09:11 UTC, kadenscott commented on Spigot-API-Patches/0229-Add-EntityChargeCrossbowEvent.patch
> ++        this.canceled = cancel;
_canceled_

2020-11-12 09:11 UTC, kadenscott commented on Spigot-API-Patches/0229-Add-EntityChargeCrossbowEvent.patch
> ++        return canceled;
_canceled_

2020-11-12 12:38 UTC, JRoy commented
done @BillyGalbreath @kadenscott

2020-11-12 12:44 UTC, Prof-Bloodstone commented
Just a FYI comment. We've discussed the naming change on Discord: https://discord.com/channels/289587909051416579/555462289851940864/776374191377088522

The gist is that Charge makes more sense in keeping true to Mojang naming (see NBT for `tag.Charged` and `tag.ChargedProjectiles`) , while using Loaded seems potentially more intuitive. 

We couldn't find a good proper name for it. Both names are good IMO.

2020-11-29 20:03 UTC, MiniDigger approved these changes, later dismissed

2021-01-03 08:02 UTC, zachbr submitted a review, later dismissed
The API is called load, the patch and commit are called charge. Please resolve before merging.
I am not overly fussed about which, both have valid reasons to use.

2021-01-03 15:09 UTC, JRoy commented
@zachbr fixed api patch to reflect the renamed event

2021-01-03 15:37 UTC, MiniDigger commented
@limbo-app ready
(havent touch this yet, just marking this again)

2021-01-03 15:37 UTC, limbo-app submitted a review, later dismissed
Pull request automatically approved for merging - a core team member has previously approved this pull request.

2021-01-03 15:58 UTC, MiniDigger commented
@limbo-app ready

2021-01-03 15:59 UTC, limbo-app approved these changes
Pull request automatically approved for merging - a core team member has previously approved this pull request.

2021-01-03 15:59 UTC, merged

2021-01-03 15:59 UTC, MiniDigger commented
thanks!