Maded Title-Objects directy sendable to targets
PaperMC/Paper pull request #4628
Opened 2020-10-08 15:12 UTC by TheFruxz

Hey!

This is my first submission of a change to PaperMC/Paper (API).

I myself think that title objects should also be sent by themselves (like in ParticleBuilder). Therefore I made this suggestion for improvement.

With kind regards
Fruxz (@TheFruxz)

2020-10-08 15:22 UTC, Proximyst requested changes
Good first contribution, just some nitpicks then it'd be good to go.

Also read the contributing file to read how to fixup this into the patch which makes the class. This doesn't need to be a new patch.

2020-10-08 15:22 UTC, Proximyst commented on Spigot-API-Patches/0231-Maded-Title-objects-directly-sendable.patch
> ++            Arrays.stream(players).forEach((player -> {
Awful use of a stream. Just use a good ol' for loop.

2020-10-08 15:22 UTC, Proximyst commented on Spigot-API-Patches/0231-Maded-Title-objects-directly-sendable.patch
> ++        if (players != null) {
Don't null check. If the user passes null, it's their problem and they're the ones who have to fix their NPE.

2020-10-08 15:22 UTC, Proximyst commented on Spigot-API-Patches/0231-Maded-Title-objects-directly-sendable.patch
> ++        if (players != null) {
Don't null check. If the user passes null, it's their problem and they're the ones who have to fix their NPE.

2020-10-08 15:22 UTC, Proximyst commented on Spigot-API-Patches/0231-Maded-Title-objects-directly-sendable.patch
> ++     * @param player defines the target of the title
```suggestion
+     * @param player the receiver of the title
```

2020-10-08 15:22 UTC, Proximyst commented on Spigot-API-Patches/0231-Maded-Title-objects-directly-sendable.patch
> ++     * @param players defines the targets of the title
```suggestion
+     * @param players the receivers of the title
```

2020-10-08 15:22 UTC, Proximyst commented on Spigot-API-Patches/0231-Maded-Title-objects-directly-sendable.patch
> ++     * @param players defines the targets of the title
```suggestion
+     * @param players the receivers of the title
```

2020-10-08 15:22 UTC, Proximyst commented on Spigot-API-Patches/0231-Maded-Title-objects-directly-sendable.patch
> ++     * <p>The players can be null, but the array itself not</p>
```suggestion
```

2020-10-08 15:22 UTC, Proximyst commented on Spigot-API-Patches/0231-Maded-Title-objects-directly-sendable.patch
> ++     * <p>The players can be null, but the list itself not</p>
```suggestion
```

2020-10-08 15:22 UTC, Proximyst commented on Spigot-API-Patches/0231-Maded-Title-objects-directly-sendable.patch
> ++                if (player != null && player.isOnline()) {
Don't null check. If the user passes null, it's their problem and they're the ones who have to fix their NPE.

Checking online is also likely unnecessary; if the player is offline, the plugin shouldn't pass them in the first place.

2020-10-08 15:22 UTC, Proximyst commented on Spigot-API-Patches/0231-Maded-Title-objects-directly-sendable.patch
> ++                if (player != null && player.isOnline()) {
Don't null check. If the user passes null, it's their problem and they're the ones who have to fix their NPE.

Checking online is also likely unnecessary; if the player is offline, the plugin shouldn't pass them in the first place.

2020-10-08 15:22 UTC, Proximyst commented on Spigot-API-Patches/0231-Maded-Title-objects-directly-sendable.patch
> ++     * <p>The player value can not be null!</p>
```suggestion
```

2020-10-08 16:21 UTC, TheFruxz commented
Hey, many thanks for the help with my first PR! I tried to commit all the changes to the repository, and integrated the commit directly into this PR. Thanks again for the help!

2020-10-08 16:24 UTC, TheFruxz commented
> Hey, many thanks for the help with my first PR! I tried to commit all the changes to the repository, and integrated the commit directly into this PR. Thanks again for the help!

P.S. My IDE apparently re-sorted the this() objects in fixup, but did not make any changes. IDK Why

2020-10-13 18:36 UTC, TheFruxz commented
For this feature, I created a new PR and I closing this PR to to avoid confusion and to fix the 'unknown repository' GitHub-Issue

NEW ONE: #4648 

Thanks for helping @Proximyst!

2020-10-13 18:36 UTC, closed without merging