Update VehicleCreateEvent
PaperMC/Paper pull request #467
Opened 2016-11-06 20:48 UTC by AlphaBlend

Updated the event to be cancellable, and give it an additional create
reason for the vehicle.

Before this PR, cancellation was impossible given that the event call happened inside the constructors for EntityBoat and EntityMinecartAbstract. This PR relocates the event call logic to the appropriate places.

As for the getSource() API method in VehicleCreateEvent, I wanted it to be as simple as returning a generic object that extends Object, only requiring determination from VehicleCreateReason such that you could create either a Block or Player object depending on the reason.

2016-11-06 20:57 UTC, kashike requested changes

2016-11-06 20:57 UTC, kashike commented on Spigot-API-Patches/0042-Update-VehicleCreateEvent.patch
> ++import javax.annotation.Nonnull;
Organise your imports!

2016-11-06 20:57 UTC, kashike commented on Spigot-Server-Patches/0182-Update-VehicleCreateEvent.patch
> ++import org.bukkit.craftbukkit.event.CraftEventFactory;
These don't need to be imported.

2016-11-06 21:42 UTC, AlphaBlend commented on Spigot-Server-Patches/0182-Update-VehicleCreateEvent.patch
> ++import org.bukkit.craftbukkit.event.CraftEventFactory;
I was using the craft event factory in two places, so i still need to fully qualify them?

2016-11-06 21:45 UTC, kashike commented on Spigot-Server-Patches/0182-Update-VehicleCreateEvent.patch
> ++import org.bukkit.craftbukkit.event.CraftEventFactory;
Fully qualify all the things!

2016-11-07 04:35 UTC, kashike requested changes

2016-11-07 04:35 UTC, kashike commented on Spigot-API-Patches/0042-Update-VehicleCreateEvent.patch
> ++        this(vehicle, new Object(), VehicleCreateReason.NONE);
Can `new Object()` be a `static final` field?

2016-11-07 04:35 UTC, kashike commented on Spigot-API-Patches/0042-Update-VehicleCreateEvent.patch
> ++    public void setCancelled(boolean cancel) {
`@Override`

2016-11-07 04:35 UTC, kashike commented on Spigot-API-Patches/0042-Update-VehicleCreateEvent.patch
> ++    public boolean isCancelled() {
`@Override`

2016-11-07 13:55 UTC, Black-Hole commented
Using a raw object is a bad design, you should use ProjectileSource. Then you won't need VehicleCreateReason.

2016-11-07 14:20 UTC, Black-Hole commented on Spigot-Server-Patches/0182-Update-VehicleCreateEvent.patch
> ++            // Paper start
Maybe move this down just before the world.addEntity(), so all properties could be used by event handlers.

2016-11-07 14:21 UTC, Black-Hole commented on Spigot-Server-Patches/0182-Update-VehicleCreateEvent.patch
> ++                // Paper start
Maybe move this down just before the world.addEntity(), so all properties could be used by event handlers.

2016-11-15 01:18 UTC, AlphaBlend commented
I have changed the implementation-side to call VehicleCreateEvent with all properties applied to the vehicle.

@Black-Hole  as for ProjectileSource I don't think this is appropriate to use in an API setting, as the name is misleading. The concept works, just it should match the name.

2016-11-15 12:55 UTC, Black-Hole commented
You could use an interface that extends ProjectileSource. Call it ActionSource maybe. Or change ProjectileSource so it extends ActionSource.

2016-12-01 00:59 UTC, Zbob750 commented
I believe we will go with a more generic ActionSource class and make ProjectileSource extend that class. The hope being that we can use it beyond just this one PR, and avoid getting ourselves back into a similar situation in the future

Several people also pointed out to me that Dispensers weren't easily accessible via ProjectileSource like entities are. So while we're in here messing with this it makes sense to tackle that as well.

Once those are done this should be an easy merge. This may all see a separate PR from me before merging into master, we'll have to see what it turns into.

Comments welcome.

2016-12-01 02:31 UTC, Black-Hole commented
I like the idea of a generic patch that introduces ActionSource and changes nms.Entity.projectileSource to use ActionSource.
The entity origin patch ( https://github.com/PaperMC/Paper/blob/master/Spigot-API-Patches/0007-Entity-Origin-API.patch ) could store the source, too. @Byteflux

2016-12-01 05:37 UTC, AlphaBlend commented
@Zbob750 I'll update this PR when we get around to adding in the ActionSource interface, or equivalent name. I agree with you that this should be extensible for current / future events that can make use of this.

2017-03-21 23:03 UTC, Black-Hole commented
CraftBukkit recently changed the calling of this event and made is cancellable:
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/2aa5ac6c92a0e53ae917cae348d662d014ef9366

2017-07-27 03:14 UTC, aikar commented
Closing since half of the PR is obsolete, and Spigots change makes the other half completely wrong now - so it would need to be an entire rewrite of approach to get the Reason.

If you still need reason, please open a new PR.

2017-07-27 03:14 UTC, closed without merging