Avoid crashing clients when fishing loot is empty, this would fix #4235
PaperMC/Paper pull request #4681
Opened 2020-10-23 15:29 UTC by schoentoon

2020-10-23 15:35 UTC, Proximyst requested changes
You have to rebase onto master to have it not include aikar's commit.

2020-10-23 15:35 UTC, Proximyst commented on Spigot-Server-Patches/0594-Avoid-error-bubbling-up-when-item-stack-is-empty-in-.patch
> ++                    PlayerFishEvent playerFishEvent = new PlayerFishEvent((Player) entityhuman.getBukkitEntity(), entityitem != null ? entityitem.getBukkitEntity() : null, (FishHook) this.getBukkitE
```suggestion
+                    PlayerFishEvent playerFishEvent = new PlayerFishEvent((Player) entityhuman.getBukkitEntity(), entityitem != null ? entityitem.getBukkitEntity() : null, (FishHook) this.getBukkitEntity(), PlayerFishEvent.State.CAUGHT_FISH); // Paper - entityitem may be null
```

2020-10-23 15:35 UTC, Proximyst commented on Spigot-Server-Patches/0594-Don-t-crash-on-negative-item-count-for-fishing-loot.patch
> ++                    System.err.println("getCount() = " + itemstack1.getCount());
Debug

2020-10-24 11:11 UTC, Proximyst approved these changes
LGTM. Thank you for your contribution.

2020-10-28 20:26 UTC, aikar approved these changes

2020-10-28 20:39 UTC, merged