Raytrace entities within collection
PaperMC/Paper pull request #4700
Opened 2020-10-28 10:16 UTC by NeumimTo

Adds method `World#raytrace` that takes a collection of entities instead of Predicate<Entity>
..another way to filter out entities we dont't want to check for ray intersection

2020-10-28 10:25 UTC, Proximyst requested changes

2020-10-28 10:25 UTC, Proximyst commented on Spigot-API-Patches/0231-Raytrace-entities-within-collection.patch
> ++     * @return the closest ray trace hit result, or <code>null</code> if there
```suggestion
+     * @return the closest ray trace hit result, or {@code null} if there
```

2020-10-28 10:25 UTC, Proximyst commented on Spigot-API-Patches/0231-Raytrace-entities-within-collection.patch
> ++    public RayTraceResult rayTraceEntities(@NotNull Vector direction, double maxDistance, double raySize, @NotNull Vector startPos, @NotNull Collection<Entity> entities);
```suggestion
+    public RayTraceResult rayTraceEntities(@NotNull Vector direction, double maxDistance, double raySize, @NotNull Vector startPos, @NotNull Collection<? extends Entity> entities);
```

2020-10-28 10:25 UTC, Proximyst commented on Spigot-API-Patches/0231-Raytrace-entities-within-collection.patch
> +
Paper comment

2020-10-28 10:25 UTC, Proximyst commented on Spigot-Server-Patches/0594-Raytrace-entities-within-collection.patch
> ++        return rayTraceEntities(direction, maxDistance, raySize, startPos, entities);
Paper comment

2020-10-28 10:25 UTC, Proximyst commented on Spigot-Server-Patches/0594-Raytrace-entities-within-collection.patch
> ++
Remove this

2020-10-28 10:25 UTC, Proximyst commented on Spigot-API-Patches/0231-Raytrace-entities-within-collection.patch
> ++     * <p>
Why? There is no new paragraph after this.

2020-10-28 10:53 UTC, NeumimTo commented on Spigot-API-Patches/0231-Raytrace-entities-within-collection.patch
> +
what does that mean?

2020-10-28 10:56 UTC, Proximyst commented on Spigot-API-Patches/0231-Raytrace-entities-within-collection.patch
> +
Check the contributing file

2020-10-29 19:10 UTC, Proximyst approved these changes, later dismissed
Nitpicks; LGTM

2020-10-29 19:10 UTC, Proximyst commented on Spigot-API-Patches/0231-Raytrace-entities-within-collection.patch
> ++
Drop this line.

2020-10-29 19:10 UTC, Proximyst commented on Spigot-Server-Patches/0594-Raytrace-entities-within-collection.patch
> ++    public RayTraceResult rayTraceEntities(Vector direction, double maxDistance, double raySize, Vector startPos, Collection<? extends Entity> entities) {
```suggestion
+        // Paper start - add entities collection
+        return rayTraceEntities(direction, maxDistance, raySize, startPos, entities);
+    }
+
+    @Override
+    public RayTraceResult rayTraceEntities(Vector direction, double maxDistance, double raySize, Vector startPos, Collection<? extends Entity> entities) {
+        // Paper end
```

2020-10-29 19:10 UTC, Proximyst commented on Spigot-Server-Patches/0594-Raytrace-entities-within-collection.patch
> +     public RayTraceResult rayTraceBlocks(Location start, Vector direction, double maxDistance) {
```suggestion
```

2020-12-02 19:17 UTC, electronicboy requested changes

2020-12-02 19:17 UTC, electronicboy commented on Spigot-Server-Patches/0594-Raytrace-entities-within-collection.patch
> ++        return rayTraceEntities(direction, maxDistance, raySize, startPos, entities);
This is basically missing all of the sanity verifications which are done in the method above

2021-03-14 14:47 UTC, closed without merging