Fix client lag on advancement loading
PaperMC/Paper pull request #4710
Opened 2020-10-31 19:13 UTC by jmanpenilla

When new advancements are added via the UnsafeValues#loadAdvancement
API, it triggers a full datapack reload when this is not necessary. The
advancement is already loaded directly into the advancement registry,
and the point of saving the advancement to the Bukkit datapack seems to
be for persistence. By removing the call to reload datapacks when an
advancement is loaded, the client no longer completely freezes up when
adding a new advancement.

2020-10-31 19:50 UTC, Proximyst commented
The commit ([5195487ec6c01a80e3a2fca8c4acfc6b9524fcf5](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/5195487ec6c01a80e3a2fca8c4acfc6b9524fcf5#src/main/java/org/bukkit/craftbukkit/util/CraftMagicNumbers.java)) in CraftBukkit doesn't state why this was needed. Are you certain this is a safe change?

2020-10-31 19:58 UTC, electronicboy commented
Does the client recieve the data properly otherwise?

2020-10-31 20:11 UTC, jmanpenilla commented
I'm pretty certain this is safe. As far as the client receiving the data, a change from this would be the client won't receive it until they are granted the achievement. I think this could be fixed with a more specific call to send the advancements rather than reloading datapacks however. I'll update the PR

2020-10-31 20:44 UTC, jmanpenilla commented
Alright, seems like this should be good now. We manually reload the player advancement data and call the method which sends the update packet, which is normally done along with datapack reloading.

2020-10-31 21:22 UTC, Proximyst requested changes

2020-10-31 21:22 UTC, Proximyst commented on Spigot-Server-Patches/0595-Fix-client-lag-on-advancement-loading.patch
> ++                    player.getAdvancementData().a(MinecraftServer.getServer().getAdvancementData());
OBFHELPER.

2020-10-31 21:22 UTC, Proximyst commented on Spigot-Server-Patches/0595-Fix-client-lag-on-advancement-loading.patch
> ++                    player.getAdvancementData().b(player);
OBFHELPER.

2020-10-31 21:35 UTC, Proximyst approved these changes, later dismissed

2020-11-11 16:18 UTC, electronicboy approved these changes

2020-11-11 16:18 UTC, merged