Throw proper exception on empty JsonList file
PaperMC/Paper pull request #4719
Opened 2020-11-01 15:48 UTC by Proximyst

Related to #4174, #4717.

As it stands, `JsonList` throws an NPE on `jsonarray.iterator()` when
the reader given is at EOF. This means there is an unintelligible
message shown to the player:

```
[16:44:31 ERROR]: Encountered an unexpected exception
java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonArray.iterator()" because "jsonarray" is null
	at net.minecraft.server.v1_16_R2.JsonList.load(JsonList.java:192) ~[patched_1.16.3.jar:git-Paper-248]
	at net.minecraft.server.v1_16_R2.DedicatedPlayerList.y(SourceFile:95) ~[patched_1.16.3.jar:git-Paper-248]
	...
```

This is clearly not understandable to the untrained eye: what is
`jsonarray`? What is `DedicatedPlayerList.y`?

This rather does a proper exception message:

```
[16:42:59 ERROR]: Encountered an unexpected exception
java.lang.NullPointerException: The file "banned-players.json" is either empty or corrupt
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787) ~[paper-1.16.3.jar:git-Paper-"8e6d90c2d"]
	at net.minecraft.server.v1_16_R2.JsonList.load(JsonList.java:190) ~[paper-1.16.3.jar:git-Paper-"8e6d90c2d"]
	at net.minecraft.server.v1_16_R2.DedicatedPlayerList.y(SourceFile:95) ~[paper-1.16.3.jar:git-Paper-"8e6d90c2d"]
	...
```

It is still an exception, which server owners may or may not understand,
but the message now says exactly what went wrong, and who would've
known, now we know what `DedicatedPlayerList.y` is, and we know what
file was broken.

This is more of a quality of life change, but it is certainly useful to
the server owners that come into `#paper-help` and the issue tracker
(#4174) to ask for help with unintelligible messages we need to open a
patched Paper project to make any sense out of.

2020-11-09 00:33 UTC, kashike requested changes

2020-11-09 00:33 UTC, kashike commented on Spigot-Server-Patches/0595-Throw-proper-exception-on-empty-JsonList-file.patch
> ++                com.google.common.base.Preconditions.checkNotNull(jsonarray, "The file \"" + this.c.getName() + "\" is either empty or corrupt"); // Paper
```suggestion
+                com.google.common.base.Preconditions.checkState(jsonarray != null, "The file \"" + this.c.getName() + "\" is either empty or corrupt"); // Paper
```

2021-01-11 01:45 UTC, electronicboy approved these changes

2021-03-03 20:55 UTC, MiniDigger commented
```
java.lang.IllegalStateException: The file "banned-players.json" is either empty or corrupt
	at com.google.common.base.Preconditions.checkState(Preconditions.java:444) ~[paper-1.16.5.jar:git-Paper-"f995f209e"]
```

2021-03-03 20:56 UTC, merged