Fix PlayerEditBookEvent
PaperMC/Paper pull request #4734
Opened 2020-11-03 21:55 UTC by Proximyst

When not signing a book, it will never call the event.
When signing the book and cancelled, it may not reflect the cancellation to the client due to the inventory not updating.

2020-11-11 16:25 UTC, electronicboy commented
Spigot has made changes to this code since this PR was created, what's relevant now?

2020-11-11 16:27 UTC, electronicboy requested changes
See PR for comments

2020-11-11 16:40 UTC, Proximyst commented
Unless they fixed the updating part, that'd still be necessary. I can reduce the PR to the updates sometime later.

2021-01-10 17:06 UTC, aurorasmiles commented
this should potentially fix #2329

2021-01-10 17:19 UTC, Proximyst commented
Closing as I'll just make a new PR if I decide to pick this back up.

2021-01-10 17:19 UTC, closed without merging