add recipe to cook events
PaperMC/Paper pull request #4789
Opened 2020-11-20 01:04 UTC by ExcessiveAmountsOfZombies

for https://github.com/PaperMC/Paper/issues/4761
has paper comments now

2020-11-20 01:22 UTC, HexedHero commented
You don't need paper comments on imports

2020-11-20 02:39 UTC, Machine-Maker requested changes

2020-11-20 02:39 UTC, Machine-Maker commented on Spigot-API-Patches/0237-add-recipe-to-cook-events.patch
> ++    // Paper end
The above Paper - start/end section can probably be combined with the one above it. Kinda redundant to have a `// Paper end` and `// Paper start` comment right after it.

2020-11-20 05:33 UTC, Chew commented
You can't edit patch files directly like that, you'll need to edit locally and rebuild.

2020-11-21 06:32 UTC, Machine-Maker requested changes

2020-11-21 06:32 UTC, Machine-Maker commented on Spigot-API-Patches/0237-add-recipe-to-cook-events.patch
> ++    this.recipe = recipe;
Shouldn't this be indented another level?

2020-11-28 21:28 UTC, closed without merging

2021-01-05 06:45 UTC, Machine-Maker commented
@ExcessiveAmountsOfZombies Why was this closed?

2021-01-06 17:58 UTC, ExcessiveAmountsOfZombies commented
@Machine-Maker I did something with the branch and screwed everything up and couldn't figure out how to fix it.

2021-01-06 18:00 UTC, Machine-Maker commented
got a problem if I remake it? patch author will be you.

2021-01-06 18:03 UTC, ExcessiveAmountsOfZombies commented
If you'd like to, sure. I think the problem was that I tried to update the patch numbers and ended up duplicating them.