Add cause to Weather/ThunderChangeEvents
PaperMC/Paper pull request #4832
Opened 2020-12-03 02:39 UTC by Machine-Maker

closes #3397

2021-02-01 05:24 UTC, Machine-Maker commented
oh no you dont

2021-03-21 23:22 UTC, Machine-Maker commented
`Rebased after the NMS repackage`

2021-04-24 09:34 UTC, MiniDigger approved these changes
lgtm, only concern I have with those setStorm methods without the new arg, shouldnt that just call the OG method, but with UNKOWN as cause?
Else when mojang adds new usages, we will not know about them.

2021-04-25 18:58 UTC, Machine-Maker commented
@MiniDigger wouldn't we know about them? cause it wouldn't compile if its just missing an argument. Or maybe I am misunderstanding what you mean.

2021-04-26 08:00 UTC, MiniDigger commented
no it would still call the old method, since that still exists with the same signature, right?

normally, when we add a new param to a method, we do
```
// Paper start
public void method(Old arg) {
	method(arg, DEFAULT);
}
public void method(Old arg, New arg) {
	// Paper end
	// old code
}
```

2021-04-26 08:20 UTC, Machine-Maker commented
But the old method doesn’t exist with the same signature. I added an argument. So any new places would be missing that argument, and it wouldn’t compile. By adding a new method and leaving the old one, **then** you end up missing when mojang adds new calls to it without our reason.

2021-05-24 05:45 UTC, Machine-Maker commented
yeah, idk what I was taking about, refactored (and rebased) this to make more sense. @MiniDigger

2021-05-24 08:10 UTC, KennyTV requested changes
You missed a setStorm/setThunder call when a world is being loaded

2021-05-24 08:10 UTC, KennyTV commented on Spigot-Server-Patches/0741-Add-cause-to-Weather-ThunderChangeEvents.patch
> ++        this.worldDataServer.setThundering(false, org.bukkit.event.weather.ThunderChangeEvent.Cause.COMMAND); // Paper - happens when weather cycle gamerule is set to false
No, this happens when players go to sleep to skip the night.

2021-05-24 08:10 UTC, KennyTV commented on Spigot-Server-Patches/0741-Add-cause-to-Weather-ThunderChangeEvents.patch
> ++        this.worldDataServer.setStorm(false, org.bukkit.event.weather.WeatherChangeEvent.Cause.COMMAND); // Paper - happens when weather cycle gamerule is set to false
No, this happens when players go to sleep to skip the night.

2021-05-24 08:10 UTC, KennyTV commented on Spigot-Server-Patches/0741-Add-cause-to-Weather-ThunderChangeEvents.patch
> ++                this.worldDataServer.setStorm(flag2, org.bukkit.event.weather.WeatherChangeEvent.Cause.COMMAND); // Paper
Why is the reason here `COMMAND`?

2021-05-24 16:41 UTC, Machine-Maker commented
mmkay, made those changes.

2021-05-24 16:45 UTC, KennyTV approved these changes

2021-05-24 16:45 UTC, merged