Fix MC-181190 curing zombie villager discount exploit
PaperMC/Paper pull request #4871
Opened 2020-12-09 02:42 UTC by BillyGalbreath

This fixes the exploit used to gain absurd trading discounts with infecting
and curing a villager on repeat by simply resetting the reputation when it
is cured.

2020-12-09 03:28 UTC, aikar requested changes

2020-12-09 03:28 UTC, aikar commented on Spigot-Server-Patches/0613-Fix-curing-zombie-villager-discount-exploit.patch
> ++        fixCuringZombieVillagerDiscountExploit = getBoolean("fix-curing-zombie-villager-discount-exploit", fixCuringZombieVillagerDiscountExploit);
this should be under game-mechanics section prob

2020-12-09 03:28 UTC, aikar commented on Spigot-Server-Patches/0613-Fix-curing-zombie-villager-discount-exploit.patch
> +-import org.bukkit.craftbukkit.entity.CraftVillager;
imports

2020-12-09 03:39 UTC, BillyGalbreath commented on Spigot-Server-Patches/0613-Fix-curing-zombie-villager-discount-exploit.patch
> ++        fixCuringZombieVillagerDiscountExploit = getBoolean("fix-curing-zombie-villager-discount-exploit", fixCuringZombieVillagerDiscountExploit);
Good call ^_^

2020-12-09 03:39 UTC, BillyGalbreath commented on Spigot-Server-Patches/0613-Fix-curing-zombie-villager-discount-exploit.patch
> +-import org.bukkit.craftbukkit.entity.CraftVillager;
I need to figure out why IJ started doing this automatically recently. Sorry :3

2020-12-09 03:56 UTC, aikar approved these changes

2020-12-09 03:56 UTC, merged

2020-12-09 07:28 UTC, mrfloris commented
Thank god this is finally addressed.

2021-02-04 16:49 UTC, VeritasDL commented
this is NOT a bug, this is a INTENDED minecraft function, why patch it out?

2021-02-04 16:50 UTC, zachbr commented
Then disable the fix.

2021-02-04 16:51 UTC, VeritasDL commented
> 
> 
> Then disable the fix.

disable a fix that shouldn't even be a fix, 10/10 suggestion
imagine disabling something that doesn't have a toggle

2021-02-04 16:52 UTC, zachbr commented
I guess you can just go cry about it some more then?

2021-02-04 18:01 UTC, aikar commented
```Confirmation Status:Confirmed
Category:
Village system
Mojang Priority:Important```

Mojang seems to disagree with you, and has labeled this an important bug.