Optimized villager pathfinding
PaperMC/Paper pull request #4915
Opened 2020-12-20 00:36 UTC by lukalt

**As I based my previous pull request #4885 on the master branch of my fork, I've re-created this pull request.**

In Minecraft 1.16, villagers consume a lot more server resources than in previous versions. I have experienced up to 35% of the CPU time being spent for villager behavior calculations on a server with lots of villager farms. This patch comes with two optimizations to tackle this problem.

The villager pathfinding searches for structures in villages a villager might navigate to (e.g. lecterns). By default, this scans all chunk sections in a horizontal range of 48 blocks. The vanilla implementation uses a very complex chain of streams performing lots of redundant computations. Furthermore, way more chunk sections are checked than actually necessary. This patch contains a rewritten version of this algorithm, which should be about 10 times faster and reduces the pressure on the garbage collector.
Using the default configuration, the behavior should not differ from vanilla, however lowering "villageSearchRadius" in the "paper.yml" should boost the performance significantly with just a little impact on the gameplay.

Furthermore, this patch adds the option to modify the "cooldown" between consecutive pathfinding calls to the same villager by modifying "villagerBehaviorMinCooldown" and
"villagerBehaviorMaxCooldown". The cooldown will be a random number of ticks between these two values. The default config values do not change the vanilla behavior at all.

This is my first contribution to paper and I hope this pr matches all requirements. If there is anything wrong, please let me know :)

2020-12-20 00:46 UTC, Machine-Maker requested changes

2020-12-20 00:46 UTC, Machine-Maker commented on Spigot-Server-Patches/0615-Optimized-villager-pathfinding.patch
> ++        villagerBehaviorMaxCooldown = getInt("villager-behavior.cooldown-max", 20);
Just so it only has to be changed in one place in the future. 
```suggestion
+        villageSearchRadius = getInt("villager-behavior.village-search-radius", villageSearchRadius);
+        villagerBehaviorMinCooldown = getInt("villager-behavior.cooldown-min", villagerBehaviorMinCooldown);
+        villagerBehaviorMaxCooldown = getInt("villager-behavior.cooldown-max", villagerBehaviorMaxCooldown);
```

2020-12-20 02:21 UTC, lukalt commented on Spigot-Server-Patches/0615-Optimized-villager-pathfinding.patch
> ++        villagerBehaviorMaxCooldown = getInt("villager-behavior.cooldown-max", 20);
Thank for this note, I've changed it

2020-12-20 08:45 UTC, HexedHero submitted a review, later dismissed

2020-12-20 10:14 UTC, MiniDigger commented on Spigot-Server-Patches/0615-Optimized-villager-pathfinding.patch
> ++        this.f = i + 20L + (long)worldserver.random.nextInt(worldserver.paperConfig.villagerBehaviorMaxCooldown - worldserver.paperConfig.villagerBehaviorMinCooldown); // Paper - Option to slow down
I am not fully awake yet, but shouldn't this be `i + 20 + min + random(max-min)`? (the + min is missing)

2020-12-20 13:35 UTC, lukalt commented on Spigot-Server-Patches/0615-Optimized-villager-pathfinding.patch
> ++        this.f = i + 20L + (long)worldserver.random.nextInt(worldserver.paperConfig.villagerBehaviorMaxCooldown - worldserver.paperConfig.villagerBehaviorMinCooldown); // Paper - Option to slow down
You're totally right, I've fixed this now

2020-12-20 14:04 UTC, MiniDigger commented on Spigot-Server-Patches/0615-Optimized-villager-pathfinding.patch
> ++        this.f = i + 20L + (long)worldserver.random.nextInt(worldserver.paperConfig.villagerBehaviorMaxCooldown - worldserver.paperConfig.villagerBehaviorMinCooldown); // Paper - Option to slow down
now you removed the +20, I think that still needs to be there.

vanilla is i + 20 + random between 0 and 20
we want i + 20 + random between min and max, which translates into i + 20 + min + random(max-min)

2020-12-21 15:50 UTC, aikar commented
I have a patch that does this similar improvements to get rid of streams that's pending merge I would rather keep my version for now as it's a bit clearer on whats going on.

So I will try to get that merged first, then see how your changes can be applied on top of that.

2021-02-23 18:29 UTC, electronicboy commented
a

2021-02-23 18:30 UTC, electronicboy requested changes
awaiting on aikar

2022-10-22 16:27 UTC, Owen1212055 commented
Closing this, as the POI search logic has been optimized by leaf. Individual behaviors can also be adjusted to occur less often 
in the config as well.

However, if you still feel that there are some optimizations that can apply here please comment!

2022-10-22 16:27 UTC, closed without merging