Add EntityPotionEffectImmunityEvent
PaperMC/Paper pull request #4920
Opened 2020-12-20 16:45 UTC by kivibot

Allows plugins to selectively disable vanilla potion effect immunities. 
Can also be used to detect if immune mobs have been hit with those effects.

Somewhat related issue #3580

2020-12-20 16:58 UTC, Proximyst requested changes

2020-12-20 16:58 UTC, Proximyst commented on Spigot-Server-Patches/0619-Add-EntityPotionEffectImmunityEvent.patch
> ++        if(this.d(mobEffect)) {
Obfhelper

2020-12-20 16:58 UTC, Proximyst commented on Spigot-Server-Patches/0619-Add-EntityPotionEffectImmunityEvent.patch
> ++        if (this.checkEffectImmunity(mobeffect, cause)) { // Paper
Why has the logic been inversed?

2020-12-25 11:50 UTC, Proximyst requested changes
See previous comment

2021-01-02 10:39 UTC, electronicboy approved these changes
Provisionally approving, an obfhelper on the actual method would be nice

2022-02-23 03:28 UTC, electronicboy approved these changes

2022-11-14 23:00 UTC, Owen1212055 commented
This is in general covered by config values, is an event really needed here?

2022-11-25 17:53 UTC, Owen1212055 commented
Closing, in general, most of this behavior is doable with config options now. 
If someone else still sees use for this and wants to pick up on this feel free. 😄

2022-11-25 17:53 UTC, closed without merging