Add HalloweenChecker to optimize mob spawns
PaperMC/Paper pull request #4947
Opened 2020-12-27 14:37 UTC by VADemon

Affected mobs: Zombie, Bats, SkeletonAbstract

By default MC checks on every **natural spawn** attempt whether it's "halloween time", it's probably not. This patch keeps track of the next upcoming date to schedule the toggle at the right time, using logarithmic back-off.
Both Halloween-Season and -Day checks are reduced to boolean comparisons.

Supersedes #4939 (that only included Bats and a coarse hourly check).

Personal todo:
[ ] write tests
[ ] Proper  LocalDateTime (I only noticed after finishing that LocalDate doesnt want to do anything with ChronoUnit.SECONDS ;))
[ ] probably an API? There's no way currently to change any of that, as its hardcoded in three places separately.

Open for commentary. For chat, Paper guild: `@vad#`

2020-12-28 10:52 UTC, MiniDigger requested changes
looking good, minor nit picks

I dont really see a use in exposing this as an api, its just a small easter egg

2020-12-28 10:52 UTC, MiniDigger commented on Spigot-Server-Patches/0623-Add-HalloweenChecker-to-optimize-halloween-related-m.patch
> ++    public enum SEASON_DATE {
```suggestion
+    public enum SeasonDate {
```

2020-12-28 10:52 UTC, MiniDigger commented on Spigot-Server-Patches/0623-Add-HalloweenChecker-to-optimize-halloween-related-m.patch
> ++package com.destroystokyo.paper.entity;
all new classes should go into the io.papermc package

2020-12-28 10:52 UTC, MiniDigger commented on Spigot-Server-Patches/0623-Add-HalloweenChecker-to-optimize-halloween-related-m.patch
> +-            int i = generatoraccess.getLightLevel(blockposition);
please comment out and add a // Paper comment, that was its easier to update

2020-12-28 10:52 UTC, MiniDigger commented on Spigot-Server-Patches/0623-Add-HalloweenChecker-to-optimize-halloween-related-m.patch
> ++
evil new line!

2020-12-28 10:52 UTC, MiniDigger commented on Spigot-Server-Patches/0623-Add-HalloweenChecker-to-optimize-halloween-related-m.patch
> ++        HALLOWEEN_DAY(10, 31, true, true),
```suggestion
+        HALLOWEEN_DAY_START(10, 31, true, true),
```

to be consistent with season start and end

2021-01-06 21:38 UTC, MeFisto94 commented on Spigot-Server-Patches/0623-Add-HalloweenChecker-to-optimize-halloween-related-m.patch
> ++        SEASON_END(10, 4, false, false);
Should probably be 11, 4, i.e. November?

2021-03-03 20:44 UTC, MiniDigger commented
@VADemon do you plan on dealing with the reviews?

2021-08-10 07:13 UTC, MiniDigger commented
superseded by #6372

2021-08-10 07:13 UTC, closed without merging