Allow Reloading of Command Aliases
PaperMC/Paper pull request #495
Opened 2016-11-22 04:17 UTC by willies952002

Use "/reload commands" to reload the aliases stored in commands.yml

2016-11-23 16:51 UTC, aikar requested changes

2016-11-23 16:51 UTC, aikar commented on Spigot-API-Patches/0042-Allow-Reloading-of-Command-Aliases.patch
> ++    /**
Missing // Paper start

2016-11-23 16:51 UTC, aikar commented on Spigot-Server-Patches/0179-Allow-Reloading-of-Command-Aliases.patch
> ++        commandsConfiguration = YamlConfiguration.loadConfiguration(getCommandsConfigFile());
This section needs work.

You need to remove the commands BEFORE reloading the configuration file, as if you remove a command from commands.yml, the way you have this, will not remove the command.

2016-11-23 16:51 UTC, aikar commented on Spigot-Server-Patches/0179-Allow-Reloading-of-Command-Aliases.patch
> ++            getCommandMap().getKnownCommands().remove(alias.toLowerCase(java.util.Locale.ENGLISH));
This whole block can be replaced with 
Set<String> keys = getCommandMap().getKnownCommands().keySet();

then keys.removeAll(getCommandAliases().keySet());

Repeat after the commandsConfiguration is reloaded per my other comment.

2016-11-25 02:26 UTC, willies952002 commented on Spigot-API-Patches/0042-Allow-Reloading-of-Command-Aliases.patch
> ++    /**
This was actually placed in a pre-existing block of code that is added by paper

2016-11-25 02:26 UTC, willies952002 commented on Spigot-Server-Patches/0179-Allow-Reloading-of-Command-Aliases.patch
> ++            getCommandMap().getKnownCommands().remove(alias.toLowerCase(java.util.Locale.ENGLISH));
This actually could be considered unreliable in terms of the following:

getCommandMap().getKnownCommands().keySet() returns ["foo","bar","baz", ...]
getCommandAliases().keySet() returns ["foo","BaR", "BAZ"]

in this case, only "foo" is removed (unless it's not case sensitive) since "BaR" and "BAZ" are not in the known commands keys.

2016-11-25 03:18 UTC, aikar commented on Spigot-Server-Patches/0179-Allow-Reloading-of-Command-Aliases.patch
> ++            getCommandMap().getKnownCommands().remove(alias.toLowerCase(java.util.Locale.ENGLISH));
Then fine, do 


```java
Set<String> commandsToRemove = getCommandAliases.keySet().stream().map(key -> key.toLowerCase(Locale.ENGLISH)).collect(Collectors.toSet());
YamlConfiguration.load(getCommandsConfig());
commandsToRemove.addAll(getCommandAliases.keySet().stream().map(key -> key.toLowerCase(Locale.ENGLISH)).collect(Collectors.toList());
getCommandMap().getKnownCommands().keySet().removeIf(key -> commandstoRemove.contains(key));
```

Build a set of all to be removed, then remove them

2016-11-25 03:19 UTC, aikar commented on Spigot-API-Patches/0042-Allow-Reloading-of-Command-Aliases.patch
> ++    /**
Ok, I didn't notice the // Paper end wasn't part of the patch, thats fine then.

2016-11-28 15:26 UTC, closed without merging

2016-11-28 15:31 UTC, willies952002 commented
Updated PR: #518