Cache burn durations
PaperMC/Paper pull request #4950
Opened 2020-12-27 22:19 UTC by lukalt

Cache the results of TileEntityFurnace.f() (which returns a map containing all fuel items along with their burn duration).  This optimizes the TileEntityFurnace.isFuel(ItemStack) function, which is called whenever a hopper pushes an item into a furnace 
( https://imgur.com/a/X4kndsx ).

2020-12-27 22:21 UTC, JRoy requested changes

2020-12-27 22:21 UTC, JRoy commented on Spigot-Server-Patches/0615-Cache-burn-durations.patch
> ++            cachedBurnDurations = f();
f() needs an obfhelper

2020-12-27 22:23 UTC, electronicboy commented
This would likely be done better by just making the f method cache the map on the first call and returning the init'd version if it already has it, wrap it in an immutable map so nothing can modify it (Nothing appears to do so, but, the immutable map would give us a useful error of something is expecting to do so)

2020-12-30 02:29 UTC, lukalt commented
Thank you for the comments. I've updated the patch according to them now

2020-12-31 02:35 UTC, MeFisto94 commented
Isn't the OBFHELPER meant to be done just the other way?
Like a mere `f() { getBurnDurations(); }`?
That way the callsites to f don't need to be updated and none can be overlooked.
But that's just my personal opinion, not sure what the team thinks.

2020-12-31 02:36 UTC, electronicboy commented
OBFHELPER is not needed here at all

2020-12-31 03:04 UTC, electronicboy submitted a review, later dismissed
provisionally approving, either you or whoever merges can deal with the needed changes, they're pretty minor

2021-01-01 15:53 UTC, MiniDigger commented
@limbo-app ready

2021-01-01 15:53 UTC, limbo-app approved these changes
Pull request automatically approved for merging - a core team member has previously approved this pull request.

2021-01-01 15:56 UTC, merged

2021-01-01 15:57 UTC, MiniDigger commented
thanks for your contribution