Add API to get the Material of Boats and Minecarts
PaperMC/Paper pull request #4965
Opened 2020-12-31 02:53 UTC by me4502

A lot of plugins currently have big switch statements to get the Material out of a Boat or Minecart. This PR adds API to get them.

For boats, this just calls an NMS method that has its own switch statement, but for Minecarts a switch statement had to be added in CraftMinecart. To prevent this exploding in cases where new cart types are added, it will default to the normal MINECART item in those cases. This is also important as there are cart types that are not represented as items, such as EntityMinecartType.SPAWNER

2020-12-31 03:05 UTC, electronicboy approved these changes, later dismissed

2020-12-31 03:11 UTC, kashike requested changes, later dismissed

2020-12-31 03:11 UTC, kashike commented on Spigot-Server-Patches/0627-Implement-API-to-get-Material-from-Boats-and-Minecar.patch
> ++
Remove this newline.

2021-01-01 14:39 UTC, Proximyst commented
@limbo-app ready

2021-01-01 14:39 UTC, limbo-app approved these changes
Pull request automatically approved for merging - a core team member has previously approved this pull request.

2021-01-01 15:06 UTC, merged