Configurable max lead distance
PaperMC/Paper pull request #4992
Opened 2021-01-04 05:06 UTC by Machine-Maker

2021-01-04 05:11 UTC, kashike requested changes

2021-01-04 05:11 UTC, kashike commented on Spigot-Server-Patches/0643-Configurable-max-lead-distance.patch
> ++    public float maxLeadDistance = 10f;
```suggestion
+    public float maxLeashDistance = 10f;
```
It's called a leash elsewhere - your log message, event names, method names.

2021-01-04 05:11 UTC, kashike commented on Spigot-Server-Patches/0643-Configurable-max-lead-distance.patch
> ++        maxLeadDistance = getFloat("max-lead-distance", maxLeadDistance);
```suggestion
+        maxLeashDistance = getFloat("max-leash-distance", maxLeashDistance);
```

2021-01-04 05:11 UTC, kashike commented on Spigot-Server-Patches/0643-Configurable-max-lead-distance.patch
> ++    private void maxLeadDistance() {
```suggestion
+    private void maxLeashDistance() {
```

2021-01-04 05:11 UTC, kashike commented on Spigot-Server-Patches/0643-Configurable-max-lead-distance.patch
> ++                if (f > entity.world.paperConfig.maxLeadDistance) { // Paper
```suggestion
+                if (f > entity.world.paperConfig.maxLeashDistance) { // Paper
```

2021-01-04 05:11 UTC, kashike commented on Spigot-Server-Patches/0643-Configurable-max-lead-distance.patch
> ++            if (f > entity.world.paperConfig.maxLeadDistance) { // Paper
```suggestion
+            if (f > entity.world.paperConfig.maxLeashDistance) { // Paper
```

2021-01-04 05:11 UTC, kashike commented on Spigot-Server-Patches/0643-Configurable-max-lead-distance.patch
> ++        log("Max leash distance: " + maxLeadDistance);
```suggestion
+        log("Max leash distance: " + maxLeashDistance);
```

2021-01-04 09:35 UTC, MiniDigger approved these changes
lgtm

2021-01-06 00:27 UTC, kashike approved these changes

2021-01-17 17:47 UTC, merged