Optimise recalcBlockCounts
PaperMC/Paper pull request #502
Opened 2016-11-23 19:20 UTC by AlfieC

Minimises operations and cuts out bit shifting & 2 loops.

2016-11-23 20:18 UTC, Techcable commented
Please actually make the changes directly inatead of commenting out the old methos.

2016-11-23 20:19 UTC, AlfieC commented
They're left there to make updating easier - if Mojang change this method completely, it's useful to see the original. It can be removed on merge.

2016-11-23 20:30 UTC, Techcable commented
If mojangs makes a change the diff won't trigger a conflict, causing us to miss changes on update.
Additionally it's more difficult for maintainers to know what changes the patch actually made, which wastes time and effort in a update.
Git is smart enough to automatically resolve simple conflicts on an update, but this makes it ignore changes by mojang, causing bugs on update.
We'll already be able to see the old mojang code, since git shows it to us if there's a conflict.

2016-11-23 20:36 UTC, AlfieC commented
I only left it commented instead of removing as that's the style I saw in the `Disable ticking snow blocks` patch. Maybe that's different as it's a constructor that was removed - but I didn't want to decide for myself.

2016-11-26 12:44 UTC, AlfieC commented
Updated PR to remove old method instead of commenting, and added an extra optimisation.

2016-11-28 21:05 UTC, aikar commented on Spigot-Server-Patches/0181-Optimise-recalcBlockCounts.patch
> ++        IBlockData iblockdata = this.c.a(this.b.a(position));
This absolutely needs obfuscation helpers

2016-12-01 15:26 UTC, aikar requested changes

2016-12-01 15:26 UTC, aikar commented on Spigot-Server-Patches/0181-Optimise-recalcBlockCounts.patch
> ++        if (block != block1) {
Based on what this change is doing, please undo the indentation change of all of this inner code.

I'm almost willing to say just short circuit return and copy the last line that isn't part of the if(), but that would introduce risk for bugs in future.

But im more comfortable with the inner code changing. and being ok still.

2016-12-27 20:42 UTC, aikar commented
@AlfieC can you get the requested changes in and ensure this applies over latest?

2017-01-10 18:55 UTC, AlfieC commented
PR updated.

2017-06-11 20:45 UTC, kashike commented
Do we want this?

2017-07-27 00:17 UTC, closed without merging