Add BlockPreDispenseEvent
PaperMC/Paper pull request #5075
Opened 2021-01-17 03:22 UTC by me4502

This PR adds an event that is called prior to a Dispenser firing anything. This allows full access to the pre-fire state of the dispenser inventory, and therefore clean cancelling of the event.

Main use case here is for plugins that want to either entirely cancel a dispenser event, or want to perform an action based off the contents of the dispenser. Due to the way the normal dispense event works, neither of these are currently possible.

This also allows working around an old Spigot bug, https://hub.spigotmc.org/jira/browse/SPIGOT-4162

2021-01-17 03:24 UTC, kashike requested changes

2021-01-17 03:24 UTC, kashike commented on Spigot-API-Patches/0263-Add-BlockPreDispenseEvent.patch
> ++    public BlockPreDispenseEvent(@NotNull Block theBlock, @NotNull ItemStack theItemStack, int theSlot) {
Drop `the`.

2021-01-17 03:24 UTC, me4502 commented on Spigot-API-Patches/0263-Add-BlockPreDispenseEvent.patch
> ++    public BlockPreDispenseEvent(@NotNull Block theBlock, @NotNull ItemStack theItemStack, int theSlot) {
Okay :(

2021-01-17 05:37 UTC, mbax commented on Spigot-API-Patches/0263-Add-BlockPreDispenseEvent.patch
> ++    public BlockPreDispenseEvent(@NotNull Block theBlock, @NotNull ItemStack theItemStack, int theSlot) {
Drop the what, kashike? 😇

2021-01-19 22:55 UTC, electronicboy approved these changes

2021-01-19 22:55 UTC, merged