Stop loop when flags is false
PaperMC/Paper pull request #5101
Opened 2021-01-22 18:56 UTC by DoctaEnkoda

It's no a big update ^^"

2021-01-22 18:59 UTC, Proximyst requested changes
The entire code is just stupid. Change it to `return false` in the loop and otherwise `return true`.

2021-01-22 22:39 UTC, DoctaEnkoda commented
it's good

2021-02-21 11:11 UTC, DoctaEnkoda commented
up ?

2021-02-21 12:33 UTC, electronicboy approved these changes

2021-02-21 12:34 UTC, merged