Optimized dirt and snow spreading
PaperMC/Paper pull request #5124
Opened 2021-01-27 21:25 UTC by lukalt

Significantly reduces the number of chunk lookups when grass is spread in random ticks. This does not change the game mechanics.

2021-02-01 16:27 UTC, Titaniumtown approved these changes
I've been testing this patch on my server for a while now w/o any issues. LGTM.

2021-02-02 07:48 UTC, MiniDigger approved these changes

2021-02-11 14:02 UTC, imDaniX requested changes
I need some _space_ plz
`if (expression)`

2021-02-19 21:24 UTC, Fox2Code approved these changes

2021-02-19 21:24 UTC, Fox2Code commented on Spigot-Server-Patches/0666-optimized-dirt-and-snow-spreading.patch
> ++        Chunk chunk = worldserver.getChunkIfLoaded(blockposition);
I really like the fact that it avoids loading chunks for spreading grass.

2021-02-23 18:22 UTC, electronicboy approved these changes

2021-04-28 21:25 UTC, PaulBGD approved these changes
Looks good, although admittedly this will only improve dirt/snow spreading by about 30%, as the light check is the heaviest part of spreading.

2022-10-22 17:45 UTC, Owen1212055 approved these changes

2022-10-22 18:14 UTC, merged