Add ElderGuardianAppearanceEvent
PaperMC/Paper pull request #5148
Opened 2021-02-02 01:42 UTC by Owen1212055

This adds an ElderGuardianAppearanceEvent which allows you to cancel the effects of an elder guardian appearance and get the players that were affected.

2021-02-02 03:15 UTC, Owen1212055 commented
I will push a fix for the annotation later.

2021-02-02 03:25 UTC, kashike requested changes

2021-02-02 03:25 UTC, kashike commented on Spigot-Server-Patches/0667-Add-ElderGuardianAppearanceEvent.patch
> +-                EntityPlayer entityplayer = (EntityPlayer) iterator.next();
Please do not change the indentation of this code - simply wrap it with the new event check.

2021-03-18 18:18 UTC, Owen1212055 commented
Redoing.

2021-03-18 18:18 UTC, closed without merging