Prevent grindstones from overstacking items fixes #5196
PaperMC/Paper pull request #5197
Opened 2021-02-17 03:52 UTC by chickeneer

Just out of view of the patch is the line
`b0 = 2;`
which sets the result quantity to two without checking whether that is possible. This explains why my fix only specifically checks for max stack sizes of 1.

Overstacked items are specifically not supported by the server and can result in item loss when the items are not handled carefully. Specifically there exists an 'issue' with shulker chests that they will destack overstacked items and simply delete items which do not fit.

2021-02-17 06:25 UTC, Proximyst requested changes
Diff on change on the line this surrounds so we don:t need to manually check it on updates.

2021-02-17 11:52 UTC, chickeneer commented
> Diff on change on the line this surrounds so we don:t need to manually check it on updates.

I didn't understand exactly what you mean, but I have added what I think you meant.

2021-02-17 12:44 UTC, Proximyst approved these changes
You hit the nail on the head :)

2021-03-07 10:56 UTC, Proximyst commented
Thanks for your contribution!

2021-03-07 10:59 UTC, merged