Add EntityExtinguishEvent
PaperMC/Paper pull request #5242
Opened 2021-02-24 02:13 UTC by aurorasmiles

Closes #5143
Replaces #5144 
I tried to see if I could manage to fix that issue and add that event. After finishing, I noticed that there already way a PR for this, but as it was made by Ivan and he is banned from the Org, I figured to open a PR anyway.
I haven't implemented cancellable, because I figured this would cause a lot of issues in the long run, and I wasn't sure how to properly address that.
Other than that there is another extinguish called in EntityHuman line 1211, but I decided to not call the event there, since the entity was never technically on fire

2021-02-24 08:49 UTC, kashike requested changes

2021-02-24 08:49 UTC, kashike commented on Spigot-Server-Patches/0678-Add-EntityExtinguishEvent.patch
> ++            new EntityExtinguishEvent(entity.getBukkitEntity(), EntityExtinguishEvent.Cause.WET); // Paper - add EntityExtinguishEvent
You need to actually call the event, too.

2021-02-24 08:49 UTC, kashike commented on Spigot-Server-Patches/0678-Add-EntityExtinguishEvent.patch
> ++                    new EntityExtinguishEvent(this.getBukkitEntity(), EntityExtinguishEvent.Cause.TIME); // Paper - add EntityExtinguishEvent
You need to actually call the event, too.

2021-02-24 08:49 UTC, kashike commented on Spigot-Server-Patches/0678-Add-EntityExtinguishEvent.patch
> ++            new EntityExtinguishEvent(this.getBukkitEntity(), EntityExtinguishEvent.Cause.WET); // Paper - add EntityExtinguishEvent
You need to actually call the event, too.

2021-02-24 08:49 UTC, kashike commented on Spigot-Server-Patches/0678-Add-EntityExtinguishEvent.patch
> ++            new EntityExtinguishEvent(this.getBukkitEntity(), EntityExtinguishEvent.Cause.WET); // Paper - add EntityExtinguishEvent
You need to actually call the event, too.

2021-02-24 08:49 UTC, kashike commented on Spigot-Server-Patches/0678-Add-EntityExtinguishEvent.patch
> ++        new EntityExtinguishEvent(this.getBukkitEntity(), EntityExtinguishEvent.Cause.DEATH); // Paper - add EntityExtinguishEvent
You need to actually call the event, too.

2021-02-24 08:49 UTC, kashike commented on Spigot-Server-Patches/0678-Add-EntityExtinguishEvent.patch
> ++            new EntityExtinguishEvent(this.getBukkitEntity(), EntityExtinguishEvent.Cause.FIREPROOF); // Paper - add EntityExtinguishEvent
You need to actually call the event, too.

2021-02-24 08:49 UTC, kashike commented on Spigot-Server-Patches/0678-Add-EntityExtinguishEvent.patch
> ++            new EntityExtinguishEvent(this.getBukkitEntity(), EntityExtinguishEvent.Cause.WET); // Paper - add EntityExtinguishEvent
You need to actually call the event, too.

2021-02-24 08:49 UTC, kashike commented on Spigot-Server-Patches/0678-Add-EntityExtinguishEvent.patch
> ++        new EntityExtinguishEvent(this.getBukkitEntity(), EntityExtinguishEvent.Cause.DEATH); // Paper - add EntityExtinguishEvent
You need to actually call the event, too.

2021-02-24 20:24 UTC, aurorasmiles commented
Changed :)

2021-02-27 14:14 UTC, Proximyst approved these changes
One note, otherwise LGTM. The note can be handled on merge.

2021-02-27 14:14 UTC, Proximyst commented on Spigot-Server-Patches/0678-Add-EntityExtinguishEvent.patch
> ++                entity.extinguish();
Don't indent

2021-03-15 10:14 UTC, SoSeDiK commented
Do you mind separating the extinguish cases a bit more, please? The previous PR had 8 cases versus 4 in this one.
That would make my life easier 😅
Like for the cauldron, I'd otherwise have to use the `CauldronLevelChangeEvent` with `ChangeReason.EXTINGUISH` and `getEntity()`, and that may be way easier with ths merged.
(or listen for this and check if the entity is inside the cauldron, and if it has water (which may not work since changeLevel() is called before extinguishing, so there will be no water for the lowest water level?))
I'd use that for my temperature module where I trigger some additional effects upon extinguish (different for every case).

2021-03-15 16:41 UTC, aurorasmiles commented
Added more reasons, removed the indents and resolved conflicts

2021-03-20 17:25 UTC, aurorasmiles commented
"rebased"

2021-03-20 22:38 UTC, Trigary requested changes
Looks good apart from the unused `BUBBLE` cause.

2021-03-20 22:38 UTC, Trigary commented on Spigot-API-Patches/0283-Add-EntityExtinguishEvent.patch
> ++        BUBBLE,
Never used. Is this an oversight?

2021-03-20 22:38 UTC, Trigary commented on Spigot-API-Patches/0283-Add-EntityExtinguishEvent.patch
> ++ * Is called when a burning {@link org.bukkit.entity.Entity} is extinguished.
Nitpick: I would specify what "burning" and "being extinguished" means. Meaning that I would add JavaDoc links to the fireTicks property.

2021-03-20 22:38 UTC, Trigary commented on Spigot-Server-Patches/0696-Add-EntityExtinguishEvent.patch
> ++            // Paper end
Kind of nitpick: that code you added is never used, so why add it? (It is never used since the server is not client-side.)

2021-03-20 22:38 UTC, Trigary commented on Spigot-Server-Patches/0696-Add-EntityExtinguishEvent.patch
> ++    // Paper end
Nitpick: you can replace all cases of
```
EntityExtinguishEvent event = CraftEventFactory.callEntityExtinguishEvent(entity, ...);
if (!event.isCancelled()) {
```
with
```
if (new EntityExtinguishEvent(entity.getBukkitEntity(), ...).callEvent()) {
```
That way you don't pollute the local scope with an `event` variable and your patch modifies one less file.

2021-03-22 20:46 UTC, yannicklamprecht requested changes

2021-03-22 20:46 UTC, yannicklamprecht commented on Spigot-Server-Patches/0696-Add-EntityExtinguishEvent.patch
> ++import org.bukkit.craftbukkit.event.CraftEventFactory;
I think that isn't needed.

2021-03-22 20:46 UTC, yannicklamprecht commented on Spigot-Server-Patches/0696-Add-EntityExtinguishEvent.patch
> ++import org.bukkit.craftbukkit.event.CraftEventFactory;
I think that isn't needed.

2021-05-24 11:46 UTC, TetraTheta commented
As mentioned in #5517, I think if this pull request want to include 'FireTickChangeEvent' event stuff, then its event name should be altered, so that that event can include both `onFire`(from 'FireTickChangeEvent'), `onExtinguish`(from 'EntityExtinguishEvent'). Just food for thought.

2021-06-02 00:06 UTC, closed without merging