Add Multiple Entries to Scoreboard Team
PaperMC/Paper pull request #5267
Opened 2021-02-26 23:06 UTC by Cryptite

It is a common pattern to fill a team up with several entries. Unfortunately, each single entry addition sends a ScoreboardTeam packet out which can be unnecessarily chatty. This patch just adds the option to set a collection of entries on a scoreboard team which can get bundled into a single packet. 

Likely not a significant optimization, but hey, every little bit helps.

2021-02-26 23:50 UTC, notOM3GA commented
Is this ment to include the show/hidePlayer api patches?

2021-02-27 01:16 UTC, Cryptite commented
Whoops, it is not. That said if approved; I don't see a huge issue with this PR having both and closing out https://github.com/PaperMC/Paper/pull/5266.

I'll do whatever paper team would like

2021-02-27 01:32 UTC, notOM3GA commented
Keeping them separate would be best

2021-02-27 11:59 UTC, theminecoder commented
If you are doing a mass entry method, I think it would make sense that we also get a mass removal one at the same time.

2021-02-27 14:05 UTC, Proximyst requested changes

2021-02-27 14:05 UTC, Proximyst commented on Spigot-Server-Patches/0679-Add-Multiple-Entries-to-Scoreboard-Team.patch
> ++    // Paper start
Feels like this could just call `#addEntry(String)` for all entries?

2021-02-27 14:05 UTC, Proximyst commented on Spigot-Server-Patches/0679-Add-Multiple-Entries-to-Scoreboard-Team.patch
> ++            this.b();
OBFHELPER

2021-05-23 15:33 UTC, electronicboy requested changes

2021-05-23 15:33 UTC, electronicboy commented on Spigot-Server-Patches/0679-Add-Multiple-Entries-to-Scoreboard-Team.patch
> ++            if (entry.length() > 40) {
This logic here just feels like this will potentially cause a desync if there is a name in the middle which is bad?

2021-09-21 20:13 UTC, Cryptite commented
New version of this: https://github.com/PaperMC/Paper/pull/6637

2021-09-21 20:13 UTC, closed without merging