Ignore chunk range check if done in the same tick
PaperMC/Paper pull request #5269
Opened 2021-02-27 05:02 UTC by froobynooby

When scheduling a chunk load, the server checks if that chunk is within the load view distance of a player. However when the view distance is increased, the range check uses the old view distance for that one tick, meaning all chunk load tasks for chunks within the newly set view distance are instantly discarded. This PR ignores the chunk range check if the elapsed time for the chunk load task is 0 ticks

Fixes #5203

2021-02-27 11:19 UTC, Proximyst requested changes, later dismissed
Blocking on review from @aikar or @electronicboy. My block may be dismissed when either one looks over this. I don't believe anyone else on the team know a tonne about the chunk system.

2021-02-28 07:25 UTC, froobynooby commented
No worries. I've also updated the PR to instead just set the new view distance before scheduling the chunk loads. I think this is preferable as the other fix is a bit of a band-aid

2021-02-28 07:32 UTC, Proximyst commented on Spigot-Server-Patches/0486-Implement-Chunk-Priority-Urgency-System-for-Chunks.patch
> ++            this.e = i;
Use an obfhelper instead

2021-02-28 07:44 UTC, electronicboy approved these changes

2021-03-09 09:56 UTC, mindgam3s commented
any idea when this is gonna get pushed into the release ?

@aikar

2021-03-09 09:57 UTC, Proximyst commented
When we get around to it.

2021-03-19 08:48 UTC, froobynooby commented
Rebased

2021-04-14 12:59 UTC, mindgam3s commented
bump ?

2021-04-14 13:13 UTC, aurorasmiles commented
Please don't randomly bump PRs, it doesn't help. We will merge it as soon as someone has time to do so.

2021-04-14 13:44 UTC, mindgam3s commented
> Please don't randomly bump PRs, it doesn't help. We will merge it as soon as someone has time to do so.

ack. sorry. I am just waiting for "just a merge" for a few weeks now. 
won't bump it again :)

2021-04-14 13:45 UTC, electronicboy commented
It's not "just a merge", it needs rebasing which requires more energy than I can afford right now, if OP wants to rebase this I'm willing to pull it 'asap', but, I have no energy to run around rebasing stuff myself, yay health.

2021-04-14 13:51 UTC, mindgam3s commented
I was under the impression that froopynooby's rebased meant he already did the rebase and it is only waiting for acceptance of akair

2021-04-14 13:52 UTC, electronicboy commented
stuff has changed in the repo since then

2021-04-14 13:54 UTC, mindgam3s commented
oh... makes sense. my bad. that's what I didn't know and thought "he just needs to merge it and it's done"

2021-04-14 13:55 UTC, mindgam3s commented
@froobynooby are you willing to rebase it again ?

2021-04-15 08:05 UTC, froobynooby commented
Rebased

2021-04-15 08:51 UTC, merged