Add JavaDoc links to Tag class pointing to custom Paper tags
PaperMC/Paper pull request #5285
Opened 2021-03-01 13:29 UTC by Trigary

Reasoning: by adding JavaDoc links users are able to find the Paper additions.

Let's say someone wants to find a tag for pickaxes. The first place to look would be the `Tag` class. What if the user does not know about these extra classes added by Paper? The user would have to give up the search. But this modification adds links to the `Tag` class, which I assume developers are already familiar with. So developers are now able to discover new tags and, hopefully, the ones they need, through these links.

2021-03-01 13:37 UTC, kashike requested changes

2021-03-01 13:37 UTC, kashike commented on Spigot-API-Patches/0154-Add-Material-Tags.patch
> ++ * <!-- Paper start -->
Remove these tags around the javadoc

2021-03-01 13:49 UTC, Trigary commented on Spigot-API-Patches/0154-Add-Material-Tags.patch
> ++ * <!-- Paper start -->
Done :)

2021-03-03 12:12 UTC, Proximyst requested changes

2021-03-03 12:12 UTC, Proximyst commented on Spigot-API-Patches/0154-Add-Material-Tags.patch
> ++ * <br><br>
Wrap the block in `<p>` instead.

2021-03-04 15:50 UTC, Trigary commented on Spigot-API-Patches/0154-Add-Material-Tags.patch
> ++ * <br><br>
Done.

2021-03-05 15:16 UTC, Proximyst approved these changes

2021-03-07 10:31 UTC, merged