Make entity tracking range use no-tick instead of ticking view distance
PaperMC/Paper pull request #5308
Opened 2021-03-05 02:26 UTC by notOM3GA

This PR fixes the entity tracking range being capped by the ticking view distance and uses the no tick view distance instead.

Before:

https://user-images.githubusercontent.com/69646789/110058184-e989f700-7d2f-11eb-9251-1f697e3072f0.mp4

After: 
https://user-images.githubusercontent.com/69646789/110058157-dd059e80-7d2f-11eb-9c70-4d37aa1c8ac1.mp4

Tested using a view distance of 3, a no-tick view distance of 7, and an entity tracking range of 128.

2021-03-05 03:55 UTC, Proximyst requested changes
Blocking on review from core. Would appreciate one from @Spottedleaf as well, if possible.

2021-03-19 12:04 UTC, notOM3GA commented
Rebased.

2022-02-23 03:32 UTC, electronicboy approved these changes

2022-02-23 03:34 UTC, Spottedleaf commented
This is the behavior as of 1.18

2022-02-23 03:34 UTC, closed without merging