NMS repackaging
PaperMC/Paper pull request #5372
Opened 2021-03-16 16:55 UTC by Proximyst

This PR blocks master.

Big thanks to @jpenilla for his work on the initial update.

2021-03-16 17:26 UTC, MiniDigger commented
needs `./paper clean` to try it out

2021-03-16 17:35 UTC, MiniDigger approved these changes
seems fine. if its broken, we blame md5

2021-03-16 21:02 UTC, jpenilla requested changes
We also need to extract the classes in `com.mojang.math`. importmcdev probably needs changes as well to work with `com.mojang.math` classes when/if we want to patch them.

2021-03-16 21:02 UTC, jpenilla commented on scripts/decompile.sh
> +    jar xf "$decompiledir/$minecraftversion-mapped.jar" net/minecraft
```suggestion
    jar xf "$decompiledir/$minecraftversion-mapped.jar" net/minecraft com/mojang/math
```

2021-03-17 10:15 UTC, jpenilla requested changes

2021-03-17 10:15 UTC, jpenilla commented on Spigot-Server-Patches/0534-Fix-SPIGOT-5989.patch
> ++++ b/t
t

2021-03-17 10:35 UTC, theminecoder commented
@Proximyst for people out of the loop, what is this very large pr doing

2021-03-17 10:36 UTC, Proximyst commented
upstream update

2021-03-17 11:12 UTC, MiniDigger commented
to iterate on that, upstream changed all nms mappings so have mojang mapped package names at dev time. this is most likely a preparation to also remap all classes, methods and fields to mojmap eventually. (nothing at runtime is changing, nothing for plugins is chaning, this is only for server dev time)

splitting up nms classes in multiple packages is challenging for us, since we rely on package private stuff all over the place, but its a change we are happy about, since it makes our mojmap migration easier too. we also need to touch all scripts to make them work properly with multiple packages.

2021-03-17 17:54 UTC, zachbr approved these changes
What a fun diff. Reviews a little better in git directly but not much.

I have confirmed this works nicely in Ubuntu 20.04 and Windows 10 in git bash after clearing the work dir (`/paper clean`). Jar layout looks as I'd expect and plugins look to be working correctly as expected.

Thanks all. Please ping a core team member immediately before merge so we can make sure the CI gets its workspace cleaned once.

2021-03-18 17:03 UTC, merged