[CI-SKIP] Fix makemcdevsrc.sh for nms relocations
PaperMC/Paper pull request #5389
Opened 2021-03-19 20:08 UTC by Black-Hole

After the recent relocations for classes in nms this script needs to be updated to support all source files in net.minecraft and subfolders.
As a side effect only the needed files are copied to the src folder instead of copying all and removing the unneeded files.

2021-03-19 20:14 UTC, Proximyst approved these changes
LGTM; would like a review from @jpenilla.

2021-03-20 05:33 UTC, electronicboy requested changes

2021-03-20 05:33 UTC, electronicboy commented on scripts/makemcdevsrc.sh
> +		cp --parents "${file}" "${mcdevsrc}"
and in the general scene of BSD being awesome, `--parents` is not standard, likely wanna use dirname to work out the actual tree to create and mkdir -p

2021-03-20 10:37 UTC, Black-Hole commented
I replaced that part of the code. I don't have any BCD system to test that code, but I think that "basename" behave the same there.

2021-03-21 04:07 UTC, electronicboy approved these changes

2021-03-21 04:07 UTC, merged