Move Paper and Fastutil imports to fully qualified names where possible
PaperMC/Paper pull request #5407
Opened 2021-03-22 23:33 UTC by broccolai

Now that every class isn't in `net.minecraft.server` many imports can be removed

2021-03-23 00:05 UTC, jpenilla requested changes
In general, looks good. Seems to have covered pretty much all of the now-unnecessary `io.` and `it.` imports. In reviewing this, I did notice quite a few `net.minecraft.` and `org.bukkit.` imports that could probably be replaced will fully qualified names as well, however those would probably be best addressed in a separate PR.

2021-03-23 00:05 UTC, jpenilla commented on Spigot-Server-Patches/0004-MC-Utils.patch
> ++                    it.unimi.dsi.fastutil.objects.Object2IntMap.Entry<EnumCreatureType> it_unimi_dsi_fastutil_objects_object2intmap_entry = (it.unimi.dsi.fastutil.objects.Object2IntMap.Entry) object
Get rid of the diff here, it's only adding a `// Paper` comment now

2021-03-23 00:05 UTC, jpenilla commented on Spigot-Server-Patches/0010-Adventure.patch
> ++import io.papermc.paper.adventure.PaperAdventure;
This import can be removed

2021-03-23 01:17 UTC, jpenilla approved these changes

2021-03-23 05:15 UTC, Proximyst requested changes
I don't think this is a good change: we've settled on a decision to just let the IDE handle imports prior, and I see no reason for us to change that now, especially as the imports section is now actually readable.

Blocking on discussion. Requires core approval.

2021-03-23 05:17 UTC, electronicboy commented
I sallute the effort but I don't see any pressing push for this, maybe on a major release but we've already got a queue we're tryna work through, such a commit would impact a good chunk of them

2021-03-23 08:35 UTC, kashike approved these changes
Approving in general - can delay merging this for a while, if we want.

2022-07-29 15:25 UTC, JRoy commented
Closing as per https://discord.com/channels/289587909051416579/555469074080202765/1002597798153293824

2022-07-29 15:25 UTC, closed without merging