Expose server protocol version
PaperMC/Paper pull request #5416
Opened 2021-03-26 10:34 UTC by KennyTV

Helo, it is I, the protocol hack dude.
Shall this stay in UnsafeValues or not?

2021-03-26 10:47 UTC, Proximyst approved these changes
Look sane. ish.
![](https://media0.giphy.com/media/UmkNfWnDh8JYk/giphy.gif)

2021-03-27 00:10 UTC, yannicklamprecht approved these changes

2021-04-12 17:24 UTC, kashike requested changes

2021-04-12 17:24 UTC, kashike commented on Spigot-API-Patches/0284-Expose-protocol-version.patch
> ++    int getServerProtocolVersion();
```suggestion
+    int getProtocolVersion();
```

2021-04-12 17:24 UTC, kashike commented on Spigot-Server-Patches/0698-Expose-protocol-version.patch
> ++    public int getServerProtocolVersion() {
```suggestion
+    public int getProtocolVersion() {
```

2021-04-12 17:44 UTC, kashike approved these changes

2021-04-12 17:45 UTC, merged