Add Tick TemporalUnit
PaperMC/Paper pull request #5445
Opened 2021-04-02 16:34 UTC by kezz

This PR adds a new class `Tick` that implements `TemporalUnit` to allow easy handling of ticks as a unit of time. Additionally, some unit tests have been provided just for fun.

For example, to create a new duration from a certain number of ticks you can simply do one of the following:
```java
Duration.of(50, Tick.tick());
Tick.of(50);
```

The inverse is also possible, calculating the whole number of ticks in a given duration:
```java
Tick.fromDuration(Duration.of(100, ChronoUnit.SECONDS));
```

This PR is a more restrictive version of the [equivalent PR in Minestom](https://github.com/Minestom/Minestom/pull/205).

2021-04-02 16:36 UTC, electronicboy commented
isDurationEstimated should return true, the nature of tying this hard to a time seems a bit flawed to me

2021-04-02 16:39 UTC, Proximyst requested changes

2021-04-02 16:39 UTC, Proximyst commented on LICENSE.md
> +Kezz <1526243+kezz@users.noreply.github.com>
Does not match your patch author

2021-04-02 16:57 UTC, kezz commented
> isDurationEstimated should return true, the nature of tying this hard to a time seems a bit flawed to me

Good point! I've edited the return type and added a note in the javadoc.

2021-04-05 09:35 UTC, kashike submitted a review, later dismissed

2021-04-05 09:35 UTC, kashike commented on Spigot-API-Patches/0284-Add-Tick-TemporalUnit.patch
> ++package io.papermc.paper;
```suggestion
+package io.papermc.paper.util;
```
Match package that `Tick` is in.

2021-08-19 13:08 UTC, Owen1212055 commented
No!

2022-10-22 15:06 UTC, Owen1212055 approved these changes

2022-10-22 15:08 UTC, Owen1212055 commented
The only place for concern has to do with the "isDurationEstimated", 
as it was mentioned 

>It's worth noting that markin the duration as estimated prevents the main use of this class existing.

2022-10-24 03:10 UTC, electronicboy commented
Yea, I mean, I really feel iffy on this. Like, the expectation of time is that, it, well, progresses at a steady rate, and, ticks trrrrrrry to but technically kinda don't. I guess the limitation of it not allowing maths from that unit elsewhere is kinda dumb and probably justifies not marking it as as an "estimation", I would probably maybe make a note of that

2022-10-24 03:11 UTC, electronicboy approved these changes

2022-11-25 21:05 UTC, merged