Make Player#playSound(Sound) follow the player
PaperMC/Paper pull request #5472
Opened 2021-04-09 10:20 UTC by kezz

Currently, if you play a sound using the Adventure `Player#playSound(Sound)` method it delegates to the `playSound(Sound, double, double, double)` method. This means that if you use this method to play, say, a record, and the player moves about the sound will not follow it, instead sticking at the location the player was at when the sound was played.

Although this could be considered correct behaviour, I believe it should be the case that if you're playing a sound on an audience member you would expect the sound to come from the audience member, following them if their location changes.

At the moment, this method falls back to sending using the custom sound effect packet using the players location, as the entity sound effect packet does not support custom sounds.

2021-04-09 10:33 UTC, TheFruxz commented
I think this should basically be left with the Minecraft original. However, an optional parameter (e.g. boolean followReceiver) would be in my opinion a good way to implement this plugin technically useful feature.

2021-04-09 11:28 UTC, Proximyst requested changes
Blocking on the outcome of KyoriPowered/adventure#316. They're much faster than us in decision-making on PRs anyways.

2021-04-09 11:40 UTC, KennyTV commented
Just changing the old playSound method would mean breaking expected behavior (being a positional sound, not an entity sound) so a `player.playSound(sound, player)` with your adventure pr sounds like the better alternative

2021-04-21 10:11 UTC, Gerrygames commented
https://bugs.mojang.com/browse/MC-138832

2021-06-07 17:12 UTC, closed without merging