Change Thread#stop() invocation to Thread#interrupt()
PaperMC/Paper pull request #5492
Opened 2021-04-14 18:58 UTC by bfu4

## Changes
This pull changes the force stop of the thread in `MinecraftServer#stop()` to use `Thread#interrupt()` instead of `Thread#stop()`. Although `Thread#stop()` is **effective**, it is still unsafe, and hence deprecated. 

## Reasoning
Oracle notes that:

> Stopping a thread causes it to unlock all the monitors that it has locked. (The monitors are unlocked as the ThreadDeath exception propagates up the stack.) If any of the objects previously protected by these monitors were in an inconsistent state, other threads may now view these objects in an inconsistent state. Such objects are said to be damaged. When threads operate on damaged objects, arbitrary behavior can result. This behavior may be subtle and difficult to detect, or it may be pronounced. Unlike other unchecked exceptions, ThreadDeath kills threads silently; thus, the user has no warning that his program may be corrupted. The corruption can manifest itself at any time after the actual damage occurs, even hours or days in the future.

Even though the server is stopped, taking the safer route is preferred. `Thread#stop()` directly invokes `Thread#stop0(Throwable)`, a native function. Viewing the native function supports the documentation above as it releases those locks during deoptimization, as well as leads to the invocation of a few other unsafe operations. 

Although it is called to force-stop the server, and probably should not matter, there is always the chance that something *that* native does cause future harm and of course, to an extent, enforces bad practices. However, if there is a case where `Thread#stop()` with absolute certainty should be used instead, then this PR would be useless -- but in the less-likely occasion the code finds a way to reach this point, `Thread#interrupt()` works about the same, without of course, the implications of `Thread#stop()` This PR introduces the usage of a safer method call, `Thread#interrupt()`, plus removes the usage of the well deprecated `Thread#stop()`.

2021-04-14 19:44 UTC, Proximyst requested changes
Blocking on review from @electronicboy or @aikar.

2021-04-15 05:44 UTC, electronicboy commented
Thread.stop was implicitly used afaik due to the various issues with calling Thread.interrupt, ideally we'd interrupt but it relies on everything potentially in the stack to respect that properly, interrupt does provide a cleaner and more expected means for telling a thread to stop doing what it's doing but it implicitly requires that stuff is actually designed for this, if the JVM is actually stalled, interrupting is going to do nothing.

I think ideally if this is an issue, we'd try to keep the tiered approach we do have now, working from the "safer" methods of just marking dead to going down the extremes to try to allow the servers state to be saved in a safe manner, ideally we'd do a lot more to try to maintain consistency in this "oh shit" states, but, people care more about the servers ability to bail out than they do ensuring that everything goes to plan, hence the brute force approach

2021-04-15 06:50 UTC, bfu4 commented
> Thread.stop was implicitly used afaik due to the various issues with calling Thread.interrupt, ideally we'd interrupt but it relies on everything potentially in the stack to respect that properly, interrupt does provide a cleaner and more expected means for telling a thread to stop doing what it's doing but it implicitly requires that stuff is actually designed for this, if the JVM is actually stalled, interrupting is going to do nothing.
> 
> I think ideally if this is an issue, we'd try to keep the tiered approach we do have now, working from the "safer" methods of just marking dead to going down the extremes to try to allow the servers state to be saved in a safe manner, ideally we'd do a lot more to try to maintain consistency in this "oh shit" states, but, people care more about the servers ability to bail out than they do ensuring that everything goes to plan, hence the brute force approach

Interesting, however there are other options for forcefully exiting the virtual machine that are somehow inherently safer (despite them definitely not sounding as they would come off safer). I understand the approach, although I think eventually the goal would be to move off of something that causes .. less corruption, memory wise. Since in context, this ***is*** the main thread for the server, another approach could be to kill the JVM over the thread, as although the jvm exit call will happen anyways, the overall exit sequence would still miss the deoptimize call (to my knowledge, at least). By all means, it's not of an issue currently, but I do think that invoking something that even Sun would deprecate probably isn't the first approach to go for, and assuming it's still around, should probably overlooked in the future. 

Definitely is a brute force approach, and effective. It depends on the application, and as you said it is something for an "oh shit" occasion, so shouldn't currently be much of a concern. The concerns with staying with a call like `Thread#stop()` are of course the implied ThreadDeath (as I'm sure that looks great in a console.. lol) and [memory] corruption that is very quite possible due the calls within stop0. I think eventually there could be a required change to the invocation and/or a better solution, however if it is what is required and cannot be worked around with the current Java version, then the invocation isn't that much of an issue. Well, until someone finds a way to repeatedly murder their Paper server, but that accountability for even getting to that point should be on them 🤣

2021-04-15 07:04 UTC, Spottedleaf requested changes
Interrupt is not handled in a manner that will actually kill the main thread. So it's not even an option.

2021-04-15 08:04 UTC, electronicboy commented
killing the JVM would just cause even wider data loss than corruption, so that's a nonstarter, there are reasons why we heavily preach about how you should have a backup strategy, because even without this stuff, a crash can cause data corruption.

Paper already tries to stop the server in an ordered manner, by setting the flag to deal with it and allow the server to safely shutdown in the majority of cases, maybe that timeout should be increased a little but, but it already deals with the majority of cases in which an overrun causes watchdog to trip. The deprecation is irrelevant, we know it's not ideal and is not the encouraged method for stopping a thread, but, we've already tried, and failed, to stop the main thread cleanly.

Beyond that, you'd need to run around to modify the server to actually deal with interruption, which given the typical areas where this is a headache, is really not something we're invested in for a mechanism which is far down the chain that nobody really should be hitting. Maybe speak to mojang about trying to handle interruption as they have their own watchdog which tries to shutdown the server, but, this falls back into the issue of plugins also not handling this.

The logic here is intended to allow servers to shutdown in an as-orderly manner as possible, i.e. allowing plugins to flush their tasks and clean up and save any data they may have, stopping the JVM would cause far too much dataloss for servers for it to be a 2nd step to the server not closing out when it's stalled, the risks here far outweigh the wants of server owners.

2021-04-15 08:04 UTC, closed without merging