Allow for Component suggestion tooltips in AsyncTabCompleteEvent
PaperMC/Paper pull request #5504
Opened 2021-04-17 07:26 UTC by jpenilla

2021-04-24 23:40 UTC, JRoy approved these changes

2021-05-06 23:25 UTC, kashike requested changes

2021-05-06 23:25 UTC, kashike commented on Spigot-API-Patches/0295-Allow-for-Component-suggestion-tooltips-in-AsyncTabC.patch
> ++        default @NotNull Stream<? extends ExaminableProperty> examinableProperties() {
Missing `@Override`

2021-05-07 17:20 UTC, kashike approved these changes
Code approved, have not tested.

2021-05-07 23:12 UTC, merged