Add persistence options for mob awareness and AI API
PaperMC/Paper pull request #5505
Opened 2021-04-17 11:27 UTC by froobynooby

Many plugins that use the API for removing awareness/AI from mobs don't want the mobs to be saved in this state. In order to try to prevent this they will try to listen to events such as `EntityRemoveFromWorldEvent` or `ChunkUnloadEvent`, but inevitably some mobs will always slip by (e.g. because of a hard crash, or edge cases people don't think about like slimes splitting). This patch removes uncertainty for plugins by making persistence an option when removing awareness/AI from mobs

2021-04-24 14:15 UTC, electronicboy commented
This should probably just be seperated into two separate state flags, maybe; One to deal with what should be persisted and one to deal with the current, this seems limited and potentially horrible to deal with in a real plugin if you wanna have full control over being able to safely have one mode as the defacto and flip over to the other here and there

2021-04-25 03:09 UTC, froobynooby commented
In that case do you think it might be better to just have a separate, more fleshed out API for disabling AI and awareness in a non-persistent way? Maybe something similar to the vanish API like
```java
void stopAI(Plugin plugin);
void startAI(Plugin plugin);
boolean isAIStopped();
```
since it's already a pretty big pain for plugins to deal with the current API given two plugins might be messing with AI and awareness at the same time

2021-05-01 07:16 UTC, froobynooby commented
I've changed the PR to instead add API for **_pausing_** awareness and AI, as opposed to the existing API which allows you to **_remove_** awareness and AI

2021-06-20 05:30 UTC, froobynooby commented
Rebased for 1.17

2021-08-21 04:11 UTC, Machine-Maker requested changes

2021-08-21 04:11 UTC, Machine-Maker commented on patches/api/0319-Add-API-for-pausing-awareness-and-AI.patch
> ++import org.bukkit.plugin.Plugin;
Don't import here, use the class FQN below.

2021-08-21 04:11 UTC, Machine-Maker commented on patches/api/0319-Add-API-for-pausing-awareness-and-AI.patch
> ++import org.bukkit.plugin.Plugin;
Remove import here as well. same reasoning

2021-08-21 04:11 UTC, Machine-Maker commented on patches/server/0715-Add-API-for-pausing-awareness-and-AI.patch
> ++    }
Instead of adding this method, and then changing all the other calls to isNoAI, just change what the isNoAI method does

2022-10-22 18:25 UTC, Owen1212055 commented
Closing PR, as it seems that this has gone inactive.

Feel free to leave a comment and resolve the requested changes and this can be reopened.

2022-10-22 18:25 UTC, closed without merging