Future proof auto fix y on login
PaperMC/Paper pull request #5555
Opened 2021-04-29 18:43 UTC by HexedHero

Use the world max height to future proof for 1.17+ worlds that have changeable max height. The old +1 to the new location seemed pointless so I removed it.

2021-04-29 18:45 UTC, JRoy requested changes
The first int is 44 above 256 and the second is 1 above, why would set set them equal to the max height?

2021-04-29 18:51 UTC, HexedHero commented
> The first int is 44 above 256 and the second is 1 above, why would set set them equal to the max height?

Thought it'll be best to keep the player within the build height due to other patches working with that such as sending chunks only if the player is in the world height and the +1 seemed pointless like I mentioned since nothing can be there to hurt the player (If they are put at max height such as 256 there are only blocks at 255 and under before it added a block space between the player and maximum block possible)

2021-04-30 06:04 UTC, MiniDigger commented
I mean, this is an really old patch, might be worth checking if the crash is still there?

2021-08-24 02:49 UTC, HexedHero commented
Superseded by #6358

2021-08-24 02:49 UTC, closed without merging