Add Horse Animation API
PaperMC/Paper pull request #5599
Opened 2021-05-09 01:18 UTC by Owen1212055

This allows you to set things like if a horse is on its hind legs, eating, etc. 

Feedback on a better method name for ``isEating`` and ``setEating`` appreciated. But it causes the horse to sort of "bob" its head. It can be seen normally by feeding a horse wheat,

2021-05-09 07:03 UTC, Prof-Bloodstone commented on Spigot-Server-Patches/0696-Horse-Api.patch
> ++    public boolean getHorseFlag(int mask) {return t(mask);} // Paper - OBFHELPER
Obfhelpers should go right above method they are for, not below. We want to conflict when its name or signature changes.
Applies to all other obfhelpers.

2021-05-09 07:03 UTC, Prof-Bloodstone commented on Spigot-Server-Patches/0696-Horse-Api.patch
> ++    public boolean isEating() {return getHorseFlag(64);} // Paper - OBFHELPER
Not sure I'd call these obfhelpers, but I also didn't see how the team handles such additions normally.

2021-05-09 15:44 UTC, Owen1212055 commented
I added newlines infront of paper start (according to https://github.com/PaperMC/Paper/pull/5598/files)? Unless I am misunderstanding.

I also got rid of the helpers that weren't actually needed. However, this makes me directly call get/set horse flag in CraftAbstractHorse which I would like feedback on.

2021-05-12 12:59 UTC, electronicboy commented
magic values need diff busters (i.e. a comment or something to bust the merge if those values change)

2021-05-12 13:11 UTC, Owen1212055 commented
> magic values need diff busters (i.e. a comment or something to bust the merge if those values change)

“Bust” the merge? Sorry, but I don’t really understand what you mean here. What should I put in this comment?

2021-05-12 14:16 UTC, Proximyst requested changes

2021-05-12 14:16 UTC, Proximyst commented on Spigot-Server-Patches/0696-Horse-Api.patch
> ++        getHandle().setHorseFlag(64, eating);
Modify the lines that specify these integers to use static fields with them instead so we can reuse here.

2021-06-01 14:54 UTC, Proximyst approved these changes
Not precisely what I meant, but this looks great nonetheless. Good job and thanks for the contribution!

2021-06-01 14:54 UTC, Proximyst commented on Spigot-Server-Patches/0696-Horse-Api.patch
> ++    public boolean isRearing() {return fa();} // Paper - OBFHELPER
Obfhelpers go on top.

2021-06-01 15:30 UTC, Owen1212055 commented
![image](https://user-images.githubusercontent.com/23108066/120350117-aeff0e80-c2cc-11eb-8829-cad6a5c51123.png)
Should I instead call setHorseFlag/getHorseFlag in the craftabstracthorse class instead for these methods?

2021-07-09 10:32 UTC, kennytv commented
Can you update this to 1.17.1? All the previous issues should be gone as well with obfhelpers no longer being required here. 😛

2021-07-10 00:21 UTC, Owen1212055 commented
Huh, I guess I forgot about this one when updating my pull requests. Going to merge this into my generic "entity behavior patch".

2021-07-10 02:35 UTC, Owen1212055 commented
Okay, now this has been updated. As a result however, this now requires https://github.com/PaperMC/Paper/pull/5744.

2021-07-11 19:32 UTC, Machine-Maker approved these changes
Looks fine. Another note that this is blocked by #5744

2021-08-29 19:43 UTC, Owen1212055 commented
Rebased and ready! No longer blocked

2021-09-18 21:07 UTC, jpenilla commented
Setting rearing to false doesn't seem to effectively stop the animation after previously having set it to true. If you look in the `stand` method, you can see vanilla sets the `standCounter` which in the tick method is used to control the standing animation. Maybe it's better to have a `stand()` or `rear()` method which calls `stand()`?

2021-10-07 00:48 UTC, Owen1212055 commented
> Setting rearing to false doesn't seem to effectively stop the animation after previously having set it to true. If you look in the `stand` method, you can see vanilla sets the `standCounter` which in the tick method is used to control the standing animation. Maybe it's better to have a `stand()` or `rear()` method which calls `stand()`? Either that, or setting it to false should be fixed.

 I can't confirm this, testing with a horse my current code seems to work fine. Can you show me what you did?
```java
 if (entity instanceof AbstractHorse horse) {
       horse.setRearing(!horse.isRearing());
 }
```

2021-10-07 04:25 UTC, jpenilla commented
I ran the same test I did before and now I'm getting different results than before... not sure what happened there. Rearing and eating both seem to work mostly fine, as does eating grass, however eating grass will disable itself 50 ticks after you enable it due to logic hardcoded in the aiStep method of AbstractHorse.

That's really my main reservation here compared to the cat methods. In the example of the cat, the methods we exposed are only called from goals, so by removing existing goals and adding your own the behavior could be controlled predictably. In the case of the horse however, the hardcoded logic in the tick method is going to be messing with these even if you remove all goals, which might be confusing when trying to use the API.

I don't really see a way around this, and I don't think it should necessarily be a merge blocker, just something to think about in how this would be slightly more caveated than some of the other additional behavior APIs.

2021-10-07 04:43 UTC, jpenilla requested changes

2021-10-07 04:43 UTC, jpenilla commented on patches/server/0712-Missing-Entity-Behavior-API.patch
> ++    // Paper start - Horse API
please use explicit `this.` for accessing instance fields/methods

2021-10-07 04:43 UTC, jpenilla commented on patches/server/0712-Missing-Entity-Behavior-API.patch
> ++    @Override
personally I would just add public methods `setStanding(boolean)`, `isMouthOpen()`, and `setMouthOpen(boolean)` in `net.minecraft.world.entity.animal.hosrse.AbstractHorse` and call those here instead of using ATs, but I guess either way is fine.

2021-10-07 04:43 UTC, jpenilla commented on build-data/paper.at
> +# Missing Entity API: Horse
If you decide to keep the ATs, please remove this comment as well as the line breaks between entries for the same patch. Generally we add a comment with the patch name and list out the ATs below. (Meaning `# Missing Entity API` should also be changed to `# Missing Entity Behavior API`)

2021-10-07 10:31 UTC, Owen1212055 commented
> I ran the same test I did before and now I'm getting different results than before... not sure what happened there. Rearing and eating both seem to work mostly fine, as does eating grass, however eating grass will disable itself 50 ticks after you enable it due to logic hardcoded in the aiStep method of AbstractHorse.
> 
> 
> 
> That's really my main reservation here compared to the cat methods. In the example of the cat, the methods we exposed are only called from goals, so by removing existing goals and adding your own the behavior could be controlled predictably. In the case of the horse however, the hardcoded logic in the tick method is going to be messing with these even if you remove all goals, which might be confusing when trying to use the API.
> 
> 
> 
> I don't really see a way around this, and I don't think it should necessarily be a merge blocker, just something to think about in how this would be slightly more caveated than some of the other additional behavior APIs.

Yea so, it may be optimal to add some kind of method but I'm not sure. Currently methods like in the fox setsleeping currently resets each tick. I get around this by manually setting it in a mob goal each tick. However, we could add some kind of override that'll cause the tick method to not change that or we could just include in the javadocs it automatically stops.

2021-10-15 23:19 UTC, jpenilla commented
Given there's already methods with similar caveats this is probably fine, maybe add something to the docs (for this new method and the aforementioned fox one) if you feel it's appropriate, not sure myself, as it's kind of an implementation detail (maybe someone else has some input?).

Like I said I don't think it should be a merge blocker, so this would get my approval after requested changes are addressed.

2021-10-21 01:09 UTC, merged