Prevent adding or removing goals while goal selector is ticking
PaperMC/Paper pull request #5629
Opened 2021-05-13 08:58 UTC by froobynooby

Throws an IllegalStateException when attempting to add or remove goals while the goal selector is ticking. This prevents a CME further down the line in the entity's tick and provides a more useful stack trace to plugin devs

Refer #5581 for more info

2021-05-13 09:42 UTC, Proximyst requested changes
I'm hesitant to doing this at all, really. We should not need to add protection against every single thing that's not documented as safe.

Either way, needs to throw a new API exception that extends from IllegalState.

2021-05-13 10:23 UTC, froobynooby commented
Is it necessary to use a new API exception if the approach being taken is to keep it undocumented (i.e. not acknowledge it in the API)? The PR is only really causing an inevitable exception to be thrown a bit earlier down the line in a more convenient location

2021-05-14 21:26 UTC, electronicboy commented
Don't think it needs an API exception, only cases where the exception should be doc'd and explicitly caught should it be given an API exception;
I question if a COW would be a better option for this kinda thing, I don't think that these goals are mutated enough at runtime to cause any massive concerns, and would allow for the type of behavior originally wanted

2021-05-16 06:05 UTC, froobynooby commented
How about something like https://gist.github.com/froobynooby/7cbb6b9d2c8544b26fcbdee40b1da56f?

It keeps an immutable copy of all goals that is invalidated (and recreated when next requested) if the goal set is modified. This preserves the ability to remove items in the set Iterator, which some plugins use

2021-05-16 07:34 UTC, KennyTV commented
That is another unnecessarily complex "fix" for something you plain and simple shouldn't be doing in the first place and where you have plenty of better opportunities to do so

2021-05-16 08:04 UTC, froobynooby commented
I don't think it's fair to say you shouldn't be using the goal API in these situations. There's no good indication of where you "should" and "should not" use the API (see examples in my comment here https://github.com/PaperMC/Paper/issues/5581#issuecomment-839646780).

I am happy to simply schedule changes for the next tick if it is decided to not fix the underlying issue - but even then I still feel we should be throwing an exception earlier on so that plugin devs know which line of code is causing the issue. At current you have to look through the server's code to check which events may be thrown in pathfinder goals

2021-05-16 08:16 UTC, KennyTV commented
It's fairly easy to figure out that targetting an entity is a goal during execution, but eitherway, I do see value in having a small warning in docs/the exception throw you've added

2021-08-26 13:53 UTC, closed without merging