Add an API to interface with Resource Packs (aka Data Packs)
PaperMC/Paper pull request #5653
Opened 2021-05-16 14:40 UTC by ConnorLinfoot

Adds an API to be able to interface with the resource packs on the server (also known as data packs) including being able to get a list of packs and if they are enabled, and be able to enable or disable them.

2021-05-16 15:01 UTC, KennyTV requested changes, later dismissed
Needs some obfuscation helpers, see https://github.com/PaperMC/Paper/blob/master/CONTRIBUTING.md#obfuscation-helpers

2021-05-16 15:01 UTC, kennytv commented on Spigot-Server-Patches/0731-Add-basic-ResourcePack-DataPack-API.patch
> ++        return repository.c().stream().map(loader -> new PaperResourcePack(loader, enabledPacks.contains(loader))).collect(Collectors.toList());
Obfhelpers

2021-05-16 15:01 UTC, kennytv commented on Spigot-Server-Patches/0731-Add-basic-ResourcePack-DataPack-API.patch
> ++        return repository.e().stream().map(loader -> new PaperResourcePack(loader, true)).collect(Collectors.toList());
Obfhelper

2021-05-16 15:01 UTC, kennytv commented on Spigot-Server-Patches/0731-Add-basic-ResourcePack-DataPack-API.patch
> ++        this.compatibility = ResourcePackCompatibility.valueOf(loader.c().name());
Obfhelpers

2021-05-16 15:01 UTC, KennyTV commented on Spigot-Server-Patches/0731-Add-basic-ResourcePack-DataPack-API.patch
> ++        List<String> enabledKeys = server.getResourcePackRepository().e().stream().map(ResourcePackLoader::e).collect(Collectors.toList());
Obfhelpers

2021-05-16 15:09 UTC, Machine-Maker requested changes

2021-05-16 15:09 UTC, Machine-Maker commented on Spigot-API-Patches/0300-Add-basic-ResourcePack-DataPack-API.patch
> ++public enum ResourcePackCompatibility {
I'd probably throw this enum inside the ResourcePack interface, kinda small and specific for its own file.

2021-05-16 15:35 UTC, ConnorLinfoot commented
That should be all the Obfhelpers added and the compatibility enum change :)

2021-05-16 15:39 UTC, MiniDigger commented
looks good to me, only concern I have is if we really wanna name this resource pack, as ppl kinda expect this to be called data pack? I know that the mappings use the resource name, but mojang doesn't, they just call it pack in their code.
there is one other PR in this area, https://github.com/PaperMC/Paper/pull/5021, that also uses the datapack name.
like, just that fact that you felt like you needed to add a "aka data packs" to the title shows that the resource pack name is misleading.

2021-05-16 15:41 UTC, Machine-Maker commented
Yeah, I would call them datapacks, (idk about capitalization). Wiki uses datapacks, and resource packs already mean something else (the packs clients use to change textures, sounds, etc).

2021-05-16 15:41 UTC, ConnorLinfoot commented
Yeah I agree on the naming being better as a data pack api rather than developers being confused and maybe even missing the existence due to the bad naming

2021-05-16 15:43 UTC, JRoy requested changes, later dismissed

2021-05-16 15:43 UTC, JRoy commented on Spigot-API-Patches/0300-Add-basic-ResourcePack-DataPack-API.patch
> ++    public static ResourcePackManager getResourcePackManager() {
please fully qualify this and remove the import

2021-05-16 15:43 UTC, JRoy commented on Spigot-API-Patches/0300-Add-basic-ResourcePack-DataPack-API.patch
> ++    ResourcePackManager getResourcePackManager();
fully qualify

2021-05-16 15:57 UTC, Proximyst approved these changes

2021-05-16 15:58 UTC, ConnorLinfoot commented
Resolved the above issue and went ahead and renamed it to be datapack

2021-05-16 16:01 UTC, JRoy requested changes

2021-05-16 16:01 UTC, JRoy commented on Spigot-API-Patches/0300-Add-basic-Datapack-API.patch
> ++
:P
```suggestion
```

2021-05-16 16:01 UTC, JRoy commented on Spigot-API-Patches/0300-Add-basic-Datapack-API.patch
> ++
```suggestion
```

2021-05-16 16:05 UTC, JRoy commented on Spigot-API-Patches/0300-Add-basic-Datapack-API.patch
> + import org.bukkit.block.data.BlockData;
```suggestion
```

2021-05-16 16:05 UTC, JRoy commented on Spigot-API-Patches/0300-Add-basic-Datapack-API.patch
> + import org.bukkit.block.data.BlockData;
```suggestion
```

2021-05-16 16:05 UTC, JRoy approved these changes

2021-05-16 16:07 UTC, JRoy commented
i didn't expect you to actually commit the code suggestions lmao, the patch may fail to apply now?

2021-05-16 16:10 UTC, ConnorLinfoot commented
> My bad, I didn't expect you to actually commit the code suggestions on github lmao, the patch may fail to apply now?

Seems to be fine :)

2021-05-16 19:57 UTC, MiniDigger approved these changes

2021-05-16 20:09 UTC, merged

2021-05-16 20:09 UTC, JRoy commented
Thanks for the contribution :)

2021-05-17 06:46 UTC, KennyTV commented
In case you or someone else is already depending on this; some jd and package "resource" references will be renamed with https://github.com/PaperMC/Paper/pull/5662