add vs code files to spigot .gitignore
PaperMC/Paper pull request #5663
Opened 2021-05-17 16:17 UTC by MagicCheese1

Visual Studio Code generates a .vscode directory and a .factorypath file. They are now ignored in the Paper-API and Paper-Server directories.

2021-05-17 17:06 UTC, MiniDigger commented
uuuh, I would consider that to be part of your global gitignore.
also no clue why anyone would wanna use a text editor to work on paper?

2021-05-17 17:16 UTC, MagicCheese1 commented
Well, text editors are getting more and more popular for everything.

2021-05-17 20:30 UTC, TheFruxz commented
_getting_, not _is_. Java is not really working well on VS-Code. Sure, it's great, that it works a little bit, but thats far from perfect

2021-05-17 22:26 UTC, FranKusmiruk commented
> _getting_, not _is_. Java is not really working well on VS-Code. Sure, it's great, that it works a little bit, but thats far from perfect. I think, if it gets more durable, stable and flexible in working with "deep code" like Java, Kotlin and becomes better in use of Maven, Gradle & Kotlin-Gradle-DSL, that something like that can be implemented. But as I know it, text editors like VS Code are currently so rare in software development with Java/Kotlin that it would be useless, because the few who actually use it should have it set in their local global .gitignore itself, because than their ran into issues like this everyday.

This is actually false, Microsoft has been pushing VSCode for Java lately and while the feature-set may not be as complete as IntelliJ it does provide a pretty usable set of features for any kind of non-frontend workflow from what I've seen (you can take a look at https://devblogs.microsoft.com/java/ where they post updates of the VSCode for Java environment). Besides, there's really no harm in having these kind of IDE or text editor files out of the way in the gitignore, that's literally what it is for.

Of course, one may argue that you can't support every kind of workflow that people may try to modify your project on but considering VSCode's popularity and growing support for Java-based environments, I think it is fair to make the exception on this case.

2021-05-17 22:28 UTC, electronicboy commented on Spigot-Server-Patches/0733-Add-vs-code-files-to-.gitignore.patch
> +From 0000000000000000000000000000000000000000 Mon Sep 17 00:00:00 2001
Stuff like this should be in an earlier patch, maybe the pom changes patch unless there was a more misc one

2021-05-17 22:30 UTC, electronicboy commented on Spigot-API-Patches/0301-Add-vs-code-files-to-.gitignore.patch
> ++/world
no idea why this needs to be in there, use `./paper t` instead of starting in the root of the project

2021-05-17 22:31 UTC, electronicboy commented
how well vs code does or does not work for modifying paper is irrelevant, if people wanna use software which works for them that is on them, I'd much rather have this stuff in the gitignore early rather than having to deal with people accidentally crudding up the workspace with IDE files

2021-06-22 20:27 UTC, KennyTV commented on Spigot-Server-Patches/0733-Add-vs-code-files-to-.gitignore.patch
> ++/src/main/resources/lang
Don't delete the line break

2021-07-18 14:04 UTC, MagicCheese1 commented
I added the changes to the last patch that changed the .gitignore.
Also fixed the line breaks.

2021-07-22 19:32 UTC, electronicboy approved these changes

2021-07-23 21:57 UTC, yannicklamprecht requested changes
Add the ~~ignorance~~ entries to the root projects .gitignore as well.

2021-07-24 11:37 UTC, MagicCheese1 commented
> Add the ~ignorance~ entries to the root projects .gitignore as well.

The root projects .gitignore already has .vscode.
Vs code does not generate .factorypath in the root project.

2021-08-07 00:27 UTC, merged