List all missing hard depends not just first
PaperMC/Paper pull request #5673
Opened 2021-05-18 17:39 UTC by Machine-Maker

Closes #5666

Throw error with all missing depends instead of just the first one the plugin load happened to check

2021-05-18 18:01 UTC, Proximyst requested changes

2021-05-18 18:01 UTC, Proximyst commented on Spigot-API-Patches/0304-List-all-missing-hard-depends-not-just-first.patch
> ++        Set<String> missingHardDependencies = new HashSet<>(); // Paper - list all missing hard depends
Set capacity to size of hard depends.

2021-05-20 09:43 UTC, lilSp00n commented
Thanks for the quick PR Machine Maker 👍

2021-05-21 05:24 UTC, Proximyst approved these changes

2021-05-21 05:24 UTC, kashike approved these changes

2021-05-21 05:30 UTC, jpenilla approved these changes

2021-05-21 05:33 UTC, merged

2021-05-21 05:33 UTC, kashike approved these changes