Worldgen Feature API
PaperMC/Paper pull request #5727
Opened 2021-05-26 05:49 UTC by dfsek

This PR adds API that allows custom generators to gain access to the "feature" stage of world generation (Bukkit calls this stage "decoration" internally).

Closes #5522 

As described in #5522, `BlockPopulator` has a host of issues, the big one being that it is *very* prone to chunk cascading. There is no convenient way around this, you either need to create [terrible management classes](https://github.com/PolyhedralDev/Terra/blob/master/platforms/bukkit/src/main/java/com/dfsek/terra/bukkit/population/PopulationManager.java), or go down the rabbit hole of NMS and [extend the Vanilla chunk generator](https://github.com/Hex27/TerraformGenerator/blob/master/implementation/v1_16_R3/src/main/java/org/terraform/v1_16_R3/NMSChunkGenerator.java). Supported API for accessing this generation stage would be massively beneficial to custom generators on Paper.

This PR creates and implements a new interface, `io.papermc.paper.world.ProtoWorld`. This new interface is required because `addDecorations` (the internal method this API delegates from) accepts only a `RegionLimitedWorldAccess`, and reading from/writing to the `ServerWorld` during chunk generation causes a deadlock. `ProtoWorld` *does*, however, contain a `getWorld` method for convenience, though warnings about reading/writing are present in the documentation. The `ProtoWorld` API also avoids use of `org.bukkit.Location`, since Location requires a World, and we want to discourage use of the World whenever we can.

This new interface is used in `org.bukkit.generator.ChunkGenerator`, which now contains a `generateDecorations` method that accepts a `ProtoWorld`. This new method has a default implementation as to maintain compatibility with existing generators. It is invoked during the feature generation phase of world generation, allowing custom generators to decorate their worlds without worrying about chunk cascading.

2021-05-26 06:09 UTC, dfsek commented
Minimal test generator that tests all API added by this PR available here: https://gist.github.com/dfsek/4b79e12f19fd3574a32701871a3aa8ed

2021-05-27 13:41 UTC, electronicboy approved these changes
generally lgtm be a few trivial things

2021-05-27 13:41 UTC, electronicboy commented on Spigot-Server-Patches/0747-Add-feature-access-to-custom-ChunkGenerators.patch
> ++            getDelegate().getFluidTickList().a(position, ((BlockFluids) ((CraftBlockData) data).getState().getBlock()).d(((CraftBlockData) data).getState()).getType(), 0);
OBFHELPERS

2021-05-27 13:41 UTC, electronicboy commented on Spigot-Server-Patches/0747-Add-feature-access-to-custom-ChunkGenerators.patch
> ++    public int getCenterX() { return a(); } // Paper - obfhelper
obfhelpers should be directly above the method they're "helping", that way if the method name changes it conflicts

2021-05-28 08:30 UTC, jpenilla requested changes
Looks good to me, tested using the provided example and seems to work well:

![image](https://user-images.githubusercontent.com/11360596/119954623-06f7e700-bf54-11eb-9268-2d07cd126096.png)

2021-05-28 08:30 UTC, jpenilla commented on Spigot-Server-Patches/0747-Add-feature-access-to-custom-ChunkGenerators.patch
> ++
These blank lines between obfhelpers and the method they are for should be removed.

2021-05-29 15:22 UTC, Spottedleaf commented on Spigot-Server-Patches/0747-Add-feature-access-to-custom-ChunkGenerators.patch
> ++    private final WeakReference<RegionLimitedWorldAccess> world;
there's no point in this being a weakref if you're clearing it immediately after use

2021-05-29 15:31 UTC, Spottedleaf commented on Spigot-Server-Patches/0747-Add-feature-access-to-custom-ChunkGenerators.patch
> ++        if(updateLiquids && ((CraftBlockData) data).getState().getBlock() instanceof BlockFluids) {
there are many reasons people will want to queue updates, it should not be restricted to just liquids (and this is done incorrectly anyways, doesn't account for waterloggable). Should add different dedicated functions that let people queue fluid or block updates for positions.

You will be able to use the getFluid method from RWLA to get the fluid state for a position.

2021-06-20 03:37 UTC, dfsek commented
Rebased ro 1.17. Ready for review/merge.

2021-06-20 04:48 UTC, jpenilla approved these changes
![2021-06-19_21 34 03](https://user-images.githubusercontent.com/11360596/122662277-825d4a80-d146-11eb-8a15-9e1f0775e50d.png)
lgtm
:shipit:

2021-06-20 04:48 UTC, merged

2021-06-23 09:55 UTC, Corenb commented
Since this patch was merged to 1.17, some datapacks crash paper. They works fine on Paper build #6 but no longer with this patch...

Here the crash report with Paper build #40 and [William Wythers Overhauled Overworld](https://www.planetminecraft.com/data-pack/william-wythers-overhauled-overworld/) datapack :
`[10:06:51] [Worker-Main-2/ERROR]: Couldn't load tag minecraft:tick as it is missing following references: dnl:main (from dungeon_now_loading),custom:main (from dungeon_now_loading)
[10:06:51] [Worker-Main-2/ERROR]: Couldn't load tag minecraft:load as it is missing following references: rng:init (from dungeon_now_loading),dnl:init (from dungeon_now_loading),custom:init (from dungeon_now_loading)
[10:06:52] [Server thread/INFO]: Starting minecraft server version 1.17
[10:06:52] [Server thread/INFO]: Loading properties
[10:06:52] [Server thread/INFO]: This server is running Paper version git-Paper-"a7cddc4" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)
[10:06:52] [Server thread/INFO]: Debug logging is disabled
[10:06:52] [Server thread/INFO]: Server Ping Player Sample Count: 12
[10:06:52] [Server thread/INFO]: Using 4 threads for Netty based IO
[10:06:52] [Server thread/INFO]: Using Aikar's Alternative Luck Formula to apply Luck attribute to all loot pool calculations. See https://luckformula.emc.gs
[10:06:52] [Server thread/INFO]: Default game type: SURVIVAL
[10:06:52] [Server thread/INFO]: Generating keypair
[10:06:52] [Server thread/INFO]: Starting Minecraft server on 0.0.0.0:42580
[10:06:52] [Server thread/INFO]: Using epoll channel type
[10:06:52] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[10:06:52] [Server thread/INFO]: Preparing level "vanilla"
[10:06:53] [Server thread/ERROR]: Feature: Not a JSON object: "wythers:generic/patch_stones_east_3"; Not a JSON object: "wythers:generic/patch_stones_south_2"; Not a JSON object: "minecraft:vines"; Not a JSON object: "minecraft:patch_melon"; Not a JSON object: "minecraft:spring_water"; Not a JSON object: "wythers:desert/oasis_patch_sugar_cane"; Not a JSON object: "minecraft:red_mushroom_normal"; Not a JSON object: "minecraft:brown_mushroom_normal"; Not a JSON object: "minecraft:red_mushroom_swamp"; Not a JSON object: "minecraft:brown_mushroom_swamp"; Not a JSON object: "minecraft:patch_waterlilly"; Not a JSON object: "minecraft:seagrass_swamp"; Not a JSON object: "minecraft:seagrass_swamp"; Not a JSON object: "minecraft:patch_grass_jungle"; Not a JSON object: "wythers:generic/flower_lily_of_the_valley"; Not a JSON object: "wythers:desert/oasis_reeds"; Not a JSON object: "wythers:desert/oasis_vegetation"; Not a JSON object: "minecraft:glow_lichen"
[10:06:53] [Server thread/ERROR]: Feature: Not a JSON object: "minecraft:seagrass_swamp"; Not a JSON object: "minecraft:vines"; Not a JSON object: "minecraft:patch_melon"; Not a JSON object: "minecraft:spring_water"; Not a JSON object: "wythers:desert/oasis_patch_sugar_cane"; Not a JSON object: "minecraft:red_mushroom_normal"; Not a JSON object: "minecraft:brown_mushroom_normal"; Not a JSON object: "minecraft:patch_waterlilly"; Not a JSON object: "minecraft:patch_grass_jungle"; Not a JSON object: "wythers:generic/flower_lily_of_the_valley"; Not a JSON object: "wythers:jungle/edge_vegetation"; Not a JSON object: "minecraft:glow_lichen"
[10:06:53] [Server thread/ERROR]: Encountered an unexpected exception
com.google.gson.JsonParseException: Error loading registry data: Not a JSON object: null
	at net.minecraft.core.RegistryAccess.lambda$readRegistry$6(RegistryAccess.java:221) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.minecraft.core.RegistryAccess.a(RegistryAccess.java:221) ~[?:?]
	at net.minecraft.core.RegistryAccess.load(RegistryAccess.java:212) ~[?:?]
	at net.minecraft.resources.RegistryReadOps.createAndLoad(RegistryReadOps.java:57) ~[patched_1.17.jar:git-Paper-"a7cddc4"]
	at net.minecraft.resources.RegistryReadOps.createAndLoad(RegistryReadOps.java:51) ~[patched_1.17.jar:git-Paper-"a7cddc4"]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:458) ~[patched_1.17.jar:git-Paper-"a7cddc4"]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:304) ~[patched_1.17.jar:git-Paper-"a7cddc4"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1118) ~[patched_1.17.jar:git-Paper-"a7cddc4"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-"a7cddc4"]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[10:06:53] [Server thread/ERROR]: This crash report has been saved to: /home/container/./crash-reports/crash-2021-06-23_10.06.53-server.txt`
[crash-2021-06-23_10.06.53-server.txt](https://github.com/PaperMC/Paper/files/6700839/crash-2021-06-23_10.06.53-server.txt)