Fix EntityLoadCrossbowEvent Sync Issue
PaperMC/Paper pull request #5739
Opened 2021-05-28 17:17 UTC by LemonCaramel

Fixes the problem that items are not synchronized when the EntityLoadCrossbowEvent is canceled.

--------

normal (apply PR)
![Normal](https://user-images.githubusercontent.com/45729082/120019524-886a7a80-c023-11eb-97bc-5e321b2d77ef.gif)

abnormal
![Abnormal](https://user-images.githubusercontent.com/45729082/120019593-9ae4b400-c023-11eb-9c79-699a5a17880c.gif)
( + check the crossbow state and amount of arrows )

2021-05-28 17:20 UTC, JRoy requested changes, later dismissed
Remove the comment from EntityLoadCrossbowEvent#setCancelled telling being to call updateInventory

2021-05-29 23:36 UTC, StealWonders commented
Should canceling sync the inventory? There are numerous other events that don't (or used to) sync. Which way is correct?

2021-05-29 23:38 UTC, electronicboy commented
Ideally, yes, calling updateInventory is a gigantic hack/copout, however, but, getting the context around of when to resend properly is often a gigantic headache

2021-07-14 17:54 UTC, Machine-Maker commented
There a reason this was closed? I'm pretty sure the issue still exists.

2021-07-14 18:11 UTC, LemonCaramel commented
This PR was closed while renaming the branch. 😢  (#5779 same)

I will reopen soon with the updated 1.17 patch

2021-07-14 19:50 UTC, LemonCaramel commented
This PR has been updated to 1.17, and it works fine.
![1_17](https://user-images.githubusercontent.com/45729082/125684002-fd82dc6f-fa49-48c5-b69b-04f45c24af59.gif)

2021-09-13 07:00 UTC, LemonCaramel commented
no :cry:

2021-09-13 07:13 UTC, electronicboy approved these changes
not fond of the updateInventory call in general, defo on my hard-fork goals to improve the behavior behind some of this stuff, but, given that I had to work around this in my own plugin, it is annoying

2021-11-12 07:55 UTC, LemonCaramel commented
hello bot

2021-12-31 06:37 UTC, electronicboy approved these changes

2021-12-31 06:51 UTC, Machine-Maker approved these changes

2021-12-31 06:54 UTC, merged