Add additional fox behavior API
PaperMC/Paper pull request #5743
Opened 2021-05-29 01:09 UTC by Owen1212055

Certain behaviors have additional animations as well.
So cute!!!
![image](https://user-images.githubusercontent.com/23108066/120051574-2a23a480-bfef-11eb-8ac6-cbd7a2e1812f.png)
Fox#setHeadTilted

![image](https://user-images.githubusercontent.com/23108066/120051896-9fdc4000-bff0-11eb-8d47-aa6de4a97688.png)
Fox#setLeaping

2021-05-29 01:10 UTC, electronicboy approved these changes

2021-05-29 01:13 UTC, Machine-Maker commented
You seem to have not committed your OBFHELPERs

2021-05-29 01:14 UTC, Owen1212055 commented
> You seem to have not committed your OBFHELPERs cause some of those methods don't exist on EntityFox

Ahhh... good catch there.

2021-05-29 01:32 UTC, Owen1212055 commented
Should be good now

2021-05-30 12:00 UTC, KennyTV requested changes
... and so on

2021-05-30 12:00 UTC, kennytv commented on Spigot-Server-Patches/0739-Fox-API.patch
> ++    public boolean isWalking() {return eN();} // Paper - OBFHELPER
```suggestion
+    public boolean isFaceplanted() {return eN();} // Paper - OBFHELPER
```

2021-05-30 12:00 UTC, kennytv commented on Spigot-Server-Patches/0739-Fox-API.patch
> ++    public void setWalking(boolean walking) {x(walking);} // Paper - OBFHELPER
```suggestion
+    public void setFaceplanted(boolean faceplanted) {x(faceplanted);} // Paper - OBFHELPER
```

2021-05-30 12:00 UTC, kennytv commented on Spigot-Server-Patches/0739-Fox-API.patch
> ++    public boolean isAngry() {return fb();} // Paper - OBFHELPER
```suggestion
+    public boolean isDefending() {return fb();} // Paper - OBFHELPER
```

2021-05-30 12:00 UTC, kennytv commented on Spigot-Server-Patches/0739-Fox-API.patch
> ++    public void setAngry(boolean angry) {y(angry);} // Paper - OBFHELPER
```suggestion
+    public void setDefending(boolean defending) {y(defending);} // Paper - OBFHELPER
```

2021-05-30 12:00 UTC, kennytv commented on Spigot-Server-Patches/0739-Fox-API.patch
> ++    public void setHeadTilted(boolean tilted) {w(tilted);} // Paper - OBFHELPER
```suggestion
+    public void setInterested(boolean interested) {w(interested);} // Paper - OBFHELPER
```

2021-05-30 12:00 UTC, KennyTV commented on Spigot-Server-Patches/0739-Fox-API.patch
> ++    public boolean isHeadTilted() {return eW();} // Paper - OBFHELPER
```suggestion
+    public boolean isInterested() {return eW();} // Paper - OBFHELPER
```

2021-05-30 18:01 UTC, Owen1212055 commented
Combined: See https://github.com/PaperMC/Paper/pull/5744#issuecomment-850769784

2021-06-22 04:01 UTC, Owen1212055 commented
Updated to 1.17

2021-06-22 07:36 UTC, KennyTV approved these changes
Thank you

2021-06-22 07:44 UTC, merged