Force NBT loading when from a command
PaperMC/Paper pull request #5751
Opened 2021-05-30 00:14 UTC by Machine-Maker

Discovered this was an issue for datapacks that used lines on signs to store data, the 2048 char limit broke the shulker preview datapack. This just allows loading tile entity nbt to bypass those limits if its the result of a command.

There are probably more places that could use this, I just don't know what they are.

2021-05-30 00:18 UTC, electronicboy requested changes

2021-05-30 00:18 UTC, electronicboy commented on Spigot-Server-Patches/0752-Force-NBT-loading-when-from-a-command.patch
> ++        this.getTileEntity().forceLoad = true; // Paper
store the current value instead of forcefully setting to false

2021-05-30 00:44 UTC, Machine-Maker commented
Reworked it when I realized the default should be to allow anything except when placed down as an item.

2021-05-30 02:16 UTC, electronicboy approved these changes

2021-08-07 00:43 UTC, Machine-Maker commented
Rebased for 1.17.1

2021-12-22 07:25 UTC, Machine-Maker commented
Rebased for 1.18.1

2022-07-10 19:07 UTC, Machine-Maker commented
Rebased for 1.19

2023-05-18 13:02 UTC, Owen1212055 commented
I honestly think that these limits should be toned down, as most of them are outdated (doesn't apply to filtered text, etc) and in general don't make much sense anymore to have.

2024-07-17 00:02 UTC, Machine-Maker commented
The issue this was created to address doesn't exist anymore as upstream removed their arbitrary limit on sign text length (2048).

2024-07-17 00:02 UTC, closed without merging