Improve Riptide API
PaperMC/Paper pull request #5753
Opened 2021-05-30 03:39 UTC by Machine-Maker

Turns out the animation part of the event *is* controlled by the server, the jump part isn't.

You can have a lot of fun with this since its on LivingEntity.

https://user-images.githubusercontent.com/15055071/120091192-ab496d00-c0bd-11eb-8e2d-4acb3dcd9241.mp4

https://user-images.githubusercontent.com/15055071/120091206-c61be180-c0bd-11eb-9625-b06d976dfc6b.mp4

2021-05-30 03:42 UTC, electronicboy commented on Spigot-Server-Patches/0752-Improve-Riptide-API.patch
> ++    public void stopRiptiding() {
OBF

2021-05-30 03:55 UTC, Machine-Maker commented on Spigot-Server-Patches/0752-Improve-Riptide-API.patch
> ++    public void stopRiptiding() {
done

2021-06-02 13:28 UTC, Elierrr approved these changes

2021-06-05 08:21 UTC, electronicboy approved these changes

2021-06-05 09:22 UTC, MiniDigger approved these changes
A bit weird that we have to do this so high up in the inheritance tree even tho not many entities actually support this, but I don't know a much nicer solution either. Lgtm

2021-06-05 20:57 UTC, Machine-Maker commented
Actually, most of the entities I did try worked fine @MiniDigger

2021-06-06 09:44 UTC, MiniDigger commented
ah ok, then the javadoc did threw me up, all good then

2021-06-08 12:05 UTC, KennyTV requested changes
You didn't pass the animation ticks into the event constructor, so I fixed that, something (your own animation when using a trident with riptide) is still bork tho. Plz fix

2025-03-23 19:15 UTC, closed without merging