Prevent loading out of bounds chunk sections
PaperMC/Paper pull request #5897
Opened 2021-06-20 07:03 UTC by jpenilla

Prevents world corruption when people get the bright idea of loading worlds generated with the Caves and Cliffs preview datapack without the datapack installed

2021-06-20 07:41 UTC, KennyTV requested changes

2021-06-20 07:41 UTC, KennyTV commented on patches/server/0715-Prevent-loading-out-of-bounds-chunk-sections.patch
> ++                    if (!JUST_CORRUPT_IT_2 && sectionIndex < 0 || sectionIndex >= sectionsCount) {
```suggestion
+                    if (!JUST_CORRUPT_IT_2 && (sectionIndex < 0 || sectionIndex >= sectionsCount)) {
```

2021-06-22 19:40 UTC, Machine-Maker approved these changes

2021-06-22 20:19 UTC, MiniDigger approved these changes

2022-10-22 23:55 UTC, Owen1212055 commented
![image](https://user-images.githubusercontent.com/23108066/197366636-6e1ddcb4-4aa7-43f1-807c-73ce05e8a736.png)
Seems like there has been a check added as of 1.19.2.

Do we want to still warn the player when this happens to their world?
Or, should this just be closed?

2022-10-23 00:06 UTC, closed without merging