Don't apply cramming damage to players
PaperMC/Paper pull request #5903
Opened 2021-06-20 16:00 UTC by Phoenix616

It does not make a lot of sense to damage players if they get crammed, especially as the usecase of teleporting lots of players to the same location isn't too uncommon and killing all those players isn't really what one would expect to happen. (And I have seen this happen before, it could even result in a server crash when the items of 100 players get dropped...)

For those who really want it a config option is provided.

2021-06-20 16:05 UTC, Proximyst requested changes, later dismissed
Looks fine

2021-06-20 16:05 UTC, Proximyst commented on patches/server/0716-Don-t-apply-cramming-damage-to-players.patch
> ++    public boolean allowPlayerCrammingDamage = false;
```suggestion
+    public boolean allowPlayerCrammingDamage = true;
```

2021-06-20 16:09 UTC, aurorasmiles commented
Please also open a PR to document the new config option in https://github.com/PaperMC/PaperDocs

2021-06-20 16:09 UTC, BillyGalbreath commented
I'm glad someone agrees with me about this ^_^ We've been doing this in Purpur for a long time now.

2021-06-20 16:09 UTC, BillyGalbreath approved these changes

2021-06-20 16:09 UTC, Phoenix616 commented on patches/server/0716-Don-t-apply-cramming-damage-to-players.patch
> ++    public boolean allowPlayerCrammingDamage = false;
Allowing cramming damage by default would defeat one of the main reasons for this fix: Saving unsuspecting server owners from killing their players and crashing the server...

And I have never seen cramming damage for players play a role in normal gameplay so this wouldn't really impact that.

2021-06-20 22:29 UTC, Machine-Maker commented on patches/server/0716-Don-t-apply-cramming-damage-to-players.patch
> ++    public boolean allowPlayerCrammingDamage = false;
mmm, I'm not quite sure about this. I think it probably should default to the, well, default behavior. The setting is there if they want to change it.

2021-06-20 22:32 UTC, Phoenix616 commented on patches/server/0716-Don-t-apply-cramming-damage-to-players.patch
> ++    public boolean allowPlayerCrammingDamage = false;
I'm unsure why you think that crashing people's server should be the default behaviour.

2021-06-20 22:34 UTC, Machine-Maker commented on patches/server/0716-Don-t-apply-cramming-damage-to-players.patch
> ++    public boolean allowPlayerCrammingDamage = false;
There are already ways to crash the server. Repeating command blocks spawning thousands of items a second. That is also default behavior right?

2021-06-20 22:47 UTC, Phoenix616 commented on patches/server/0716-Don-t-apply-cramming-damage-to-players.patch
> ++    public boolean allowPlayerCrammingDamage = false;
A change that can easily prevent an admin error and has near zero impact on Vanilla gameplay should be done imo. if it saves people from making this error.

Without this enabled by default this PR is essentially worthless because as pointed out by Billy: A plugin could've already fixed this issue before and I guarantee you that 99.99% of servers do not run such a thing nor are aware that players can take cramming damage at all until they have crashed their servers with dozens if not hundreds of players online.

And imo. it's the software's job to help prevent such situation and use sensible defaults. Optional performance improvements with minimal gameplay impact are enabled by default too after all (e.g. EAR, hopper improvements, feature/structure search improvements), this isn't much different.

2021-06-20 23:04 UTC, pop4959 commented on patches/server/0716-Don-t-apply-cramming-damage-to-players.patch
> ++    public boolean allowPlayerCrammingDamage = false;
Just randomly glanced at this issue, and if I may pitch my two cents, this kind of fix seems to perfectly align with Paper's goals (as I understand them). The about section even states it "aims to fix gameplay and mechanics inconsistencies". I would strongly suggest that this is an inconsistency, and defaulting to false here is the expected behavior for most people. This likely impacts very few servers anyway, and if someone *does not* want this default for whatever reason, they can easily toggle it (again, probably little / no servers in practice).

2021-06-20 23:05 UTC, electronicboy approved these changes

2021-06-20 23:06 UTC, electronicboy commented on patches/server/0716-Don-t-apply-cramming-damage-to-players.patch
> ++        return super.isInvulnerableTo(damageSource) || this.isChangingDimension() || (!level.paperConfig.allowPlayerCrammingDamage && damageSource == DamageSource.CRAMMING) || this.getAbilities().in
Missing //Paper? and the change we add should probably be on the end of there just for the sake of easy cut & paste if we hit a conflict here

2021-06-20 23:06 UTC, Puremin0rez commented on patches/server/0716-Don-t-apply-cramming-damage-to-players.patch
> ++    public boolean allowPlayerCrammingDamage = false;
This has been debated before in other PRs - you can see Aikars comments on a similar topic of defaulting to change gameplay.

> You're welcome to change it. Most people will prefer these on, and we would rather inconvenience an extreme minority rather than telling the majority to flip the configs.

I share the same opinion.

See https://github.com/PaperMC/Paper/pull/3222

2021-06-20 23:10 UTC, Phoenix616 commented on patches/server/0716-Don-t-apply-cramming-damage-to-players.patch
> ++        return super.isInvulnerableTo(damageSource) || this.isChangingDimension() || (!level.paperConfig.allowPlayerCrammingDamage && damageSource == DamageSource.CRAMMING) || this.getAbilities().in
Yeah, I forgot about the comment thing, and moving it to the back makes sense I guess, I think I thought the getAbilities call was more expensive but that actually only returns one object.

2021-07-19 09:21 UTC, kennytv approved these changes
![pufferfish](https://user-images.githubusercontent.com/28825609/126136617-c78a83aa-1f77-478b-8a4f-be09c002f61d.png)

2021-07-19 09:31 UTC, merged

2021-08-23 07:56 UTC, molor commented
I don't understand, this prevents cramming damage only if

1. many players (w/o mobs) on same block
2. many mobs (w/o players except the target player) on same block where the target player stands,
3. both?

If both, can you add an setting to allow cramming damage to player from mobs only?

2021-08-23 08:03 UTC, NoahvdAa commented
> I don't understand, this prevents cramming damage only if
> &lt;snip&gt;

This prevents players from taking cramming damage of any kind (unless allow-player-cramming-damage is set to true of course)

2021-08-23 13:06 UTC, Phoenix616 commented
If you want more fine-grained control over this use a plugin, the PR was meant to prevent a pretty unknown behaviour in the server which is potentially exploitable.