Add back Optimise random block ticking
PaperMC/Paper pull request #5964
Opened 2021-06-23 03:47 UTC by Machine-Maker

Tested, and doesn't produce the vine issue anymore. Patch changes taken from [here](https://github.com/Tuinity/Tuinity/commit/7a55e31818184721673dd1e6b84d3957c9b9dc8e#diff-4f883f1ea4dd39067f4b47f105c4a4c4d801513750d97500b6725a2e489493ae).

2021-06-23 08:16 UTC, MiniDigger commented on patches/server/0381-Optimise-random-block-ticking.patch
> ++package com.tuinity.tuinity.util.math;
Let's go with io.papermc

2021-06-23 08:18 UTC, MiniDigger commented
Am I still blind or are there strange whitespace changes?

2021-06-23 08:20 UTC, Proximyst requested changes
fine by me

2021-06-23 08:20 UTC, Proximyst commented on patches/server/0381-Optimise-random-block-ticking.patch
> +diff --git a/src/main/java/com/tuinity/tuinity/util/math/ThreadUnsafeRandom.java b/src/main/java/com/tuinity/tuinity/util/math/ThreadUnsafeRandom.java
Paper

2021-06-23 15:52 UTC, Machine-Maker commented
Moved ThreadUnsafeRandom and fixed those weird whitespace issues.

2021-07-07 18:26 UTC, Machine-Maker commented
Fixed a couple issues w/this

2021-09-05 20:37 UTC, Owen1212055 commented
I’m guessing this can be closed since it came from Tuinity?

2021-09-05 21:05 UTC, closed without merging