[1.17] Add Entity Visibility API
PaperMC/Paper pull request #6000
Opened 2021-06-25 21:35 UTC by Janmm14

Closes #5973 

This is a port to 1.17 of #5993

2021-06-26 00:22 UTC, Trigary requested changes
Unfortunately `Level#sendParticles` also exists and is used by entities (eg. `Squid#spawnInk`, `LivingEntity#checkFallDamage`). You would need to handle that similarly to sounds.

2021-06-26 06:11 UTC, Janmm14 commented
> 
> 
> Unfortunately `Level#sendParticles` also exists and is used by entities (eg. `Squid#spawnInk`, `LivingEntity#checkFallDamage`). You would need to handle that similarly to sounds.

I've now edited sendParticle and playSound for all entities

2021-06-29 11:09 UTC, Janmm14 commented
stuff fixed

2021-07-12 09:26 UTC, Janmm14 commented
bump

2021-09-10 11:18 UTC, Janmm14 commented
.

2021-10-17 17:17 UTC, MiniDigger commented on patches/api/0321-Add-Entity-Visibility-API.patch
> ++    boolean canSee(@NotNull org.bukkit.entity.Entity entity);
is the FQN required here? the class is in the same package

2021-10-17 17:17 UTC, MiniDigger commented on patches/server/0719-Add-Entity-Visibility-API.patch
> ++        public final void updatePlayers(com.destroystokyo.paper.util.misc.PooledLinkedHashSets.PooledObjectLinkedOpenHashSet<ServerPlayer> newTrackerCandidates) {
this is missing a paper comment, and really, it should be a AT

2021-10-17 17:19 UTC, MiniDigger commented on patches/server/0719-Add-Entity-Visibility-API.patch
> ++    public final Mob removerMob; // Paper - private -> public - Entity Visibility API
AT

2021-10-17 17:28 UTC, Janmm14 commented on patches/server/0719-Add-Entity-Visibility-API.patch
> ++        public final void updatePlayers(com.destroystokyo.paper.util.misc.PooledLinkedHashSets.PooledObjectLinkedOpenHashSet<ServerPlayer> newTrackerCandidates) {
"AT"?

2021-10-17 17:29 UTC, lynxplay commented on patches/server/0719-Add-Entity-Visibility-API.patch
> ++        public final void updatePlayers(com.destroystokyo.paper.util.misc.PooledLinkedHashSets.PooledObjectLinkedOpenHashSet<ServerPlayer> newTrackerCandidates) {
https://github.com/PaperMC/Paper/blob/master/build-data/paper.at allows you to change access modifiers.

2021-10-17 18:00 UTC, NoahvdAa commented on patches/api/0321-Add-Entity-Visibility-API.patch
> ++    // Paper start - Entity Visibility API
Don't create a new comment "block" here, move it into the already existing one

2021-10-17 18:00 UTC, NoahvdAa commented on patches/api/0321-Add-Entity-Visibility-API.patch
> ++    // Paper start - Entity Visibility API
same here

2021-10-17 18:00 UTC, NoahvdAa commented on patches/server/0719-Add-Entity-Visibility-API.patch
> ++    // Paper start - Entity Visibility API
Same here

2021-10-17 18:00 UTC, NoahvdAa commented on patches/server/0719-Add-Entity-Visibility-API.patch
> ++    public boolean canSee(org.bukkit.entity.Entity entity) {
Would it be a good idea to null check the entity? (same for methods below)

2021-11-10 12:05 UTC, jaylawl commented
Please don't let this die

2021-11-29 21:06 UTC, Janmm14 commented on patches/api/0321-Add-Entity-Visibility-API.patch
> ++    // Paper start - Entity Visibility API
But its done like that in many more places and helps with keeping patches individual.

2021-11-29 21:09 UTC, Janmm14 commented on patches/api/0321-Add-Entity-Visibility-API.patch
> ++    // Paper start - Entity Visibility API
But litterally a couple lines above the same thing happens, it also helps to keep patches a little more individual.

2021-11-29 21:15 UTC, Janmm14 commented on patches/server/0719-Add-Entity-Visibility-API.patch
> ++        public final void updatePlayers(com.destroystokyo.paper.util.misc.PooledLinkedHashSets.PooledObjectLinkedOpenHashSet<ServerPlayer> newTrackerCandidates) {
Cannot use AT for this one because method is added by patch 0431

2021-11-29 21:17 UTC, Machine-Maker commented on patches/server/0719-Add-Entity-Visibility-API.patch
> ++        public final void updatePlayers(com.destroystokyo.paper.util.misc.PooledLinkedHashSets.PooledObjectLinkedOpenHashSet<ServerPlayer> newTrackerCandidates) {
then go back to the patch that adds it and change the visibility there.

2021-11-29 21:37 UTC, Janmm14 commented on patches/server/0719-Add-Entity-Visibility-API.patch
> ++    public final Mob removerMob; // Paper - private -> public - Entity Visibility API
done

2021-11-29 21:37 UTC, Janmm14 commented on patches/api/0321-Add-Entity-Visibility-API.patch
> ++    boolean canSee(@NotNull org.bukkit.entity.Entity entity);
fixed

2021-11-29 21:37 UTC, Janmm14 commented on patches/server/0719-Add-Entity-Visibility-API.patch
> ++    public boolean canSee(org.bukkit.entity.Entity entity) {
null checks added

2021-11-29 21:40 UTC, Janmm14 commented
soo I remembered again I had this thing open, please check again

2021-11-29 21:42 UTC, Machine-Maker requested changes
Just as a note, [upstream added something](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/37fd1917e73f1f0b16dcef01cac940cd52510d73) that might conflict with this. Probably needs to be considered somehow here.

2021-11-29 21:42 UTC, Machine-Maker commented on patches/server/0719-Add-Entity-Visibility-API.patch
> ++        public final void updatePlayers(com.destroystokyo.paper.util.misc.PooledLinkedHashSets.PooledObjectLinkedOpenHashSet<ServerPlayer> newTrackerCandidates) { // Paper - Entity Visibility API -
Unsure if you saw my comment [here](https://github.com/PaperMC/Paper/pull/6000#discussion_r758742147), but if this is a method added by paper in a previous patch, you should go back to that patch and change the visibility there to reduce the diff.

2021-11-29 22:10 UTC, Janmm14 commented
Will check

> Just as a note, [upstream added something](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/37fd1917e73f1f0b16dcef01cac940cd52510d73) that might conflict with this. Probably needs to be considered somehow here.

Looks like this patch got a little redundant.

I will create a PR to upstream with the details upstream ignored (sounds, particles).
As they accepted the base idea, the fixes to it will hopefully be accepted as well.

2022-11-25 23:11 UTC, Owen1212055 commented
Seeing as upstream has merged _most_ of what this pr was meant to bring this will be closed.

The whole "hide by default behavior" seems to be covered by another issue which has some PRs for it as well. https://github.com/PaperMC/Paper/issues/7395

Because blocking sounds/particles might still be a wanted feature, feel free to open a separate PR (here or upstream) that covers that specific area while using the current visibility API that upstream has.

Thank you for your contribution, and sorry we couldn't get to merge this. ☹️

2022-11-25 23:11 UTC, closed without merging