Add PlayerArmorStandCreateEvent
PaperMC/Paper pull request #617
Opened 2017-02-22 01:00 UTC by AlphaBlend

This PR adds an event when a player creates an armor stand.

2017-02-22 02:13 UTC, kashike commented
...and you can't use an interact event... why?

2017-02-22 08:24 UTC, AlphaBlend commented
Aren't there events already present that could be replaced by an interact event? I could use an interact event, but isn't specificity good? Your comment is making me think though.

2017-02-22 08:25 UTC, kashike requested changes

2017-02-22 08:25 UTC, kashike commented on Spigot-API-Patches/0051-Add-PlayerArmorStandCreateEvent.patch
> ++    private boolean canceled;
Should be `cancelled`.

2017-02-22 08:25 UTC, kashike commented
Yes and no. What's the use case for this specific event?

2017-02-22 12:11 UTC, AlfieC commented
Should this not be abstracted and a destroy event added too?

2017-02-22 21:20 UTC, AlphaBlend commented
@kashike you can retrieve the location the armor stand will be placed without doing some calculations ahead of time. On top of that, it brings this in line with an event like PlayerArmorStandManipulateEvent, keeping consistency.

@AlfieC one thing at a time :) but I can totally see that.

2017-02-24 20:21 UTC, AlphaBlend commented on Spigot-API-Patches/0051-Add-PlayerArmorStandCreateEvent.patch
> ++    private boolean canceled;
Fixed.

2017-07-09 06:52 UTC, Zbob750 commented
The gist from a quick discussion in IRC is that this event is unnecessary given that it's covered by other events and, while it does expose a few extra items, this is not the only way to get to them.

Therefore we will decline, thanks anyway.

2017-07-09 06:52 UTC, closed without merging