Add advancement display API
PaperMC/Paper pull request #6175
Opened 2021-07-13 10:16 UTC by syldium

Adds API for displaying advancements.
This allows custom menus and the use of translatable components.
Example: https://gist.github.com/syldium/4f304340ee26d31bea009295a7196522

2021-07-13 14:59 UTC, Machine-Maker commented on patches/server/0727-Add-advancement-display-API.patch
> ++        return PaperAdventure.asAdventure(this.handle.getTitle());
Perhaps both this and the description should be cached? I’m unsure so this isn’t a needed change for the moment.

2021-07-14 02:34 UTC, Machine-Maker reviewed
The whole `AdvancementTree` interface seems odd to me, why weren't the methods on that interface just added to the regular Advancement interface and implemented in CraftAdvancement?

2021-07-14 09:26 UTC, syldium commented
> The whole `AdvancementTree` interface seems odd to me, why weren't the methods on that interface just added to the regular Advancement interface and implemented in CraftAdvancement?

The idea is that the background property has an effect only on the root advancement when the tab is created. The `AdvancementTree` interface suggests that this property is more related to the whole tree rather than to a single advancement for me.

2021-07-14 17:51 UTC, Machine-Maker commented
Yeah, I understand that, but I feel like it's weird to deviate from the nms DisplayInfo class so much which just has a nullable ResourceLocation for that background.

2021-07-17 11:29 UTC, syldium commented
`AdvancementTree` interface removed to match NMS, `CraftItemStack#asCraftMirror` → `CraftItemStack#asBukkitCopy` in `AdvancementDisplay#icon`.

2021-07-25 20:23 UTC, Machine-Maker reviewed
I'm not sure ComponentLike is appropriate for Advancement? Some adventure peeps should weigh in here.

2021-07-25 20:23 UTC, Machine-Maker commented on patches/server/0728-Add-advancement-display-API.patch
> ++        return this.handle.getDisplay() == null ? null : new io.papermc.paper.advancement.PaperAdvancementDisplay(this.handle.getDisplay());
Should a new instance be created for each getDisplay call?

*just a comment, not a suggestion, need for feedback to determine whats better*

2021-07-25 20:28 UTC, kezz commented
> I'm not sure ComponentLike is appropriate for Advancement? Some adventure peeps should weigh in here.

I think just `Translatable` is fine. Similarly `Frame` doesn't really need to implement `StyleBuilderApplicable`.

2021-08-12 13:31 UTC, syldium commented
Implements #6382.
I don't think that `Advancement` should implement `Translatable`, because datapacks can create new ones without translatable components. `#asComponent` exposes the name wrapped in square brackets used in the chat.

2021-08-12 22:54 UTC, Machine-Maker requested changes
Needs unit tests to check the Frame translationKey and the Frame NamedTextColor are equal to their NMS counterparts.

EDIT: Also, Advancement shouldn't implement ComponentLike

2021-08-12 22:54 UTC, Machine-Maker commented on patches/server/0732-Add-advancement-display-API.patch
> ++        return this.handle.getDisplay() == null ? null : new io.papermc.paper.advancement.PaperAdvancementDisplay(this.handle.getDisplay());
This shouldn't be re-created every time getDisplay is called. Add a field to CraftAdvancement and set it either in the first getDisplay call, or the ctor.

2021-08-12 22:54 UTC, Machine-Maker commented on patches/server/0732-Add-advancement-display-API.patch
> ++        return switch (this.handle.getFrame()) {
To facilitate the unit testing of bukkit `Frame` and nms `FrameType` this should probably be moved to static method to convert from nms to bukkit.

2021-08-15 00:29 UTC, Machine-Maker approved these changes

2021-08-15 11:37 UTC, kezz commented on patches/api/0329-Add-advancement-display-API.patch
> ++        public static final Index<String, Frame> NAMES = Index.create(Frame.class, color -> color.name);
```suggestion
+        public static final Index<String, Frame> NAMES = Index.create(Frame.class, frame -> frame.name);
```

2021-10-20 19:52 UTC, JRoy approved these changes

2021-10-20 19:58 UTC, kashike approved these changes

2021-10-20 19:59 UTC, merged