Add Spawner Potential API
PaperMC/Paper pull request #6221
Opened 2021-07-18 05:29 UTC by thamid-gamer

Does part 2 of and fixes #1611

2021-07-27 16:22 UTC, Machine-Maker requested changes
There is still some missing stuff in here for spawners, for example entities can have equipment, or anything really but that's very hard to do with bukkit's current Entity API.

2021-07-27 16:22 UTC, Machine-Maker commented on patches/api/0324-Add-Spawner-Potential-API.patch
> ++    // Paper - update javadoc
Don't need to comment javadoc changes

2021-07-27 16:22 UTC, Machine-Maker commented on patches/api/0324-Add-Spawner-Potential-API.patch
> ++// Paper start - update javadoc
another unneeded comment

2021-07-27 16:22 UTC, Machine-Maker commented on patches/server/0728-Implement-Spawner-Potential-API.patch
> ++    // Paper start
If this logic in this function is copied from somewhere else in `BaseSpawner`, make a note of where its taken from for future updaters of this patch.

2021-07-28 18:57 UTC, thamid-gamer commented
rebased + did suggestions

2021-12-04 18:55 UTC, thamid-gamer commented
not quite stale

2022-02-04 01:27 UTC, thamid-gamer commented
shoo + would like suggestion on a better way with itemstacks vs entities for spawner entries

2022-04-14 14:31 UTC, closed without merging