Allow plugins to inject jars into the PluginClassLoader
PaperMC/Paper pull request #6249
Opened 2021-07-22 13:30 UTC by voodootje0

Due to java 16 reflection changes, it's no longer possible to get the protected addURL method in the URLClassLoader.

2021-07-22 13:35 UTC, lynxplay commented
Related to #5631

2021-07-22 13:39 UTC, Proximyst requested changes
We've already decided not to expose any kind of way to do this directly, especially with Spigot's Maven loader thingy. I believe just changing the accessor to package-private would fix this?

2021-07-22 13:39 UTC, lynxplay commented on patches/api/0324-Allow-plugins-to-inject-jars-into-the-PluginClassLoa.patch
> ++        if (pluginClassloader instanceof org.bukkit.plugin.java.PluginClassLoader) {
Could make use of Java 16's instanceOf's pattern matching to clean this up a little.

2021-07-22 13:42 UTC, lynxplay commented on patches/api/0324-Allow-plugins-to-inject-jars-into-the-PluginClassLoa.patch
> ++    void addToClasspath(Plugin plugin, java.nio.file.Path path);
Missing `NotNull` annotations.

2021-07-22 13:47 UTC, lynxplay commented
> We've already decided not to expose any kind of way to do this directly, especially with Spigot's Maven loader thingy. I believe just changing the accessor to package-private would fix this?

Really just overwriting and delegating the `addUrl` method in the PluginClassLoader would do the trick, as that class is not encapsulated inside any module (as of now). Right now, PluginClassLoader does not overwrite the method, meaning that plugins that tried to make the `URLClassLoader`'s method accessible failed (due to that class being in a module).

I would also advertise for actually overwriting the `addUrl` method instead of creating a new one that, for some reason, throws an AssertionError ?

2021-09-20 14:43 UTC, lynxplay commented
I would still like this PR to be updated to reflect the requested changes from proxi.

2021-11-26 20:10 UTC, closed without merging