Prevent AFK kick while watching end credits (#6239).
PaperMC/Paper pull request #6265
Opened 2021-07-24 14:57 UTC by NoahvdAa

This PR implements #6239 by preventing an AFK kick if the player is switching dimensions and in the end.

2021-07-24 14:59 UTC, Machine-Maker requested changes
I feel like there's a viewingCredits boolean on the player entity or something, would that work better than a dimension check?

2021-07-24 14:59 UTC, Machine-Maker commented on patches/server/0731-Prevent-AFK-kick-while-watching-end-credits.patch
> ++import net.minecraft.world.level.dimension.DimensionType;
Don't add an import, use the FQN on the change below

2021-07-24 15:12 UTC, NoahvdAa commented
> I feel like there's a viewingCredits boolean on the player entity or something, would that work better than a dimension check?

I tried looking for that as well, but couldn't find it.

2021-07-24 17:00 UTC, Machine-Maker commented
I think `wonGame` is that boolean. Based on where its set, it looks like when its true, the player is viewing the credits? It gets set back to false when the player respawns

2021-07-24 17:10 UTC, Machine-Maker approved these changes
Needs testing to make sure `wonGame` is what i think it is.

2021-07-24 17:11 UTC, NoahvdAa commented
> I think `wonGame` is that boolean. Based on where its set, it looks like when its true, the player is viewing the credits? It gets set back to false when the player respawns

That appears to be it, the only parts lines where `wonGame` is modified have to do with dimension switching. I've gone and updated the patch to use `wonGame`.

2021-07-29 19:46 UTC, NoahvdAa commented
Whoops, I tried to rename the branch but that ended up closing the PR.

2021-08-02 08:04 UTC, Proximyst approved these changes

2021-08-02 08:43 UTC, merged