Implement Better Player Experience API
PaperMC/Paper pull request #6267
Opened 2021-07-25 00:47 UTC by jakebacker

This adds a more useful API to get the total amount of experience the player currently has. This fixes #6253 

### Background
The current experience API allows to get the player's exp levels, percent to the next exp level, and total, lifetime experience. Some plugins need to be able to access the total number of experience points a player has at a given time. This adds `Player#getCurrentExperience` which does just that.

2021-07-25 16:17 UTC, imDaniX commented
Should it not return `long` instead?

2021-07-25 16:25 UTC, jakebacker commented
Yep, it should! I'll go fix that

2021-08-29 13:28 UTC, me4502 commented
Does it make sense to have a setter as well?

2021-10-30 05:31 UTC, jakebacker commented
Bump. Any update on this?

2021-10-30 08:55 UTC, olijeffers0n commented
> Bump. Any update on this?

I mean, they did ask about a setter. I think this is a good idea to have. So that is the next step really.

2022-01-13 04:21 UTC, Machine-Maker requested changes

2022-01-13 04:21 UTC, Machine-Maker commented on patches/server/0731-Implement-new-experience-API.patch
> ++        }
This is a big block fully of magic numbers and formulas. Probably add some comments directing people to where this information was gotten, and comments on the src where you gleaned this from to catch any diff that is made there.

2022-01-13 04:21 UTC, Machine-Maker commented on patches/api/0324-Add-better-player-experience-API.patch
> ++    public long getCurrentExperience();
I think this method should be on the `HumanEntity` interface, ik most of the methods are on `Player` but there's on XP method on HumanEntity and that matches up with the experience fields being on nms Player not ServerPlayer

2022-09-11 17:01 UTC, Lulu13022002 commented on patches/server/0731-Implement-new-experience-API.patch
> ++    }
These formulas seems to be wrong, if you see https://minecraft.fandom.com/wiki/Talk:Experience#Formula_for_%22EXP_until_next_level%22_in_incorrect

You should use the vanilla Player#getXpNeededForNextLevel() to be accurate.
Also 3000000 is not a long but still an int which fit into 32 bits signed so give you at least 2^31 exp when you want to test the long usage.

2022-10-03 19:00 UTC, closed without merging