Implement branch reader
PaperMC/Paper pull request #6270
Opened 2021-07-25 16:58 UTC by Toffikk

This change allows the version fetcher to work properly on all branches

2021-07-25 17:03 UTC, Proximyst requested changes
I personally see little to no reason to accept. Just set the branch constant per branch...

2021-07-25 17:03 UTC, Proximyst commented on patches/server/0019-Implement-Paper-VersionChecker.patch
> ++  }
https://docs.oracle.com/en/java/javase/16/docs/api/java.base/java/util/Properties.html

2021-07-25 17:03 UTC, Proximyst commented on patches/server/0019-Implement-Paper-VersionChecker.patch
> ++    private static final String GITHUB_BRANCH_NAME = BranchReader.getBranch();
Implement it in the same class

2021-07-25 17:03 UTC, Proximyst commented on patches/server/0019-Implement-Paper-VersionChecker.patch
> ++}
Use reformatting in your IDE...

2021-07-25 17:03 UTC, Proximyst commented on patches/server/0019-Implement-Paper-VersionChecker.patch
> ++				Logger.getLogger(BranchReader.class.getName()).log(Level.SEVERE, "Could not get branch info from branch-info.properties!", ex);
Most definitely not severe; use Log4j logger too.

2021-07-25 17:03 UTC, Proximyst commented on patches/server/0019-Implement-Paper-VersionChecker.patch
> ++		InputStream branchStream = Bukkit.class.getClassLoader().getResourceAsStream("branch-info.properties");
try-with-resources

2021-07-25 17:03 UTC, Proximyst commented on patches/server/0019-Implement-Paper-VersionChecker.patch
> ++		InputStream branchStream = Bukkit.class.getClassLoader().getResourceAsStream("branch-info.properties");
```suggestion
+		InputStream branchStream = MinecraftServer.class.getClassLoader().getResourceAsStream("branch-info.properties");
```

2021-07-30 03:34 UTC, JRoy requested changes
I have no idea why you're going through the trouble to parse the git branch a second time, we already put the branch in the manifest as per this patch: https://github.com/PaperMC/Paper/blob/b854e7e8023a287a44118e895d7c0896fa16df16/patches/server/0717-Add-git-branch-and-commit-to-manifest.patch

2021-10-05 05:15 UTC, closed without merging