Allow using Mojang item optimizations instead of the one provided by Spigot.
PaperMC/Paper pull request #6290
Opened 2021-07-29 21:14 UTC by NoahvdAa

This PR allows server owners to use Mojang's implementation of tick skipping for items, instead of the one provided by Spigot. There are several situations where Mojang's system, which is based on the entity id and entity age, is preferred over the one Spigot uses, which only uses entity age. For example, the [wireless redstone system](https://www.youtube.com/watch?v=FLynwXDnETI) mentioned in #6277. These types of systems need the item id based implementation to function correctly. This change brings back something that could be considered a vanilla mechanic, and should be easy to maintain.

_Small sidenote:_ I'm not 100% sure I rebased the patches correctly, please let me know if anything needs changing.

2021-09-05 01:05 UTC, Amaroq-Clearwater commented
When you get the chance, you should update this patch in order to resolve the various conflicts.

2021-09-05 06:59 UTC, NoahvdAa commented
Conflicts should be resolved now.

2021-12-11 06:47 UTC, Pangi790927 commented
so will this be added in paper?

2021-12-18 16:35 UTC, StarMiner99 commented
would be great if this gets merged

2021-12-22 07:13 UTC, electronicboy commented on patches/server/0359-Allow-using-Mojang-item-optimizations.patch
> ++            if(!(entity instanceof net.minecraft.world.entity.item.ItemEntity && entity.level.paperConfig.useMojangItemOptimizations)) // Paper - Prevent skipping if mojang item optimizations are us
idk why but I kinda hate the way this is expressed, maybe just my tired brain but idk

2021-12-22 07:13 UTC, electronicboy approved these changes

2022-01-13 04:11 UTC, Machine-Maker commented
Can't this whole thing be fixed by making spigot's ActivationRange tick skip check the same as `ItemEntity`? Adding the entityId to the tickCount?

2022-01-19 02:44 UTC, Machine-Maker requested changes
Looks good, but I think there is now no need for a config option. This should just fix the issue by changing spigot’s skip logic in `ActivationRange`. That should resolve all issues without creating any unexpected behavior.

2022-01-19 06:50 UTC, NoahvdAa commented
The patch now leaves Mojang's optimizations alone (aside from diff on change) and changes spigot's activation range check to `tickCount + entityId + 1`, because mojang skips on `tickCount + entityId`. Tested using [cubicmetre's wireless redstone world](https://www.youtube.com/watch?v=sBNuqZKa_Lw), everything appears to work as intended.

2022-01-19 19:03 UTC, Machine-Maker approved these changes

2022-01-19 19:18 UTC, merged