Update PlayerPostRespawnEvent to check for anchor respawn
PaperMC/Paper pull request #6341
Opened 2021-08-06 03:07 UTC by MisterVector

This PR adds a new method to the PlayerPostRespawnEvent event, isAnchorSpawn(), to check if the respawn was due to an anchor.

2021-08-06 03:26 UTC, Machine-Maker requested changes
Should probably be just added to the patch that adds this event seeing as it’s a Paper-specific event.

2021-08-06 03:44 UTC, MisterVector commented
You're right, so I'll get down to figuring that all out at some point. New to this build system. :)

2021-08-06 05:06 UTC, MisterVector commented
On second thought I'm not sure of the implications of doing that, as the variable I'm trying to pass as an argument did not exist at the time of that patch's creation. What would be the best approach if this was going to be accomplished?

2021-08-06 16:33 UTC, Machine-Maker commented
> What would be the best approach if this was going to be accomplished?

You can either re-order the patches, as in find the patch that adds the variable that you need, get its number, add 1 to it, and rename the patch file to that. (make sure you re-order both the server and api patches to they are still "in sync") 

-- OR --

You can add whatever you need to the patch you are editing, and then remove it from the patch that comes after that also adds it.

2021-08-23 04:42 UTC, MisterVector commented
Rebased both api and server patches with the specified changes. Hopefully this won't be hard to sort out before merging.

I did add `isAnchorSpawn = flag3; // Paper - Fix anchor respawn acting as a bed respawn from the end portal` which is kind of strange given the comment not being within the context of this PR. Anyways, things should hopefully be ok from my end.

2021-08-23 04:53 UTC, MisterVector commented
On second thought I shouldn't have added `PlayerRespawnEvent respawnEvent = new PlayerRespawnEvent(respawnPlayer, location, isBedSpawn && !isAnchorSpawn, isAnchorSpawn); // Paper - Fix anchor respawn acting as a bed respawn from the end portal` to my patch, the assignment of isanchorSpawn should have been enough as I included it in my event call.

2021-08-23 18:48 UTC, MisterVector commented
I will redo this again, trying to leave out the things that should not be included.

2021-08-24 08:06 UTC, NoahvdAa approved these changes

2021-08-24 08:06 UTC, NoahvdAa commented on patches/server/0319-Implement-PlayerPostRespawnEvent.patch
> ++                    isAnchorSpawn = flag3;
Missing Paper comment.
```suggestion
+                    isAnchorSpawn = flag3; // Paper
```

2021-08-24 17:39 UTC, NoahvdAa commented
Isn't this a duplicate of #5465?

2021-08-25 02:18 UTC, MisterVector commented
Yep... did not look for this beforehand, wasn't actually expecting someone wanted to do this before... well I'll close this out then.

2021-08-25 02:18 UTC, closed without merging