Add /paper dumplisteners command
PaperMC/Paper pull request #6359
Opened 2021-08-08 03:46 UTC by TwoLeggedCat

Useful to find what plugin is responsible for an annoying thing.

No idea if that Component usage is anywhere near reasonable, haven't actually used Adventure much.

2021-10-07 06:16 UTC, jpenilla requested changes

2021-10-07 06:16 UTC, jpenilla commented on patches/server/0742-Add-paper-dumplisteners-command.patch
> ++            sender.sendMessage(Component.text("Usage: /paper dumplisteners [className]").color(NamedTextColor.RED));
Component.text(String, TextColor)

2021-10-07 06:16 UTC, jpenilla commented on patches/server/0742-Add-paper-dumplisteners-command.patch
> ++        Component message = Component.text("Listeners for " + args[1] + ": ");
use Component.text() for a mutable builder, then append to that instead of reassigning this variable over and over. Could also use the Component.toComponent collector, or a JoinConfiguration for the list part.

2021-10-07 06:16 UTC, jpenilla commented on patches/server/0742-Add-paper-dumplisteners-command.patch
> ++            sender.sendMessage(Component.text("Error: " + e).color(NamedTextColor.RED));
Component.text(String, TextColor)

use getMessage on the exception instead of implicit toString

maybe also log to console?

2021-10-07 06:16 UTC, jpenilla commented on patches/server/0742-Add-paper-dumplisteners-command.patch
> ++                    Component.text(listener.getPlugin().getName())
If a plugin has more than one listener registered, this will look kind of weird. Maybe also print the type name of the Listener implementation class? With more info it might also be better to have a bulleted format instead of comma separated.

2021-10-07 06:30 UTC, Proximyst commented on patches/server/0742-Add-paper-dumplisteners-command.patch
> ++            sender.sendMessage(Component.text("Error: " + e).color(NamedTextColor.RED));
Error should only be in console; the sender should simply get a `Something went wrong.` message.

2021-11-06 14:07 UTC, TwoLeggedCat commented on patches/server/0742-Add-paper-dumplisteners-command.patch
> ++            sender.sendMessage(Component.text("Error: " + e).color(NamedTextColor.RED));
<table>
  <tr>
    <td>getMessage()</td>
    <td>toString()</td>
  <tr>
    <td>com.destroystokyo.paper.event.entity.EventWhichDoesNotExist</td>
    <td>java.lang.ClassNotFoundException: com.destroystokyo.paper.event.entity.EventWhichDoesNotExist</td>
   </tr>
   <tr>
     <td>org.bukkit.Bukkit.getHandlerlist()</td>
     <td>java.lang.NoSuchMethodException: org.bukkit.Bukkit.getHandlerList()</td>
   </tr>
</table>

The latter seems much more helpful and is fairly human readable. Perhaps the solution, though, is to print a real error depending on the exception given, i.e. `The specified class does not have a HandlerList. Are you sure you picked a valid event?` on a NoSuchMethod.

2021-11-06 14:39 UTC, TwoLeggedCat commented on patches/server/0742-Add-paper-dumplisteners-command.patch
> ++                    Component.text(listener.getPlugin().getName())
<img width="987" alt="image" src="https://user-images.githubusercontent.com/80929284/140613475-9178dccc-f711-4c19-baad-fb9b6f4342d2.png">

How's this? (in this case I just threw four extra listeners in my main class but presumably no one would do that in reality)

2022-10-25 17:38 UTC, Owen1212055 commented
Because this PR has been inactive for a while, I will be closing this.
If you are still interested in your PR, please feel free to comment and we can reopen it for you. 😄

2022-10-25 17:38 UTC, closed without merging