Apply furnace cook speed multiplier through event
PaperMC/Paper pull request #6378
Opened 2021-08-11 09:21 UTC by lynxplay

Previously the upstream FurnaceStartSmeltEvent would default to the
recipes cooking time, ignoring any modifications from the furnace speed
multiplier.
While this works correctly for upstream, paper introduces the speed
multiplier API, which allows a different cook time from the one provided
by the recipe.

This commit now passes the modified cooktime to the furnace start smelt
event explicitly, instead of allowing the event to default to the
recipes cooking time, thus ensuring that the speed modifier is
respected.

Resolves: #6376

2021-08-11 09:23 UTC, NoahvdAa requested changes

2021-08-11 09:23 UTC, NoahvdAa commented on patches/api/0154-Implement-furnace-cook-speed-multiplier-API.patch
> ++        this.totalCookTime = cookingTime; // Paper start - furnace cook speed multiplier
```suggestion
+        this.totalCookTime = cookingTime; // Paper - furnace cook speed multiplier
```

2021-08-11 09:24 UTC, lynxplay commented on patches/api/0154-Implement-furnace-cook-speed-multiplier-API.patch
> ++        this.totalCookTime = cookingTime; // Paper start - furnace cook speed multiplier
nice catch, thank you <3

2021-08-11 09:25 UTC, NoahvdAa approved these changes

2021-08-11 23:36 UTC, Machine-Maker approved these changes

2021-09-03 17:04 UTC, electronicboy approved these changes

2021-09-03 21:47 UTC, lexikiq approved these changes

2021-09-22 19:46 UTC, merged