Mark fish and axolotls from buckets as persistent
PaperMC/Paper pull request #6392
Opened 2021-08-13 23:41 UTC by Machine-Maker

Fixes [SPIGOT-6618](https://hub.spigotmc.org/jira/browse/SPIGOT-6618).

This doesn't actually change any behavior on the server side of things because Paper only counts mobs that have a `NATURAL` SpawnReason and fish/axolotls from buckets have a `SPAWNER_EGG` reason, but it does affect what is returned by the api method `LivingEntity#getRemoveWhenFarAway` which would've returned false for fish/axolotls without this change.

2021-08-13 23:48 UTC, electronicboy approved these changes

2021-08-21 08:58 UTC, kennytv requested changes
`fromBucket` can be false

2021-08-21 18:55 UTC, Machine-Maker commented
Yep, totally correct

2021-08-21 19:09 UTC, kennytv approved these changes

2021-09-22 04:59 UTC, merged