Allows for chorus fruit teleports to work above the nether roof
PaperMC/Paper pull request #6485
Opened 2021-08-25 07:03 UTC by Rasbora1337

Allow chorus fruit teleports to work above the nether roof by using the y value of getMaxBuildHeight() instead of getLogicalHeight() when the config option allow-chorus-teleport-above-logical-height is set to true.

2021-08-25 07:11 UTC, Proximyst approved these changes
Looks good, thanks!

2021-08-25 07:11 UTC, Proximyst commented on patches/server/0753-allow-chorus-fruit-teleports-work-above-nether-roof.patch
> ++                    //Paper - add option to let chorus fruit teleport calculation go up to nether build height instead of roof height
On the same line as the change, and space between `//` and `Paper`.

2021-08-25 07:30 UTC, NoahvdAa approved these changes
Aside from what Proxi already mentioned, LGTM! 👍

2021-08-25 20:38 UTC, Machine-Maker requested changes

2021-08-25 20:38 UTC, Machine-Maker commented on patches/server/0753-allow-chorus-fruit-teleports-work-above-nether-roof.patch
> ++                    (world.paperConfig.allowChorusAboveLogicalHeight ? ((ServerLevel) world).getMaxBuildHeight() : ((ServerLevel) world).getLogicalHeight()) - 1)); // Paper - add option to let choru
idrk what the convention for paper comments on multi-line "lines", but if you are gonna have that line span two lines, I'd put a paper start and paper end before and after those two lines instead of only one paper comment after the second line.

Also, I think you still need to subtract 1 from the getMaxBuildHeight just like the logicalHeight.

2021-08-25 21:59 UTC, Machine-Maker approved these changes

2021-08-25 21:59 UTC, Machine-Maker commented on patches/server/0753-allow-chorus-fruit-teleports-work-above-nether-roof.patch
> ++                // Paper start - add option to let chorus fruit teleport calculation go up to nether build height instead of roof height
This comment, while true, probably shouldn't include the word `nether` since this doesn't apply to the nether. 
Maybe something like go up to the max world height instead of the logical height

2021-08-25 22:06 UTC, Machine-Maker commented on patches/server/0753-allow-chorus-fruit-teleports-work-above-nether-roof.patch
> ++                    (world.paperConfig.allowChorusAboveLogicalHeight ? ((ServerLevel) world).getMaxBuildHeight() : ((ServerLevel) world).getLogicalHeight()) - 1));
I think those casts to ServerLevel are redundant too, but that can be removed by the merger

2021-08-25 22:20 UTC, NoahvdAa commented on patches/server/0753-allow-chorus-fruit-teleports-work-above-nether-roof.patch
> ++                    (world.paperConfig.allowChorusAboveLogicalHeight ? ((ServerLevel) world).getMaxBuildHeight() : ((ServerLevel) world).getLogicalHeight()) - 1)); // Paper - add option to let choru
> Also, I think you still need to subtract 1 from the getMaxBuildHeight just like the logicalHeight.

This confused me a bit at first, but 1 isn't subtracted from getLocalHeight, but from the result of the ternary operation.

2021-08-26 13:44 UTC, MiniDigger commented
please link a docs PR that documents this new option before we merge.

2021-08-27 02:21 UTC, Rasbora1337 commented
> please link a docs PR that documents this new option before we merge.

https://github.com/PaperMC/PaperDocs/pull/107

2021-08-30 15:01 UTC, closed without merging

2021-08-30 15:02 UTC, kennytv commented
I did the dumb again 🦧 (plz don't push to master for prs). Please rebase your master branch locally, force push, and reopen the pr.