Prevent crashes or kicks from invalid enchantment keys
PaperMC/Paper pull request #6559
Opened 2021-09-04 21:33 UTC by NoahvdAa

Fixes #6558. I felt like this is worth patching since it can be abused on servers that give access to creative mode (or servers with some really scuffed command blocks). Swallowing the exception feels like the smallest and easiest solution as there doesn't seem to be a convenient way of checking if a namespacedkey is valid.

2021-09-04 21:42 UTC, Camotoy commented
In the listed issue's case, I feel like it would be better to check for the key nullability in `CraftNamedspacedKey#fromMinecraft` before trying to make the `NamedspacedKey`. That way the key isn't even attempted because Paper already knows it's invalid.

2021-09-04 21:56 UTC, Owen1212055 commented
The thing is there are so many issues just like this one that are caused by creative mode. Is it really worth having one patch for one fix while there are probably so many others? I would say to make this some kind of generic "fix _some_ illegal creative item crashes" patch that can be expanded onto.

Although it may not even be worth it at all, because of how many there are regardless.

2021-09-05 07:33 UTC, NoahvdAa commented
> I feel like it would be better to check for the key nullability in CraftNamedspacedKey#fromMinecraft before trying to make the NamedspacedKey.

Pretty sure the key path isn't null, but just an empty string. Would have to check that further to be 100% sure though.

> The thing is there are so many issues just like this one that are caused by creative mode.

This isn't directly caused by creative mode (it just makes it easier to exploit it), but I see what you mean. Perhaps this patch could be rebranded to something like you suggested, "Fix some invalid item crashes and kicks".

2021-10-23 15:52 UTC, kennytv requested changes
This is not a good fix for the issue at hand, not really a fix at all, actually

2021-10-23 19:00 UTC, Doc94 commented
Maybe is better make a check in CraftNamespacedKey::fromMinecraft(MinecraftKey minecraft) and return null if is invalid?

forget this.. i see another issue and this not fix any only get another error returning null :/

2021-10-24 13:58 UTC, NoahvdAa commented
Closing in favour of #6825.

2021-10-24 13:58 UTC, closed without merging