Readd root/admin user detection
PaperMC/Paper pull request #6593
Opened 2021-09-12 12:07 UTC by NoahvdAa

This PR re-adds the root/admin user warning originally introduced in #2432. The original patch was reverted (ecfaff5) because of console spam issues on CentOS. In this PR, a different way of checking for for root/admin privileges is used, which shouldn't cause console spam.

Tested on macOS 11.4, Ubuntu 20.04, Centos 8 and Windows Server 2022.

2021-09-12 13:08 UTC, molor commented
In Windows Server, a single default user named Administrator is used on the every our host, and all user applications/services are run on his behalf. We understand all the risks and agree with them, we take all the risks on ourselves. Where is the startup option that allows to remove this (useless for us) warning?.. Or maybe we can disable this check for WS?

2021-09-12 13:17 UTC, Proximyst requested changes

2021-09-12 13:17 UTC, Proximyst commented on patches/server/0806-Add-root-admin-user-detection.patch
> +From: egg82 <eggys82@gmail.com>
Feel free to coauthor yourself as you came up with a new way of detecting it.

2021-09-12 13:17 UTC, Proximyst commented on patches/server/0806-Add-root-admin-user-detection.patch
> ++                if (io.papermc.paper.util.ServerEnvironment.userIsRootOrAdmin()) {
Let’s use a logger here

2021-09-12 18:02 UTC, Proximyst requested changes
https://docs.oracle.com/en/java/javase/16/docs/api/jdk.security.auth/com/sun/security/auth/module/package-summary.html
There’s API to detect this properly, apparently. Could you please take a look at this instead?

2021-09-12 18:20 UTC, NoahvdAa commented
Lynx and I came up with the solution used in 489bfa7, which uses Windows [Security identifiers](https://docs.microsoft.com/en-us/windows/security/identity-protection/access-control/security-identifiers). This seems to match command prompt running as administrator correctly. I'm not very familiar with how Windows works, can someone who knows Windows a little better help confirm that this is the best way to check for this?

2021-09-12 18:28 UTC, lynxplay commented
> Lynx and I came up with the solution used in [489bfa7](https://github.com/PaperMC/Paper/commit/489bfa7dc0f912a4f15afaa0e0c677a25465b0f1), which uses Windows [Security identifiers](https://docs.microsoft.com/en-us/windows/security/identity-protection/access-control/security-identifiers). This seems to match command prompt running as administrator correctly. I'm not very familiar with how Windows works, can someone who knows Windows a little better help confirm that this is the best way to check for this?

Added to this, neither of us are running windows so if someone with access to a windows machine / windows-server machine could validate if this PR works correctly, that would be sweet :+1:

2021-09-13 05:55 UTC, TheFruxz commented
MacOS should be checked too I think

2021-09-13 05:59 UTC, electronicboy commented
it already does

2021-09-13 18:12 UTC, sulu5890 commented on patches/server/0806-Add-root-admin-user-detection.patch
> ++            DedicatedServer.LOGGER.error("****************************");
> ATTACKERS WILL HAVE COMPLETE ACCESS AND CONTROL OF YOUR MACHINE

I really don't like the wording here, I can see a lot of people thinking that this means Minecraft "hackers" will be able to access their machine, playing further into the common misunderstanding that giving out your IP address will allow players access to your computer etc.

2021-09-13 18:21 UTC, NoahvdAa commented on patches/server/0806-Add-root-admin-user-detection.patch
> ++            DedicatedServer.LOGGER.error("****************************");
How does this sound?

> YOU ARE RUNNING THIS SERVER AS AN ADMINISTRATIVE OR ROOT USER. THIS IS NOT ADVISED.
> YOU ARE OPENING YOURSELF UP TO POTENTIAL RISKS WHEN DOING THIS.
> MALWARE AND MALICIOUS PLUGINS WILL HAVE COMPLETE ACCESS AND CONTROL OF YOUR MACHINE.

2021-09-13 18:22 UTC, sulu5890 commented on patches/server/0806-Add-root-admin-user-detection.patch
> ++            DedicatedServer.LOGGER.error("****************************");
Yeah, just taking out the last bit about attackers makes it much better.

2021-09-20 05:28 UTC, Proximyst requested changes

2021-09-20 05:28 UTC, Proximyst commented on patches/server/0806-Add-root-admin-user-detection.patch
> ++                isRunningAsRoot = new String(inputStream.readAllBytes()).trim().equals("0");
https://docs.oracle.com/en/java/javase/17/docs/api/jdk.security.auth/com/sun/security/auth/module/UnixSystem.html#getUid()

2021-09-20 05:28 UTC, Proximyst commented on patches/server/0806-Add-root-admin-user-detection.patch
> ++            runningAsRootOrAdmin = Arrays.asList(new NTSystem().getGroupIDs()).contains("S-1-16-12288");
```suggestion
+            runningAsRootOrAdmin = Set.of(new NTSystem().getGroupIDs()).contains("S-1-16-12288");
```
Also move the constant out to a field to make it more readable.

2021-09-20 05:28 UTC, Proximyst commented on patches/server/0806-Add-root-admin-user-detection.patch
> ++    private static final boolean runningAsRootOrAdmin;
`UPPER_SNAKE_CASE`

2021-09-20 06:03 UTC, me4502 commented on patches/server/0806-Add-root-admin-user-detection.patch
> ++            DedicatedServer.LOGGER.error("YOU ARE RUNNING THIS SERVER AS AN ADMINISTRATIVE OR ROOT USER. THIS IS NOT ADVISED.");
In order to minimise the amount of info about why this is a problem, could you please link to this post?

https://madelinemiller.dev/blog/root-minecraft-server/

I feel keeping the first line, then replacing the rest with "FOR MORE INFORMATION, SEE <link>" is probably the most concise wording. But if you have a better idea that also works

2021-09-20 08:18 UTC, NoahvdAa commented on patches/server/0806-Add-root-admin-user-detection.patch
> ++            DedicatedServer.LOGGER.error("YOU ARE RUNNING THIS SERVER AS AN ADMINISTRATIVE OR ROOT USER. THIS IS NOT ADVISED.");
Replaced the third line with a link to your article. I feel like keeping the second line is important, to clearly signal that there is a risk.

2021-09-20 08:31 UTC, Proximyst approved these changes
Looks good

2021-09-20 08:31 UTC, Proximyst commented on patches/server/0806-Add-root-admin-user-detection.patch
> ++            DedicatedServer.LOGGER.error("****************************");
I'd argue error is the wrong level: this should be a `warn`.

2021-10-02 07:54 UTC, MiniDigger approved these changes

2021-10-02 09:34 UTC, merged