config for disabling entity tag tags
PaperMC/Paper pull request #6613
Opened 2021-09-15 21:54 UTC by Machine-Maker

2021-09-17 08:15 UTC, Proximyst requested changes

2021-09-17 08:15 UTC, Proximyst commented on patches/server/0807-config-for-disabling-entity-tag-tags.patch
> ++                    if (player == null || !minecraftserver.getPlayerList().isOp(player.getGameProfile())) {
Should use permissions

2021-09-17 08:15 UTC, Proximyst commented on patches/server/0807-config-for-disabling-entity-tag-tags.patch
> ++                                nbtPathArgument.parse(new com.mojang.brigadier.StringReader(tag)).remove(itemNbt.getCompound("EntityTag"));
This seems real wasteful...

2021-09-22 19:06 UTC, Machine-Maker commented on patches/server/0807-config-for-disabling-entity-tag-tags.patch
> ++                    if (player == null || !minecraftserver.getPlayerList().isOp(player.getGameProfile())) {
Now using `minecraft.nbt.place`

2021-09-22 19:07 UTC, Machine-Maker commented on patches/server/0807-config-for-disabling-entity-tag-tags.patch
> ++                                nbtPathArgument.parse(new com.mojang.brigadier.StringReader(tag)).remove(itemNbt.getCompound("EntityTag"));
Yep, it certainly is. Moved the `NbtPath` creating to PaperWorldConfig so it happens once. Has the benefit of notifying users of an invalid tag at startup as well.

2021-12-09 17:45 UTC, Machine-Maker commented
Rebased for 1.18

2022-12-17 06:03 UTC, Machine-Maker commented
Rebased for 1.19.3

2022-12-17 16:59 UTC, jpenilla approved these changes
I'd like for this to be added to the docs as well

2022-12-27 21:34 UTC, Owen1212055 approved these changes
Tested, looks good.
Do note that there are some rather simple PRS that it may be nice to squash into this config update.
See: 
https://github.com/PaperMC/Paper/pull/7231
https://github.com/PaperMC/Paper/pull/7622

2022-12-28 01:52 UTC, Machine-Maker commented
I think we'll hold off. It's really not an issue to increase the config version frequently.

2022-12-28 02:59 UTC, merged