Re-readd root/admin user detection
PaperMC/Paper pull request #6703
Opened 2021-10-02 18:47 UTC by NoahvdAa

This PR re-adds the root reverted in e8830b27. The check was throwing false positives because of a OpenJDk bug (no issue # yet, will add here later). This PR uses a different method for getting the UID (executing the id command), which isn't affected by the openjdk issue.

2021-10-02 18:51 UTC, clrxbl commented
Why run `id -u` with the username specifically?
The command should should already return the current user's ID.

2021-10-02 18:53 UTC, Prof-Bloodstone commented
Wondering if it'd be better to use available API as before, and if it returns root as user, then use the command to confirm it?
This way it could potentially be faster and doesn't require for the `id` binary to be on the system most of the time.

2021-10-02 19:49 UTC, Proximyst requested changes

2021-10-02 19:49 UTC, Proximyst commented on patches/server/0814-Add-root-admin-user-detection.patch
> ++                try (final InputStream inputStream = Runtime.getRuntime().exec("id -u").getInputStream()) {
Should use processes.

2021-10-02 22:25 UTC, NoahvdAa commented on patches/server/0814-Add-root-admin-user-detection.patch
> ++                try (final InputStream inputStream = Runtime.getRuntime().exec("id -u").getInputStream()) {
Is there an advantage to spawning a process with something like a ProcessBuilder (I'm assuming that's what you're talking about here) vs spawning one via `Runtime#exec`?

2021-10-03 02:39 UTC, me4502 commented
How common is it for servers to not contain the id binary?

I'd question whether it's better to have it default to warning when it's missing - but guess it depends how often it's missing 

Logic being a host can easily fix it themselves if it shows up due to missing id binary

2021-10-08 12:11 UTC, lynxplay requested changes

2021-10-08 12:11 UTC, lynxplay commented on patches/server/0814-Add-root-admin-user-detection.patch
> ++                // Due to an OpenJDK bug, UnixSystem#getUid incorrectly returns 0 when the user doesn't have a username.
Should probably now also reference the [openjdk issue](https://bugs.openjdk.java.net/browse/JDK-8274721) to ease traceability/link to more information as to why this double check had to be implemented.

2021-10-09 07:33 UTC, me4502 approved these changes

2021-10-09 08:44 UTC, Proximyst approved these changes

2021-10-09 09:29 UTC, merged