Convert section chars in components to components in more places
PaperMC/Paper pull request #6704
Opened 2021-10-02 19:12 UTC by Machine-Maker

Fixes #4888

Does the same conversion in more places to ensure comparisons are correct. Section chars in top-level components are now converted to json structure. This doesnt touch section chars in children components, but it didnt originally do that either.

2021-12-06 19:29 UTC, Machine-Maker commented
Rebased for 1.18

2022-02-05 01:34 UTC, electronicboy approved these changes

2022-03-15 22:44 UTC, Machine-Maker commented
Rebased for 1.18.2

2022-12-12 00:13 UTC, Machine-Maker commented
Rebased for 1.19.3

2023-08-16 21:34 UTC, Machine-Maker commented
This now also fixes https://github.com/PaperMC/Paper/issues/9399

2023-08-16 22:09 UTC, kashike requested changes

2023-08-16 22:09 UTC, kashike commented on patches/server/0434-Update-itemstack-legacy-name-and-lore.patch
> ++        return PaperAdventure.asJson(adventures, false);
```suggestion
+        return asJson(adventures, false);
```

2023-08-16 22:09 UTC, kashike commented on patches/server/0434-Update-itemstack-legacy-name-and-lore.patch
> ++                jsons.add(ItemStack.convert(GsonComponentSerializer.gson().serialize(component)));
Have the conversion method be in `PaperAdventure`.

2024-09-24 00:01 UTC, Machine-Maker commented
Closing this as we've already removed any existing logic we had that did this. As more and more move to components, its less and less feasible to try and fix plugin mistakes here. Will be closing the linked issues as well.

2024-09-24 00:01 UTC, closed without merging