Thunder chance
PaperMC/Paper pull request #6709
Opened 2021-10-03 06:18 UTC by adrian-kong

Lets you configure the chance of thunder in each chunk #6688 ?
I edited the patch this time :D

2021-10-03 08:16 UTC, kennytv requested changes

2021-10-03 08:16 UTC, kennytv commented on patches/server/0035-Disable-thunder-and-add-chance-config.patch
> ++        log("Thunder has a 1/" + thunderChance + " chance of striking each chunk.");
Move this into the disableThunder method, maybe rename that. Math.max the value so it can't be negative or 0, and no log message is needed here

2021-10-03 09:42 UTC, MiniDigger commented
could you please attach a docs PR that documents this new option? 
https://github.com/PaperMC/PaperDocs/blob/master/source/server/configuration.rst

2021-10-03 09:43 UTC, MiniDigger commented on patches/server/0035-Disable-thunder-and-add-chance-config.patch
>  +    public boolean disableThunder;
the different order here compared to the method below bothers me more than I would like to admit :D

2021-10-03 09:43 UTC, MiniDigger approved these changes
lgtm!

2021-10-03 09:45 UTC, MiniDigger commented
oh, the build is failing, you most likely forgot to do a apply/rebuild round trip after editing the patch.
you should locally apply all patches, fix the conflict and rebuild. if you don't know how to do that, either join #paper-dev on discord or just leave it be for the merger to handle while rebasing later.

2021-10-03 09:58 UTC, adrian-kong commented
> could you please attach a docs PR that documents this new option? https://github.com/PaperMC/PaperDocs/blob/master/source/server/configuration.rst

is this it https://github.com/PaperMC/PaperDocs/pull/117

2021-10-03 10:00 UTC, adrian-kong commented
> oh, the build is failing, you most likely forgot to do a apply/rebuild round trip after editing the patch. you should locally apply all patches, fix the conflict and rebuild. if you don't know how to do that, either join #paper-dev on discord or just leave it be for the merger to handle while rebasing later.

got confused with the patching i just edited it

2021-10-03 10:00 UTC, lynxplay commented
> > could you please attach a docs PR that documents this new option? https://github.com/PaperMC/PaperDocs/blob/master/source/server/configuration.rst
> 
> is this it [PaperMC/PaperDocs#117](https://github.com/PaperMC/PaperDocs/pull/117)

Yes! That looks good :+1:

2021-10-07 18:59 UTC, molor commented
Reactively fast creation and slow, like a turtle, merging.. ):

2021-10-07 19:01 UTC, aurorasmiles commented
> 
> 
> Reactively fast creation and slow, like a turtle, merging.. ):

You're always welcome to test and review PRs, that helps us :)

2021-10-07 19:04 UTC, electronicboy commented
Y U NO MERGE BROKEN PR?! WTF?!
(but, seriously, please refrain from useless commentary, this is open source software where you're owed fuck all)

as for the PR in hand, maybe shove the config under game mechanics? or maybe a better name would be better here? I kinda hate brigadiering this type of stuff on random PRs but not fond of everything basically being a root setting or shoved under some "and 200 other configs" in a branch, not too sure

2021-10-24 14:54 UTC, lynxplay commented
Should be closed in favour of #6823, as upstream implemented this feature.

2021-10-24 15:00 UTC, aurorasmiles commented
Thanks for the heads up!
Implemented Upstream with https://github.com/PaperMC/Paper/pull/6823

2021-10-24 15:00 UTC, closed without merging