Add more datapack API
PaperMC/Paper pull request #6711
Opened 2021-10-03 10:29 UTC by NoahvdAa

Adds a new `DatapackManager#loadDatapack` method, allowing users to load datapacks from the API.

Fixes #4654.

2021-12-13 21:10 UTC, NoahvdAa commented
Rebased for 1.18!

2022-03-06 21:59 UTC, NoahvdAa commented
Rebased for 1.18.2, label can be removed.

2022-03-06 22:10 UTC, Machine-Maker requested changes

2022-03-06 22:10 UTC, Machine-Maker commented on patches/api/0296-Datapack-API.patch
> ++     * Loads a new datapack and enables it.
```suggestion
+     * Loads a new datapack and optionally enables it.
```

2022-03-06 22:10 UTC, Machine-Maker commented on patches/api/0296-Datapack-API.patch
> ++}
Do we need a custom exception? All its doing is a custom string.format, can't that just be done in the FileNotFoundException ctor?

2022-03-07 07:18 UTC, NoahvdAa commented
Thanks, fixed

2022-03-20 10:06 UTC, closed without merging