Fix cancelled snow bucket placement
PaperMC/Paper pull request #6751
Opened 2021-10-08 20:24 UTC by Machine-Maker

SolidBucketItems need to use the existing capturedBlockStates, but have their block place event handled elsewhere, so the event called in ItemStack needs to be skipped.

Fixes #6630

2021-12-07 20:55 UTC, Machine-Maker commented
Rebased for 1.18

2021-12-11 08:55 UTC, lerokko commented
I am unfamiliar with the merging approval procedure, forgive me if this is the wrong place to ask. But this bug is one of 2 that keeps me from updating. Is there any eta on when or if this is merged at all?

2021-12-24 20:59 UTC, Owen1212055 requested changes
It seems like your fix causes an unintended desync, where ghost blocks will appear but the server will be fine. I'm guessing it works fine if you are targetting the affected block since it's resent to the client late.

https://user-images.githubusercontent.com/23108066/147372065-fcd05d08-9e72-4a92-b2b4-10cdea1be65c.mp4

2021-12-24 22:01 UTC, Machine-Maker commented
Rebased.

And @Owen1212055 I think I fixed that issue. I remember when I originally made my PR thinking that I must be missing smth, but I did only test with direct placing, and so the client is updated to the clicked on block not changing.

2021-12-24 23:12 UTC, Owen1212055 approved these changes
Tested fix, works!

2022-01-23 20:43 UTC, electronicboy approved these changes

2022-02-09 18:03 UTC, NoahvdAa approved these changes
Works!

2022-02-09 21:16 UTC, Rollczi approved these changes

2022-02-12 13:56 UTC, merged