Strip raytracing for entity line of sight
PaperMC/Paper pull request #6765
Opened 2021-10-11 19:33 UTC by PaulBGD

The IBlockAccess#rayTrace method is very wasteful in both allocations,
and in logic. While EntityLiving#hasLineOfSight provides static
parameters for collisions with blocks and fluids, the method still does
a lot of dynamic checks for both of these, which result in extra work.
As well, since the fluid collision option is set to NONE, the entire
fluid collision system is completely unneeded, yet used anyways.

This is also used for fast line of sight merging in ItemEntity, as it
follows the same rules as hasLineOfSight.

2021-10-11 19:39 UTC, lynxplay requested changes

2021-10-11 19:39 UTC, lynxplay commented on patches/server/0826-Strip-raytracing-for-entity-line-of-sight.patch
> ++        if (iblockdata.isAir()) return null; // Tuinity - optimise air cases
The `// Tunity` comment probably slipped through :+1: should be `// Paper` or, as all this is in a paper comment block, just a comment maybe ?

2021-10-11 19:40 UTC, PaulBGD commented on patches/server/0826-Strip-raytracing-for-entity-line-of-sight.patch
> ++        if (iblockdata.isAir()) return null; // Tuinity - optimise air cases
Whoops, thought I got that removed. It was copied from an opt added to the original `rayTraceBlockDirect` by leaf, I'll just remove the comment now that this is all squished down.

2021-10-29 23:10 UTC, PaulBGD commented
Bump

2021-10-31 17:29 UTC, Spottedleaf commented
This looks fine

2021-11-22 18:29 UTC, PaulBGD commented
Closing as it'd have to be rebased/redone for 1.18 anyways.

2021-11-22 18:29 UTC, closed without merging