Add ItemFactory#getMonsterEgg API
PaperMC/Paper pull request #6772
Opened 2021-10-14 18:28 UTC by BillyGalbreath

This adds a lovely convenience method for creating an `ItemStack` of a mob's spawner egg from a mob's `EntityType`

2021-10-14 18:39 UTC, Machine-Maker requested changes

2021-10-14 18:39 UTC, Machine-Maker commented on patches/server/0827-Add-ItemFactory-getMonsterEgg-API.patch
> ++    public static final Map<EntityType<? extends Mob>, SpawnEggItem> BY_ID = Maps.newIdentityHashMap(); // Paper - private -> public
Use access transformer

2021-10-16 04:27 UTC, Machine-Maker approved these changes

2021-10-16 13:16 UTC, MiniDigger approved these changes

2021-10-20 21:35 UTC, merged