Add more Llama API
PaperMC/Paper pull request #6773
Opened 2021-10-14 18:28 UTC by BillyGalbreath

This adds some useful API to Llamas, including two new events

2021-10-14 18:42 UTC, Machine-Maker requested changes

2021-10-14 18:42 UTC, Machine-Maker commented on patches/server/0827-Add-more-Llama-API.patch
> ++    public Llama getCaravanTail() {
Probably better to just access transform the field instead of adding a getter for it

2021-10-15 11:28 UTC, lynxplay commented on patches/api/0338-Add-more-Llama-API.patch
> ++import org.jetbrains.annotations.Nullable;
Should probably be replaced either with its fully qualified name in the respective usecases (tho the ranged entity api imports a few lines above seems to disagree with the guidelines :joy:)

2021-10-15 11:28 UTC, lynxplay commented on patches/api/0338-Add-more-Llama-API.patch
> ++    boolean hasCaravanTail();
Is this method actually useful ? I know it maps an internal method directly to the API but it seems to be just a somewhat useful shortcut for `getCaravanTail() != null`.

2021-10-15 11:39 UTC, Proximyst approved these changes
Looks OK to me.

2021-10-15 11:39 UTC, Proximyst commented on patches/server/0827-Add-more-Llama-API.patch
> +-
Don't drop this line, please. Same applies for other places where such is done.

2021-10-15 11:39 UTC, Proximyst commented on patches/api/0338-Add-more-Llama-API.patch
> ++    boolean hasCaravanTail();
It's common practice to have this method in the API for some reason. I don't find it useful personally, but it's not a big deal to just have it.

Note also that it's not even useful in terms of IDE (and Kotlin) support for it, as an IDE will still yell at:

```java
if (!llama.hasCaravanTail()) {
  return;
}

llama.getCaravanTail().isOp(); // IntelliJ will say it's potentially throwing an NPE.
```

2021-10-16 04:32 UTC, Machine-Maker approved these changes

2021-10-16 13:15 UTC, MiniDigger approved these changes

2022-02-26 12:11 UTC, closed without merging