EntityPickupItemEvent
PaperMC/Paper pull request #679
Opened 2017-05-05 07:06 UTC by BillyGalbreath

I finally found a need to cancel zombie/skeleton from picking up items. Upon searching for a way to do it, I found many requests to both Spigot and Bukkit dating as far back as 2012 (maybe older) for this event. Since it's now mid-way through 2017, I figure its time we have this.

Tested with sample plugin:

`public class Test extends JavaPlugin implements Listener {
    @Override
    public void onEnable() {
        getServer().getPluginManager().registerEvents(this, this);
    }

    @EventHandler
    public void onEntityPickupItem(EntityPickupItemEvent event) {
        ItemStack stack = event.getItem().getItemStack();

        System.out.println(event.getEntity().getType()
                + " tried to picked up "
                + stack.getAmount()
                + "x "
                + stack.getType()
                + " but event was cancelled");

        event.setCancelled(true);
    }
}`

2017-06-11 20:34 UTC, kashike requested changes

2017-06-11 20:34 UTC, kashike commented on Spigot-API-Patches/0051-EntityPickupItemEvent.patch
> ++    public boolean isCancelled() {
`@Override`

2017-06-11 20:34 UTC, kashike commented on Spigot-API-Patches/0051-EntityPickupItemEvent.patch
> ++    public void setCancelled(boolean cancel) {
`@Override`

2017-06-11 20:34 UTC, kashike commented on Spigot-Server-Patches/0211-EntityPickupItemEvent.patch
> ++                    new CraftItem(this.world.getServer(), entityitem));
squash these into one line

2017-06-11 21:12 UTC, kashike approved these changes

2017-06-12 00:41 UTC, zachbr approved these changes

2017-06-12 00:42 UTC, merged