Bonemeal API
PaperMC/Paper pull request #6794
Opened 2021-10-17 19:02 UTC by Owen1212055

This adds some bonemeal api with a blockstate predicate. I am aware there is already api to simulate bonemeal, but this offers the advantage of being able to chose which blocks actually get modified.

2021-10-17 19:04 UTC, NoahvdAa commented on patches/server/0827-BoneMeal-API.patch
> ++++ b/src/main/java/net/minecraft/world/item/BoneMealItem.java
Missing paper comments for this file

2021-10-17 19:12 UTC, lynxplay requested changes

2021-10-17 19:12 UTC, lynxplay commented on patches/server/0827-BoneMeal-API.patch
> ++        var context = new net.minecraft.world.item.context.UseOnContext(this.getHandle(), null, net.minecraft.world.InteractionHand.MAIN_HAND, net.minecraft.world.item.Items.BONE_MEAL.getDefaultInst
The variable `blockFace` does not exist here. I am guessing this should have been `face`.

2021-10-17 19:14 UTC, Owen1212055 commented on patches/server/0827-BoneMeal-API.patch
> ++        var context = new net.minecraft.world.item.context.UseOnContext(this.getHandle(), null, net.minecraft.world.InteractionHand.MAIN_HAND, net.minecraft.world.item.Items.BONE_MEAL.getDefaultInst
Yea was just onto fixing that, thanks tho!

2021-10-20 03:24 UTC, Machine-Maker requested changes

2021-10-20 03:24 UTC, Machine-Maker commented on patches/server/0827-BoneMeal-API.patch
> ++        world.captureBlockStates = false;
I think this might be a situation where you want to set the capture variables back to what they were before,

2021-10-20 03:24 UTC, Machine-Maker commented on patches/server/0827-BoneMeal-API.patch
> ++        }
I'm concerned the capturedBlockStates collection will sometimes have blocks in it already when a plugin calls this method. Say during a block place event handler or something. So you really need to only check blockstates that have been added directly as a result of the applyBonemeal call, not ones that were already captured before.

2021-11-13 19:45 UTC, Owen1212055 commented
I'd like your opinion on this, I now store the previous collections + if it is capturing before and reset it after. But i'd like to see if I should also capture the blocks that the plugin updates via the predicate or just ignore it (like I currently ignore it).

2021-12-26 18:39 UTC, Owen1212055 commented
Rebased

2022-02-25 13:46 UTC, Owen1212055 commented
Feedback still appreciate on this, and I still think that this API would be useful.

2022-04-27 11:55 UTC, Owen1212055 commented
Still relevant and looking for feedback. :)

2022-06-05 12:16 UTC, NoahvdAa commented on patches/api/0351-BoneMeal-API.patch
> ++     * Modification done in the predicate are respected
```suggestion
+     * Modifications done in the predicate are respected
```

2022-06-05 12:16 UTC, NoahvdAa commented on patches/server/0839-BoneMeal-API.patch
> ++        var context = new net.minecraft.world.item.context.UseOnContext(this.getHandle(), null, net.minecraft.world.InteractionHand.MAIN_HAND, net.minecraft.world.item.Items.BONE_MEAL.getDefaultInst
var 😭

2022-06-06 04:06 UTC, Owen1212055 commented on patches/server/0839-BoneMeal-API.patch
> ++        var context = new net.minecraft.world.item.context.UseOnContext(this.getHandle(), null, net.minecraft.world.InteractionHand.MAIN_HAND, net.minecraft.world.item.Items.BONE_MEAL.getDefaultInst
I have a complicated relationship with var.

2024-04-12 21:22 UTC, closed without merging