Fixed a bunch of missing method mappings
PaperMC/Paper pull request #6810
Opened 2021-10-21 04:25 UTC by Machine-Maker

Just found with a simple `\s\w\(` regex search, probably more out there.

2021-10-21 14:34 UTC, MiniDigger approved these changes

2021-10-21 18:19 UTC, jpenilla commented on build-data/mappings-patch.tiny
> +c	net/minecraft/core/dispenser/IDispenseBehavior$24	net/minecraft/core/dispenser/DispenserItemBehavior$24
`DispenserItemBehavior` doesn't exist, it's `DispenseItemBehavior`, additionally this mapping is already present in the generated mappings, the issue seems to maybe be with mercury not remapping it properly? That is unless the inner classes somehow got mismatched in the generated mappings. Either way this mapping is wrong because the inner class name is not 24 in both mappings.

2021-10-21 18:26 UTC, jpenilla requested changes
I don't have time to review every single mapping here, and I think that actually outlines the problem with this PR, is the maintenance burden for having this many mapping patches which need to be manually reviewed and updated for each version.

I think rather than just grepping the source for missed mappings, we should focus on mapping things which we actually notice and use which would be nice to give a proper name to.

The methods where CraftBukkit added parameters are probably all fine, but they aren't excluded from needing checking and updating with even a minor revision bump. And stuff like the `DispenseItemBehavior` mapping I commented on should questionably be in the mappings patch at all.

2021-10-21 18:48 UTC, Machine-Maker commented on build-data/mappings-patch.tiny
> +c	net/minecraft/core/dispenser/IDispenseBehavior$24	net/minecraft/core/dispenser/DispenserItemBehavior$24
Huh, why does it actually work then? it does successfully remap the method name inside `DispenseItemBehavior`, either way ill change it. 

As for it not being 24, I just used intellij's structure view tab to see what number it was, and both have it as 24.

2021-10-25 21:45 UTC, jpenilla commented on build-data/mappings-patch.tiny
> +c	net/minecraft/core/dispenser/IDispenseBehavior$24	net/minecraft/core/dispenser/DispenserItemBehavior$24
https://github.com/PaperMC/paperweight/pull/99

2021-11-04 04:55 UTC, jpenilla approved these changes

2021-11-04 07:48 UTC, MiniDigger approved these changes

2021-11-04 14:08 UTC, merged