Allow Changing of Player Sample in ServerListPingEvent
PaperMC/Paper pull request #682
Opened 2017-05-06 21:31 UTC by willies952002

This will allow plugins to change what a player sees when they hover over the player count on the multiplayer server list when the `ServerListPingEvent` is fired.

2017-05-06 23:31 UTC, jonesdj1 commented
This would be fantastic.

2017-05-15 15:35 UTC, Zbob750 commented
I would rather see this just accept player objects until we get our own profile API in place.
We can add some to-do comments in place to handle profiles once that is in.

2017-05-16 02:14 UTC, willies952002 commented
I don't see how using player objects would be practical in the sense that this is meant for adding the ability to easily modify the "Player Sample", which various servers have taken advantage of by using either Packets or Bungeecord's ability to modify it directly during the `ProxyPingEvent`, allowing them to do things such as: ![this](https://i.domnian.com/8f2d6918.png)

If anything, I could switch it to accepting simple Strings then build the profiles from there in server code

2017-05-16 02:34 UTC, kashike commented
I don't agree with using `Player`s.

2017-05-16 03:33 UTC, Zbob750 commented
I don't really like it either but this shouldn't be both a ServerListPingEvent and an authlib profile API PR.

2017-05-16 06:55 UTC, electronicboy commented
Wouldn't it make more sense to expose that as a Map<String, Player>, Player included so that we at least know who is inside that, as well as a String so that they can actually control what is going to be presented to the client. So long as the code following the event accepts that the value is potentially going to be null, I feel that that is a sane option and would likely be much more preferred by developers (and more in line with existing API design/behavior)

2017-06-12 18:59 UTC, aikar requested changes
I think this API for now and the future only needs to be a `List<String>`, and maybe named `setSampleText(List<String>);`

Since the profiles are not bound to real players, there's no benefit to using Profiles or Player objects.

Lets just use Strings, which removes the need to add the authlib to the PR.

2017-06-12 18:59 UTC, aikar commented on Spigot-API-Patches/0051-Allow-Changing-of-Player-Sample-in-ServerListPingEve.patch
> ++    public void setSample(java.util.List<com.mojang.authlib.GameProfile> profiles) {
See comment feedback

2017-07-27 03:06 UTC, aikar approved these changes

2017-07-27 03:08 UTC, aikar commented
Manually merged in c86f61f8afd3b99d490e11690091aca5731d28b0

2017-09-09 19:06 UTC, RoboMWM commented
So this broke plugins that iterate over the event to remove players from the list (and thus the player count that appears). Are all plugins supposed to do what EssentialsX does (detect if paper, and use reflection to get and remove players) https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/EssentialsServerListener.java or should compatibility be added?

2017-09-13 00:16 UTC, Zbob750 commented
Actually no. I don't want this on this PR.

2017-09-13 00:16 UTC, closed without merging