Per world ticks per spawn settings
PaperMC/Paper pull request #6891
Opened 2021-11-13 20:37 UTC by Machine-Maker

Fixes #6838

2021-11-13 20:53 UTC, kennytv requested changes

2021-11-13 20:53 UTC, kennytv commented on patches/server/0844-Per-world-ticks-per-spawn-settings.patch
> ++    public Reference2IntMap<MobCategory> perWorldTicksPerSpawns = new Reference2IntOpenHashMap<>(NaturalSpawner.SPAWNING_CATEGORIES.length);
Why does that use a reference map

2021-11-13 20:53 UTC, kennytv commented on patches/server/0844-Per-world-ticks-per-spawn-settings.patch
> ++            perWorldSpawnLimits.put(category, getInt("ticks-per-spawn." + category.getName(), perWorldTicksPerSpawns.getInt(category)));
lowercase category name

2021-11-13 20:53 UTC, kennytv commented on patches/server/0844-Per-world-ticks-per-spawn-settings.patch
> ++            perWorldSpawnLimits.put(category, getInt("ticks-per-spawn." + category.getName(), perWorldTicksPerSpawns.getInt(category)));
Wrong map used

2022-04-30 16:37 UTC, electronicboy approved these changes

2022-07-03 21:36 UTC, Machine-Maker commented
Rebased for 1.19

2024-03-03 21:36 UTC, kennytv approved these changes

2024-03-03 22:50 UTC, Owen1212055 approved these changes

2024-03-03 22:53 UTC, merged