Port generator settings (flat bedrock) to 1.18
PaperMC/Paper pull request #6944
Opened 2021-11-28 12:45 UTC by NoahvdAa

1.18 changed bedrock generation around a bunch, so creating our own ConditionSource seemed like the cleanest solution.

2021-11-28 13:11 UTC, Machine-Maker reviewed
Are you making any changes to anything in the SurfaceRules class besides the dev fixes? I don't think you have to do that at all then, just let it not be imported, and you dont have to fix anything.

2021-11-28 13:29 UTC, NoahvdAa commented
> Are you making any changes to anything in the SurfaceRules class besides the dev fixes? I don't think you have to do that at all then, just let it not be imported, and you dont have to fix anything.

I could've sworn the access transformers didn't work without the decompile fix, looks like I was wrong.

2021-11-28 18:42 UTC, Machine-Maker requested changes

2021-11-28 18:42 UTC, Machine-Maker commented on patches/server/0344-Generator-Settings.patch
> ++    private final record PaperBedrockGradientRule(net.minecraft.resources.ResourceLocation randomName, VerticalAnchor trueAtAndBelow, VerticalAnchor falseAtAndAbove, boolean invert) implements Surfa
1. This isn't a rule, its a ConditionSource
2. I think you mean `Taken from SurfaceRules$VerticalGradientConditionSource`
3. (optional) make randomName a String just to remove the need for the fully qualified import in the record ctor and in usages of this condition source.

2021-11-28 18:42 UTC, Machine-Maker commented on patches/server/0344-Generator-Settings.patch
> ++    public net.minecraft.world.level.Level getWorld() { return this.level; } // Paper
Throw an exception that's not an NPE if this is called when level is null I think. I suppose its possible if some plugin creates a WorldGenerationContext

2021-11-30 18:26 UTC, closed without merging

2021-11-30 18:31 UTC, kennytv commented
Reopen to master plz