Port flat bedrock (generator settings) to 1.18
PaperMC/Paper pull request #6960
Opened 2021-11-30 18:52 UTC by NoahvdAa

#6944 but targeted to amster

2021-12-01 01:08 UTC, Machine-Maker approved these changes

2021-12-01 01:21 UTC, kashike requested changes

2021-12-01 01:21 UTC, kashike commented on patches/server/0345-Flat-bedrock-generator-settings.patch
> ++        generateFlatBedrock = getBoolean("generator-settings.flat-bedrock", false);
```suggestion
+    public boolean generateFlatBedrock = false;
+    private void generatorSettings() {
+        generateFlatBedrock = getBoolean("generator-settings.flat-bedrock", this.generateFlatBedrock);
```

2021-12-01 01:23 UTC, Machine-Maker commented on patches/server/0345-Flat-bedrock-generator-settings.patch
> ++        generateFlatBedrock = getBoolean("generator-settings.flat-bedrock", false);
handled

2021-12-01 01:24 UTC, kashike approved these changes

2021-12-01 01:31 UTC, merged

2021-12-05 10:10 UTC, molor commented
It's fine that `generator-settings.flat-bedrock` doesn't appear in `paper.yml` by default if I delete it and restart the server?