FallingBlock auto expire setting
PaperMC/Paper pull request #7037
Opened 2021-12-05 20:08 UTC by Owen1212055

This gives the ability to disable falling blocks from being able to expire automatically.
This also saves with nbt under ``DisableAutoExpire``, although I am not sure this behavior is needed.

2021-12-10 03:04 UTC, imDaniX commented
Maybe a couple of options to actually set the expire timers instead? Also, what's the use-case for this nbt?

2021-12-10 03:59 UTC, Owen1212055 commented
> Maybe a couple of options to actually set the expire timers instead? Also, what's the use-case for this nbt?

What do you propose? And I’m not sure, since I don’t know if new fields like this should be serialized into the entity or not.

2021-12-10 05:56 UTC, imDaniX commented
> What do you propose? So like modifying it without changing the entity age? (Currently set age modifies this timer and the entity age) And I’m not sure, since I don’t know if new fields like this should be serialized into the entity or not.

Sorry, actually did read an entire PR wrong.

2021-12-24 00:18 UTC, Owen1212055 commented
Simplified by removing the tag, this is now a simple boolean.
Current variables for falling blocks by spigot aren't retained either... so I felt perhaps it wasn't needed to keep it.

This is a rather simple API addition and is ready.

2022-03-11 21:41 UTC, Owen1212055 commented
Rebased

2022-05-06 14:35 UTC, kennytv requested changes

2022-05-06 14:35 UTC, kennytv commented on patches/server/0877-FallingBlock-auto-expire-setting.patch
> ++            this.autoExpire = nbt.contains("Paper.AutoExpire");
get the boolean value

2022-05-06 14:37 UTC, Owen1212055 commented on patches/server/0877-FallingBlock-auto-expire-setting.patch
> ++            this.autoExpire = nbt.contains("Paper.AutoExpire");
LOL nice, will do

2022-05-06 15:08 UTC, Owen1212055 commented
Rebased and fixed

2022-05-06 15:09 UTC, kennytv approved these changes

2022-05-06 15:21 UTC, merged