[ci skip] Add nullable annotation to field
PaperMC/Paper pull request #7042
Opened 2021-12-06 00:56 UTC by Owen1212055

Not sure if this change needs to go through, but it's just a one-line change. 

Intellij always marks this field as not able to be null, and although it's not null when the entity is alive it can be null when it's dead. Generally just a bit misleading.

2021-12-06 12:27 UTC, kashike requested changes

2021-12-06 12:27 UTC, kashike commented on patches/server/0242-Add-Debug-Entities-option-to-debug-dupe-uuid-issues.patch
> ++    public @javax.annotation.Nullable net.minecraft.server.level.ChunkMap.TrackedEntity tracker; // Paper
```suggestion
+    public @org.jetbrains.annotations.Nullable net.minecraft.server.level.ChunkMap.TrackedEntity tracker; // Paper
```

2021-12-08 19:37 UTC, kashike approved these changes

2021-12-11 16:23 UTC, Owen1212055 commented
Rebased and should be ready

2021-12-13 04:30 UTC, Machine-Maker approved these changes

2021-12-13 04:31 UTC, merged