Call EntityKnockbackByEntityEvent on non-living entities (#5886)
PaperMC/Paper pull request #7058
Opened 2021-12-07 18:19 UTC by aerulion

Call the EntityKnockbackByEntityEvent when hitting non-living entities like minecarts. Closes issue #5886.

This is my first time working with patches, so I have no idea if I did it correctly. Please tell me if I did something wrong, and I will try to fix it as fast as I can.

2021-12-13 08:27 UTC, Machine-Maker requested changes
I don't think you can re-use this event for non-LivingEntitys. The event probably should've been created without using the LivingEntity interface, but that didnt happen.

2021-12-13 08:27 UTC, Machine-Maker commented on patches/api/0114-Add-EntityKnockbackByEntityEvent.patch
> ++        return super.getEntity();
You can't do this to the API. what if a plugin is using this event and is relying on this method returning a LivingEntity, as the contract currently states. but you change it to an entity (which I think is an ABI break), and suddenly the plugin is gonna have all sorts of problems.

2021-12-13 11:26 UTC, aerulion commented
Thank you for the review. I understand that changing existing API in that way is something that shouln't be done. Sorry for the inconvinience. In this case, would it be reasonable to implement new event like a "EntityPushEntityEvent"? That would be a bit misleading in my opinion since it is only fired when pushed by attacking, and only covers entities that aren't covered by the existing one.

2021-12-17 05:00 UTC, aerulion commented
I hope implementing this new event provides a better solution to the initial problem. I implemented the event not only for pushes by attack, but also for collisions, since I think it less misleading and generally more useful in this way. Furthermore, I hope this doesn't have a negative impact on performance, since the event gets called quite often.

2022-04-05 20:28 UTC, closed without merging