Update Log4J to snapshot
PaperMC/Paper pull request #7069
Opened 2021-12-10 01:19 UTC by darbyjack

2021-12-10 01:20 UTC, electronicboy approved these changes

2021-12-10 01:22 UTC, jpenilla requested changes
Should check whether `com.lmax:disruptor` should be bumped as well.

Also need to look into [whether https://github.com/PaperMC/Paper/blob/master/patches/server/0717-Set-AsyncAppender-dispatch-thread-to-be-a-daemon-thr.patch should be dropped](https://github.com/PaperMC/Paper/blob/4e355c488dc72e3c6701c69d2e4d6099449671b4/patches/server/0717-Set-AsyncAppender-dispatch-thread-to-be-a-daemon-thr.patch)

2021-12-10 01:22 UTC, jpenilla commented on patches/server/0831-Bump-log4j-to-snapshp.patch
> ++    maven("https://repository.apache.org/content/groups/snapshots/") {
This needs to go in libraryRepositories in the root build file as well.

2021-12-10 01:36 UTC, jpenilla approved these changes

2021-12-10 01:39 UTC, clrxbl commented
Log4J 2.15.0 is releasing, shouldn't we move to that?

2021-12-10 01:40 UTC, electronicboy commented
is it out yet?

2021-12-10 01:41 UTC, clrxbl commented
https://github.com/apache/logging-log4j2/pull/608#issuecomment-990474429

Seems like it might take a few hours, but it might be worth waiting for the full release instead of moving to snapshots right now. (especially with the fix already in Paper)

2021-12-10 01:42 UTC, electronicboy commented
fix is missing a few expects, hence snapshot; Will take them a few hours to release and then a few hours to propagate often, easy to just go for it and update post that

2021-12-10 02:02 UTC, merged

2021-12-10 03:02 UTC, ken-kentan commented
Do you have a plan to backport this update to 1.17.1?

2021-12-10 03:02 UTC, darbyjack commented
Working on that right now!

2021-12-10 09:17 UTC, Luca-Guettinger commented
Is there a plan to backport this update to 1.15.2?

2021-12-12 16:10 UTC, DumbGameMaker commented
if you need to mitigate the log4j exploit below 1.18, you can follow the instructions over [here](https://www.minecraft.net/en-us/article/important-message--security-vulnerability-java-edition)

2021-12-12 16:13 UTC, kennytv commented
The legacy builds have already been updated. See the Minecraft post for further information or just use Vanilla clients/recently updated mod loaders.