Optimize Util#sequence
PaperMC/Paper pull request #7115
Opened 2021-12-14 04:58 UTC by IzzelAliz

There's a huge increase on startup memory footprint after updating to 1.18. Investigation shows that `net.minecraft.Util#sequence` allocates O(n^2) memory on n-size list.

After some rough testing, my optimization can reduce at least 500mb startup RAM usage, as well as a slightly incresed chunk loading speed.

Allocation record:
![allocate](https://user-images.githubusercontent.com/21029868/145935592-1ca07eaa-13e3-45f6-8778-eea7e827683e.png)

Original implementation:
![orig](https://user-images.githubusercontent.com/21029868/145935628-de377aeb-8ce8-4cfe-889e-cc335972d882.png)

Optimization:
![opti](https://user-images.githubusercontent.com/21029868/145935634-e8c316ac-5dd2-4b51-94e3-493fe40dcf55.png)

2021-12-14 05:02 UTC, lynxplay commented on patches/server/0831-Optimize-Util-sequence.patch
> ++import java.util.ArrayList;
This should most likely be a fully qualified name e.g.
```java
final var list = new java.util.ArrayList<V>(future.size());
```

2021-12-16 10:37 UTC, kennytv requested changes

2021-12-16 10:37 UTC, kennytv commented on patches/server/0831-Optimize-Util-sequence.patch
> ++                var list = Lists.<V>newArrayListWithCapacity(futures.size());
Var makes this more awkward to read, just do `List<V> list = new ArrayList<>(futures.size());`

2021-12-16 10:37 UTC, kennytv commented on patches/server/0831-Optimize-Util-sequence.patch
> ++        return CompletableFuture.allOf(futures.toArray(new CompletableFuture[0]))
Put `new CompletableFuture[0]` into a private static final field to reuse

2021-12-17 20:52 UTC, kennytv approved these changes

2022-02-09 17:29 UTC, kennytv commented
Well looks like basically the same exact code will make it into 1.18.2

2022-02-12 13:28 UTC, merged