Bucketable API
PaperMC/Paper pull request #7204
Opened 2021-12-26 21:13 UTC by Owen1212055

This exposes the bucket-able interface used in Minecraft, which are used by entities like axolotls, fishes, and the upcoming tadpole mob.

  This was decided to be put into a separate patch. [see relevant conversation](https://canary.discord.com/channels/289587909051416579/555462289851940864/923108395656020019)

2021-12-26 22:42 UTC, Machine-Maker requested changes

2021-12-26 22:42 UTC, Machine-Maker commented on patches/server/0839-Bucketable-API.patch
> ++        return CraftItemStack.asCraftMirror(this.getHandle().getBucketItemStack());
This should be asBukkitCopy so it doesn't give any wrong ideas about modifying the returned itemstack having an effect on the entities ability to reflect changes (which it doesn't have)

2021-12-30 07:52 UTC, jpenilla approved these changes
Looks good, might want to look into also exposing `Bucketable.bucketMobPickup`, possibly a method to actually bucket the Bucketable, and another to get it's bucket item with nbt.

2021-12-30 19:40 UTC, Owen1212055 commented
> Bucketable

Yea thing is it basically uses raw interaction code, and fires an event. So I guess if it's really wanted it can be pr'd later, but this should be a good base if anyone would want to.

2021-12-30 19:57 UTC, Machine-Maker approved these changes

2021-12-30 19:58 UTC, merged