Player steer vehicle event
PaperMC/Paper pull request #7274
Opened 2022-01-03 17:15 UTC by rgnter

Event called when packet [`PacketPlayInSteerVehicle`](https://wiki.vg/Protocol#Steer_Vehicle) is sent by player.

2022-01-03 17:18 UTC, electronicboy commented
Wrong package, events generally fire before mutation, i also don't see the use of this as it's going to miss a lot of context, etc

2022-01-03 17:21 UTC, rgnter commented
Nothing gets mutated, and what do you mean by wrong package?

2022-01-03 17:22 UTC, Owen1212055 commented
We use the ``io.papermc.paper`` package instead.

2022-01-03 17:23 UTC, lynxplay commented
Your event should live in the io.papernc package. Additionally even without mutation (which idk why this event isn't allowing mutation in the first place) events should still be called before the internal logic happens.

2022-01-03 17:23 UTC, electronicboy commented
> Nothing gets mutated

So, what you're telling me, is that nothing on the server happens at all from this packet?

2022-01-03 17:24 UTC, rgnter commented
Alright sorry about that, can fix that. Anyways, if you do not approve of this API extension i am not going to bother. I believe the event should be rather a monitor of action.

2022-01-03 17:25 UTC, rgnter commented
The values get used by the server, thats right. But since the event is immutable I dont think its really necessary to call it before server logic(which does not mutate these data)

2022-01-03 17:25 UTC, Owen1212055 requested changes
Here is my advice here on some minor nit-picks.

2022-01-03 17:25 UTC, Owen1212055 commented on patches/api/0352-steer-vehicle-event.patch
> ++public class PlayerSteerVehicleEvent extends Event {
This should extend PlayerEvent, we have no way to actually get the player who steered this.

2022-01-03 17:25 UTC, Owen1212055 commented on patches/server/0842-steer-vehicle-event.patch
> ++        // paper end
Use new PlayerSteerVehicleEvent(...).callEvent();
Use a fully qualified import as well.

2022-01-03 17:26 UTC, rgnter commented
Alright, tottaly forgot about player in this event. I will modify the patch.

2022-01-03 17:27 UTC, electronicboy commented
The values get used by the server, which is thus mutating the state of the server

I don't see the need for random events slapped around the server for knowing that a packet was sent by the client, that's more protocol lib territory; I fail to see a useful application of this which wouldn't be better suited for proper API over different mechanisms exposed in the game

2022-01-03 17:29 UTC, rgnter commented
Alright, i won't bother modifying the patch if you do not see use of this event.

2022-01-03 17:29 UTC, closed without merging

2022-01-04 07:37 UTC, MiniDigger commented
useful application of this would be riding entities cat, I definitely do see a value here, I had to deal with this stuff myself in the past.
I would name the event in a way that its clear that this is the input from the client only.

2022-01-04 10:38 UTC, yannicklamprecht commented
> useful application of this would be riding entities cat, I definitely do see a value here, I had to deal with this stuff myself in the past.
> I would name the event in a way that its clear that this is the input from the client only.

PlayerMovementInputEvent?