Unregister the enchantments registered by plugins on reload
PaperMC/Paper pull request #7282
Opened 2022-01-04 20:42 UTC by shiina-xi-yu

I've meet bugs on slimefun and LiteXpansion with reload command. The LiteXpansion could not register its new class because there is already one old instance in the enchantment list. So it would use the old classes and cause some suspicious errors and memory leak. This commit would unregister the enchantments which is registered by plugins, so it can fix wrong things and avoid confusing errors.
By the way we have repaired the tab completion of the reload command.

2022-01-04 20:47 UTC, electronicboy requested changes
I err on stuff like this, hacking into internals is already not supported and when you do unsupported stuff, it's 100% on you to ensure that you clean up after yourself, so, am not exactly sure if this is something I desire, making CraftEnchantment forcefully return true also completely means that this is basically useless if a plugin actually registers stuff properly into the server?

2022-01-04 20:47 UTC, electronicboy commented on patches/api/0352-Unregister-the-enchantment-registered-by-plugin-when.patch
> ++import com.google.common.collect.Lists; // Paper
no

2022-01-04 20:47 UTC, electronicboy commented on patches/api/0352-Unregister-the-enchantment-registered-by-plugin-when.patch
> ++        return args.length == 1 ? Lists.newArrayList("permissions", "commands") : Collections.emptyList(); // Paper
This belongs in the patch that did this, not a new one

2022-01-04 20:47 UTC, electronicboy commented on patches/server/0842-Unregister-the-enchantment-registered-by-plugin-when.patch
> ++    {
bad code style

2022-01-04 20:50 UTC, Machine-Maker requested changes
I don't think this is something that needs to be in Paper. I agree with cat that this is internals, and registering custom enchants is not something that is supported (aka its not API). The reload command, (I assume you mean bukkit:reload, not minecraft:reload) is also not super well supported, but it does exist and its on plugins to correctly handle it.

2022-01-05 18:04 UTC, Lucky-fish commented
Lucky fish 0w0, [1/5/22 7:37 PM]
> I don't think this is something that needs to be in Paper. I agree with cat that this is internals, and registering custom enchants is not something that is supported (aka its not API). The reload command, (I assume you mean bukkit:reload, not minecraft:reload) is also not super well supported, but it does exist and its on plugins to correctly handle it.

So why don't you just remove ```org.bukkit.enchantments.Enchantments#registerEnchantment``` since it is not supported? And you marked it ```Generally not to be used from within a plugin```. but you didn't say it would cause undefined behavior or deprecate this method or move it to craft bukkit module. I suggest you may need to remove that API or move it to the craft bukkit since it should be used internally.
And for performance, you may need to use a local variable to store the tab complete results instead of creating a new list which would consume a lot of CPU.
And I think you should remove the /reload command since it is no longer supported and can avoid a lot of issues in the future.
Maybe you need to add a developer option to reload all the plugins dynamically in order to reduce time wasted on waiting the server restarts.

2022-01-05 18:40 UTC, Machine-Maker commented
> So why don't you just remove org.bukkit.enchantments.Enchantments#registerEnchantment since it is not supported? And you marked it Generally not to be used from within a plugin. but you didn't say it would cause undefined behavior or deprecate this method or move it to craft bukkit module. I suggest you may need to remove that API or move it to the craft bukkit since it should be used internally.


It's used in internals to match up nms enchantments with bukkit ones. That's why the boolean guarding it exists to prevent further registrations. It has to be on the api Enchantment abstract class, because the api class needs to have a byName/byKey to CraftEnchantment instances, which is what is passed as an argument to registerEnchantment from the nms Enchantments class with a new CraftEnchantment instance that wraps the nms Enchantment. This has to happen because the EnchantmentWrapper class has to have some way to get the *actual* CraftEnchantment implementation because the wrapper only redirects to that, it doesn't contain any information about the enchantment.

2022-01-05 18:42 UTC, Machine-Maker commented
> And I think you should remove the /reload command since it is no longer supported and can avoid a lot of issues in the future.
Maybe you need to add a developer option to reload all the plugins dynamically in order to reduce time wasted on waiting the server restarts.

There shouldn't be a need for *reloading* the server unless a plugin hasn't provided an option to only reload things that specific plugin needs, like a config file, or lang file, or something like that. As for `reducing time wasted` on server restarts, the paper server, with one plugin for "development" takes me like 4 seconds to startup. Hardly any wasted time.

2022-01-06 12:21 UTC, embeddedt commented
> As for reducing time wasted on server restarts, the paper server, with one plugin for "development" takes me like 4 seconds to startup.

Unless there has been some major improvement since 1.16, this is not the case for everyone. For development, I run Linux on a 4th gen i3 with 16GB RAM. The server still takes a good 20 seconds to start at minimum, and at least 5 seconds are spent loading libraries.

By comparison, reloading a plugin is almost instantaneous.

2022-01-06 12:36 UTC, electronicboy commented
given our intent as well as upstreams intent to move stuff away from hardcoded classes towards the Mojang registries, this PR is not a behavioural change that is maintainable and much of the mechanism used here is likely going to be removed in the future

I don't see the benefits of trying to maintain this API behavioural change for something which is going to change in the "near" future anyways, it's 100% on plugins messing with internals to clean up after themselves, and this is not a patch that would be retainable in the future, not is it written in a manner which I feel ultimately comfortable with, there are many ways in which plugins mess with this and some would be captured by this, some wouldn't.

2022-01-06 12:36 UTC, closed without merging