Fix EntityEquipment and related javadocs
PaperMC/Paper pull request #7380
Opened 2022-01-20 23:05 UTC by Machine-Maker

Sooooo many things wrong here.

The EntityEquipment javadocs state that various getters return "a copy of" which is not true for the CraftInventoryPlayer impl.

The much better fix, would be to make them actually return copies since there are setters, and I would be totally fine with doing that, but it might be considered too big of a break even tho the contract (via the javadoc) says they are copies.

Another issue here, is the nullability annotations are wrong on EntityEquipment because the two different impls of it use different logic. Would also prefer to make them all notnull, but that might also be a behavioral break.

2022-03-05 15:37 UTC, Owen1212055 requested changes
Looks good when looking at the underlying implementation.

Some missing paper comments tho

2022-03-05 15:37 UTC, Owen1212055 commented on patches/api/0054-Fix-upstream-javadocs.patch
> ++    public @Nullable ItemStack @NotNull[] getExtraContents();
Paper comment

2022-03-05 15:37 UTC, Owen1212055 commented on patches/api/0054-Fix-upstream-javadocs.patch
> ++    public @Nullable ItemStack @NotNull[] getArmorContents();
Paper comment

2022-03-20 04:02 UTC, Machine-Maker commented
Rebased for 1.18.2

2022-05-30 23:32 UTC, electronicboy approved these changes

2022-05-31 20:40 UTC, merged