Be able to set how many threads are allocated for handling chat
PaperMC/Paper pull request #7483
Opened 2022-02-16 21:36 UTC by OOP-778

Since I don't even know when chat has been handled by CachedThreadPool which from my knowledge should be only used in cases where you do a lot of stuff await for results then close it.
I really think making the chat handled by a configurable ForkJoinPool gives a faster experience for the handling of the messages and improves the performance of machine & server.

2022-02-16 21:56 UTC, electronicboy commented
I mean, the big aspect here is gonna be the resizing factor, e.g. the cached thread pool can drop to the minimum number of threads which depending on servers can widly swing from a message every minute towards a flood in one ago

Given that we're not actually using the features of an FJP it seems pretty redundant to use one vs just tweaking the thread pool to retain a thread or two or using a fixed size thread

2022-02-16 22:03 UTC, OOP-778 commented
Well I think that FJP actually is better for use here, since fixed sized thread pool executor would just reject a task at some point. While FJP would never. Resizing factor is gonna be per server, honestly I'd rather have it take those threads than having it to continously grow I think other would also agree on that.

2022-02-16 22:04 UTC, electronicboy commented
I don't see where a fixed size pool would reject tasks if setup properly vs a FJP?

2022-02-16 22:08 UTC, OOP-778 commented
Right we could actually move it into a fixed thread pool. Or I guess we could also do a way of setting x threads per x player. ex. 100 players = 2 threads, 200 = 4, etc. I feel like that would be much better too.

2022-02-16 22:19 UTC, electronicboy commented
issue is that fixed size has its own set of issues, am not sure if there is a fixed sized pool which can resize cleanly, which is why I kinda suggested on tweaking the config for the cached pool;

right now the entire thing can close off iirc, we could set a minimum number of threads to stick around vs requiring one to be fired up as people start chatting, etc, can also tweak how long a thread is allowed to idle for to allow for some sane time window before stuff starts scaling back

2022-02-16 22:21 UTC, OOP-778 commented
So do I just change the ForkJoinPool into fixed thread pool and and edit this PR?

2022-02-16 22:40 UTC, electronicboy commented
Not too sure as there is still merits for the cached pool in that it can resize, but, maybe we should be taking advantage of the fact that you can control some aspects of the resize, e.g. core thread count, thread keepalive

an FJP for the most part acts the same as a cached pool when you're not using the work-stealing aspects, so am not exactly too sure where you'd be seeing any improvements using one

would be interested to see what others think on this though

2022-03-06 14:26 UTC, Owen1212055 requested changes

2022-03-06 14:26 UTC, Owen1212055 commented on patches/server/0867-Be-able-to-set-how-many-threads-are-allocated-for-ha.patch
> ++    public void handle(ServerGamePacketListener listener) {
You need to mark the entire diff in paper comments (paper start/paper end), not just the statement.

Additionally, there's no need to change the handle method.

2022-03-06 14:26 UTC, Owen1212055 commented on patches/server/0867-Be-able-to-set-how-many-threads-are-allocated-for-ha.patch
> ++import net.minecraft.server.MinecraftServer;
I would use fully qualified imports

2022-06-02 00:55 UTC, electronicboy commented
https://gist.github.com/electronicboy/9e89c9898e0ec2347ece8adc292f8e5b - I haven't tested this, but, this seems like a less invasive method which does what's needed here, (and a bit more)
Setting the core size would allow you to have X number of chat threads always sitting around, as well as allowing to limit the size of the thread pool rather than the default of "unlimited"

2022-11-23 23:29 UTC, Owen1212055 commented
Superseded by https://github.com/PaperMC/Paper/pull/7878

2022-11-23 23:29 UTC, closed without merging