Add titleOverride to InventoryOpenEvent
PaperMC/Paper pull request #7540
Opened 2022-03-04 20:49 UTC by Machine-Maker

Adds an optional override title component to InventoryOpenEvent

See `InventoryOpenEvent#setTitleOverride` docs for special case for Horses.

2022-05-04 21:50 UTC, electronicboy approved these changes

2023-04-29 00:14 UTC, LemonCaramel requested changes

2023-04-29 00:14 UTC, LemonCaramel commented on patches/server/0905-Add-titleOverride-to-InventoryOpenEvent.patch
> ++                    title = container.getTitle();
```suggestion
+                    title = (container == null) ? null : container.getTitle();
```
If `InventoryOpenEvent` is cancelled, `container` is null

2023-08-26 19:21 UTC, lynxplay approved these changes

2023-08-26 19:28 UTC, merged