Add allow server listing client option
PaperMC/Paper pull request #7595
Opened 2022-03-13 21:42 UTC by NoahvdAa

Adds the `ALLOWS_SERVER_LISTINGS` client option from #7268. Also addresses [MM's comment](https://github.com/PaperMC/Paper/pull/7268#discussion_r777680170) by adding a constructor that takes a map as an argument. I'm not entirely sure how I feel about this map approach, but it's definitely better than adding a new constructor every time.

2022-03-13 21:46 UTC, electronicboy approved these changes

2022-03-15 06:15 UTC, Machine-Maker requested changes

2022-03-15 06:15 UTC, Machine-Maker commented on patches/api/0194-Add-Player-Client-Options-API.patch
> ++    public PlayerClientOptionsChangeEvent(@NotNull Player player, @NotNull Map<ClientOption<?>, ?> options) {
Add an ApiStatus.Internal annotation to the ctor. no plugin should really need to construct this event I think.

2022-03-15 06:15 UTC, Machine-Maker commented on patches/api/0194-Add-Player-Client-Options-API.patch
> ++        this.allowsServerListings = (boolean) options.get(ClientOption.ALLOW_SERVER_LISTINGS);
wrap these in requireNonNulls. yeah, the map isn't great. but its better than ending up with 40 constructors in 2 years I think

2022-03-18 22:36 UTC, Machine-Maker approved these changes

2022-06-22 22:43 UTC, NoahvdAa commented
Rebased for 1.19, label can be removed!

2022-06-23 03:00 UTC, Machine-Maker commented
is the `textFilteringEnabled` field in the ServerboundClientInformationPacket not used by the client yet? or can that be added here too?. I see it checking a flag on the userApiService on the client, so maybe that's something that can be set on the account?

2022-06-24 16:54 UTC, NoahvdAa commented
Could've sworn that was part of the original PR, it has now been added!

2022-07-18 09:14 UTC, NoahvdAa commented
Rebased.

2022-07-18 09:39 UTC, kennytv approved these changes

2022-07-20 21:44 UTC, Owen1212055 approved these changes

2022-10-26 22:02 UTC, Owen1212055 commented
Out of the scope of this PR, but PlayerClientOptionsChangeEvent could use similar love.

2022-10-26 23:06 UTC, Owen1212055 approved these changes

2022-10-26 23:09 UTC, merged