Add EntityDyeEvent and CollarColorable interface
PaperMC/Paper pull request #7625
Opened 2022-03-19 04:20 UTC by Machine-Maker

Resolves https://github.com/PaperMC/Paper/issues/7477

Adds EntityDyeEvent and makes it the super type for SheepDyeWoolEvent. Also adds CollarColorable interface for Wolf/Cat. 

EntityDyeEvent is called for sheep, wolf, and cat currently. Shulkers can be dyed, but not naturally so they were excluded.

2022-03-19 13:10 UTC, Doc94 commented on patches/api/0376-Add-EntityDyeEvent-and-CollarColorable-interface.patch
> ++     * Set the collar color of this wolf
```suggestion
+     * Set the collar color of this entity
```

2022-03-19 13:11 UTC, Doc94 commented on patches/api/0376-Add-EntityDyeEvent-and-CollarColorable-interface.patch
> ++     * @return the DyeColor the sheep is being dyed
This can be more generic? based in this event its not only for sheeps?

2022-03-29 09:12 UTC, kennytv requested changes
missing static handlerlist

2022-03-29 18:31 UTC, Machine-Maker commented
Sounds like there should be a test for that... :). Added that method

2022-03-30 20:08 UTC, kennytv approved these changes

2022-04-23 19:38 UTC, merged