Fix tick function tag running before load
PaperMC/Paper pull request #7713
Opened 2022-04-08 19:35 UTC by etil2jz

When enabling or reloading a datapack that has functions for both tick and load, the former runs before the latter, which causes problems in some cases such as initializing scoreboard values before increasing them per tick.
See https://bugs.mojang.com/browse/MC-187539

2022-04-08 19:38 UTC, Machine-Maker commented
Ugh, I'm a little conflicted. Like I see its marked as a bug, but doesn't this introduce more inconsistency with data pack behavior from vanilla? I almost want to say that this shouldn't be fixed before Vanilla does since data packs are developed with Vanilla in mind. According to that mojira issue, this has been around for a while despite being a confirmed bug.

2022-04-16 21:07 UTC, etil2jz commented
This seems to fix more inconsistencies than it can add. I believe performing the load check before the tick function is what was intended to be. Having a config option is a possibility, but as you said it's *a lot* for a single bugfix.

2022-04-16 21:13 UTC, Machine-Maker commented
> This seems to fix more inconsistencies than it can add.

I'm talking about inconsistencies in behavior between a data pack running on a vanilla server and one on a paper server. Ideally data packs should perform the same on both, but this would change the order of those functions on paper servers where its still "broken" on vanilla servers. So I'm not sure how it fixes more inconsistencies than it adds.

2022-04-16 21:14 UTC, jpenilla requested changes
I agree with Machine, this should not be fixed before vanilla.

2022-06-27 22:21 UTC, closed without merging