Fix cancelling PlayerDropItemEvent for carried items
PaperMC/Paper pull request #7727
Opened 2022-04-10 18:05 UTC by Machine-Maker

Fixes https://github.com/PaperMC/Paper/issues/7726

Now if the PlayerDropItemEvent is cancelled and the drop is trigged by clicking outside a menu, the item remains on the cursor instead of going back into the inventory or being deleted if the inventory is full.

2022-04-10 18:09 UTC, kennytv submitted a review, later dismissed

2022-04-10 21:41 UTC, Machine-Maker commented
There needs to be a consensus on what happens if the player closes the inventory with the item in their cursor and the drop item event is cancelled (and the inventory is full). Thoughts on what should happen?

2022-07-20 16:48 UTC, Owen1212055 requested changes
https://user-images.githubusercontent.com/23108066/180033453-ddefdbe1-82aa-4f0e-a654-dd6332b91d85.mp4
Items outside of guis still seem to disappear.
(cancelling the event)

It also seems that now dropping items outside of your inventory just causes them to disappear.

https://user-images.githubusercontent.com/23108066/180038817-bd0bb20c-95fa-4ca2-8a9c-b8139ecedc17.mp4

(Swapping hands toggles between cancelling the event)

2022-07-20 17:00 UTC, Machine-Maker commented
Yeah, I made some changes cause I spotted a bug in what I was doing before, but I didn't test those. I guess I broke it more.

2022-07-20 21:28 UTC, Machine-Maker commented
Ok, fixed that issue

2023-04-11 20:20 UTC, Machine-Maker commented
I like this idea. But what should the default behavior be? Just delete the item?

2023-04-16 00:13 UTC, Machine-Maker commented
Ok, added that overflow consumer. Tested it as well, setting the consumer to drop the itemstack in the world anyways. By default, it just sets the count of the stack to 0 to "delete" the itemstack.

2023-04-16 00:51 UTC, aerulion commented on patches/api/0416-Fix-cancelling-PlayerDropItemEvent-for-carried-items.patch
> ++     * server is unable to handle cancelling the event. An example of this might be canceling the
In the first sentence cancelling is spelled with 2 L, in the second only with 1

2024-04-09 22:38 UTC, bridgelol commented
Any chance this can get merged at some point? Adding an overflow consumer seems like the best option imo.

2025-03-23 19:15 UTC, closed without merging