Add BrainMemoryUpdateEvent
PaperMC/Paper pull request #7845
Opened 2022-05-23 19:04 UTC by Togira123

This PR adds an event that fires whenever an entity updates its memory. It differentiates between memory add/change/delete. The event can be cancelled which causes this memory not to be updated. The event has two parameters, the first one being the MemoryKey of the memory that is being updated and the second one being either "ADD", "CHANGE" or "DELETE", which are properties of an enum declared in the event class. It's unfortunately not possible to also pass an Entity in that event since there is no reference from the brain class to the entity this brain belongs to. If I wanted to pass the entity directly with the methods that update the memory instead I'd have to change like 80 files, which seemed a bit overkill.

2022-05-23 19:11 UTC, kennytv requested changes

2022-05-23 19:11 UTC, kennytv commented on patches/api/0384-Add-BrainMemoryUpdateEvent.patch
> ++    public static final type DELETE = type.DELETE;
Remove these

2022-05-23 19:11 UTC, kennytv commented on patches/api/0384-Add-BrainMemoryUpdateEvent.patch
> ++    public enum type {
Uppercase T

2022-05-23 19:11 UTC, kennytv commented on patches/server/0905-Fix-decompile-errors.patch
> ++                return DataResult.success(new Brain<>(memoryModules, sensors, immutableList, mutableObject::getValue)); // Paper - decompile error
This line didn't change

2022-05-23 19:11 UTC, kennytv commented on patches/server/0906-Add-BrainMemoryUpdateEvent.patch
> ++                // Paper start - check whether memory is being added/changed/deleted
Clean this up by only putting the change type into a var since the rest of the call is always the same

2022-06-01 08:10 UTC, Togira123 commented
Why did the check fail this time on that commit, even though it succeeded a week ago? it still results in "build successful" for me when running ./gradlew test on my local repo...

2022-06-01 15:58 UTC, electronicboy commented
The caching is probably screwing it up, as this is technically trying to do a build with older stuff, i.e. a decompiler update which was recently done on the main branch

But, I'm not fond of this, I really fail to understand the merit of such an event especially within the context, i.e. none, not even the entity is available

2022-06-01 16:02 UTC, Togira123 commented
> The caching is probably screwing it up, as this is technically trying to do a build with older stuff, i.e. a decompiler update which was recently done on the main branch
> 
> But, I'm not fond of this, I really fail to understand the merit of such an event especially within the context, i.e. none, not even the entity is available

Alright, I knew the use cases for this event would probably be very small. I'll close this pull request then.

2022-06-01 16:02 UTC, closed without merging