Event/Effect API Improvements
PaperMC/Paper pull request #7877
Opened 2022-06-06 01:43 UTC by Owen1212055

Adds block event api, redoes the world event api,  and adds alot of missing entity effect api.
I have added 1.19 stuff because it's coming soon.

Feedback Wanted:
### **BlockEvent**
- Is it worth having the applicable materials on the event? It's not actually needed anywhere because Minecraft does the checks itself. I was debating wether or not to put it into its individual block classes, but I am not sure as it wouldn't fit EntityEffect.
### **In general**
- Most likely will convert these classes into type tokens (https://github.com/PaperMC/Paper/pull/5605), as then it would allow the nullable Axis to be an Optional.
- Any suggestions on a better way to handle converting these types instead of the big crazy instanceof chain? Might be the only way but I am not sure if there is a nicer way available for now.
- Better names? These names collide so maybe it would be better to keep them named as ``XEffect``? Although minecraft refers to them as events it might not be worth changing it, but, opinions.

TODO:
- Convert to type tokens?

Each type has been tested (the non 1.19 ones of course).

2022-06-06 07:48 UTC, kennytv submitted a review, later dismissed
We definitely don't want to manually keep track of those hardcoded numbers for WorldEvents, not sure yet what that would look like (also something we'll have to do for other things in the future)... There's also not much of a point in having to update Bukkit's Effect enum given it's more than fully replaced here, just keep it with the deprecation for removal and tell people to move on

2022-06-06 14:38 UTC, Owen1212055 commented
> We definitely don't want to manually keep track of those hardcoded numbers for WorldEvents, not sure yet what that would look like (also something we'll have to do for other things in the future)... There's also not much of a point in having to update Bukkit's Effect enum given it's more than fully replaced here, just keep it with the deprecation for removal and tell people to move on

I should mention that we will be able to a test to validate and make sure we have them all. See stuff like WorldEvents.
Do you want me to not update the entity effect enum then? I'll just deprecate it and replace it then.

2023-03-16 17:29 UTC, Machine-Maker requested changes

2023-03-16 17:29 UTC, Machine-Maker commented on patches/api/0384-Event-Effect-API-Improvements.patch
> ++++ b/src/main/java/io/papermc/paper/world/event/SculkChargeEventConfiguration.java
Should be inside a separate inner package like `world/event/data/`

2023-03-16 17:29 UTC, Machine-Maker commented on patches/api/0384-Event-Effect-API-Improvements.patch
> ++public class SimpleWorldEvent extends WorldEvent {
Should be a non-public innerclass of WorldEvent. The less public types we expose to the API, the better. Although, what is the point of this? Why not make WorldEvent not-abstract and still extend it for the other types?

2023-03-16 17:29 UTC, Machine-Maker commented on patches/api/0384-Event-Effect-API-Improvements.patch
> ++public abstract class BlockEvent {
`@ApiStatus.NonExtendable`

or just make it a concrete type that is sealed to inner `Configurable` type (or a better name).

2023-03-16 17:29 UTC, Machine-Maker commented on patches/api/0384-Event-Effect-API-Improvements.patch
> ++public class SimpleBlockEvent extends BlockEvent {
Is this needed? Just make BlockEvent concrete and sealed.

2023-03-16 17:29 UTC, Machine-Maker commented on patches/api/0384-Event-Effect-API-Improvements.patch
> ++public class ConfigurableWorldEvent<T> extends WorldEvent {
same issue here with `Configurable`

2023-03-21 22:23 UTC, Owen1212055 commented
Should I separate this into fixes for entity effect api and then the world/block event api?

2023-03-21 22:34 UTC, Machine-Maker commented
Yeah, I think that would be best. One doesn't need new api, the other is a set of new API.

2024-12-22 23:35 UTC, Owen1212055 commented
If someone wants to continue this, please feel free to take my patches. :)

2024-12-22 23:35 UTC, closed without merging