Update Adventure to 4.11.0 and implement ComponentLogger
PaperMC/Paper pull request #7937
Opened 2022-06-11 05:10 UTC by JRoy

:trollface: 

Closes #7873
Closes #7867

2022-06-11 07:11 UTC, zml2008 requested changes

2022-06-11 07:11 UTC, zml2008 commented on patches/api/0005-Adventure.patch
> ++    public net.kyori.adventure.text.logger.slf4j.ComponentLogger getComponentLogger() {
A global logger was a mistake in the first place, don't add another one with component support to extend the mistake

2022-06-11 07:11 UTC, zml2008 commented on patches/server/0589-Add-support-for-hex-color-codes-in-console.patch
> -+    private static final char COLOR_CHAR = 0x7f;
This breaks any error messages containing the literal section symbol

2022-06-11 07:11 UTC, zml2008 commented on patches/server/0008-Adventure.patch
> ++        return PaperAdventure.asPlain(message, null);
This shouldn't be asPlain if you want to preserve colors -- it should be something like `HexFormattingConverter.SERIALIZER.serialize(translate(message, Locale.getDefault()))`

2022-06-11 18:05 UTC, kashike submitted a review, later dismissed
As per @zml2008's comments.

2022-06-12 19:47 UTC, zml2008 approved these changes

2022-06-12 20:44 UTC, jpenilla requested changes, later dismissed

2022-06-12 20:44 UTC, jpenilla commented on patches/server/0590-Add-support-for-hex-color-codes-in-console.patch
> ++
?

2022-06-12 21:06 UTC, kennytv approved these changes

2022-06-12 21:07 UTC, merged