Add missing important BlockStateListPopulator methods
PaperMC/Paper pull request #7952
Opened 2022-06-12 17:32 UTC by Owen1212055

Methods like generating a tree (with predicate) throw exceptions due to the dummy generator access class throwing exceptions for these methods.
Override them!

```kt
java.lang.UnsupportedOperationException: Not supported yet.
	at org.bukkit.craftbukkit.util.DummyGeneratorAccess.getLevelData(DummyGeneratorAccess.java:84) ~[main/:?]
	at net.minecraft.world.level.LevelAccessor.createTick(LevelAccessor.java:43) ~[main/:?]
	at net.minecraft.world.level.LevelAccessor.scheduleTick(LevelAccessor.java:61) ~[main/:?]
	at net.minecraft.world.level.block.LiquidBlock.updateShape(LiquidBlock.java:133) ~[main/:?]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.updateShape(BlockBehaviour.java:1068) ~[main/:?]
	at net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplate.lambda$updateShapeAtEdge$4(StructureTemplate.java:420) ~[main/:?]
	at net.minecraft.world.phys.shapes.DiscreteVoxelShape.forAllAxisFaces(DiscreteVoxelShape.java:191) ~[minecraft.jar:?]
	at net.minecraft.world.phys.shapes.DiscreteVoxelShape.forAllFaces(DiscreteVoxelShape.java:171) ~[minecraft.jar:?]
	at net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplate.updateShapeAtEdge(StructureTemplate.java:409) ~[main/:?]
	at net.minecraft.world.level.levelgen.feature.TreeFeature.lambda$place$11(TreeFeature.java:163) ~[minecraft.jar:?]
	at java.util.Optional.map(Optional.java:260) ~[?:?]
	at net.minecraft.world.level.levelgen.feature.TreeFeature.place(TreeFeature.java:161) ~[minecraft.jar:?]
	at net.minecraft.world.level.levelgen.feature.Feature.place(Feature.java:154) ~[minecraft.jar:?]
	at net.minecraft.world.level.levelgen.feature.ConfiguredFeature.place(ConfiguredFeature.java:24) ~[minecraft.jar:?]
	at org.bukkit.craftbukkit.CraftRegionAccessor.generateTree(CraftRegionAccessor.java:395) ~[main/:?]
	at org.bukkit.craftbukkit.CraftRegionAccessor.generateTree(CraftRegionAccessor.java:311) ~[main/:?]
```

Spigot mapped, but is equal to isFluidAtPosition
```kt
java.lang.UnsupportedOperationException: Not supported yet.
	at org.bukkit.craftbukkit.v1_19_R1.util.DummyGeneratorAccess.b(DummyGeneratorAccess.java:240) ~[paper-1.19.jar:git-Paper-4]
	at net.minecraft.world.level.levelgen.feature.foliageplacers.FoliagePlacer.tryPlaceLeaf(FoliagePlacer.java:89) ~[?:?]
	at net.minecraft.world.level.levelgen.feature.foliageplacers.FoliagePlacer.placeLeavesRow(FoliagePlacer.java:78) ~[?:?]
	at net.minecraft.world.level.levelgen.feature.foliageplacers.BlobFoliagePlacer.createFoliage(BlobFoliagePlacer.java:40) ~[?:?]
	at net.minecraft.world.level.levelgen.feature.foliageplacers.FoliagePlacer.createFoliage(FoliagePlacer.java:39) ~[?:?]
	at net.minecraft.world.level.levelgen.feature.TreeFeature.lambda$doPlace$5(TreeFeature.java:90) ~[?:?]
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.0.1-jre.jar:?]
	at net.minecraft.world.level.levelgen.feature.TreeFeature.doPlace(TreeFeature.java:89) ~[?:?]
	at net.minecraft.world.level.levelgen.feature.TreeFeature.place(TreeFeature.java:152) ~[?:?]
	at net.minecraft.world.level.levelgen.feature.Feature.place(Feature.java:154) ~[?:?]
	at net.minecraft.world.level.levelgen.feature.ConfiguredFeature.a(ConfiguredFeature.java:24) ~[?:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftRegionAccessor.generateTree(CraftRegionAccessor.java:395) ~[paper-1.19.jar:git-Paper-4]
	at org.bukkit.craftbukkit.v1_19_R1.CraftRegionAccessor.generateTree(CraftRegionAccessor.java:311) ~[paper-1.19.jar:git-Paper-4]
```

2022-06-12 17:36 UTC, electronicboy approved these changes

2022-06-14 09:05 UTC, kennytv requested changes, later dismissed

2022-06-14 09:05 UTC, kennytv commented on patches/server/0910-Add-missing-important-BlockStateListPopulator-method.patch
> ++        return state.test(this.getBlockState(pos).getFluidState());
```suggestion
+        return state.test(this.getFluidState(pos));
```

2022-06-15 01:14 UTC, Owen1212055 commented
Rebased and resolved conflicts

2022-06-15 01:20 UTC, Machine-Maker approved these changes

2022-06-15 16:30 UTC, merged