Add missing coverages for getTileEntity in order to attempt to avoid exeptions when calling getTileEntity
PaperMC/Paper pull request #797
Opened 2017-07-22 23:43 UTC by electronicboy

while looking over #791, I noticed that this method was missing the case in order to attempt to fix issues with shulker boxes. in specific, this patch will not fix #791 which I feel is a case of a plugin modifying the world async, but will aid in recovering any potential damage to the world that has occured once the causation has been removed from the server.

it's due to this logic, I cannot potentially see how #791 can even occur beyond something somehow slipping between bukkits getState() type lookup, and the type lookup that occurs in NMS while it actually grabs the TE from the world.

(This is also the fixed version of the commit, not the sleep deprived commit that ended up on my repo, oops)

I'm somewhat dubious on maintaining this due to the obfuscated fields, the fact that this really belongs up the stream and not down here, and the missing case for pistons which considering how long pistons have been in the game I can't see if it's just a case of "it was missed" or if it's intentional for some reason...

2017-07-23 07:40 UTC, kashike approved these changes

2017-07-25 01:43 UTC, aikar commented
Erm, Strongly not a fan of use of so many obfuscated variables that's going to break.

Can you do type instanceof instead?

2017-07-25 01:46 UTC, aikar requested changes

2017-07-25 01:46 UTC, aikar commented on Spigot-Server-Patches/0223-Add-missing-coverages-for-getTileEntity-in-order-to-.patch
> ++        else if (type == Blocks.WHITE_SHULKER_BOX ||
Looks like all of this can be replaced with type instanceof BlockShulkerBox and solve the obfuscation issue.

2017-07-27 03:10 UTC, aikar approved these changes

2017-07-27 03:11 UTC, merged