Use .toRealPath in createDirectories (paper config)
PaperMC/Paper pull request #7997
Opened 2022-06-16 01:32 UTC by Owen1212055

Fixes https://github.com/PaperMC/Paper/issues/7969

Symbolic links seem to not be handled nicely in Files#createDirectories, so attempt to use the real path. 
There will most likely be a future patch that targets correctly handling symlinks for this method when used in other places in the source code. But I wanted to get this out so that it can specifically target to fix this issue.

There was a bug report on this, but it was marked as NAI: https://bugs.openjdk.org/browse/JDK-8130464

2022-06-24 18:29 UTC, Machine-Maker approved these changes

2022-06-24 18:35 UTC, electronicboy approved these changes

2022-06-24 18:35 UTC, electronicboy commented
(Validated the behavior here using jshell, seems to work as expected here)

2022-06-24 18:38 UTC, Machine-Maker requested changes
actually no, this doesn't work. It throws an exception if the config directory doesn't exist at all. toRealPath requires it to exist

2022-06-25 18:38 UTC, Owen1212055 commented
Updated and fixed, see paper contributing. If anyone knows a better place for this type of util method would be appreciated, but it probably is just fine there?

2022-06-25 20:34 UTC, Machine-Maker approved these changes

2022-06-25 20:40 UTC, merged