Add fire-tick-delay option
PaperMC/Paper pull request #8037
Opened 2022-06-22 11:36 UTC by vytskalt

Closes #7277

2022-06-22 11:43 UTC, electronicboy requested changes

2022-06-22 11:43 UTC, electronicboy commented on patches/server/0918-Add-fire-tick-delay-option.patch
> ++        public int fireTickDelay = 30;
This belongs in the config files patch

2022-07-07 23:51 UTC, electronicboy approved these changes

2022-07-20 21:34 UTC, Owen1212055 approved these changes
To be honest, it would probably be less of a diff if you just modify the pre-existing method and add a level param. 

But looks good here.

2022-07-21 12:51 UTC, vytskalt commented
> To be honest, it would probably be less of a diff if you just modify the pre-existing method and add a level param.
> 
> But looks good here.

Done

2022-10-22 22:57 UTC, merged

2022-10-23 03:18 UTC, ByteBeamer commented
Thanks so much for this!