Add xp orb spawn reason for frogs
PaperMC/Paper pull request #8045
Opened 2022-06-24 12:30 UTC by Lulu13022002

Track the spawn reason of the xp orb dropped when frogs breeds

2022-06-25 18:40 UTC, Owen1212055 approved these changes

2022-06-25 20:37 UTC, Machine-Maker approved these changes
I think this patch should mark the ExperienceOrb ctor that doesn't take a SpawnReason as deprecated. Just to increase the likelihood
that usages of it are caught earlier.

2022-06-25 20:58 UTC, Lulu13022002 commented
I can deprecate the default constructor if you wants ? Also there is a decompile issue in the getBrain method return which needs to be cast into a Brain<Frog> before merging this one and the new event

2022-06-25 20:59 UTC, Machine-Maker commented
Yeah, add the `@Deprecated` to that constructor.

2022-06-26 08:01 UTC, kennytv approved these changes

2022-07-06 01:39 UTC, Machine-Maker requested changes

2022-07-06 01:39 UTC, Machine-Maker commented on patches/server/0125-ExperienceOrbs-API-for-Reason-Source-Triggering-play.patch
> ++    @Deprecated
Now add the `@DoNotUse` annotation to it and remove the `@Deprecated` annotation. That annotation will cause there to be build errors if the annotated method or constructor is used anywhere in the source.

This was just added the other week.

2022-07-06 13:33 UTC, Lulu13022002 commented on patches/server/0125-ExperienceOrbs-API-for-Reason-Source-Triggering-play.patch
> ++    @Deprecated
Fixed i have also cast the brain frog to resolve the build error

2022-07-06 22:24 UTC, Machine-Maker approved these changes

2022-07-07 21:23 UTC, electronicboy approved these changes

2022-07-07 21:38 UTC, merged