Add MaterialTags for the different Types of Tools
PaperMC/Paper pull request #8049
Opened 2022-06-25 19:56 UTC by thelooter

Adds MaterialTags for the following Types of Tools:

- Wooden Tools
- Stone Tools
- Iron Tools
- Gold Tools
- Diamond Tools

2022-06-25 20:24 UTC, imDaniX commented
Just by tags names, it's actually a bit unclear what's included into those - we also have items like shears, flint'n'steel, clock and compass, bucket.

2022-06-25 20:39 UTC, thelooter commented
What Names would you suggest instead?

2022-06-25 21:02 UTC, CatDevz commented
I disagree in the names being unclear. I feel the sheers, flint n steel, click, compass and bucket fit into their own category independent of the main tiered tools.

2022-06-25 21:03 UTC, CatDevz requested changes
Seems that netherite was ignored.

Could also be cool to include armor sets?

2022-06-25 21:03 UTC, CatDevz commented on patches/api/0157-Add-Material-Tags.patch
>  +}
Where is Netherite

2022-06-25 21:08 UTC, imDaniX commented
> I disagree in the names being unclear. I feel the sheers, flint n steel, click, compass and bucket fit into their own category independent of the main tiered tools.

I mean, while bucket, compass and clock don't really fit there, shears and flint'n'steel absolutely do - both are indeed tools, made using iron, both do have durability and can be enchanted. If we don't include these in iron tools, at least is should be noted in javadocs.

2022-06-25 21:13 UTC, CatDevz commented
> > I disagree in the names being unclear. I feel the sheers, flint n steel, click, compass and bucket fit into their own category independent of the main tiered tools.
> 
> I mean, while bucket, compass and clock don't really fit there, shears and flint'n'steel absolutely do - both are indeed tools, made using iron, both do have durability and can be enchanted. If we don't include these in iron tools, at least is should be noted in javadocs.

I can agree with it being included in the JavaDocs, however I don't think they should be included as they are not tiered. The naming of wooden, iron, exc. makes me assume the collections are refering to the tiered tools.

Maybe an `UNTIERED_TOOLS` collection could be made for those?

2022-06-25 21:19 UTC, thelooter commented on patches/api/0157-Add-Material-Tags.patch
>  +}
Should be added now

2022-06-25 21:20 UTC, CatDevz approved these changes
LGTM :+1:

2022-07-03 19:27 UTC, NoahvdAa approved these changes
looks good from web

2022-07-20 15:44 UTC, Owen1212055 approved these changes
In the future, I recommend creating PRS on other branches (not your master branch, because it makes some things difficult) 

Looks good tho

2022-07-21 04:45 UTC, thelooter commented
> In the future, I recommend creating PRS on other branches (not your master branch, because it makes some things difficult)
> 
> Looks good tho

Yeah I usually do. Only noticed I was on master after opening the PR.

2022-09-28 22:54 UTC, thelooter commented
Any update on this?

2022-09-29 12:01 UTC, electronicboy approved these changes

2022-10-22 21:51 UTC, merged