Fix playing adventure sounds on World
PaperMC/Paper pull request #8077
Opened 2022-06-30 02:45 UTC by Machine-Maker

playing adventure sounds on a World had some unexpected side effects due to ForwardingAudience's delegation to each individual audience. This overrides all 3 playSound methods in CraftWorld with better implementations.

2023-02-23 22:46 UTC, Machine-Maker commented
Rebased for 1.19.3

2023-02-23 23:22 UTC, jpenilla requested changes

2023-02-23 23:22 UTC, jpenilla commented on patches/server/0010-Adventure.patch
> ++    @Deprecated
unneeded change

2023-02-23 23:25 UTC, jpenilla approved these changes
Approved

2023-02-24 00:12 UTC, kashike approved these changes

2023-05-31 01:36 UTC, merged