Fix EntityChangeBlockEvent for silverfish
PaperMC/Paper pull request #8099
Opened 2022-07-05 12:36 UTC by Lulu13022002

The new block data of this event is wrong when the gamerule mobGriefing is false and the silverfish try to call its friends in the nearby infested blocks

2022-07-05 15:39 UTC, Machine-Maker requested changes, later dismissed

2022-07-05 15:39 UTC, Machine-Maker commented on patches/server/0874-Fix-new-block-data-for-EntityChangeBlockEvent.patch
> ++                                if (event.getBlock().isEmpty()) { // Paper
This isn't right. isEmpty checks if the block is air, which it definitely is not since there is `block instanceof InfestedBlock` right above it.

2022-07-05 16:10 UTC, Lulu13022002 commented on patches/server/0874-Fix-new-block-data-for-EntityChangeBlockEvent.patch
> ++                                if (event.getBlock().isEmpty()) { // Paper
You have right i have checked the old data and not the new one, fixed in the latest changes

2022-07-05 17:31 UTC, Machine-Maker commented on patches/server/0874-Fix-new-block-data-for-EntityChangeBlockEvent.patch
> ++                                if (event.getTo().isAir()) { // Paper
I think there is still a problem here. destroyBlock runs different logic than setBlock and so what if the mobGriefing gamerule is set to false, but the event sets the block to air? Should it run the destroyBlock logic? That wouldn't happen in vanilla since the game rule is set to false.

2022-07-05 17:38 UTC, Lulu13022002 commented on patches/server/0874-Fix-new-block-data-for-EntityChangeBlockEvent.patch
> ++                                if (event.getTo().isAir()) { // Paper
Yes do you think it's better to keep the vanilla behavior or allow plugin to bypass the gamerule ?
But the things is that in vanilla there are no plugin also.

2022-07-07 19:27 UTC, Lulu13022002 commented on patches/server/0874-Fix-new-block-data-for-EntityChangeBlockEvent.patch
> ++                                if (event.getTo().isAir()) { // Paper
Fixed, i have keep the vanilla behavior here

2022-07-07 21:48 UTC, electronicboy approved these changes

2022-07-20 17:30 UTC, Owen1212055 approved these changes
Tested and looks good, I confirmed and this looks like vanilla behavior as well.

2022-10-26 21:55 UTC, Owen1212055 approved these changes
BEFORE:
``
EntityChangeBlockEvent{block=CraftBlock{pos=BlockPos{x=101, y=104, z=-127},type=INFESTED_CHISELED_STONE_BRICKS,data=Block{minecraft:infested_chiseled_stone_bricks},fluid=net.minecraft.world.level.material.EmptyFluid@7e19755a}, cancel=false, to=CraftBlockData{minecraft:air}, entity=CraftSilverfish}
``

AFTER:
``
EntityChangeBlockEvent{block=CraftBlock{pos=BlockPos{x=101, y=104, z=-127},type=INFESTED_CHISELED_STONE_BRICKS,data=Block{minecraft:infested_chiseled_stone_bricks},fluid=net.minecraft.world.level.material.EmptyFluid@6f49d153}, cancel=false, to=CraftBlockData{minecraft:chiseled_stone_bricks}, entity=CraftSilverfish}
``

2022-10-26 22:05 UTC, merged