LivingEntity#setKiller
PaperMC/Paper pull request #820
Opened 2017-07-31 06:51 UTC by BillyGalbreath

Allow plugins to set the killer of a LivingEntity.

This is useful for when plugins remove entities manually but still want other plugins to register it as killed by a player, etc.

2017-08-01 02:53 UTC, kashike requested changes

2017-08-01 02:53 UTC, kashike commented on Spigot-API-Patches/0065-LivingEntity-setKiller.patch
> ++     * <p>Can set null</p>
`@Nullable` the parameter, then

2017-08-01 02:53 UTC, kashike requested changes

2017-08-01 02:53 UTC, kashike commented on Spigot-Server-Patches/0230-LivingEntity-setKiller.patch
> ++    public void setKiller(Player killer) {
`@Override`

2017-08-04 05:21 UTC, BillyGalbreath commented
Changes made as requested

2017-08-21 21:48 UTC, phenomax commented
Any updates here?

2017-08-23 06:24 UTC, kashike commented on Spigot-Server-Patches/0230-LivingEntity-setKiller.patch
> ++        getHandle().lastDamageByPlayerTime = entityPlayer == null ? 0 : 100;
Where do these numbers come from?

2017-08-23 07:09 UTC, BillyGalbreath commented on Spigot-Server-Patches/0230-LivingEntity-setKiller.patch
> ++        getHandle().lastDamageByPlayerTime = entityPlayer == null ? 0 : 100;
It's been like a month, so I can't remember.. I'll be able to check this weekend.

The numbers are ticks that the killer is remembered (100 being 5 seconds which is Mojang's thing, and 0 is removing this timer if unsetting a killer). The code comes from some other NMS method that actually damages the entity, I just can't remember where off the top of my head.

2017-08-24 15:54 UTC, BillyGalbreath commented on Spigot-Server-Patches/0230-LivingEntity-setKiller.patch
> ++        getHandle().lastDamageByPlayerTime = entityPlayer == null ? 0 : 100;
Ok, the 100 value is from net.minecraft.server.EntityLiving#damageEntity()
My copy has it at line 909, but i'm a bit outdated
https://gyazo.com/9a11f5178a3d312f53a14153eb0f0bdc

Its also used at line 314 in the same file for the getExpReward() method
https://gyazo.com/10cb084b2fe2243b9a8df4104a5be551
so, the PR has 100 set if a plugin uses the API to set a killer, and then to 0 if they are unsetting (setting null) a killer

Also same file in the die() method it checks this value to determine dropped items
https://gyazo.com/fc4ef3bd28ef80dd6a6fa3e9e1b692dc
https://gyazo.com/f3afa5af15239f1848bf6dbf97e5333f

And here's the obfuscated method Y() that ticks this value down to 0 (if its above 0) and sets the killer as null when the value reaches 0
https://gyazo.com/de2254e06040b20e308ee2e20ba0e37d

2017-08-24 19:25 UTC, Zbob750 commented
Merged w/ 75cb198fd2a5f3f6a246dc4eaff07267bcea145f

Thanks

2017-08-24 19:25 UTC, closed without merging