Inline Import Diffs
PaperMC/Paper pull request #8207
Opened 2022-07-29 15:32 UTC by Peter-Crawley

Reopen of #8200 but rebased for master.

Inlines a bunch of import diffs which create merge conflicts and unneeded patch diffs.

2022-07-29 15:46 UTC, JRoy requested changes

2022-07-29 15:46 UTC, JRoy commented on patches/api/0021-Add-BaseComponent-sendMessage-methods-to-CommandSend.patch
> -+import net.kyori.adventure.text.Component;
Do not inline adventure imports

2022-07-29 15:46 UTC, JRoy commented on patches/api/0026-Use-ASM-for-event-executors.patch
> -+// Paper start
Imports in this patch are intentional

2022-07-29 15:46 UTC, JRoy commented on patches/api/0045-Add-String-based-Action-Bar-API.patch
> -+import net.kyori.adventure.text.Component;
ditto

2022-07-29 15:46 UTC, JRoy commented on patches/api/0112-Add-getNearbyXXX-methods-to-Location.patch
> -+import java.util.Collection;
Imports in this patch are intentional

2022-07-29 15:46 UTC, JRoy commented on patches/api/0210-Support-components-in-ItemMeta.patch
> -+import net.kyori.adventure.text.Component;
ditto

2022-07-29 15:46 UTC, JRoy commented on patches/api/0280-Allow-for-Component-suggestion-tooltips-in-AsyncTabC.patch
> -+import net.kyori.examination.Examinable;
Imports in this patch are intentional

2022-07-29 15:46 UTC, JRoy commented on patches/api/0292-Add-Adventure-message-to-PlayerAdvancementDoneEvent.patch
> -+import net.kyori.adventure.text.Component;
ditto

2022-07-29 15:46 UTC, JRoy commented on patches/api/0328-Add-missing-team-sidebar-display-slots.patch
> -+import net.kyori.adventure.text.format.NamedTextColor; // Paper
ditto

2022-08-04 11:22 UTC, Peter-Crawley commented
The issues @JRoy previously mentioned are resolved, I forgot to mention it originally. Also the PR has been rebased. I haven't worked on the server patches yet because the chances of it being accepted are still uncertain, so if that could be clarified that would be great.

2022-08-05 08:16 UTC, aurorasmiles commented
This PR will realistically not be merged. While we appreciate it, the sheer scope of it is way too big to just casually merge it, and if we don't merge it now the rebasing will get worse every day. Merging this PR would force every other PR to be rebased, and that isn't something we really want to do outside of big changes like version updates.
Something like this might be done by us during an update in the future, but as other people already mentioned, it just isn't something that's that big of a deal. I'd prefer that things like that either happen in one sweep from us, or just in small chunks during other PRs. For example if you open a PR to fix something in a patch, removing the imports from that patch at the same time would be a good way to do it.

I'll close this now, still thank you for the work!

2022-08-05 08:16 UTC, closed without merging