PlayerAttemptPickupItemEvent additions
PaperMC/Paper pull request #823
Opened 2017-07-31 07:33 UTC by BillyGalbreath

Replaces #753 

I finally figured out how to edit existing patches. ;)

2017-08-01 12:48 UTC, HuManKeat requested changes

2017-08-01 12:48 UTC, PotatoStealer commented on Spigot-API-Patches/0055-PlayerAttemptPickupItemEvent.patch
> ++    public boolean getFlyAtPlayer() {
getFlyAtPlayer is misleading, granted it gives the implication that you're returning an object that WILL fly at the player.
if possible, willFlyAtPlayer would be better imo

2017-08-01 12:48 UTC, PotatoStealer commented on Spigot-Server-Patches/0215-PlayerAttemptPickupItemEvent.patch
> ++
unnecessary empty space?

2017-08-01 13:30 UTC, BillyGalbreath commented on Spigot-Server-Patches/0215-PlayerAttemptPickupItemEvent.patch
> ++
Empty space isn't mine. It's just the diff is weird (it removes empty space but adds it back?)

2017-08-01 13:31 UTC, BillyGalbreath commented on Spigot-API-Patches/0055-PlayerAttemptPickupItemEvent.patch
> ++    public boolean getFlyAtPlayer() {
Should have said something last month with PlayerPickuoItemEvent addition. Renaming here now would make it inconsistent.

2017-11-11 04:51 UTC, Zbob750 commented
d7039347b06ecc8c65e3dbe0ca532d83960c75ef
Thanks

2017-11-11 04:51 UTC, closed without merging