Fix calling UnknownCommandEvent
PaperMC/Paper pull request #8232
Opened 2022-08-03 17:29 UTC by Machine-Maker

Fixes https://github.com/PaperMC/Paper/issues/8225
Fixes https://github.com/PaperMC/Paper/issues/8329

2022-09-10 15:31 UTC, kennytv requested changes, later dismissed
With this, the event is still called for invalid Vanilla command syntax (like `/tp asd asd asd` or just `/tp`)

2022-10-27 17:26 UTC, electronicboy commented on patches/server/0139-Add-UnknownCommandEvent.patch
> ++            this.dispatcher.setConsumer(existing); // Paper
I would probably validate that the consumer hasn't changed in the meantime

2022-10-27 17:27 UTC, electronicboy approved these changes

2022-11-01 17:40 UTC, Lulu13022002 commented on patches/server/0139-Add-UnknownCommandEvent.patch
> ++        // Pape rend
Small typo

2022-11-01 17:40 UTC, Lulu13022002 commented on patches/server/0139-Add-UnknownCommandEvent.patch
> ++                // Paper end
This comment should probably go one line above

2022-11-01 18:14 UTC, Machine-Maker commented on patches/server/0139-Add-UnknownCommandEvent.patch
> ++            this.dispatcher.setConsumer(existing); // Paper
I just removed the whole consumer thing. Found a better way to know if a vanilla command was run

2023-01-07 22:07 UTC, pauhull commented
Is this going to be fixed?

2023-02-15 23:24 UTC, electronicboy approved these changes

2023-02-17 02:07 UTC, merged