Missing eating regain reason
PaperMC/Paper pull request #8244
Opened 2022-08-05 10:23 UTC by Lulu13022002

Correct the javadoc of the eating regain reason because currently only animal trigger this and not the player
Also add the missing reason for the llama and the cat
I'm not sure if we can consider also the iron golem with the iron ingots ?

2022-08-06 08:38 UTC, kennytv requested changes

2022-08-06 08:38 UTC, kennytv commented on patches/api/0391-Missing-eating-regain-reason.patch
> ++         * When an animal regains health from eating consumables
Should go into the javadox fixup patch

2022-08-08 05:34 UTC, Machine-Maker reviewed
Should the `EATING` reason be used for Iron Ingots being given to Iron Golems? It's using the same logic, consume a resource to heal the entity, but maybe the word "eating" shouldn't describe that for iron golems.

2022-08-08 08:50 UTC, Lulu13022002 commented
It depends if we consider the golem as a robot or not, If so the word REPAIR can be better

2022-08-08 09:35 UTC, kennytv approved these changes

2022-09-18 03:24 UTC, merged