fix-teleporting-outside-worldborder-with-enderpearl
PaperMC/Paper pull request #8247
Opened 2022-08-05 16:52 UTC by zJanny

Fixes being able to teleport behind the worldborder with an enderpearl

2022-08-05 18:50 UTC, Owen1212055 requested changes
Welcome to Paper! 😄 

Here are some things, if you need any help feel free to ask in #paper-dev.
But a good reference is the [guide](https://github.com/PaperMC/Paper/blob/master/CONTRIBUTING.md).

2022-08-05 18:50 UTC, Owen1212055 commented on patches/server/0933-fix-teleporting-outside-worldborder-with-enderpearl.patch
> ++import org.bukkit.WorldBorder;
In general, please try inlining imports and use fully qualified class names instead.

2022-08-05 18:50 UTC, Owen1212055 commented on patches/server/0933-fix-teleporting-outside-worldborder-with-enderpearl.patch
> ++                    // Paper end
Look at level.getWorldBorder().isWithinBounds() This logic is already done and will probably be generally much nicer.

There's also Level#isLoadedAndInBounds, which might be fine?

2022-08-05 19:00 UTC, Lulu13022002 commented
Maybe the teleportation should collide with the border instead of just be ignored, bc it can be frustrating in case of flee.

2022-08-05 19:40 UTC, zJanny commented
> Maybe the teleportation should collide with the border instead of just be ignored, bc it can be frustrating in case of flee.



> Maybe the teleportation should collide with the border instead of just be ignored, bc it can be frustrating in case of flee.

There is already a Minecraft bug report for projectiles not colliding with the border which has been assigned low priority. 
So this will probably be fixed by Mojang in the future, this patch should just fix that players can use enderpearls to teleport out of bounds.

2022-08-05 21:37 UTC, pop4959 commented
If the intended behavior is for the pearl to collide with the border I think I'd prefer that. If I'm understanding correctly this would just mean that the player loses the pearl and doesn't teleport, which feels hacky. (correct me if wrong)

2022-08-06 06:46 UTC, zJanny commented
> If the intended behavior is for the pearl to collide with the border I think I'd prefer that. If I'm understanding correctly this would just mean that the player loses the pearl and doesn't teleport, which feels hacky. (correct me if wrong)

2022-08-06 10:07 UTC, Lulu13022002 commented
Cool, i have already done that in an older version but basically the projectile raytrace start from the ProjectileUtil#getHitResult method
so this class should call your modified raytrace that take in account the border (in level.clip) but since this method is too generic your own logic should be implemented aside (see ClipContext#Block)

2022-08-07 09:14 UTC, closed without merging