Remove reputation values of 0 instead of ignoring
PaperMC/Paper pull request #8258
Opened 2022-08-07 15:09 UTC by Owen1212055

Fixes https://github.com/PaperMC/Paper/issues/7142

2022-08-07 15:32 UTC, kennytv requested changes
needs another default return value for unfilled entries to not update any unset reputation type

2022-08-07 16:33 UTC, Owen1212055 commented
Now uses an enum map, where it will only remove values if explicitly set to 0.

2022-08-08 09:33 UTC, kennytv approved these changes

2022-08-08 18:35 UTC, SpiritOTHawk approved these changes

2022-08-14 17:43 UTC, kennytv commented on patches/server/0411-Add-villager-reputation-API.patch
> ++                int reputation = rep.getReputation(api);
Move this into the if

2022-08-14 18:47 UTC, Owen1212055 commented
Resolved + Rebased + yes

2022-10-02 01:53 UTC, Owen1212055 commented
Rebased

2022-11-12 17:40 UTC, lynxplay approved these changes

2022-11-12 17:41 UTC, merged