Fix: Allow loading if no permission to write configuration
PaperMC/Paper pull request #8306
Opened 2022-08-16 08:27 UTC by DrupalDoesNotExists

https://github.com/PaperMC/Paper/issues/8301

2022-08-16 08:36 UTC, molor commented on patches/server/0935-Fix-Allow-loading-if-no-permission-to-write-configur.patch
> ++            }
Maybe should `throw exception;` again there if that condition is false, to keep the "old behavior" (let's crash if exception is not an instance of AccessDeniedException, or at least print stack trace)?

2022-08-16 09:02 UTC, Peter-Crawley commented
Generally adding imports in patches is discouraged, also this probably is supposed to be done as part of editing the original configuration patch. Also it may be a good idea to handle the exceptions that occur with the other configuration files `server.properties`, `bukkit.yml`, and `spigot.yml`.

2022-08-16 11:07 UTC, Lulu13022002 commented
Be more explicit on the error message. Mention the name (absolute path) of the file permission issue and also it's not the configuration that it's read-only but the file of the configuration.
The files server.properties, bukkit.yml/spigot.yml fail already silently so no need to handle them but you can unify the error message
for example instead of Could not save [NAME]/Failed to store properties to file: [NAME]. use your specific message for permission case.
For bukkit/spigot.yml: Check if it's an instanceof SecurityException
For server.properties: Modify the craftbukkit block: "Don't attempt writing to file if it's read only" and instead of just return, log a warning

2022-08-16 22:24 UTC, karthanistyr commented on patches/server/0935-Fix-Allow-loading-if-no-permission-to-write-configur.patch
> ++                LOGGER.warn("Configuration is read-only. If there any new settings, you need to apply them manually!");
> If there any new settings, you need to apply them manually!

I think this is a wrong statement. Not all new settings must be added to the config file if they have a default value (which is the case for the vast majority of them), and Paper will work fine without them being in the config file at all!
A better wording would be like "Please remember to review the documentation for the complete list of configuration settings."

Maybe worth mentioning the docs URL https://docs.papermc.io/paper/configuration

2022-08-16 22:25 UTC, karthanistyr requested changes

2022-08-16 22:25 UTC, karthanistyr commented on patches/server/0935-Fix-Allow-loading-if-no-permission-to-write-configur.patch
> ++                LOGGER.warn("Configuration is read-only. If there any new settings, you need to apply them manually!");
> If there any new settings, you need to apply them manually!

I think this is a wrong statement. Not all new settings must be added to the config file if they have a default value (which is the case for the vast majority of them), and Paper will work fine without them being in the config file at all!
A better wording would be like "Please remember to review the documentation for the complete list of configuration settings."

Maybe worth mentioning the docs URL https://docs.papermc.io/paper/configuration

2022-08-17 01:00 UTC, electronicboy commented
1) This should go in the configuration patch rather than being tacked on the end
2) honestly, I'd much rather have config file saving through a flag, which can maybe be applied to the other configs down the line if needed, 99% of people seeing that exception there actually have deeper issues in their environment rather than it being an elective choice; ofc, this is probs something which we'd need comments on

2022-08-20 13:25 UTC, karthanistyr commented
A few questions:

* > Generally adding imports in patches is discouraged

@Peter-Crawley It doesn't look like this is possible to avoid, at least the imports for logging, unless there is more extensive refactoring. Any reason why that is, and is it a blocker in this instance?

* > I'd much rather have config file saving through a flag,

@electronicboy Do you agree that this is perhaps outside of the scope of this fix, and could happen later with a well-defined refactoring? The goal here is to avoid the hard crash that was introduced by the migration to Configurate and return to the previous behaviour (printing the stack trace to the console but loading continued fine).

2022-08-20 13:26 UTC, lynxplay commented
You avoid imports by fully qualifying your code. E.g.
```java

import foo.Bar;

Bar.something();
```

vs
```java
foo.Bar.something();
```

2022-08-20 13:39 UTC, karthanistyr commented
ah yes I know that, I thought what was meant was "no new dependency"

2022-08-21 03:05 UTC, electronicboy commented
I don't think that the hard crash from an unexpected illegal state is a bug; Maybe a regression over expectations, but, this imho s more a feature request to me that a "fix", maybe a system property would be better as those tend to fare better in terms of compatibility with different MC environments

It's taken 2 months or so until somebody noticed this as a regression in terms of behavior, the fact that it blew up early on borked file perms honestly kinda seemed like a bit of a blessing

2022-08-21 07:07 UTC, karthanistyr commented
I disagree that this is either an illegal state or borked file perms. This is a legitimate system state, and there is no good technical reason why you should enforce writability alone with a crash. The configuration file on a host system is not Paper's property.

The fact that failing to save the config file now crashes is a regression not just on expectations but on design, this requirement (and now behaviour) has never been documented anywhere. It's more of an expectation on your part than on mine at this point.

2022-08-21 10:40 UTC, karthanistyr commented
I'm proposing #8318 as a stop-gap solution to ease the crash while a broader design is decided within the core team.

2022-09-16 19:05 UTC, closed without merging