Stop large look changes from crashing the server
PaperMC/Paper pull request #8326
Opened 2022-08-24 13:58 UTC by Jaren8r

Supersedes #7459, with a proper diff this time

2022-08-24 14:31 UTC, Lulu13022002 commented
This can also happens for all projectile see the Projectile#lerpRotation. But since this is just faster/simpler than looping over a large value, you should search in the code all bad pattern of this.

2022-08-24 14:43 UTC, Jaren8r commented
That's the only other use of that pattern I could find in the server code, so I went ahead and changed that too.

2022-08-24 15:51 UTC, Lulu13022002 commented
Hmm what about ProjectileUtil#rotateTowardsMovement (will probably not crash) and Mth#rotlerp then? I can't test if these crash because of the two other loop that run in the tick directly. Also the fix provided for the projectile is wrong, you forgot to increment instead of replace
basically: prevRot **+**= Math.round((newRot - prevRot) / 360.0F) * 360.0F;

2022-08-24 16:01 UTC, Jaren8r commented
> Also the fix provided for the projectile is wrong, you forgot to increment instead of replace

Blah, good catch. It's fixed now.

2022-09-04 07:34 UTC, kennytv requested changes

2022-09-04 07:34 UTC, kennytv commented on patches/server/0936-Stop-large-look-changes-from-crashing-the-server.patch
> +From: Jaren Knodel <Jaren@Knodel.com>
Put the original patch author here

2022-09-04 09:32 UTC, Jaren8r commented on patches/server/0936-Stop-large-look-changes-from-crashing-the-server.patch
> +From: Jaren Knodel <Jaren@Knodel.com>
Done

2022-09-04 10:57 UTC, kennytv approved these changes

2022-09-17 03:30 UTC, merged

2022-09-23 21:38 UTC, asquared31415 commented
Can this get backported to all supported versions? It affects 1.18.2 and possibly other versions as well.

2022-09-23 21:40 UTC, electronicboy commented
1.18 is EOL and has far exceeded its support lifecycle, if somebody wants to open a PR, maybe; but, I can't justify throwing any time towards it