Limit size of Authenticator Cache Thread Pool
PaperMC/Paper pull request #8360
Opened 2022-09-14 10:48 UTC by Peter-Crawley

@MiniDigger 
![Screenshot from 2022-09-14 11-48-06](https://user-images.githubusercontent.com/49043380/190134611-e3ec3c06-f8fe-4f6a-aa69-a898b19e4c5b.png)

2022-09-14 21:32 UTC, jpenilla commented
the thread factory should not be removed

2022-09-16 19:02 UTC, electronicboy requested changes

2022-09-16 19:02 UTC, electronicboy commented on patches/server/0116-Cache-user-authenticator-threads.patch
> ++    private static final java.util.concurrent.ExecutorService authenticatorPool = new java.util.concurrent.ThreadPoolExecutor(0, 16, 60L, java.util.concurrent.TimeUnit.SECONDS, new java.util.concurr
as said on the comments, the thread factory needs to stay that we we can get thrown exceptions, and the name of the threads correct

2022-09-17 21:58 UTC, electronicboy approved these changes

2022-09-17 21:58 UTC, merged