Improve performance of ThreadedLevelLightEngine
PaperMC/Paper pull request #8377
Opened 2022-09-21 20:18 UTC by bluelhf

This PR adds small improvements that improve the performance of the threaded level light engine and Starlight interface.

||Old|New
|---|---|---
|Memory allocations|![The memory allocation call tree for the previous implementation](https://user-images.githubusercontent.com/52505120/191599753-347adaa1-6c8e-478b-873b-736307392385.png)|![The memory allocation call tree for the new implementation](https://user-images.githubusercontent.com/52505120/191599920-6ed620ea-f94e-41ea-a593-edb0af1b3b87.png)|
|CPU samples|![The CPU sample call tree for the previous implementation](https://user-images.githubusercontent.com/52505120/191600298-ae5ca9c8-ce24-43cc-8ec5-6e1ab4b3d662.png)|![The CPU sample call tree for the new implementation](https://user-images.githubusercontent.com/52505120/191600502-76d4b9af-36ca-44ab-b98e-922c55a4604c.png)|

<sup>Lower is better in both allocated bytes and CPU samples.</sup>

This is done by swapping the CompletableFuture `thenCombine(...)` with a more efficient `thenCompose(...)` (we don't care about the result of the other CompletableFuture, as it does not have one). Additionally, a `HashSet` field in `StarlightInterface.LightQueue.ChunkTasks` was converted to an `ObjectOpenHashSet`. I did not measure the performance impact of this alone, but I would be surprised if the HashMap-backed java.util HashSet was faster than a 'real' implementation.

2022-09-21 20:30 UTC, NoahvdAa requested changes
👋 Congrats on making your first PR, welcome to Paper!

This change should modify the existing [starlight patch](https://github.com/PaperMC/Paper/blob/9e614e6f9a1b625ba550a147266a474400c013c6/patches/server/0788-Rewrite-the-light-engine.patch) instead of creating a new patch, you can just fixup your current patch into it. The contributing guide has instructions on it in case you're unsure how to do it.

Since you're modifying Starlight itself, this PR should also be opened to the [Starlight repo](https://github.com/PaperMC/Starlight/), to prevent the changes getting lost in a future update.

2022-09-21 20:56 UTC, bluelhf commented
I hope I did it right...

2022-09-24 23:39 UTC, Spottedleaf commented
When https://github.com/PaperMC/Starlight/pull/160 is merged I will port the diff under your commit details to master.

2022-09-24 23:39 UTC, closed without merging

2022-09-25 15:35 UTC, bluelhf commented
> When https://github.com/PaperMC/Starlight/pull/160 is merged I will port the diff under your commit details to master.

thank you this makes my life ten times easier i do not understand the patch system in the slightest