Fix typos in isTickingWorlds API javadocs
PaperMC/Paper pull request #8382
Opened 2022-09-24 13:01 UTC by lynxplay

2022-09-24 21:04 UTC, jpenilla requested changes, later dismissed

2022-09-24 21:04 UTC, jpenilla commented on patches/api/0383-Add-method-isTickingWorlds-to-Bukkit.patch
> ++     * Gets whether the worlds are being ticked right now or not.
`or not` is redundant here

2022-09-24 21:04 UTC, jpenilla commented on patches/api/0383-Add-method-isTickingWorlds-to-Bukkit.patch
> ++     * Gets whether the worlds are being ticked right now or not.
same as above

2022-09-24 21:15 UTC, lynxplay commented on patches/api/0383-Add-method-isTickingWorlds-to-Bukkit.patch
> ++     * Gets whether the worlds are being ticked right now or not.
Resolved :+1:

2022-09-25 00:00 UTC, electronicboy approved these changes

2022-09-25 00:01 UTC, merged