Added PermissibleBase getters and setters
PaperMC/Paper pull request #8463
Opened 2022-10-12 15:36 UTC by Badbird5907

Adding this API will remove the need to use reflections in plugins to get and set `PermissibleBase` on `CraftHumanEntity` to override permissions logic

2022-10-12 15:47 UTC, Owen1212055 commented
See: https://github.com/PaperMC/Paper/pull/8108

Do note that this expands the whole permission overriding and allows you to override the permission logic in the SimplePluginManager.

2022-10-12 16:17 UTC, Badbird5907 commented
Added the missing annotations causing tests to fail

2022-10-13 10:14 UTC, kennytv requested changes

2022-10-13 10:14 UTC, kennytv commented on patches/api/0400-Added-PermissibleBase-getter-and-setter.patch
> ++import org.bukkit.permissions.PermissibleBase;
Inline the import

2022-10-13 10:14 UTC, kennytv commented on patches/api/0400-Added-PermissibleBase-getter-and-setter.patch
> +-
Don't change indents/spacing

2022-10-13 17:07 UTC, Badbird5907 commented
Did the requested changes
_idea didn't like the indents_

2022-10-13 17:58 UTC, Lulu13022002 commented on patches/server/0926-Added-PermissibleBase-getter-and-setter.patch
> ++    protected PermissibleBase perm = new PermissibleBase(this);
Missing the paper comment

2022-10-13 17:58 UTC, Lulu13022002 commented on patches/api/0400-Added-PermissibleBase-getter-and-setter.patch
> ++     * @return the old {@link org.bukkit.permissions.PermissibleBase}
These links seems a little bit too redundant, maybe keep only the links into the description but not into the parameter explanation ?

2022-10-13 19:22 UTC, zml2008 commented
this feels like the kind of thing that exposes internal details of api impl which makes evolving the permissions api harder, and makes it easier for plugin developers to make mistakes without any traceability.

you'd be better off reworking how permissions are set and computed in the first place to remove the numerous footguns developers encounter when customizing permissions api logic - things like state tracking across the various join/quit/kick events, the permissions impact of recalculating permissions, and all the logic with default permissions

2022-10-13 19:30 UTC, electronicboy commented
The thing with evolving the perm API is that it's generally one of the many things which has been left to rot, hence why any perm plugin of note will literally just rip the thing out in order to add basic features, such as verbose mode, wildcards, etc

I'm much open towards expanding this API, but, I'd much rather that be an effort kicked off through perm plugin devs whom know their needs here so that we can actually deliver towards it, but, at this point, people reflect into this mess anyways that I don't have a strong urge to deny this personally, but, did wanna ask people like Luck if they had any thoughts or considerations; It's not like exposing this in the API is a huge priority for us and I'd much rather see perm plugin devs discuss this sorta thing

2022-11-12 19:11 UTC, Owen1212055 commented
Closing, as in general as specified above it's best to instead expand this API instead of trying to move around it like this.

2022-11-12 19:11 UTC, closed without merging