Add a simple way to check the type of EquipmentSlot
PaperMC/Paper pull request #8477
Opened 2022-10-16 12:40 UTC by SoSeDiK

Adds `EquipmentSlot#isHand` and `EquipmentSlot#isArmor` to check the type of the slot.

2022-10-16 17:45 UTC, jpenilla commented on patches/api/0403-Add-LivingEntity-swingHand-EquipmentSlot-convenience.patch
> ++        com.google.common.base.Preconditions.checkArgument(hand.isHand(), String.format("Expected a valid hand, got \"%s\" instead!", hand));
potential npe
```suggestion
+        com.google.common.base.Preconditions.checkArgument(hand != null && hand.isHand(), String.format("Expected a valid hand, got \"%s\" instead!", hand));
```

2022-10-16 17:47 UTC, jpenilla requested changes

2022-10-16 17:47 UTC, jpenilla commented on patches/api/0402-Add-EquipmentSlot-convenience-methods.patch
> ++     * @return true if this is a hand slot
```suggestion
+     * @return whether this is a hand slot
```

2022-10-16 17:47 UTC, jpenilla commented on patches/api/0402-Add-EquipmentSlot-convenience-methods.patch
> ++     * @return true if this is an armor slot
```suggestion
+     * @return whether this is an armor slot
```

2022-10-17 20:23 UTC, kennytv approved these changes

2022-10-20 18:12 UTC, YanisBft approved these changes

2022-10-22 19:56 UTC, Machine-Maker approved these changes

2022-10-22 23:24 UTC, jpenilla approved these changes

2022-10-22 23:50 UTC, merged

2022-10-23 02:08 UTC, theminecoder commented
Will the fact that the patch that adds the methods is added after the patch that uses it affect version upgrades in the future (when likely applying patches one by one)?

2022-10-23 02:10 UTC, Owen1212055 commented
I mean, because it's just one API method it most likely won't have any effect. However, it's probably better if those patches are moved.