Fix MC-117075: TE Unload Lag Spike
PaperMC/Paper pull request #848
Opened 2017-08-09 23:14 UTC by Zbob750

PaperMC port of https://github.com/MinecraftForge/MinecraftForge/pull/4281

2017-08-10 02:37 UTC, kashike requested changes

2017-08-10 02:37 UTC, kashike commented on Spigot-Server-Patches/0232-Fix-MC-117075-TE-Unload-Lag-Spike.patch
> ++        this.removeTileEntitiesForRemovedChunks(); // Paper - Fix MC-117075: TE Unload Lag Spike
Should go above `this.O = false;`

2017-08-10 06:00 UTC, liach commented
You can utterly change those tile lists to collections and add methods that remove those tiles without resizing an array, etc. See the original comment on MinecraftForge/MinecraftForge#4236

2017-08-11 02:08 UTC, Zbob750 commented
Handled manually

2017-08-11 02:08 UTC, closed without merging