Fix rendering for translatable death messages
PaperMC/Paper pull request #8534
Opened 2022-11-02 01:58 UTC by PrimordialMoros

When using a `TranslatableComponent` in `PlayerDeathEvent#deathMessage` the client should view the rendered translation of the component (assuming the key is registered in the GlobalTranslator).

Currently, the component in `PlayerDeathEvent#deathMessage` is converted to a vanilla component and when written to a chat packet, the GlobalTranslator is not utilized (client will only translate keys found in its ResourcePack).

That results in the client only seeing the translation key.

Since this is related to Adventure, I figured I'd use the existing patch, let me know if it needs to be in a separate one.

Here's a plugin to test.
```java
public final class TestPlugin extends JavaPlugin implements Listener {
    @Override
    public void onEnable() {
        this.getServer().getPluginManager().registerEvents(this, this);
        TranslationRegistry registry = TranslationRegistry.create(Key.key("test", "translations"));
        registry.defaultLocale(Locale.ENGLISH);
        registry.register("test.death", Locale.ENGLISH, new MessageFormat("Test translation: {0} died"));
        GlobalTranslator.translator().addSource(registry);
    }

    @EventHandler
    public void onDeath(PlayerDeathEvent event) {
        event.deathMessage(Component.translatable("test.death").args(event.getEntity().name()));
    }
}
```

2022-11-03 20:25 UTC, Machine-Maker commented
This is not the right fix. Instead, any use of the ClientboundSystemChatPacket constructor that just takes an nms Component and a boolean should instead use the main ctor, passing in a json string from PaperAdventure.asJsonString(). Then that ctor should be marked as `@DoNotUse` as there is no way to get the locale context in the packet ctor.

2022-11-04 17:40 UTC, PrimordialMoros commented
There were 3 more uses of the nms component ctor but it's all vanilla translations. If needed I can change those too but figured I'd keep the diff small for now.

2022-11-19 18:47 UTC, Owen1212055 requested changes
Logic wise, looks good.

Now because of the new DoNotUse Annotation added you have to make sure to replace the usages of those methods
![image](https://user-images.githubusercontent.com/23108066/202866670-0cc8f080-5a0b-49b4-bd8b-622ba55e2af9.png).
```
Method net/minecraft/network/protocol/game/ClientboundSystemChatPacket#<init>(Lnet/minecraft/network/FriendlyByteBuf;)V makes call to bad method net/minecraft/network/protocol/game/ClientboundSystemChatPacket#<init>(Lnet/minecraft/network/chat/Component;Z)V
Method net/minecraft/server/network/ServerGamePacketListenerImpl#tryHandleChat(Ljava/lang/String;Ljava/time/Instant;Lnet/minecraft/network/chat/LastSeenMessages$Update;)Z makes call to bad method net/minecraft/network/protocol/game/ClientboundSystemChatPacket#<init>(Lnet/minecraft/network/chat/Component;Z)V
Method net/minecraft/server/network/ServerGamePacketListenerImpl#broadcastChatMessage(Lnet/minecraft/network/chat/PlayerChatMessage;)V makes call to bad method net/minecraft/network/protocol/game/ClientboundSystemChatPacket#<init>(Lnet/minecraft/network/chat/Component;Z)V
Method net/minecraft/server/level/ServerPlayer#lambda$sendSystemMessage$9(Lnet/minecraft/network/chat/Component;)Lnet/minecraft/network/protocol/Packet; makes call to bad method net/minecraft/network/protocol/game/ClientboundSystemChatPacket#<init>(Lnet/minecraft/network/chat/Component;Z)V
```

2022-11-19 21:50 UTC, PrimordialMoros reviewed
Changed as requested.

2022-11-21 14:04 UTC, Owen1212055 approved these changes

2022-12-06 21:41 UTC, Machine-Maker requested changes
The vanilla components in the places which previous used the ctor now marked as `DoNotUse` will not use the adventure global renderer. PaperAdventure#asJsonString(nms.Component, Locale) just skips the locale if the component is a plain nms Component. So instead of that, just wrap the vanilla components in PaperAdventure.asAdventure() or convert the whole vanilla component to use the adventure component types.

2022-12-06 23:37 UTC, PrimordialMoros commented
Is that something that should be supported? If someone wanted to edit vanilla translation they should be using the resource pack and not the global renderer.

2022-12-06 23:58 UTC, Machine-Maker commented
I think it should be yes.

The goal of the global renderer is to NOT have to use resource packs. You can already use resource packs with custom translations, you don’t have to only use vanilla ones in resource packs. So if you are arguing for the use of them, you should also argue that the global renderer is useless “cause why not just use resource packs for them”.

2022-12-07 16:49 UTC, PrimordialMoros reviewed
Rebased and converted components to adventure so that GlobalTranslator can be used to override vanilla death messages,

2022-12-09 19:56 UTC, PrimordialMoros commented
Rebased for 1.19.3

2022-12-23 04:46 UTC, Machine-Maker approved these changes

2023-03-04 21:56 UTC, merged

2023-03-04 21:56 UTC, Owen1212055 commented
Thank you for the contribution, apologies for the wait. 😦