Avoid a cubed max search distance for POIs
PaperMC/Paper pull request #8576
Opened 2022-11-19 13:10 UTC by Lulu13022002

Redo of #7830 
The max search distance used to get the closest Poi data on X/Z axis is cubed instead of squared (one time in the parameter and another time in the function) for almost all search.
Generally this has been hidden by another check that already do a pre distance check between the poi pos and the source pos for individual component but the issue still happens for diagonal distance search.
Discovered by Samsuik

2022-11-19 16:08 UTC, Owen1212055 requested changes
There seems to be another group of methods which require the same fixing.

See AquirePoi#start
```java
io.papermc.paper.util.PoiAccess.findNearestPoiPositions(poiManager, this.poiType, predicate, entity.blockPosition(), 48, 48*48, PoiManager.Occupancy.HAS_SPACE, false, 5, poiposes);
```

This calls PoiAccess#findNearestPoiRecords
```java
 public static void findNearestPoiRecords(final PoiManager poiStorage,
                                             final Predicate<Holder<PoiType>> villagePlaceType,
                                             // position predicate must not modify chunk POI
                                             final Predicate<BlockPos> positionPredicate,
                                             final BlockPos sourcePosition,
                                             final int range, // distance on x y z axis
                                             final double maxDistance,
                                             final PoiManager.Occupancy occupancy,
                                             final boolean load,
                                             final int max,
                                             final List<PoiRecord> ret) {
        final Predicate<? super PoiRecord> occupancyFilter = occupancy.getTest();

        final double maxDistanceSquared = maxDistance * maxDistance;
        final Double2ObjectRBTreeMap<List<PoiRecord>> closestRecords = new Double2ObjectRBTreeMap<>();
        int totalRecords = 0;
        double furthestDistanceSquared = maxDistanceSquared;
```

Notice how these methods seem to square it too. So, most likely this should be fixed here too? 
Please correct me if I am wrong..

2022-11-19 16:16 UTC, Lulu13022002 commented
:smile: I was literally relooking at the code and figured that now

2022-11-19 17:36 UTC, Owen1212055 approved these changes

2022-11-20 10:40 UTC, kennytv approved these changes

2022-11-21 14:57 UTC, lynxplay approved these changes

2022-11-21 15:02 UTC, merged