Added missing check
PaperMC/Paper pull request #8624
Opened 2022-12-08 20:05 UTC by NonSwag

Fixed the option "spigot.yml > commands > log" so commands won't be logged into the console anymore if the option is disabled.
The respective code in ServerGamePacketListenerImpl was missing a simple check whether the option is disabled.

2022-12-10 01:07 UTC, Owen1212055 commented
It seems you have two patches in your PR, please remove your previous patch.

2022-12-10 01:09 UTC, Owen1212055 commented on patches/server/0954-added-missing-check.patch
> ++        if (SpigotConfig.logCommands) // Paper - option was not respected
Make sure you wrap your diff in paper comments.
Also use a fully qualified import.
Don't change the indentation of the logging message, this allows you to reduce the diff.
```java
if (org.spigotmc.SpigotConfig.logCommands) // Paper - option was not respected
ServerGamePacketListenerImpl.LOGGER.info(this.player.getScoreboardName() + " issued server command: " + command);
} // Paper
```

2022-12-12 23:08 UTC, electronicboy approved these changes

2022-12-17 01:04 UTC, Machine-Maker requested changes
Also Owen's comment.

2022-12-17 01:04 UTC, Machine-Maker commented on patches/server/0954-added-missing-check.patch
> +Subject: [PATCH] added missing check
The patch title needs to be more descriptive. This tells someone almost nothing.

2022-12-17 01:04 UTC, Machine-Maker commented on patches/server/0953-fixed-npe.patch
> +Subject: [PATCH] fixed npe
This belongs in a separate PR. You seemed to have closed your other PRs for this?

2022-12-23 17:41 UTC, Owen1212055 commented
Superseded as inactivity has prevented us from pushing these patches. Thank you for your contributions!

2022-12-23 17:41 UTC, closed without merging