Fix CreativeCategory api
PaperMC/Paper pull request #8665
Opened 2022-12-13 21:03 UTC by Machine-Maker

Probably in the future this should be expanded to get all itemstacks in a specific category. It's not perfect system since ItemStacks are in categories now, so also a method to check if an ItemStack is in a specific category would be nice.

2022-12-23 15:42 UTC, Owen1212055 requested changes
This doesn't seem to work? 
Tested and it always returns an empty set.

2022-12-23 18:14 UTC, Machine-Maker commented
It'd help if I actually pushed from my local repo...

2022-12-23 18:18 UTC, Owen1212055 approved these changes

2023-05-24 20:19 UTC, AlmightyAnubis commented
Would also be nice if the Materials in the Material Enum would be sortet the way the new search tab in the creativ inventory is sortet. So the wood is grouped etc.

2023-05-24 20:22 UTC, Machine-Maker commented
The material enum is most likely being deprecated either this update or next update, not really worth it.

Even so, I don't really think the order of fields is important at all. Also, some materials are in multiple categories, so not sure how that would factor into the field order.

2023-05-24 20:29 UTC, AlmightyAnubis commented
In the search bar, more or less all items are contained. And they are sortet in the new way, which is much more convinient. When I list items, I would really like this way of order over the old one.
![image](https://github.com/PaperMC/Paper/assets/62308030/dc5badd9-f9d8-42af-9070-9240effa9d36)

2023-05-24 20:32 UTC, electronicboy approved these changes

2023-09-08 18:00 UTC, Warriorrrr approved these changes

2023-09-08 18:00 UTC, Warriorrrr commented on patches/server/0980-Fix-CreativeCategory-api.patch
> ++    public static final List<CreativeModeTab> BLOCK_TABS = CreativeModeTabs.allTabs().stream().filter(tab -> tab.getType() == CreativeModeTab.Type.CATEGORY).toList();
CreativeModeTabs#streamAllTabs can be used here

2024-11-25 05:22 UTC, KodingDev commented
Hey, any updates on this? Can't really fallback to the existing implementation since it's just a constant for all items.

2024-11-25 08:01 UTC, NonSwag commented
> Hey, any updates on this? Can't really fallback to the existing implementation since it's just a constant for all items.

Iirc the creative categories are deprecated since they no longer exist on the server

2024-11-25 14:35 UTC, KodingDev commented
Gotcha, any way we could semi mimic it with tags? That's about the only half-baked solution that's really worked for us

2025-03-23 19:15 UTC, closed without merging