Adds the cancellable ban events and implements them in the server, resolves #678
PaperMC/Paper pull request #870
Opened 2017-08-30 21:04 UTC by spammy23

2017-08-30 21:27 UTC, electronicboy requested changes

2017-08-30 21:27 UTC, electronicboy commented on Spigot-API-Patches/0067-Added-ban-events-resolves-678.patch
> ++++ b/src/main/java/org/bukkit/event/server/BanEvent.java
if there is anything we have learnt, any classes we add should ideally be in our own package as opposed to bukkits

2017-08-30 21:27 UTC, electronicboy commented on Spigot-Server-Patches/0236-Implemented-the-cancellable-ban-events.patch
> +-import java.io.IOException;
Don't reorganise imports, you might wanna disable this feature in your IDE for dealing with paper stuff as it causes issues like this that make handling diffs a headache for everyone.

2017-08-30 21:27 UTC, electronicboy commented on Spigot-Server-Patches/0236-Implemented-the-cancellable-ban-events.patch
> ++        BanIpEvent event = new BanIpEvent(new CraftIpBanEntry(target, entry, list));
// paper

2017-08-30 21:27 UTC, electronicboy commented on Spigot-Server-Patches/0236-Implemented-the-cancellable-ban-events.patch
> ++        if(event.isCancelled()) return null;
This API is pretty much contracted to not return null, do change that contract now would potentially be breaking

2017-08-30 21:27 UTC, electronicboy commented on Spigot-Server-Patches/0236-Implemented-the-cancellable-ban-events.patch
> ++        if(event.isCancelled()) return null;
null

2017-08-30 21:27 UTC, electronicboy commented on Spigot-API-Patches/0067-Added-ban-events-resolves-678.patch
> ++    private boolean cancel = true;
true?

2017-08-30 21:27 UTC, electronicboy commented on Spigot-Server-Patches/0236-Implemented-the-cancellable-ban-events.patch
> ++        if(event.isCancelled()) return null;
I am partially concerned with the practices in this PR, this really isn't all that inclusive either due to how CB has wrapped this, in the event that a ban is done with the vanilla command, this won't actually be caught by this PR.

I would say that these changes are actually better being made in the NMS BanList's, that way it's more inclusive

2017-09-04 13:12 UTC, spammy23 commented
Changing source branch

2017-09-04 13:12 UTC, closed without merging