Parity for respawn events
PaperMC/Paper pull request #8705
Opened 2022-12-21 12:04 UTC by Lulu13022002

The PlayerPostRespawnEvent doesn't support the respawn anchor and doesn't have the respawn flag. This also fix a bug where isBedSpawn is true for respawn anchor.

2023-07-02 23:16 UTC, Machine-Maker requested changes

2023-07-02 23:16 UTC, Machine-Maker commented on patches/api/0287-Reorganize-respawn-events.patch
> +-    private final boolean isAnchorSpawn;
Add a Paper comment saying these were moved to the super type

2023-07-02 23:16 UTC, Machine-Maker commented on patches/api/0287-Reorganize-respawn-events.patch
> +-
Add a paper comment here too saying they were moved to the super type.

2024-06-18 21:30 UTC, SoSeDiK commented
Bump, hoping this PR could get some attention

2024-12-23 17:43 UTC, closed without merging