Make PlayerPurchaseEvent respect result item
PaperMC/Paper pull request #8750
Opened 2023-01-02 01:21 UTC by fr3qu3ncy-dev

When modifying a trade using setTrade() in PlayerPurchaseEvent or PlayerTradeEvent, the result item of that new trade is completely ignored. With this change, you can easily manipulate villager trading from within these events, because it sets the clicked item (which is the result item in MerchantResultSlot) to the new result item.

2023-01-02 02:29 UTC, Machine-Maker commented
I think this won’t work for some inventory actions. Like shift clicking? Just mutating the stack object isn’t enough for that.

2023-01-02 02:35 UTC, fr3qu3ncy-dev commented
@Machine-Maker Also tested with shift clicking, working fine.

2023-01-02 19:49 UTC, Machine-Maker commented
@fr3qu3ncy-dev shift clicking did not work at all. I set the trade to a custom trade in PlayerTradeEvent, shift-clicked the result slot to move the result into my inventory, and the server actually hung in an infinite loop somewhere.

2023-01-02 20:12 UTC, Machine-Maker requested changes
See my comment about the places this is broken.

2023-01-03 19:37 UTC, fr3qu3ncy-dev commented
@Machine-Maker What did you set the recipe to?
![villager_working](https://user-images.githubusercontent.com/58204360/210428830-57557f3d-ce1e-414f-82be-9e4d5e466bc4.gif)

2023-01-03 20:43 UTC, Machine-Maker commented
Set it to something that doesn’t consume the ingredients. I basically changed all trades to diamond for a dirt. Put in emeralds, and shift clicking out didn’t work.

2023-03-24 13:19 UTC, closed without merging