add config for velocity secret key file
PaperMC/Paper pull request #8755
Opened 2023-01-02 21:34 UTC by Misterio77

Adds a `proxies.velocity.secret-file` option, making it possible to specify a file containing the velocity secret file instead of including it in the yml.

Should work nicely, here's a couple of questions:
- Should I bump the config version to 29?
- Should we somehow deprecate the previous option? For now, I've added a log warning for it.

Fixes https://github.com/PaperMC/Paper/issues/6332

2023-01-02 21:40 UTC, tomcraft commented
You should edit the patch adding Velocity support rather than adding a new one.

2023-01-02 21:43 UTC, electronicboy commented
And config file stuff should stay in the config patch

If we're going to force people to move over, we should be handling that as
a migration, but, I'm not sure we should force people to use an external
file

On Mon, 2 Jan 2023, 21:40 _tomcraft, ***@***.***> wrote:

> You should edit the patch adding Velocity support rather than adding a new
> one.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/PaperMC/Paper/pull/8755#issuecomment-1369228290>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAJMAZFU6XH3DT6GWTWD5MLWQNDMTANCNFSM6AAAAAATPDTIWU>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2023-01-03 06:57 UTC, Machine-Maker requested changes

2023-01-03 06:57 UTC, Machine-Maker commented on patches/server/0957-add-config-for-velocity-secret-key-file.patch
> ++            }
I'm not a fan of adding unneeded methods to the config class. Preferably it's just fields. Perhaps we should have a custom type to handle secret in text or secret in file?

2023-01-03 06:57 UTC, Machine-Maker commented on patches/server/0957-add-config-for-velocity-secret-key-file.patch
> ++import java.io.IOException;
Inline the imports (same with other imports into nms classes)

2023-11-09 07:24 UTC, robbelouwet commented
Hi there, what's the status on this?

2024-03-03 21:28 UTC, Owen1212055 commented
Superseded by https://github.com/PaperMC/Paper/pull/10127

2024-03-03 21:28 UTC, closed without merging