Allow plugins to use SLF4J for logging
PaperMC/Paper pull request #890
Opened 2017-09-21 16:49 UTC by Minecrell

This is a set of 3 commits to improve the logging implementation of Paper and allow plugins to use SLF4J as alternative logging API. The exact changes and the reasoning for them is explained in the commit messages (either directly or in the patches) so I'm not going to repeat everything here.

SLF4J is a commonly used abstraction for various logging frameworks and it is the easiest way to handle logging in an implementation-agnostic way. It is also used by many Java libraries as logging abstraction. I intend to create a similar PR for Waterfall so eventually, the same logging API can be used on Paper, Waterfall, Sponge and other modding APIs.

The primary difficulty to make this work was to move the plugin prefixes out of a custom JUL `PluginLogger` implementation and handle them directly in the underlying logging framework (Log4J). Otherwise, messages logged with SLF4J would be missing the plugin prefix.

The solution is pretty simple: Use the plugin name as logger name and make it visible in the log using the Log4J configuration. Hide the logger name for Minecraft and Paper log messages to make it less verbose.

2017-09-21 16:53 UTC, kashike requested changes

2017-09-21 16:53 UTC, kashike commented on Spigot-API-Patches/0067-Handle-plugin-prefixes-in-implementation-logging-con.patch
> ++    private Logger logger = null; // Paper: PluginLogger -> Logger
`// Paper - PluginLogger -> Logger`

2017-09-21 16:53 UTC, kashike commented on Spigot-API-Patches/0067-Handle-plugin-prefixes-in-implementation-logging-con.patch
> ++        this.logger = Logger.getLogger(description.getName()); // Paper: Handle plugin prefix in implementation
`// Paper - Handle plugin prefix in implementation`

2017-09-21 16:53 UTC, kashike commented on Spigot-Server-Patches/0238-Use-Log4j-IOStreams-to-redirect-System.out-err-to-lo.patch
> ++        <!-- Paper: Add additional Log4J dependencies -->
`// Paper - Add additional Log4J dependencies`

2017-09-21 16:53 UTC, kashike commented on Spigot-Server-Patches/0239-Handle-plugin-prefixes-using-Log4J-configuration.patch
> ++                                <!-- Paper: Exclude log4j2-test.xml -->
`// Paper - Exclude log4j2-test.xml`

2017-09-21 16:53 UTC, kashike commented on Spigot-API-Patches/0068-Allow-plugins-to-use-SLF4J-for-logging.patch
> ++        <!-- Paper: Add SLF4J -->
`// Paper - Add SLF4J`

2017-09-21 16:53 UTC, kashike commented on Spigot-Server-Patches/0239-Handle-plugin-prefixes-using-Log4J-configuration.patch
> ++        Bukkit.getLogger().log( Level.INFO, "Server Ping Player Sample Count: {0}", playerSample ); // Paper: Use logger
`// Paper - Use logger`

2017-09-21 16:54 UTC, kashike commented
Have you tested this with some popular plugins, such as `WorldEdit` and `EssentialsX`?

2017-09-21 16:55 UTC, Minecrell commented
@kashike I tested this with the incredibly popular `Bukkittest` plugin: https://gist.github.com/Minecrell/4de33b1b007dba9ce037907cd573c898. I'm sure it has at least as many download as Essentials and WorldEdit...

2017-09-21 17:15 UTC, kashike requested changes

2017-09-21 17:15 UTC, kashike commented on Spigot-API-Patches/0067-Handle-plugin-prefixes-in-implementation-logging-con.patch
> ++        this.logger = Logger.getLogger(description.getName()); // Paper: Handle plugin prefix in implementation
Should be `getPrefix()`.

2017-09-21 18:00 UTC, Minecrell commented
@kashike All fixed. 

I tested with Essentials and WorldEdit and after some work log messages are now visible. Essentials needs a workaround because it uses the `Essentials` logger internally instead of the plugin logger, and redirects its messages to the plugin logger by setting that as a parent. However, since the main plugin logger is now also called `Essentials` this results in an infinite loop. Fixed that by disallowing plugins to modify the parent of the plugin logger. (The warning can be avoided in Essentials [by checking if `getLogger() == LOGGER` ](https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/Essentials.java#L158)).

WorldEdit works correctly but it doesn't use the plugin logger either so a different logger name is displayed in some cases.

Example log: https://gist.github.com/Minecrell/53eb99d4e06eb006b30f7a67decd7be9#file-gistfile1-txt-L104-L119

2017-09-21 18:47 UTC, Minecrell commented
Tested a "few" more plugins. All plugins are working but mostly older, large plugins bypass the plugin logger entirely and add the plugin prefix manually. Some of these plugins will now show the full qualified logger name additionally. We could white-list the packages manually as a workaround...

- **Essentials**: ✔️  Added workaround (see comment above)
- **WorldEdit**: ❗️ Doesn't use plugin logger, full qualified logger name is shown additionally.
- **WorldGuard**: ❗️ Like WorldEdit
- **PermissionsEx**: ❗️ Like WorldEdit
- **Vault**: ✔️ 
- **ProtocolLib**: ✔️ 
- **ServerListPlus**: ✔️ (Great plugin, would recommend it)
- **ViaVersion**: ✔️ 
- **TitleManager**: ❓ Doesn't log anything after starting the server.
- **LuckPerms**: (✔️) Uses colored output and bypasses logger entirely
- **GriefPrevention**: ✔️ 
- **Multiverse-Core**: (✔️) Uses `Minecraft` logger instead of plugin logger and adds plugin prefix manually. Prefix is shown after the `:` (like always without this PR), works correctly otherwise:
    ```
    [20:36:45 INFO] [Multiverse-Core]: Enabling Multiverse-Core v2.5-b719
    [20:36:45 INFO]: [Multiverse-Core] Version 2.5-b719 (API v20) Enabled
    ```
- **Citizens**: (✔️) Like Multiverse-Core
- **VoxelSniper**: ✔️ 
- **NoCheatPlus**: (✔️) Like Multiverse-Core
- **PlaceholderAPI**: ✔️ 
- **ASkyBlock**: ✔️ 
- **Dynmap**: ✔️ 
- **BuycraftX**: ✔️

2017-09-22 07:50 UTC, Minecrell commented
I disabled the logger prefix manually for `com.sk89q.*` and `ru.tehkode.*` so the messages logged by WorldEdit, WorldGuard and PermissionsEx now show up correctly in the log. Adding exclusions for specific plugins is annoying but since these are the only plugins with this problem (at least from the ones I've tested) it might be the best way to fix them.

The implementation in this PR works correctly, it's only plugins that bypass the plugin loggers which may cause issues.

2017-09-22 08:46 UTC, kashike commented
Could you provide an updated log, please?

2017-09-22 09:01 UTC, Minecrell commented
@kashike I could. Maybe I will... Actually, why not? https://gist.github.com/Minecrell/35f5dbb69eefaa3137daece6224588a4

2017-09-22 09:09 UTC, Minecrell commented
@kashike Log with latest Paper build without my changes: https://gist.github.com/Minecrell/daa3e038f47751ed380fba661d3def73

2017-09-22 11:40 UTC, Minecrell commented
Opened similar PR for Waterfall: https://github.com/WaterfallMC/Waterfall/pull/176

2017-09-22 19:25 UTC, Minecrell commented
Moved plugin prefix back to behind the `:` as discussed in `#paper` so it now looks pretty much like before: https://gist.github.com/Minecrell/97145ddccc0062eb7c2f84152caffb50

2017-09-23 18:46 UTC, zachbr approved these changes

2017-09-23 19:51 UTC, kashike approved these changes

2017-09-23 19:56 UTC, kashike commented
![pull the lever](https://media.giphy.com/media/14rfBl2RMAHtCM/giphy.gif)

2017-09-23 19:57 UTC, kashike commented
Thanks, @Minecrell.

2017-09-23 19:57 UTC, merged

2017-09-26 11:49 UTC, mibby commented
Noticed a plugin merging start-up logging verbose with world loading verbose on a single line whereas it didn't before. 

2nd line in particular.
```
[04:07:22] [Server thread/INFO]: [LibsDisguises] Discovered nms version: v1_12_R1
[04:07:23] [Server thread/INFO]: [DabCore] Attempting to load default ItemUtils[DabCore] Loaded default, enjoy :)Preparing start region for level 3 (Seed: -1991970816273548549)[LibsDisguises] Loaded 0 custom disguises
[04:07:23] [Server thread/INFO]: [ConditionalCommands] Enabling ConditionalCommands v1.4
```

Other than that, just EssentialsX whining.
```
[04:07:29] [Server thread/WARN]: [Essentials] Ignoring attempt to change parent of plugin logger
```

2017-09-26 13:14 UTC, Minecrell commented
@mibby That's because DabCore does wonderful logging using `System.out.print` instead of either using a logger(!!) or inserting a new line (e.g. using `println`). Spigot handles this incorrectly, and I fixed it in this PR. Not sure if we should revert it just to keep incorrect behavior...

The Essentials warning is unrelated but can be fixed easily in Essentials. I will try to submit a PR to fix it when I have time, but until then it's just a warning, nothing breaks due to it.