Replace throwing an exception with logging a warning if plugin bootstrap loads another plugin
PaperMC/Paper pull request #8914
Opened 2023-02-24 17:55 UTC by viktorhrekh

Makes the plugin bootstrap more flexible about wrapping your own plugin interfaces into JavaPlugin implementation

2023-02-24 17:59 UTC, viktorhrekh commented
@Owen1212055, created another PR as it seems easier and cleaner :)

2023-02-24 19:41 UTC, Machine-Maker requested changes

2023-02-24 19:41 UTC, Machine-Maker commented on patches/server/0962-Log-warning-instead-of-exception-if-plugin-bootstrap.patch
> ++                    logger.warning("Plugin " + getMeta().getName() + " uses bootstrap that is returning another plugin.");
Does this even have to be a warning? I would just log an info that contains the type of the provided plugin and something about it not matching the configured main class.

2023-02-25 14:14 UTC, lynxplay approved these changes

2023-02-25 14:18 UTC, lynxplay commented
LGTM, generally should go into the original paper plugins patch instead of its own patch.
You can do that yourself or the developer or maintainer merging this can do it for you :+1:

2023-02-25 18:00 UTC, viktorhrekh commented
@lynxplay @Machine-Maker

2023-02-26 17:41 UTC, Machine-Maker approved these changes

2023-02-28 12:17 UTC, merged