fix for #8982
PaperMC/Paper pull request #8998
Opened 2023-03-18 14:07 UTC by GOjayson

If it is totally wrong please let me know, i'm new and trying to help.

2023-03-18 14:11 UTC, lynxplay requested changes
Welcome to your first paper PR! 

As mini mentioned, this should most likely be behind a configuration option.
We also definitely still want to remove the PublicBukkitValues from the tag before sending.

To add configuration to paper (see minis comment on the issue) you want to be editing https://github.com/PaperMC/Paper/blob/master/patches/server/0005-Paper-config-files.patch. I'd argue we would want boolean toggles for PDC and LootTables separately.

2023-03-18 14:14 UTC, GOjayson commented
Okay thank you for the directions!

2023-03-21 10:02 UTC, GOjayson commented
Hmm, I might have done the patching wrong.

2023-03-21 19:21 UTC, Lulu13022002 reviewed
It seems that you have now two patches, when you add a new change (to an already created patch) you need to amend the commit (while the rebase) to avoid creating a duplicate patch but for now you can just drop the first one

2023-03-21 19:21 UTC, Lulu13022002 commented on patches/server/0967-Added-config-to-Hide-loottables-and-PDC.patch
> ++        if (hidePdc && tag.contains("PlayerData")) {
This is the wrong tag for the pdc, idk from what this come but the pdc tag is the "PublicBukkitValues" even if the name is not really good.

2023-03-21 19:21 UTC, Lulu13022002 commented on patches/server/0967-Added-config-to-Hide-loottables-and-PDC.patch
> ++import java.awt.print.Paper;
Clean your import a little bit to reduce the diff

2023-03-21 19:21 UTC, Lulu13022002 commented on patches/server/0967-Added-config-to-Hide-loottables-and-PDC.patch
> ++        public boolean hideLootTables = false;
I don't think this is the right config section. should go below the anticheat.obfuscation.tile-entities/block-entities or somethings like that.

2023-03-21 19:26 UTC, GOjayson commented on patches/server/0967-Added-config-to-Hide-loottables-and-PDC.patch
> ++        if (hidePdc && tag.contains("PlayerData")) {
Ohw wow, yea found it a bit confusing. Thanks.

2023-03-21 19:26 UTC, GOjayson commented on patches/server/0967-Added-config-to-Hide-loottables-and-PDC.patch
> ++import java.awt.print.Paper;
Will clean up, Thanks

2023-03-21 19:27 UTC, GOjayson commented on patches/server/0967-Added-config-to-Hide-loottables-and-PDC.patch
> ++        public boolean hideLootTables = false;
Yea i've just put them somewhere in the config, i'm not farmiliar yet with all config things. Thank you for correcting me, will change it.

2023-03-22 18:48 UTC, GOjayson commented
Okay, finallly. I got a headache trying not to push the wrong things. I hope this is better. 

I don't know if the Configuration part is fully right now. I've put it into Anticheat and added the bools to an enity configurationpart.

2023-03-22 18:58 UTC, GOjayson commented
Ok should all be fixed now.

2023-03-23 13:38 UTC, GOjayson commented
No... nvm. I don't know what happend exactly but my branch is a mess. I'm going to close this PR and open a new one.

2023-03-23 13:38 UTC, closed without merging