Fix PaperPluginMeta#getDisplayName
PaperMC/Paper pull request #9038
Opened 2023-03-24 19:48 UTC by TheRealRyGuy

fixes #9027, below is the only change
```java
@Override
    public @NotNull String getDisplayName() {
        return this.displayName + " v" + this.getVersion();
    }
```

2023-03-24 19:56 UTC, Machine-Maker requested changes
The fix for this is to change what is assigned to the `displayName` field when the meta is created.

2023-03-24 19:58 UTC, Owen1212055 commented
Also please merge this change into the original paper plugin patch.

2023-03-24 20:14 UTC, TheRealRyGuy commented
```java
pluginConfiguration.displayName = pluginConfiguration.name.replace('_', ' ') + " v" + pluginConfiguration.version;
```
Assuming the original patch was `patches/server/0013-Paper-Plugins.patch`, done

2023-03-24 20:14 UTC, Machine-Maker approved these changes

2023-03-25 01:45 UTC, TheLukeGuy commented
Thanks for fixing this. :)

The behavior of the `/version` command with just this change is a little weird with Paper plugins:
```
> pl
[21:36:12 INFO]: Server Plugins (2):
[21:36:12 INFO]: Paper Plugins:
[21:36:12 INFO]:  - Outlet
[21:36:12 INFO]: Bukkit Plugins:
[21:36:12 INFO]:  - Essentials
> ver outlet
[21:36:13 INFO]: Outlet v1.0.0-SNAPSHOT version 1.0.0-SNAPSHOT
[21:36:13 INFO]: A modern plugin manager for Paper.
[21:36:13 INFO]: Website: https://github.com/TheLukeGuy/outlet
[21:36:13 INFO]: Author: TheLukeGuy
> ver essentials
[21:36:15 INFO]: Essentials version 2.20.0-dev+45-bf14b88
[21:36:15 INFO]: Provides an essential, core set of commands for Bukkit.
[21:36:15 INFO]: Website: https://essentialsx.net/
[21:36:15 INFO]: Authors: Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, md_5, Iaccidentally, drtshock, vemacs, SupaHam, mdcfe, JRoy and pop4959
```

As you can see, the first line of `/ver [paper plugin name]` is `[Plugin name] v[plugin version] version [plugin version]`, while the first line of `/ver [bukkit plugin name]` is `[Plugin name] version [plugin version]`. This was the only oddity that I could find from a couple minutes of basic testing, but I didn't do a deep look into where `getDisplayName` is used.

2023-03-25 03:13 UTC, TheRealRyGuy commented
Should've fixed version command, didn't realize it relied on description files 
This did modify PluginDescriptionFile instantiation which probably has repercussions I can't think of, but here we are. Current application makes more sense in my head, as `PluginDescriptionFile#rawName` should have underscores, where `#name` should be the formatted nice name I feel like

2023-03-25 03:26 UTC, Machine-Maker requested changes

2023-03-25 03:26 UTC, Machine-Maker commented on patches/server/0013-Paper-Plugins.patch
> ++            config.getName(),
I disagree with this change. the rawName and name parameters should be set correctly. the `displayName` is not correct here. The first parameter should just be getName(), the second parameter should be getName() but replacing `_` with ` ` (which is what getDisplayName() used to be).

2023-03-25 04:40 UTC, TheRealRyGuy commented
yeah you right, that made no sense oops
this (should?) be the final major place where versioning needs a quick fix though

2023-03-25 06:25 UTC, Machine-Maker approved these changes

2023-03-28 01:39 UTC, Owen1212055 approved these changes

2023-03-28 02:56 UTC, merged