Fixed Unix Domain Socket Patch
PaperMC/Paper pull request #9086
Opened 2023-04-02 21:13 UTC by MarkusTieger

It Fixes that an exception is thrown when using a Unix Domain Socket.

2023-04-15 23:31 UTC, Owen1212055 requested changes
Please wrap your diff in paper comments, and use fully qualified names to avoid imports.

2023-09-08 16:10 UTC, Warriorrrr commented
@MarkusTieger Any chance you could revisit this PR and address Owen's comment? If you don't have time to update it we could update/supersede this ourselves.

2023-09-08 23:27 UTC, MarkusTieger commented
> @MarkusTieger Any chance you could revisit this PR and address Owen's comment? If you don't have time to update it we could update/supersede this ourselves.

Sorry, i completely forgot about this pr. I will update it tomorrow and address the comments...

2023-09-09 17:05 UTC, MarkusTieger commented
If you need something to test:
https://github.com/MarkusTieger/Velocity/tree/dev/3.0.0
(from an older velocity pr, that wasn't merge because it broke the api. I updated it and it still works fine. Velocity 5.0.0 does support uds, but not 1.20.1)

2023-09-15 06:35 UTC, Warriorrrr reviewed
Still missing some paper comments, will give this a test later today

2023-09-15 06:35 UTC, Warriorrrr commented on patches/server/0608-Add-Unix-domain-socket-support.patch
> ++        java.net.InetAddress rawAddress = java.net.InetAddress.getLoopbackAddress();
Some paper comments are still needed here

2023-09-15 06:35 UTC, Warriorrrr commented on patches/server/0608-Add-Unix-domain-socket-support.patch
> ++                        if(rawSocketAddress != null && rawSocketAddress instanceof java.net.InetSocketAddress rawInetSocketAddress) {
Missing space between the if and (, same for the diff below

2023-09-15 15:23 UTC, Warriorrrr commented on patches/server/0609-Add-Unix-domain-socket-support.patch
> ++                        if (rawSocketAddress != null && rawSocketAddress instanceof java.net.InetSocketAddress rawInetSocketAddress) {
Null check here can be removed here and in the other spot, the instanceof takes care of it

2023-09-16 23:51 UTC, electronicboy submitted a review, later dismissed

2023-09-16 23:59 UTC, lynxplay commented
After some further discussion, this should properly address the API as well.
imo best to pass the entire SocketAddress to the PlayerLoginEvent and AsyncPlayerPreLoginEvent, deprecated the existing
methods yielded InetAddress and having them do the fallback, e.g. the API would have the 
```java
if (this.socketAddr instanceOf InetSocketAddress inet) return inet.getAddress();
return getLoopback()
```

and adding a new method that yields the plain socket addr.
Additionally, mark the constructors you change with `@ApiStatus.Internal`

2023-09-26 10:21 UTC, MarkusTieger commented
Would be great, if someone could rebase it, because there are conflicts and i never actually dealt with them in **patches**.
(Let's say i tryed, and after that, the applyPatches task failed)

2024-11-11 14:18 UTC, MarkusTieger commented
tbh I don't want to deal with this pr anymore.

2024-11-11 14:18 UTC, closed without merging