Handle location of player if was moved for not valid world
PaperMC/Paper pull request #9116
Opened 2023-04-10 16:04 UTC by Doc94

This close #9081 like the issue said when the world of spawn change because the world is unloaded or not exists keep the previous location causing issues when the player spawn, this PR modify two patchs related to handle the world spawn for add a conditional for call a method used to handle location for "new" players in world.

2023-04-10 16:08 UTC, Doc94 commented
NOTE: I prefer only edit the patchs... but maybe is better merge the two patchs in one because the two are related to the spawn player. (but dont know how correctly make this and not destroy git in the process)

also... if can add the label for get a JAR for allow the user in the ticket test, i make basic test using vanilla worlds (me in the end, stop server, delete end and start server again)

2023-04-10 21:31 UTC, Machine-Maker requested changes
This only handles when the dimension isn't parsed successfully from the playerdata. You need to add something where the server checks if a world exists with the parsed key. Where the logger warns about spawning in an unknown world

2023-08-16 08:20 UTC, Warriorrrr reviewed
needResetSpawnPos should also be set to true if the world isn't found like MM said. https://github.com/PaperMC/Paper/blob/73af2d4cea597e65dd13dafab6325ea5709c9067/patches/server/0435-Spawn-player-in-correct-world-on-login.patch also defaults the level key to overworld which will also need to be accounted for.

2023-08-16 08:20 UTC, Warriorrrr commented on patches/server/0384-Move-player-to-spawn-point-if-spawn-in-unloaded-worl.patch
> ++            // Paper stop
```suggestion
+            // Paper end
```

2023-11-04 21:12 UTC, Machine-Maker commented
Superseded by #9887

2023-11-04 21:12 UTC, closed without merging