add AttemptItemMergeEvent
PaperMC/Paper pull request #9152
Opened 2023-04-19 06:22 UTC by ham1255

*updated version of* #9151  

Basically this event is called before ItemMergeEvent which can allow to see which items are trying to merge,
unlike ItemMergeEvent which thrown on successful merged items, this event is called before checking if can be merged

## example:
throwing Dead bush with Red

```java
@EventHandler
    public void onAttemptItemMerge(AttemptItemMergeEvent e) {
        Item source = e.getEntity();
        Item target = e.getTarget();
        this.getSLF4JLogger().info("Item {} {}  is trying to merge with {} {}",
                source.getItemStack().getType(), source.getUniqueId(), target.getItemStack().getType(), target.getUniqueId());
    }
```
console:
```
[10:13:27 INFO]: [paperweight-test-plugin] Item DEAD_BUSH a474ec48-be9d-4079-85d2-a5c69d8aed03  is trying to merge with RED_SAND 28cbb557-ca5b-49b7-8524-fe2a77eb4181
[10:13:27 INFO]: [paperweight-test-plugin] Item RED_SAND 28cbb557-ca5b-49b7-8524-fe2a77eb4181  is trying to merge with DEAD_BUSH a474ec48-be9d-4079-85d2-a5c69d8aed03
[10:13:29 INFO]: [paperweight-test-plugin] Item DEAD_BUSH a474ec48-be9d-4079-85d2-a5c69d8aed03  is trying to merge with RED_SAND 28cbb557-ca5b-49b7-8524-fe2a77eb4181
[10:13:29 INFO]: [paperweight-test-plugin] Item RED_SAND 28cbb557-ca5b-49b7-8524-fe2a77eb4181  is trying to merge with DEAD_BUSH a474ec48-be9d-4079-85d2-a5c69d8aed03
```

2023-04-19 06:27 UTC, lynxplay commented
I am rather confused here, the ItemMergeEvent provides both the item entities involved in the merge as per:
https://jd.papermc.io/paper/1.19/org/bukkit/event/entity/ItemMergeEvent.html#getEntity()
https://jd.papermc.io/paper/1.19/org/bukkit/event/entity/ItemMergeEvent.html#getTarget()

Beyond that, what is the point of calling this event before even testing for mergeability ?
Items that will never merge do not "attempt" to merge either, so the event name seems off here.

2023-04-19 06:35 UTC, ham1255 commented
1: ItemMergeEvent only fires when item successfully merges, not when tries to merge.

2: Reason i called it AttemptItemMergeEvent is because is tryToMerge method from game's code 
- if name is not sutible what do you suggest here?

converting to draft for now

2023-04-19 06:38 UTC, lynxplay commented
Ah, I misread your PR then. Exposing an event called when invalid items "attempt" or well, whatever they do, to merge seems interesting. I presume use-cases for this is manually merging non-mergable items ?

It would be a rather hot event when called concerning it would fire every tick for items that won't merge.

2023-04-25 17:57 UTC, Machine-Maker requested changes
I'm still not sold on the need for this event. You are incorrect in saying that `ItemMergeEvent` is only called after a merge. It is cancellable, and cancelling it stops the merge from happening.

2023-04-25 17:57 UTC, Machine-Maker commented on patches/api/0416-Add-AttemptItemMergeEvent.patch
> ++package org.bukkit.event.entity;
New events should go in a paper package not bukkit.

2023-04-25 17:57 UTC, Machine-Maker commented on patches/server/0975-Implement-event-calling-for-AttemptItemMergeEvent.patch
> ++import org.bukkit.event.entity.AttemptItemMergeEvent; // Paper - AttemptItemMergeEvent
Don't add this import, just use the fully qualified name directly.

2023-04-25 17:57 UTC, Machine-Maker commented on patches/server/0975-Implement-event-calling-for-AttemptItemMergeEvent.patch
> ++        if (org.bukkit.craftbukkit.event.CraftEventFactory.callAttemptItemMergeEvent(other, this).isCancelled()) return; // Paper - AttemptItemMergeEvent
Change this to just be a line addition instead of a line replacement

2023-04-26 00:39 UTC, ham1255 commented
> I'm still not sold on the need for this event. You are incorrect in saying that `ItemMergeEvent` is only called after a merge. It is cancellable, and cancelling it stops the merge from happening.

reason i said it that way looking at merge method that where event resides. but eh i agree its incorrect to say it that way.

also reason i added the event is doing merging myself *in a plugin* rather using server code, so i can change items data etc rather than relying on some runnable

2023-05-03 11:17 UTC, electronicboy commented
part of my question here is why is this event firing for items which will never be mergable? really not fond of adding spammy as all heck events for niche use-cases

2023-05-07 15:23 UTC, closed without merging