Add PlayerShieldDisableEvent
PaperMC/Paper pull request #9177
Opened 2023-05-01 21:28 UTC by Cryptite

Called whenever a player's shield is being disabled. The cooldown (default 100 ticks) is also provided to optionally be changed

2023-05-02 12:48 UTC, Owen1212055 commented on patches/api/0417-Add-PlayerShieldDisableEvent.patch
> ++     * @return Return the Entity that caused the shield disable attempt
Can you document what might make it be null?

2023-05-06 16:09 UTC, kennytv approved these changes

2023-05-06 16:40 UTC, Machine-Maker requested changes
As I was looking over the impl for this event, I realized its REALLY close to another event, the `PlayerItemCooldownEvent`. 

Would it be better to make this event a sub-event of that event, adding the extra context for the damager? The cooldown event is called right inside addCooldown, so its not really that big of a refactor I don't think.

2023-05-06 16:40 UTC, Machine-Maker commented on patches/api/0417-Add-PlayerShieldDisableEvent.patch
> ++    private static final HandlerList handlers = new HandlerList();
Use java standards for static finals, `HANDLER_LIST` preferably.

2023-05-06 23:27 UTC, Cryptite commented
> As I was looking over the impl for this event, I realized its REALLY close to another event, the `PlayerItemCooldownEvent`.
> 
> Would it be better to make this event a sub-event of that event, adding the extra context for the damager? The cooldown event is called right inside addCooldown, so its not really that big of a refactor I don't think.

Less code best code!

2023-05-07 04:08 UTC, Machine-Maker requested changes

2023-05-07 04:08 UTC, Machine-Maker commented on patches/api/0417-Add-PlayerShieldDisableEvent.patch
> ++    private static final HandlerList HANDLER_LIST = new HandlerList();
My idea actually involved not having a handler list on this event. That way a listener for PlayerItemCooldownEvent would also catch this one.

2023-05-07 04:08 UTC, Machine-Maker commented on patches/server/0977-Add-PlayerShieldDisableEvent.patch
> ++            this.getCooldowns().addCooldown(Items.SHIELD, shieldDisableEvent.getCooldown());
same situation here, need to not fire the event inside addCooldown.

2023-05-07 04:08 UTC, Machine-Maker commented on patches/server/0977-Add-PlayerShieldDisableEvent.patch
> ++                player.getCooldowns().addCooldown(Items.SHIELD, shieldDisableEvent.getCooldown());
You need some way to bypass the `PlayerItemCooldownEvent` that is fired inside addCooldown because we just fired it.

2023-05-07 04:08 UTC, Machine-Maker requested changes
I should've been more explicit with what I meant by making it a sub event. Not just re-using the class, but replacing the PlayerItemCooldownEvent call with this one.

2023-12-24 22:15 UTC, Owen1212055 commented on patches/server/1053-Add-PlayerShieldDisableEvent.patch
> ++                if (!shieldDisableEvent.callEvent()) return;
@lynxplay Seeing as thou you may have reimplemented this stuff, is there a reason why `return` is being done here? (Also applies above)

2023-12-28 23:07 UTC, lynxplay commented
Rebased this once more.
I have dropped the extends for the item cooldown event.

In general, issue with that even being a child of item cooldown event is that plugins listening for the cooldown event itself might cancel a shield disable, leading to the extra "effect" of a disabled shield damage event, (no stopUse item call and no game event) which might not be intended.

2023-12-29 00:01 UTC, Machine-Maker approved these changes

2023-12-29 00:27 UTC, merged