[WIP] Sponge Async lighting patch porting
PaperMC/Paper pull request #920
Opened 2017-10-16 21:43 UTC by mikroskeem

I did quick copypasta from my [initial try](https://github.com/mikroskeem/asynclighting) of async patch port.

Known needed changes:
- Remove bunch of `// MCP - ...` comments
- More OBFHELPERS (and thus imports) needed!
- Paper start/end comments need to be improved (imo)

Do not merge yet, code needs review and changes listed above (atleast)

2017-10-17 17:31 UTC, aikar requested changes
As mentioned on IRC. I'd like to see most of the sponge neighbor changes removed, and keep to the CB system as they seem to function the same.

However, we can keep just the new additions to maintain the new getNeighbors()/getNeighbor() method to get direct chunk refs, as that avoids map lookups.

So can you remove all the areNeighborsLoaded changes and keep that logic to as it was and only keep the parts to maintain the neighbors chunk array.

2017-10-17 17:31 UTC, aikar commented on Spigot-Server-Patches/0246-Port-Sponge-Async-lighting-patch-to-Paper.patch
> ++    public void setBlockLight(int i, int j, int k, int l) { b(i, j, k, l); }
Missing // Paper - OBFHELPER

2017-10-17 17:31 UTC, aikar commented on Spigot-Server-Patches/0246-Port-Sponge-Async-lighting-patch-to-Paper.patch
> ++        // Paper start - asynclighting
Is it intended that any calls to the previous recheckGaps is now no longer going to do anything....?

2017-10-17 17:31 UTC, aikar commented on Spigot-Server-Patches/0246-Port-Sponge-Async-lighting-patch-to-Paper.patch
> ++    private java.util.concurrent.CopyOnWriteArrayList<Short> queuedSkyLightingUpdates = new java.util.concurrent.CopyOnWriteArrayList<>();
Can we use a ConcurrentLinkedQueue for all of these?

COWAL imo should not be used for things you expect lots of changes to.

2017-10-17 17:31 UTC, aikar commented on Spigot-Server-Patches/0246-Port-Sponge-Async-lighting-patch-to-Paper.patch
> ++        asyncLightingThreads = getInt("settings.async-lighting-threads", 2);
I'm actually in favor of not making this configurable at all.

It's going to lead to people thinking more threads = better.

2017-11-16 05:02 UTC, daboluo666 commented
Awesome! I believe this has a good performance improvement, what is hindering your plan? @mikroskeem

2017-11-16 07:18 UTC, electronicboy commented
There is currently an issue where the patch basically ends up breaking world generation, I have some levels of theory into what is going on, but need to look closer at CBs/Spigots changes in regards to ticking chunks

2017-12-01 11:15 UTC, SecretlyJealous commented
Really hoping this patch is sorted before 1.13 comes out, been stuck using Paper-1228 because of the lag/crashes that occur when calculating the lightmap properly.

2017-12-18 07:41 UTC, electronicboy commented
In the latest build (https://ci.destroystokyo.com/job/PaperSpigot/1275/), I have brought back spigots broken lighting logic, it was never intended that we'd leave this change in without the async chunk lighting for this long, however, shamefully I haven't had the time to sit down and work out the issues around craftbukkits chunk ticking logic which is causing breakage.

2018-03-18 18:20 UTC, kashike commented
@mikroskeem Do you plan on completing this?

2018-03-18 18:52 UTC, zachbr commented
@kashike I believe @electronicboy has already pulled this into a feature branch and was doing work on it there. My understanding is that the changes in that branch are more up-to-date than the ones in this PR. https://github.com/PaperMC/Paper/tree/feature/async-lighting

2018-03-18 20:31 UTC, mikroskeem commented
In that case yes, this can be closed.

2018-03-18 20:32 UTC, closed without merging