Allow LEFT_CLICK_AIR in 3.0->4.5 range of entity
PaperMC/Paper pull request #9211
Opened 2023-05-14 13:50 UTC by Moulberry

In Creative, the block and entity reach is the same (4.5), so the code works as is.
In Adventure, the event always fires, so the code works as is.
In Survival, the block reach is 4.5 and the entity reach is 3.0. Therefore, the existing code will not fire a LEFT_CLICK_AIR if an entity is between 3.0 and 4.5 blocks away.

To be honest, this entire method of performing a raycast to decide whether or not to fire a LEFT_CLICK_AIR is rather error-prone, even with this fix. As of 1.19.4, the vanilla client will send the block/entity interaction packets before the swing, so using that information to decide whether or not to fire LEFT_CLICK_AIR would (in my opinion) be more reliable.

2023-05-14 14:33 UTC, Owen1212055 commented on patches/server/0979-Allow-LEFT_CLICK_AIR-in-3.0-4.5-range-of-entity.patch
> +         org.bukkit.util.RayTraceResult result = this.player.level.getWorld().rayTrace(origin, origin.getDirection(), d3, org.bukkit.FluidCollisionMode.NEVER, false, 0.1, entity -> entity != this.pla
Can this fix also be extended to this ray? Make the width 0, not 0.1.

2023-05-14 14:34 UTC, Owen1212055 commented on patches/server/0979-Allow-LEFT_CLICK_AIR-in-3.0-4.5-range-of-entity.patch
> ++        if (result == null || this.player.gameMode.getGameModeForPlayer() == GameType.ADVENTURE || (player.gameMode.getGameModeForPlayer() != GameType.CREATIVE && result.getHitEntity() != null && or
Double-paper comments for this are a bit iffy. Maybe instead we could just squash this into the original patch, and make the logic a bit more readable here.

2023-05-20 20:34 UTC, Owen1212055 commented on patches/server/0530-Fix-interact-event-not-being-called-sometimes.patch
> ++        if (this.player.gameMode.getGameModeForPlayer() == GameType.ADVENTURE) {
Avoid changing the indentation to reduce diff

2023-05-20 21:26 UTC, 3meraldK commented
Tested on build-pr-jar, and works.

2023-05-20 21:34 UTC, Moulberry commented
Last commit changes Adventure mode bypass to specifically check if the hit type is block. The old patch was broken in this regard.

2023-06-11 12:01 UTC, 3meraldK commented
Can you @Owen1212055 review this pull?

2023-06-12 19:38 UTC, Owen1212055 approved these changes
Tested locally, LGTM. Needs to be rebased however.

2023-06-13 09:58 UTC, Moulberry commented
PR is based once again

2023-06-19 14:10 UTC, Moulberry commented
I'm not going to continually rebase this PR.
Whenever a maintainer is ready to merge, it can be rebased.

2023-06-22 15:01 UTC, kennytv approved these changes

2023-07-13 23:56 UTC, Machine-Maker requested changes
Other than the one thing, this is good.

2023-07-13 23:56 UTC, Machine-Maker commented on patches/server/0521-Fix-interact-event-not-being-called-sometimes.patch
> ++                CraftEventFactory.callPlayerInteractEvent(this.player, Action.LEFT_CLICK_AIR, this.player.getInventory().getSelected(), InteractionHand.MAIN_HAND);
I think this action should be `LEFT_CLICK_BLOCK` correct? If the ray trace hits a block, that means you interacted with a block?

2023-07-14 17:39 UTC, lynxplay approved these changes
LGTM

2023-07-15 19:40 UTC, Owen1212055 approved these changes

2023-07-16 15:27 UTC, Machine-Maker approved these changes

2023-07-16 15:58 UTC, merged