Add transient modifiers
PaperMC/Paper pull request #9244
Opened 2023-05-31 21:45 UTC by Malfrador

This PR adds a new method to  [AttributeInstance](https://jd.papermc.io/paper/1.19/org/bukkit/attribute/AttributeInstance.html), ``addTransient(AttributeModifier)``. This allows adding modifiers as transient. Transient modifiers don't get saved with the NBT data.
Vanilla itself uses transient modifiers for speed modifications like sprinting or powder snow. This just exposes it in the API.
I added this API to my fork earlier and it works fine there.

Closes #9243

2023-05-31 21:49 UTC, JRoy requested changes

2023-05-31 21:49 UTC, JRoy commented on patches/api/0416-Add-transient-modifier-API.patch
> ++
paper comments

2023-05-31 21:49 UTC, JRoy commented on patches/server/0984-Add-transient-modifier-API.patch
> ++
paper comments

2023-05-31 21:49 UTC, JRoy commented on patches/server/0984-Add-transient-modifier-API.patch
> ++import org.jetbrains.annotations.NotNull;
inline import

2023-05-31 23:35 UTC, Owen1212055 approved these changes

2023-06-01 00:37 UTC, Machine-Maker approved these changes

2023-06-01 10:59 UTC, Lulu13022002 commented
I think an override is needed in the UnmodifiableAttributeInstance class

2023-06-01 14:58 UTC, Malfrador commented
Added an override, didn't know this API existed.

2023-06-01 17:47 UTC, electronicboy approved these changes

2023-06-05 17:15 UTC, merged