Suppress Item Meta Validation Checks
PaperMC/Paper pull request #9331
Opened 2023-06-12 18:47 UTC by Owen1212055

Fixes https://github.com/PaperMC/Paper/issues/9314

The underlying issue is item meta, but getting rid of that implementation is future plans. 😄

2023-06-13 05:14 UTC, Machine-Maker requested changes

2023-06-13 05:14 UTC, Machine-Maker commented on patches/server/0978-Suppress-Item-Meta-Validation-Checks.patch
> ++                } catch (Exception ignored) {} // Paper
I'm not sure I really like this. We shouldn't catch "all" exceptions as that could hide stuff. But just handle the key being invalid for each or the mat or pattern being null.

2023-06-13 05:26 UTC, Owen1212055 commented on patches/server/0978-Suppress-Item-Meta-Validation-Checks.patch
> ++                } catch (Exception ignored) {} // Paper
I mean any errors that would be occurring here anyways shouldn’t happen anyways, as there is no reason why arbitrary NBT should throw exceptions like this. And these are really temporary fixes.

I mean I’m happy to more fine tune it, but I just don’t see the point.

Should I:
- Only catch certain exception types (NPE, illegal arg ex)
- Change logic to check if the key is null
- Leave it be

I’m open, curious what others think too.

2023-06-14 04:03 UTC, Machine-Maker commented on patches/server/0978-Suppress-Item-Meta-Validation-Checks.patch
> ++                } catch (Exception ignored) {} // Paper
I think you check if key is null, and then check if returned trimMaterial/Pattern is null. If any of them are null, you just don't create the ArmorTrim instance and set it to the `trim` field.

2023-07-13 20:29 UTC, Machine-Maker approved these changes

2023-07-13 20:59 UTC, merged