Mark Player.sendSignChange as deprecated
PaperMC/Paper pull request #9382
Opened 2023-06-22 16:56 UTC by Infynyty

As discussed in #9303 this pull request marks the Player.sendSignChange methods as deprecated in favor of Player.sendBlockUpdate.

2023-06-22 19:29 UTC, Machine-Maker requested changes
The methods should be deprecated in adventure, and the deprecation messages on both the String and Component methods should all point to sendBlockUpdate. Also, I think it should expand more on how to exactly replicate behavior, like say to create sign tile states via `Material.OAK_SIGN.createBlockData().createTileState()` or whatever it is exactly.

2023-06-26 04:06 UTC, KabanFriends commented
Is there even an API to create arbitary TileStates?

2023-06-26 04:10 UTC, KabanFriends commented
> The methods should be deprecated in adventure, and the deprecation messages on both the String and Component methods should all point to sendBlockUpdate. Also, I think it should expand more on how to exactly replicate behavior, like say to create sign tile states via `Material.OAK_SIGN.createBlockData().createTileState()` or whatever it is exactly.

Is there even an API to create arbitrary TileStates?
Also, names mentioned in the docs seems to be wrong. It should be `sendBlockChange` instead

2023-06-26 06:09 UTC, Machine-Maker commented
> Is there even an API to create arbitrary TileStates?

Yes, recently added by upstream, `BlockData#createBlockState`.

2023-06-26 06:21 UTC, yannicklamprecht commented
> > The methods should be deprecated in adventure, and the deprecation messages on both the String and Component methods should all point to sendBlockUpdate. Also, I think it should expand more on how to exactly replicate behavior, like say to create sign tile states via `Material.OAK_SIGN.createBlockData().createTileState()` or whatever it is exactly.
> 
> Is there even an API to create arbitrary TileStates?
> Also, names mentioned in the docs seems to be wrong. It should be `sendBlockChange` instead of `sendBlockUpdate`.


Have fun with the examples.
https://gist.github.com/yannicklamprecht/f42caeade70ffec33ee1e0c15bcabfef

2023-07-19 21:26 UTC, Owen1212055 approved these changes

2023-07-20 22:06 UTC, yannicklamprecht approved these changes

2023-07-22 19:28 UTC, Machine-Maker approved these changes

2023-07-22 19:38 UTC, merged