feat: add minimessage tag resolvers overload to CommandSender#sendMes…
PaperMC/Paper pull request #9505
Opened 2023-07-17 21:49 UTC by powercasgamer

2023-07-17 21:52 UTC, lynxplay commented on patches/api/0005-Adventure.patch
> ++
probably accidentally reformatted imports ?

2023-07-17 21:54 UTC, powercasgamer commented on patches/api/0005-Adventure.patch
> ++
> probably accidentally reformatted imports ?

Accidentally imported TagResolver at first

2023-07-18 00:56 UTC, Machine-Maker requested changes

2023-07-18 00:56 UTC, Machine-Maker commented on patches/api/0005-Adventure.patch
> ++    default void sendRichMessage(final @NotNull String message, final net.kyori.adventure.text.minimessage.tag.resolver.TagResolver... resolvers) {
```suggestion
+    default void sendRichMessage(final @NotNull String message, final net.kyori.adventure.text.minimessage.tag.resolver.@NotNull TagResolver... resolvers) {
```

2023-07-18 02:44 UTC, Machine-Maker approved these changes

2023-07-20 09:05 UTC, kashike approved these changes

2023-07-23 05:46 UTC, merged