Add and implement PlayerFailMoveEvent
PaperMC/Paper pull request #9535
Opened 2023-07-26 13:44 UTC by Moulberry

Event runs when the client attempts to move, but is prevented from doing so by the server

The movement can be allowed by calling "setAllowed(true)"
Warning messages can be prevented by calling "setLogWarning(false)"

Event can be used to:
- Prevent lagback when interacting with certain game elements like launchers, double jump, etc.
- Disable movement checks for admins
- Prevent 'moved too quickly' and 'moved wrongly' messages from being logged

Event can also be implemented for vehicle movement, but I've skipped that in this PR.

2023-07-26 16:02 UTC, Camotoy commented
I could see this having use for Geyser wherever we can't figure out, or implement a reasonable fix, for incorrect movement.

It does seem like you could reduce diff by having a function that is called in the three spots you replace? Each codeblock seems to be doing, more or less, the same thing.

2023-08-06 02:45 UTC, kennytv requested changes

2023-08-06 02:45 UTC, kennytv commented on patches/server/0994-Implement-PlayerFailMoveEvent.patch
> ++                                var event = fireFailMove(io.papermc.paper.event.player.PlayerFailMoveEvent.FailReason.MOVED_INTO_UNLOADED_CHUNK,
var bad

2023-08-06 02:45 UTC, kennytv commented on patches/server/0994-Implement-PlayerFailMoveEvent.patch
> ++                                    this.internalTeleport(this.player.getX(), this.player.getY(), this.player.getZ(), this.player.getYRot(), this.player.getXRot(), Collections.emptySet());
If you dont change the line, as dumb as it'll look, keep the original indent of those particular lines so it's clear it is unchanged/no diff

2023-08-06 03:46 UTC, kennytv approved these changes

2023-08-07 12:52 UTC, CodeByCam requested changes

2023-08-07 12:52 UTC, CodeByCam commented on patches/server/0994-Implement-PlayerFailMoveEvent.patch
> ++                                    toX, toY, toZ, f, f1, false);
Can you please add obf helpers for `f` & `f1`, same below

2023-08-07 12:53 UTC, codebycam commented on patches/server/0994-Implement-PlayerFailMoveEvent.patch
> ++                                    toX, toY, toZ, f, f1, false);
After this change it'll be ready for merge :-D

2023-08-08 02:50 UTC, CodeByCam approved these changes
Thanks!

2023-08-08 02:50 UTC, CodeByCam commented
@kennytv Please merge :-D

2023-08-08 02:51 UTC, merged