Add clicked position to PlayerUseUnknownEntityEvent
PaperMC/Paper pull request #9604
Opened 2023-08-14 07:11 UTC by kennytv

Fixes the event being called 4 times (2 per hand) when a player right clicks with no difference to the event data. Also adds some javadoc and removes an unnecessary access transformer

2023-08-14 07:45 UTC, lynxplay requested changes, later dismissed

2023-08-14 07:45 UTC, lynxplay commented on patches/api/0036-Add-PlayerUseUnknownEntityEvent.patch
> ++ * Useful for plugins dealing with virtual entities (entities that don't actually spawned on the server).
```suggestion
+ * Useful for plugins dealing with virtual entities (entities that aren't actually spawned on the server).
```

2023-08-14 07:45 UTC, lynxplay commented on patches/api/0036-Add-PlayerUseUnknownEntityEvent.patch
> ++     * Returns the location of the unknown entity that was interacted with.
```suggestion
+     * Returns the entity id of the unknown entity that was interacted with.
```

2023-08-14 07:45 UTC, lynxplay commented on patches/server/0083-Add-PlayerUseUnknownEntityEvent.patch
> ++            pos != null ? io.papermc.paper.math.Position.fine(pos.x, pos.y, pos.z) : null)
Should we be adding MCUtil helpers for position creation (from Vec3 and BlockPos respectively) if we want to expand the usage of position here ?

2023-08-14 10:55 UTC, NoahvdAa requested changes
Looks good apart from the fact that it doesn't compile

2023-08-14 10:55 UTC, NoahvdAa commented on patches/server/0009-MC-Utils.patch
> ++    }
```suggestion
+    public static FinePosition toPosition(Vec3 vector) {
+        return Position.fine(vector.x, vector.y, vector.z);
+    }
+
+    public static BlockPosition toPosition(Vec3i vector) {
+        return Position.block(vector.getX(), vector.getY(), vector.getZ());
+    }
```

this doesn't compile

2023-08-14 11:01 UTC, kennytv commented
Shhh

2023-08-14 11:12 UTC, NoahvdAa approved these changes

2023-08-14 22:29 UTC, Machine-Maker requested changes

2023-08-14 22:29 UTC, Machine-Maker commented on patches/api/0036-Add-PlayerUseUnknownEntityEvent.patch
> ++    public @Nullable Position getClickedPosition() {
I think the vector in the packet is a relative vector to the armor stand, it's not a position.

2023-08-15 06:18 UTC, Cryptite commented
This isn't exactly the right place for this comment, probably, but is there some way in which this event could either be cancelled, or toggled as "consumed" in such a way where interacting with an unknown entity stops all subsequent future actions? And/or maybe there's another way to already handle this. Examples are:

- Right-clicking a packet NPC holding a consumable both interacts with it, but also you start eating.
- Same thing but when holding projectiles (pearls, potions, etc)

2023-08-15 09:38 UTC, kennytv commented
It'd be best if you created an issue for that

2023-08-15 15:14 UTC, Machine-Maker approved these changes

2023-08-16 07:58 UTC, merged