Add `Material#getPlacedType` API
PaperMC/Paper pull request #9607
Opened 2023-08-15 09:35 UTC by tal5

## Additions

- `Material#getPlacedType` - returns the type an item would be placed as (usually the same, but is different in some cases, e.g. pumpkin seeds -> pumpkin stem).
- `UnsafeValues#getPlacedType(Material)` - bridge method for `Material#getPlacedType`.

## Notes

- Currently it returns a `Material`, as that's what's stored internally - might make sense to return `BlockData` to avoid potential issues with more complex data being added in the future/as it might make sense to represent it as `BlockData`?
- `BlockData#getPlacementMaterial` (other way around from this) seems to return `AIR` when a block doesn't have an item equivalent, while this returns `null` for items that can't be placed.
`null` makes more sense imo, but either is fine I guess - let me know if that should be changed to match.

2023-08-15 15:12 UTC, Machine-Maker requested changes
I think returning BlockData would be more appropriate if we had a method that called `BlockItem#getPlacementState` which returns the equivalent BlockData in nms (BlockState). For just this, Material is fine.

----

I guess since Material is just going to be straight up deprecated by upstream hopefully next major version, I don't really have an issue adding more methods to Material that only apply to items or blocks but not both

2023-08-15 15:12 UTC, Machine-Maker commented on patches/api/0426-Add-Material-getPlacedType-API.patch
> ++     */
Can drop the javadoc here, just increases workload to maintain it since its a copy

2023-08-16 07:22 UTC, Warriorrrr commented
This seems to be a duplicate of https://github.com/PaperMC/Paper/pull/6680 if I'm not mistaken

2024-03-10 00:28 UTC, Owen1212055 commented
Closing, as in general we are waiting for upstream's blocktype/itemtype API to better expose this types of API.

2024-03-10 00:28 UTC, closed without merging