Expose Hand during BlockCanBuildEvent
PaperMC/Paper pull request #9636
Opened 2023-08-21 13:20 UTC by the456gamer

useful for checking metadata / pdc of block to be placed

2023-08-21 13:51 UTC, MiniDigger commented
cant you just call the method on player?

2023-08-21 13:52 UTC, the456gamer commented
as general usage, or in this prs implementation?
because currently the hand the block is place from isn't exposed.

2023-08-21 14:08 UTC, MiniDigger commented
then it makes more sense to expose the hand, as thats the only thing you cant right now, no?

2023-08-21 17:52 UTC, Machine-Maker requested changes

2023-08-21 17:52 UTC, Machine-Maker commented on patches/server/1015-Expose-hand-during-BlockCanBuildEvent.patch
> ++            BlockCanBuildEvent event = new BlockCanBuildEvent(CraftBlock.at(world, blockposition), player, CraftBlockData.fromData(iblockdata1), defaultReturn, context.getHand() == net.minecraft.wor
There is a method in CraftEquipmentSlot to convert the hand.

2023-08-21 17:52 UTC, Machine-Maker commented on patches/api/0429-Expose-hand-during-BlockCanBuildEvent.patch
> ++    public BlockCanBuildEvent(@NotNull final Block block, @Nullable final Player player, @NotNull final BlockData type, final boolean canBuild, @NotNull final org.bukkit.inventory.EquipmentSlot hand
Add `@ApiStatus.Internal` to the constructor. It's possible we want this to be a new constructor. Usually for most events I don't care, but its possible this event is created/fired by plugins more than others.

2023-08-21 17:52 UTC, Machine-Maker commented on patches/api/0429-Expose-hand-during-BlockCanBuildEvent.patch
> ++    public org.bukkit.inventory.EquipmentSlot getHand() {
Missing `@NotNull`

2023-08-21 20:40 UTC, Machine-Maker commented on patches/api/0429-Expose-hand-during-BlockCanBuildEvent.patch
> ++    @org.jetbrains.annotations.ApiStatus.Internal // Paper
Can just mark this as deprecated instead. Actually, also mark this as `DoNotUse` to make sure we catch any that upstream might add. 

So replace `Internal` with `Deprecated` and `DoNotUse`. Just for this method tho, the other one is good.

2023-08-21 21:08 UTC, 456dev commented on patches/api/0429-Expose-hand-during-BlockCanBuildEvent.patch
> ++    @org.jetbrains.annotations.ApiStatus.Internal // Paper
what about the existing deprecated one, or leave that as-is. should i also add a deprecation reason in the javadoc, or leave it

2023-08-21 21:09 UTC, Machine-Maker commented on patches/api/0429-Expose-hand-during-BlockCanBuildEvent.patch
> ++    @org.jetbrains.annotations.ApiStatus.Internal // Paper
Just leave that one as is. No need to mention anything in the javadocs either

2023-08-22 12:15 UTC, kennytv approved these changes

2023-08-22 20:51 UTC, Machine-Maker approved these changes

2023-08-23 00:41 UTC, merged