Fix MC-868
PaperMC/Paper pull request #9709
Opened 2023-09-11 09:11 UTC by TreemanKing

Fixes MC-868
Adds a check if distance between minecart and detector rail is less than maximum distance of the centre of a blcok to the edge of a block (0.5)

Closes
#9698

2023-09-11 09:54 UTC, vadcx commented
Throughout the MC codebase to avoid the math.sqrt function (expensive) the distance checks are made on squared values.

If the classic formula is math.sqrt((x2-x1)²+(y2-y1)²) < limit

then removing sqrt on both sides of the equation leaves (x2-x1)²+(y2-y1)² < limit²

The ...distanceSquared function should be somewhere in vanilla. Please double-check me on the 0.5d² value.

2023-09-14 21:26 UTC, Machine-Maker requested changes
This breaks (possibly) expected behavior for the detector rail as it currently operates. I created the setup below and summoned a minecart at varying points on the track horizontally. In vanilla, I could spawn it on 3/10ths of the adjacent block and it would still trigger the detector rail. With this PR, the position has to be within the detector block x/z coord.

2023-09-14 22:15 UTC, TreemanKing commented
> This breaks (possibly) expected behavior for the detector rail as it currently operates. I created the setup below and summoned a minecart at varying points on the track horizontally. In vanilla, I could spawn it on 3/10ths of the adjacent block and it would still trigger the detector rail. With this PR, the position has to be within the detector block x/z coord.

From testing that I did prior to posting the PR, I used the sqrt(2) as the maximum distance (centre to corner). When I had used this, the bug would still persist (considering a velocity of 0.7 or greater from memory), which I believe what current basic vanilla function uses.

As the block should only take the entities from the basic orthogonal directions as it can only face 4 directions, and to this that it's attempting to detect then interacting entity (entity on block). 

I do believe some redstone contraptions that use detector rails should be used as a test to see if any current redstone contraptions will break. Only thing I can think of is if the redstone is required to be on for that fraction of a second longer.

2023-09-17 11:53 UTC, vadcx commented
Treeman, did you consider the fix posted in the originial MC-868? [Link to comment by FX - PR0CESS](https://bugs.mojang.com/browse/MC-868?focusedId=1163054&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1163054)

> Now I will mention why this should not be fixed xD
> 
> When changing this code you run into an issue with client rendering. Due to the client using interpolation, the client will render the minecart as if it's turning and then put it in the right place. So that issue should be solved first... which is not an easy issue to fix.

2023-09-17 12:01 UTC, TreemanKing commented
> Treeman, did you consider the fix posted in the originial MC-868? [Link to comment by FX - PR0CESS](https://bugs.mojang.com/browse/MC-868?focusedId=1163054&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1163054)
> 
> > Now I will mention why this should not be fixed xD
> > 
> > When changing this code you run into an issue with client rendering. Due to the client using interpolation, the client will render the minecart as if it's turning and then put it in the right place. So that issue should be solved first... which is not an easy issue to fix.

His solution checks a single co-ordinate.

2024-06-06 21:17 UTC, closed without merging