Fix strikeLightningEffect powers lightning rods and clears copper
PaperMC/Paper pull request #9780
Opened 2023-09-30 10:48 UTC by notTamion

resolves #9736 
Not sure if the check for isSilent should be removed i am just going to leave it in for now incase any plugins are using the deprecated methods as a workaround

2023-09-30 11:05 UTC, kennytv commented
Thanks - I think another if needs the visual check where it is able to set fire to the world

2023-09-30 11:33 UTC, notTamion commented
Is it also in the LightningBolt class? Incase you are talking about the spawnFire method, that one already got a check in it.
When testing the changes it doesn't set anything on fire. Or is there something i am missing?

2023-10-01 00:18 UTC, kennytv approved these changes
Oh yeah right, thanks!

2023-10-04 01:40 UTC, Machine-Maker requested changes
This is a vanilla behavior break. The vanilla `visualOnly` boolean is exclusively used for the skeleton trap lightning, which in vanilla, does affect lightning rods and copper blocks. To add the check for it here would change that behavior.

2023-10-05 12:52 UTC, notTamion commented
Would creating an extra boolean and using that for the skeleton trap be an good way of fixing this? This way we can use the visualOnly boolean for the strikeLightningEffect method. This also fixes misleading variable names. Is this a good way to do it or are there better ways?

2023-10-08 15:05 UTC, notTamion commented
Fixed the behavior break by creating an extra skeletonTrap boolean that is used for skeleton traps instead of the visualOnly boolean. This way we also avoid confusion with variable names. I hope this way of fixing it is acceptable

2023-10-20 15:03 UTC, Lulu13022002 commented on patches/server/1039-Fix-strikeLightningEffect-powers-lightning-rods-and-.patch
> ++            } else { // Paper
This diff is not needed it's better indeed but this will be part of the spigot cleanup it shouldn't be there

2023-10-20 15:03 UTC, Lulu13022002 commented on patches/server/1039-Fix-strikeLightningEffect-powers-lightning-rods-and-.patch
> ++                if (!CraftEventFactory.callBlockIgniteEvent(this.level(), blockposition, this).isCancelled()) { // Paper
Same here

2023-10-20 15:03 UTC, Lulu13022002 commented on patches/server/1039-Fix-strikeLightningEffect-powers-lightning-rods-and-.patch
> ++                    if (!CraftEventFactory.callBlockIgniteEvent(this.level(), blockposition1, this).isCancelled()) { // Paper
Same here

2023-10-20 15:03 UTC, Lulu13022002 commented on patches/server/1039-Fix-strikeLightningEffect-powers-lightning-rods-and-.patch
> ++    //Paper end
Missing a space between // and Paper end, also the setter is not really needed if the field is already public so you can either make the field private and use the setter or directly use the field access

2023-10-22 00:41 UTC, Machine-Maker commented
Vanilla's `visualOnly` field **is** the skeleton trap boolean. All other uses of it for anything else should be reverted. Instead of using the vanilla field for what it originally ways, we are just changing its meaning, and adding a field to replace it. It should be the other way around. Add an "isEffect" boolean that is checked in the correct places, and remove `visualOnly` from anywhere it's not used in vanilla. Then make the API isEffect method return that new boolean.

2023-11-11 19:59 UTC, Machine-Maker approved these changes

2023-11-11 20:09 UTC, merged