More Anvil Events
PaperMC/Paper pull request #981
Opened 2018-01-21 14:48 UTC by BillyGalbreath

I'm bored.

2018-01-21 16:57 UTC, Scrayos commented
Those events are amazing! I was always searching for something like that. I'm currently work-arounding it with Packet-Listeners, and I would love to replace them with bukkit-events.

2018-01-21 17:15 UTC, aikar requested changes

2018-01-21 17:15 UTC, aikar commented on Spigot-Server-Patches/0267-More-Anvil-Events.patch
> +-                    if (i > 2) {
Can we avoid the indentation change? Cant see context below, but could we return early if the damage event is cancelled?

2018-01-21 17:15 UTC, aikar commented on Spigot-Server-Patches/0267-More-Anvil-Events.patch
> +-                        world.setTypeAndData(blockposition, iblockdata.set(BlockAnvil.DAMAGE, Integer.valueOf(i)), 2);
Again here, can we return early instead if cancelled?

2018-01-21 17:15 UTC, aikar commented on Spigot-API-Patches/0085-More-Anvil-Events.patch
> ++     * Gets the anvil damage value
Can you make it more clear that this is the NEW damage value

2018-01-21 17:15 UTC, aikar commented on Spigot-API-Patches/0085-More-Anvil-Events.patch
> ++     * 3+ = Anvil is breaking
3 being the breaking point is an implementation detail.

I think we should consolidate the 2 events into this one, and add a isBreaking method that returns true if damage >= 3, and false if < 3.

Then we can add a setBreaking(boolean) that simply sets damage level to 3 if true, else leave as is if < 3, and set to 2 if was 3 before.

2018-01-21 17:15 UTC, aikar commented on Spigot-API-Patches/0085-More-Anvil-Events.patch
> ++public class AnvilBreakEvent extends InventoryEvent implements Cancellable {
See comments on the other event, i think we can remove this event.

2018-01-21 17:17 UTC, aikar commented on Spigot-Server-Patches/0267-More-Anvil-Events.patch
> +-                        world.setTypeAndData(blockposition, iblockdata.set(BlockAnvil.DAMAGE, Integer.valueOf(i)), 2);
Though with a merged event, you wont even need to change anything about this.

2018-01-22 02:53 UTC, BillyGalbreath commented
Changes made as requested

2018-01-22 17:01 UTC, Black-Hole commented
Since 1.13 is nearly complete this PR should wait, since in 1.13 anvil will be split into three different blocks.

2018-01-25 13:41 UTC, BillyGalbreath commented
Since 1.13 is NOT nearly here, lets NOT wait. ;)

2018-01-26 02:27 UTC, zachbr commented
I can understand why some may want this held back until 1.13.

This event is pretty well based around magic data values.
My understanding is that these values will almost certainly be changing come 1.13. Even if not moving to some form of state, changing nonetheless. If 1.13 migrates these to a more concrete state, whether that be blockstates or just new values, we could probably abstract those magic values into something with actual meaning.

Do we want to introduce this event for ... a month, month in half, w/e only to have all the data it uses change and force plugins to update then anyway?

2018-01-26 13:41 UTC, BillyGalbreath commented
I dont mind if it gets delayed until 1.13, I dont even use this. I was working on something else in the code here (an anvil repair event that didnt work out) and ended up adding this out of boredom/defeat. Figured since the 1.12->1.13 update is going to be another one of those 1.8->1.9 updates that make a huge chunk of the community not update it would still get used for quite some time in 1.12 (I'm not in that crowd, I'm ready for 1.13 already) ^_^

2018-01-26 13:52 UTC, Scrayos commented
Yeah, I also think this can wait until 1.13, but I really hope once 1.13 is out, this PR will still be remembered and it will make it into PaperSpigot. There is waaay too little control over anvils now, and I am absolutely looking forward to having this within PaperSpigot.

2018-06-10 10:30 UTC, BillyGalbreath commented
6 months later... :P

2018-06-10 13:56 UTC, MiniDigger commented
1.13 will come out eventually :D

2018-07-21 04:39 UTC, closed without merging