Add API to get the collision shape of a block before it's placed
PaperMC/Paper pull request #9821
Opened 2023-10-11 15:32 UTC by TrollyLoki

2023-10-11 17:00 UTC, Machine-Maker requested changes

2023-10-11 17:00 UTC, Machine-Maker commented on patches/api/0442-Add-API-to-get-the-collision-shape-of-a-block-before.patch
> ++     * @param location the location to simulate placing the block at
I don't think `simulate` is the correct word. It feels like it means its doing more than just checking what the collision would be. I think a better description would be `the location used to calculate the collision shape`, or something like that.

2023-10-14 18:57 UTC, Machine-Maker approved these changes

2023-10-14 19:34 UTC, lynxplay commented on patches/api/0442-Add-API-to-get-the-collision-shape-of-a-block-before.patch
> ++     * Gets the block collision shape that would result if this block data were placed at a particular location.
I think the javadocs here are somewhat misleading.
The method only computes the collision shape of the block data in the passed location without any placement like logic running.

That is fine, I can 100% see the usage of this method, but I think we need to be very detailed about *what* this method does.
From a) the name and b) the documentation it is not instantly obvious that this, e.g., would not have a Material.OAK_FENCE.createBlockData() return the shape a fence would be in at location A if a connecting fence is next to it.

The docs are in that regard "technically" correct, the fence block data would have no direction marked and would have a single bounding box of a fence that is not connected, but most people would not expect this behaviour.

I think we'd save ourself and plugin developers down the line a lot of time if we further explain the logic this method provides :)

2023-10-26 03:31 UTC, TrollyLoki commented
I removed the word placed and replaced it with calculated as I did in the parameter description. Also added another line clarifying that the result may differ from what would actually result if the block was actually placed.

2023-10-28 23:23 UTC, electronicboy approved these changes

2023-11-04 21:15 UTC, Owen1212055 approved these changes

2023-11-04 21:32 UTC, merged