Add Enchantment cost API
PaperMC/Paper pull request #9856
Opened 2023-10-20 11:33 UTC by luisc99

Cost is a property of individual enchantments, and is used by vanilla in combination with environmental aspects like tool enchantability and bookshelf count to determine the final cost of an enchantment as shown in an enchanting table.

Having access to the base cost of an enchantment using these vanilla methods can allow plugin developers to determine the "value" of an enchantment, and use it in custom logic where needed. I came across this recently when trying to assign an economic value to enchantments during tool repairing, and noticed these values don't seem to be obtainable under the current API.

2023-10-20 20:33 UTC, Machine-Maker requested changes
I think the naming and javadocs of these methods need to make it more clear that its not the `number of experience levels needed`. As you briefly mention, its not the direct cost. I don't think calling it a "cost" is really correct. And the `@return` tag in the javadoc doesn't do anything to dispel that notion.

Maybe something like `getMin/MaxModifiedCost`? Since it is used when comparing it to the modified level amount on the enchant clicked.

2023-10-21 12:44 UTC, luisc99 commented
I agree this concept of "cost" is a bit confusing. The original method names were mainly to match the Mojang ones, as the existing similar surrounding methods all did, but I've changed it them to be clearer. I've also updated the javadocs a bit, to hopefully try make it more obvious the cost isn't directly related to experience levels and to add a bit more context.

2023-10-21 20:41 UTC, Machine-Maker requested changes
These patches can be nicely squashed into the `More Enchantment API` patch that already exist for the server and the API. You can then add yourself as a co author of the patch with
`Co-authored-by: Luis <luisc99@icloud.com>`

2023-10-22 00:19 UTC, Machine-Maker approved these changes

2023-10-28 23:54 UTC, NoahvdAa approved these changes

2023-11-11 19:58 UTC, Owen1212055 approved these changes

2023-11-11 20:09 UTC, merged