Fix log level of advancement debug message
PaperMC/Paper pull request #9860
Opened 2023-10-22 16:06 UTC by jpenilla

This message when advancements are removed was added in 1.20.2. It doesn't provide anything useful and spams the console when removing advancements.

2023-10-22 16:09 UTC, lynxplay commented
Would probably fit nicely into 0901-Improve-logging-and-errors.patch. That patch already has removal of unneeded logs.

2023-10-22 16:14 UTC, electronicboy approved these changes

2023-10-22 16:18 UTC, Machine-Maker requested changes, later dismissed
What lynx said, this can go into the logging fixes patch.

2023-10-23 16:27 UTC, lynxplay approved these changes

2023-10-23 17:07 UTC, merged