Skip Folia's EntityScheduler executeTick checks if the scheduler hasn't been used at least once
PaperMC/Paper pull request #9984
Opened 2023-11-29 15:48 UTC by MrPowerGamerBR

This PR is mostly for "hey maybe there is a better solution for this", since I don't expect this PR to be accepted since it is mostly a hacky hack that probably has concurrency issues (accessing `hasScheduledAtLeastOneTask` outside of a synchronized block) and probably has a better solution.

Folia's EntityScheduler `executeTick` loop in `MinecraftServer`'s `tickChildren` is slooooow if you have a lot of entities (example: for a server with 15k entities, it uses ~1.7ms every tick, even if none of your plugins are using Folia's EntityScheduler)

To workaround this, we just don't attempt to do any of the checks if the scheduler hasn't been used at least once. Yes, I know, the scheduler increments the `tickCount`, but that doesn't matter since all the scheduled tasks are "relative" to the current tick count, not bound to the server's tick count.

This gives a nice performance boost since most server entities won't ever use a entity scheduler anyway, think about it: Are plugins really going to add a scheduler to each item frame, each armor stand, each dropped item, each... you get my point xd.

Another way of doing this is changing the scheduler to store entities that have pending tasks into a global list to avoid getting all entities from all worlds, this is what I have done in my fork, and maybe this is a better less hacky solution, BUT that will probably make Folia explode, this needs to be tested further in a Folia environment instead of a Paper environment (on a Paper environment, I have been using this patch for one week+ without any issues): https://github.com/SparklyPower/SparklyPaper/blob/ver/1.20.2/patches/server/0010-Skip-EntityScheduler-s-executeTick-checks-if-there-i.patch

If anyone wants to reproduce the performance impact: Just spawn a bunch of entities, I used Armor Stands to test this.

(In the profiler, the loop is `net.minecraft.server.MinecraftServer.lambda$tickChildren$15()`)

**Profiler Before the Changes:** https://spark.lucko.me/eRvT1QqnI0
**Profiler After the Changes:** https://spark.lucko.me/DDAk1JQC0u

2023-11-29 16:11 UTC, kennytv requested changes

2023-11-29 16:11 UTC, kennytv commented on patches/server/0975-Folia-scheduler-and-owned-region-API.patch
> ++        if (!this.hasScheduledAtLeastOneTask)
Add brackets

2023-11-29 16:11 UTC, kennytv commented on patches/server/0975-Folia-scheduler-and-owned-region-API.patch
> ++    private boolean hasScheduledAtLeastOneTask = false;
I'd maybe call this `awaitingFirstTask = true`

2023-11-29 16:30 UTC, MrPowerGamerBR commented
I have made another PR that also solves the same issue, but that one is based off the patch I mentioned in this PR's description:  #9985

I decided to open a new PR instead of editing this one because I think both approaches are nice: 
* This one requires less changes, but if a EntityScheduler has been used at least once, then the scheduler will continue being ticked until retired.
* The other one requires more changes, but is cleaner and better overall.

2023-12-02 20:27 UTC, kennytv commented
Closing this in favor of https://github.com/PaperMC/Paper/pull/9985

2023-12-02 20:27 UTC, closed without merging