Adding chunk serialization events
PaperMC/Paper pull request #9990
Opened 2023-11-30 13:10 UTC by derverdox

This patch adds new Chunk events that are called during the serialization / generation process of chunks.
A problem some developers may face while using the ChunkLoad or ChunkUnload events is the fact that they are called synchronously.
These proposed events are called during the process.

The use case of such events is that heavy saving / loading tasks from cache to the chunk nbt container or vice versa are executed asynchronously aswell but in the same thread
that saves / loads / generates the chunk.

2023-11-30 13:15 UTC, powercasgamer commented on patches/server/1055-Adding-ChunkSerialization-and-Generation-events.patch
> ++package de.verdox.mccreativelab.worldgen;
Why is this in another package? Also looks like the exact same methods are in CraftEventFactory?

2023-11-30 13:30 UTC, derverdox commented on patches/server/1055-Adding-ChunkSerialization-and-Generation-events.patch
> ++package de.verdox.mccreativelab.worldgen;
Oh I thought I removed it. This was a patch from a private fork.

2023-12-02 21:08 UTC, kennytv requested changes

2023-12-02 21:08 UTC, kennytv commented on patches/api/0449-Adding-ChunkSerialization-and-Generation-events.patch
> ++        return this.chunk;
This should get docs as to when the chunk is null or not null

2023-12-02 21:08 UTC, kennytv commented on patches/api/0449-Adding-ChunkSerialization-and-Generation-events.patch
> ++    private static final HandlerList handlers = new HandlerList();
Uppercase name for static final fields

2023-12-02 21:08 UTC, kennytv commented on patches/api/0449-Adding-ChunkSerialization-and-Generation-events.patch
> ++    public ChunkDeserializeEvent(@NotNull final World world, @Nullable final Chunk chunk, final int chunkX, final int chunkZ, @NotNull final PersistentDataContainer chunkPersistentDataContainer) {
Extra line between the field and constructor

2023-12-02 21:08 UTC, kennytv commented on patches/server/1055-Adding-ChunkSerialization-and-Generation-events.patch
> ++                // Paper end - add ChunkDataEvents
Single line changes just get a ` // Paper - ...` comment at the end of the line

2023-12-02 21:08 UTC, kennytv commented on patches/server/1055-Adding-ChunkSerialization-and-Generation-events.patch
> ++import org.bukkit.persistence.PersistentDataContainer;
Especially in this class it's going to be ugly, but please remove the added imports and instead fully qualify them when used in code to reduce diff

2025-03-23 19:15 UTC, closed without merging